package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '332293'
	when
		$gda : GrlDetAmounts(hpePdtType in ( "IRS" ) && htyTradCat in ( "01" , "02" ) && intInd == "N" && ownUse21 == null && fixedRate >= 3)
	then
        
end





rule '1150740' extends '332293' salience 1240

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxtHo06("99.999");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150739' extends '332293' salience 1230
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Long", getCase1_1150761() == "less than 1 month")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-LONG_lessthan1month");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150741' extends '332293' salience 1220
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Long", getCase1_1150761() == "1-3 months")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-LONG_1-3months");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150742' extends '332293' salience 1210
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Long", getCase1_1150761() == "3-6 months")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-LONG_3-6months");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150743' extends '332293' salience 1200
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Long", getCase1_1150761() == "6-12 months")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-LONG_6-12months");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150744' extends '332293' salience 1190
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Long")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-LONG_1.0-1.9yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150745' extends '332293' salience 1180
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Long")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-LONG_1.9-2.8yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150746' extends '332293' salience 1170
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Long")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-LONG_3.6-4.3yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150747' extends '332293' salience 1160
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Long")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GRSM3_C1_ALL-LONG_4.3-5.7yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150748' extends '332293' salience 1150
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Long")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-LONG_5.7-7.3yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150749' extends '332293' salience 1140
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Long")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-LONG_7.3-9.3yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150750' extends '332293' salience 1130
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Long")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-LONG_9.3-10.6yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150751' extends '332293' salience 1120
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Long")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-LONG_10.6-12yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150752' extends '332293' salience 1110
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Long", getCase1_1150761() == "12-20 yr")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-LONG_12-20yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150753' extends '332293' salience 1100
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Long", getCase1_1150761() == "more than 20 yr")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-LONG_morethan20yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150754' extends '332293' salience 1090
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Short", getCase1_1150761() == "1-3 months")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-SHORT_1-3months");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150755' extends '332293' salience 1080
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Short")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-SHORT_1.0-1.9yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150756' extends '332293' salience 1070
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Short")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-SHORT_1.9-2.8yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150757' extends '332293' salience 1060
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Short")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-SHORT_10.6-12yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150758' extends '332293' salience 1050
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Short", getCase1_1150761() == "12-20 yr")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-SHORT_12-20yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150759' extends '332293' salience 1040
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Short")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-SHORT_2.8-3.6yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150760' extends '332293' salience 1030
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Short", getCase1_1150761() == "3-6 months")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-SHORT_3-6months");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150761' extends '332293' salience 1020
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Short")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-SHORT_3.6-4.3yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150762' extends '332293' salience 1010
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Short")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-SHORT_4.3-5.7yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150763' extends '332293' salience 1000
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Short")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-SHORT_5.7-7.3yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150764' extends '332293' salience 990
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Short", getCase1_1150761() == "6-12 months")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-SHORT_6-12months");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150765' extends '332293' salience 980
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Short")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-SHORT_7.3-9.3yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150766' extends '332293' salience 970
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Short")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-SHORT_9.3-10.6yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150767' extends '332293' salience 960
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Short", getCase1_1150761() == "less than 1 month")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-SHORT_lessthan1month");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150768' extends '332293' salience 950
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Short", getCase1_1150761() == "more than 20 yr")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-SHORT_morethan20yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end

rule '1150769' extends '332293' salience 940
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1150761() == "Long")
        
    then
        $gda.setCustomTxtHo06("MKRSATDI_GR3_C1_ALL-LONG_2.8-3.6yr");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3583");
        
end


