package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '331342'
	when
		$gda : GrlDetAmounts(hacAmtCl != null && hacAmtCl not in ( "06" , "07" , "14" , "15" , "16" , "17" ))
	then
        
end





rule '1036246' extends '331342' salience 2330

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxt02("99.999");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036048' extends '331342' salience 2320

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0001000")
        
    then
        $gda.setCustomTxt02("A0001000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036049' extends '331342' salience 2310

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0003000")
        
    then
        $gda.setCustomTxt02("A0003000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036050' extends '331342' salience 2300

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0005000")
        
    then
        $gda.setCustomTxt02("A0005000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036051' extends '331342' salience 2290

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0006000")
        
    then
        $gda.setCustomTxt02("A0006000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036052' extends '331342' salience 2280

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0007000")
        
    then
        $gda.setCustomTxt02("A0007000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036053' extends '331342' salience 2270

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0009000")
        
    then
        $gda.setCustomTxt02("A0009000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036054' extends '331342' salience 2260

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0011000")
        
    then
        $gda.setCustomTxt02("A0011000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036055' extends '331342' salience 2250

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0012000")
        
    then
        $gda.setCustomTxt02("A0012000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036056' extends '331342' salience 2240

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0014000")
        
    then
        $gda.setCustomTxt02("A0014000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036057' extends '331342' salience 2230

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0015000")
        
    then
        $gda.setCustomTxt02("A0015000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036058' extends '331342' salience 2220

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0016000")
        
    then
        $gda.setCustomTxt02("A0016000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036059' extends '331342' salience 2210

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0017000")
        
    then
        $gda.setCustomTxt02("A0017000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036060' extends '331342' salience 2200

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0019000")
        
    then
        $gda.setCustomTxt02("A0019000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036061' extends '331342' salience 2190

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0020000")
        
    then
        $gda.setCustomTxt02("A0020000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036062' extends '331342' salience 2180

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0021000")
        
    then
        $gda.setCustomTxt02("A0021000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036063' extends '331342' salience 2170

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0022000")
        
    then
        $gda.setCustomTxt02("A0022000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036064' extends '331342' salience 2160

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0023000")
        
    then
        $gda.setCustomTxt02("A0023000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036065' extends '331342' salience 2150

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0024000")
        
    then
        $gda.setCustomTxt02("A0024000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036066' extends '331342' salience 2140

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0025000")
        
    then
        $gda.setCustomTxt02("A0025000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036067' extends '331342' salience 2130

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000")
        
    then
        $gda.setCustomTxt02("A0027000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036068' extends '331342' salience 2120

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0028000")
        
    then
        $gda.setCustomTxt02("A0028000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036069' extends '331342' salience 2110

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0029000")
        
    then
        $gda.setCustomTxt02("A0029000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036070' extends '331342' salience 2100

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0031000")
        
    then
        $gda.setCustomTxt02("A0031000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036071' extends '331342' salience 2090

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0032000")
        
    then
        $gda.setCustomTxt02("A0032000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036072' extends '331342' salience 2080

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0033000")
        
    then
        $gda.setCustomTxt02("A0033000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036073' extends '331342' salience 2070

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0035000")
        
    then
        $gda.setCustomTxt02("A0035000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036074' extends '331342' salience 2060

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0038000")
        
    then
        $gda.setCustomTxt02("A0038000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036075' extends '331342' salience 2050

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0039000")
        
    then
        $gda.setCustomTxt02("A0039000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036076' extends '331342' salience 2040

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0040000")
        
    then
        $gda.setCustomTxt02("A0040000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036077' extends '331342' salience 2030

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0045000")
        
    then
        $gda.setCustomTxt02("A0045000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036078' extends '331342' salience 2020

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0046000")
        
    then
        $gda.setCustomTxt02("A0046000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036079' extends '331342' salience 2010

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0050000")
        
    then
        $gda.setCustomTxt02("A0050000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036080' extends '331342' salience 2000

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0051000")
        
    then
        $gda.setCustomTxt02("A0051000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036081' extends '331342' salience 1990

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0052000")
        
    then
        $gda.setCustomTxt02("A0052000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036082' extends '331342' salience 1980

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0053000")
        
    then
        $gda.setCustomTxt02("A0053000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036083' extends '331342' salience 1970

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0054000")
        
    then
        $gda.setCustomTxt02("A0054000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036084' extends '331342' salience 1960

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0055000")
        
    then
        $gda.setCustomTxt02("A0055000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036085' extends '331342' salience 1950

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0056000")
        
    then
        $gda.setCustomTxt02("A0056000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036086' extends '331342' salience 1940

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0057000")
        
    then
        $gda.setCustomTxt02("A0057000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036087' extends '331342' salience 1930

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0058000")
        
    then
        $gda.setCustomTxt02("A0058000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036088' extends '331342' salience 1920

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0061000")
        
    then
        $gda.setCustomTxt02("A0061000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036089' extends '331342' salience 1910

    when
        
        GrlDetAmounts(this == $gda, actCode == "A2536000")
        
    then
        $gda.setCustomTxt02("A2536000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036090' extends '331342' salience 1900

    when
        
        GrlDetAmounts(this == $gda, actCode == "A2537000")
        
    then
        $gda.setCustomTxt02("A2537000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036091' extends '331342' salience 1890

    when
        
        GrlDetAmounts(this == $gda, actCode == "A2538000")
        
    then
        $gda.setCustomTxt02("A2538000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036092' extends '331342' salience 1880

    when
        
        GrlDetAmounts(this == $gda, actCode == "A2539000")
        
    then
        $gda.setCustomTxt02("A2539000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036093' extends '331342' salience 1870

    when
        
        GrlDetAmounts(this == $gda, actCode == "A2540000")
        
    then
        $gda.setCustomTxt02("A2540000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036094' extends '331342' salience 1860

    when
        
        GrlDetAmounts(this == $gda, actCode == "A2541000")
        
    then
        $gda.setCustomTxt02("A2541000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036095' extends '331342' salience 1850

    when
        
        GrlDetAmounts(this == $gda, actCode == "A2549000")
        
    then
        $gda.setCustomTxt02("A2549000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036096' extends '331342' salience 1840

    when
        
        GrlDetAmounts(this == $gda, actCode == "A2729000")
        
    then
        $gda.setCustomTxt02("A2729000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036097' extends '331342' salience 1830

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3145000")
        
    then
        $gda.setCustomTxt02("A3145000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036098' extends '331342' salience 1820

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3146000")
        
    then
        $gda.setCustomTxt02("A3146000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036099' extends '331342' salience 1810

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3147000")
        
    then
        $gda.setCustomTxt02("A3147000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036100' extends '331342' salience 1800

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3176000")
        
    then
        $gda.setCustomTxt02("A3176000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036101' extends '331342' salience 1790

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3177000")
        
    then
        $gda.setCustomTxt02("A3177000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036102' extends '331342' salience 1780

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3178000")
        
    then
        $gda.setCustomTxt02("A3178000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036103' extends '331342' salience 1770

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3179000")
        
    then
        $gda.setCustomTxt02("A3179000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036104' extends '331342' salience 1760

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3282000")
        
    then
        $gda.setCustomTxt02("A3282000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036105' extends '331342' salience 1750

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3291000")
        
    then
        $gda.setCustomTxt02("A3291000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036106' extends '331342' salience 1740

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000")
        
    then
        $gda.setCustomTxt02("A3329000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036107' extends '331342' salience 1730

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3331000")
        
    then
        $gda.setCustomTxt02("A3331000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036108' extends '331342' salience 1720

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000")
        
    then
        $gda.setCustomTxt02("A3332000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036109' extends '331342' salience 1710

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3333000")
        
    then
        $gda.setCustomTxt02("A3333000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036110' extends '331342' salience 1700

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3853000")
        
    then
        $gda.setCustomTxt02("A3853000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036111' extends '331342' salience 1690

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3854000")
        
    then
        $gda.setCustomTxt02("A3854000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036112' extends '331342' salience 1680

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3890000")
        
    then
        $gda.setCustomTxt02("A3890000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036113' extends '331342' salience 1670

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3891000")
        
    then
        $gda.setCustomTxt02("A3891000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036114' extends '331342' salience 1660

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3906000")
        
    then
        $gda.setCustomTxt02("A3906000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036115' extends '331342' salience 1650

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3908000")
        
    then
        $gda.setCustomTxt02("A3908000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036116' extends '331342' salience 1640

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3910000")
        
    then
        $gda.setCustomTxt02("A3910000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036117' extends '331342' salience 1630

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3912000")
        
    then
        $gda.setCustomTxt02("A3912000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036118' extends '331342' salience 1620

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3914000")
        
    then
        $gda.setCustomTxt02("A3914000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036119' extends '331342' salience 1610

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3916000")
        
    then
        $gda.setCustomTxt02("A3916000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036120' extends '331342' salience 1600

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000")
        
    then
        $gda.setCustomTxt02("A3931000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036121' extends '331342' salience 1590

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3943000")
        
    then
        $gda.setCustomTxt02("A3943000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036122' extends '331342' salience 1580

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4144000")
        
    then
        $gda.setCustomTxt02("A4144000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036123' extends '331342' salience 1570

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4145000")
        
    then
        $gda.setCustomTxt02("A4145000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036124' extends '331342' salience 1560

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4152000")
        
    then
        $gda.setCustomTxt02("A4152000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036125' extends '331342' salience 1550

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4257000")
        
    then
        $gda.setCustomTxt02("A4257000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036126' extends '331342' salience 1540

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4392000")
        
    then
        $gda.setCustomTxt02("A4392000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036127' extends '331342' salience 1530

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4412000")
        
    then
        $gda.setCustomTxt02("A4412000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036128' extends '331342' salience 1520

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4564000")
        
    then
        $gda.setCustomTxt02("A4564000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036129' extends '331342' salience 1510

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4565000")
        
    then
        $gda.setCustomTxt02("A4565000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036130' extends '331342' salience 1500

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4598000")
        
    then
        $gda.setCustomTxt02("A4598000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036131' extends '331342' salience 1490

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4620000")
        
    then
        $gda.setCustomTxt02("A4620000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036132' extends '331342' salience 1480

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0334000")
        
    then
        $gda.setCustomTxt02("B0334000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036133' extends '331342' salience 1470

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0593000")
        
    then
        $gda.setCustomTxt02("B0593000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036134' extends '331342' salience 1460

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0594000")
        
    then
        $gda.setCustomTxt02("B0594000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036135' extends '331342' salience 1450

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0595000")
        
    then
        $gda.setCustomTxt02("B0595000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036136' extends '331342' salience 1440

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000")
        
    then
        $gda.setCustomTxt02("B0596000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036137' extends '331342' salience 1430

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0597000")
        
    then
        $gda.setCustomTxt02("B0597000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036138' extends '331342' salience 1420

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0607000")
        
    then
        $gda.setCustomTxt02("B0607000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036139' extends '331342' salience 1410

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0608000")
        
    then
        $gda.setCustomTxt02("B0608000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036140' extends '331342' salience 1400

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0609000")
        
    then
        $gda.setCustomTxt02("B0609000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036141' extends '331342' salience 1390

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0610000")
        
    then
        $gda.setCustomTxt02("B0610000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036142' extends '331342' salience 1380

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0611000")
        
    then
        $gda.setCustomTxt02("B0611000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036143' extends '331342' salience 1370

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0612000")
        
    then
        $gda.setCustomTxt02("B0612000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036144' extends '331342' salience 1360

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0229000")
        
    then
        $gda.setCustomTxt02("L0229000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036145' extends '331342' salience 1350

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0230000")
        
    then
        $gda.setCustomTxt02("L0230000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036146' extends '331342' salience 1340

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0233000")
        
    then
        $gda.setCustomTxt02("L0233000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036147' extends '331342' salience 1330

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0234000")
        
    then
        $gda.setCustomTxt02("L0234000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036148' extends '331342' salience 1320

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0237000")
        
    then
        $gda.setCustomTxt02("L0237000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036149' extends '331342' salience 1310

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0238000")
        
    then
        $gda.setCustomTxt02("L0238000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036150' extends '331342' salience 1300

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0239000")
        
    then
        $gda.setCustomTxt02("L0239000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036151' extends '331342' salience 1290

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0241000")
        
    then
        $gda.setCustomTxt02("L0241000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036152' extends '331342' salience 1280

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000")
        
    then
        $gda.setCustomTxt02("L0242000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036153' extends '331342' salience 1270

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0243000")
        
    then
        $gda.setCustomTxt02("L0243000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036154' extends '331342' salience 1260

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0244000")
        
    then
        $gda.setCustomTxt02("L0244000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036155' extends '331342' salience 1250

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0245000")
        
    then
        $gda.setCustomTxt02("L0245000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036156' extends '331342' salience 1240

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0246000")
        
    then
        $gda.setCustomTxt02("L0246000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036157' extends '331342' salience 1230

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0249000")
        
    then
        $gda.setCustomTxt02("L0249000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036158' extends '331342' salience 1220

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0250000")
        
    then
        $gda.setCustomTxt02("L0250000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036159' extends '331342' salience 1210

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0251000")
        
    then
        $gda.setCustomTxt02("L0251000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036160' extends '331342' salience 1200

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0252000")
        
    then
        $gda.setCustomTxt02("L0252000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036161' extends '331342' salience 1190

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0253000")
        
    then
        $gda.setCustomTxt02("L0253000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036162' extends '331342' salience 1180

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0254000")
        
    then
        $gda.setCustomTxt02("L0254000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036163' extends '331342' salience 1170

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0255000")
        
    then
        $gda.setCustomTxt02("L0255000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036164' extends '331342' salience 1160

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0256000")
        
    then
        $gda.setCustomTxt02("L0256000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036165' extends '331342' salience 1150

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0257000")
        
    then
        $gda.setCustomTxt02("L0257000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036166' extends '331342' salience 1140

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0258000")
        
    then
        $gda.setCustomTxt02("L0258000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036167' extends '331342' salience 1130

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0265000")
        
    then
        $gda.setCustomTxt02("L0265000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036168' extends '331342' salience 1120

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0266000")
        
    then
        $gda.setCustomTxt02("L0266000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036169' extends '331342' salience 1110

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0267000")
        
    then
        $gda.setCustomTxt02("L0267000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036170' extends '331342' salience 1100

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0268000")
        
    then
        $gda.setCustomTxt02("L0268000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036171' extends '331342' salience 1090

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0269000")
        
    then
        $gda.setCustomTxt02("L0269000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036172' extends '331342' salience 1080

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0270000")
        
    then
        $gda.setCustomTxt02("L0270000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036173' extends '331342' salience 1070

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0271000")
        
    then
        $gda.setCustomTxt02("L0271000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036174' extends '331342' salience 1060

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0272000")
        
    then
        $gda.setCustomTxt02("L0272000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036175' extends '331342' salience 1050

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0273000")
        
    then
        $gda.setCustomTxt02("L0273000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036176' extends '331342' salience 1040

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0277000")
        
    then
        $gda.setCustomTxt02("L0277000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036177' extends '331342' salience 1030

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0279000")
        
    then
        $gda.setCustomTxt02("L0279000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036178' extends '331342' salience 1020

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0280000")
        
    then
        $gda.setCustomTxt02("L0280000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036179' extends '331342' salience 1010

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1425000")
        
    then
        $gda.setCustomTxt02("L1425000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036180' extends '331342' salience 1000

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1605000")
        
    then
        $gda.setCustomTxt02("L1605000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036181' extends '331342' salience 990

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1615000")
        
    then
        $gda.setCustomTxt02("L1615000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036182' extends '331342' salience 980

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2510000")
        
    then
        $gda.setCustomTxt02("L2510000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036183' extends '331342' salience 970

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2528000")
        
    then
        $gda.setCustomTxt02("L2528000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036184' extends '331342' salience 960

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2529000")
        
    then
        $gda.setCustomTxt02("L2529000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036185' extends '331342' salience 950

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2530000")
        
    then
        $gda.setCustomTxt02("L2530000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036186' extends '331342' salience 940

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2531000")
        
    then
        $gda.setCustomTxt02("L2531000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036187' extends '331342' salience 930

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2532000")
        
    then
        $gda.setCustomTxt02("L2532000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036188' extends '331342' salience 920

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2533000")
        
    then
        $gda.setCustomTxt02("L2533000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036189' extends '331342' salience 910

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2550000")
        
    then
        $gda.setCustomTxt02("L2550000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036190' extends '331342' salience 900

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2569000")
        
    then
        $gda.setCustomTxt02("L2569000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036191' extends '331342' salience 890

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2571000")
        
    then
        $gda.setCustomTxt02("L2571000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036192' extends '331342' salience 880

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2730000")
        
    then
        $gda.setCustomTxt02("L2730000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036193' extends '331342' salience 870

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3180000")
        
    then
        $gda.setCustomTxt02("L3180000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036194' extends '331342' salience 860

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3181000")
        
    then
        $gda.setCustomTxt02("L3181000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036195' extends '331342' salience 850

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3182000")
        
    then
        $gda.setCustomTxt02("L3182000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036196' extends '331342' salience 840

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3183000")
        
    then
        $gda.setCustomTxt02("L3183000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036197' extends '331342' salience 830

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3279000")
        
    then
        $gda.setCustomTxt02("L3279000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036198' extends '331342' salience 820

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3283000")
        
    then
        $gda.setCustomTxt02("L3283000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036199' extends '331342' salience 810

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3334000")
        
    then
        $gda.setCustomTxt02("L3334000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036200' extends '331342' salience 800

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3340000")
        
    then
        $gda.setCustomTxt02("L3340000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036201' extends '331342' salience 790

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3343000")
        
    then
        $gda.setCustomTxt02("L3343000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036202' extends '331342' salience 780

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3345000")
        
    then
        $gda.setCustomTxt02("L3345000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036203' extends '331342' salience 770

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3346000")
        
    then
        $gda.setCustomTxt02("L3346000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036204' extends '331342' salience 760

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3348000")
        
    then
        $gda.setCustomTxt02("L3348000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036205' extends '331342' salience 750

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3351000")
        
    then
        $gda.setCustomTxt02("L3351000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036206' extends '331342' salience 740

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3873000")
        
    then
        $gda.setCustomTxt02("L3873000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036207' extends '331342' salience 730

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3892000")
        
    then
        $gda.setCustomTxt02("L3892000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036208' extends '331342' salience 720

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3893000")
        
    then
        $gda.setCustomTxt02("L3893000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036209' extends '331342' salience 710

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3899000")
        
    then
        $gda.setCustomTxt02("L3899000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036210' extends '331342' salience 700

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3907000")
        
    then
        $gda.setCustomTxt02("L3907000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036211' extends '331342' salience 690

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3909000")
        
    then
        $gda.setCustomTxt02("L3909000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036212' extends '331342' salience 680

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3911000")
        
    then
        $gda.setCustomTxt02("L3911000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036213' extends '331342' salience 670

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3913000")
        
    then
        $gda.setCustomTxt02("L3913000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036214' extends '331342' salience 660

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3915000")
        
    then
        $gda.setCustomTxt02("L3915000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036215' extends '331342' salience 650

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3917000")
        
    then
        $gda.setCustomTxt02("L3917000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036216' extends '331342' salience 640

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3932000")
        
    then
        $gda.setCustomTxt02("L3932000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036217' extends '331342' salience 630

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3933000")
        
    then
        $gda.setCustomTxt02("L3933000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036218' extends '331342' salience 620

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3934000")
        
    then
        $gda.setCustomTxt02("L3934000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036219' extends '331342' salience 610

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3935000")
        
    then
        $gda.setCustomTxt02("L3935000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036220' extends '331342' salience 600

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3936000")
        
    then
        $gda.setCustomTxt02("L3936000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036221' extends '331342' salience 590

    when
        
        GrlDetAmounts(this == $gda, actCode == "L4146000")
        
    then
        $gda.setCustomTxt02("L4146000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036222' extends '331342' salience 580

    when
        
        GrlDetAmounts(this == $gda, actCode == "L4147000")
        
    then
        $gda.setCustomTxt02("L4147000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036223' extends '331342' salience 570

    when
        
        GrlDetAmounts(this == $gda, actCode == "L4150000")
        
    then
        $gda.setCustomTxt02("L4150000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036224' extends '331342' salience 560

    when
        
        GrlDetAmounts(this == $gda, actCode == "L4258000")
        
    then
        $gda.setCustomTxt02("L4258000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036225' extends '331342' salience 550

    when
        
        GrlDetAmounts(this == $gda, actCode == "L4448000")
        
    then
        $gda.setCustomTxt02("L4448000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036226' extends '331342' salience 540

    when
        
        GrlDetAmounts(this == $gda, actCode == "L4467000")
        
    then
        $gda.setCustomTxt02("L4467000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036227' extends '331342' salience 530

    when
        
        GrlDetAmounts(this == $gda, actCode == "L4597000")
        
    then
        $gda.setCustomTxt02("L4597000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036228' extends '331342' salience 520

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0064000")
        
    then
        $gda.setCustomTxt02("Q0064000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036229' extends '331342' salience 510

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0065000")
        
    then
        $gda.setCustomTxt02("Q0065000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036230' extends '331342' salience 500

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0066000")
        
    then
        $gda.setCustomTxt02("Q0066000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036231' extends '331342' salience 490

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0068000")
        
    then
        $gda.setCustomTxt02("Q0068000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036232' extends '331342' salience 480

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0069000")
        
    then
        $gda.setCustomTxt02("Q0069000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036233' extends '331342' salience 470

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0070000")
        
    then
        $gda.setCustomTxt02("Q0070000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036234' extends '331342' salience 460

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0071000")
        
    then
        $gda.setCustomTxt02("Q0071000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036235' extends '331342' salience 450

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0073000")
        
    then
        $gda.setCustomTxt02("Q0073000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036236' extends '331342' salience 440

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0075000")
        
    then
        $gda.setCustomTxt02("Q0075000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036237' extends '331342' salience 430

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0076000")
        
    then
        $gda.setCustomTxt02("Q0076000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036238' extends '331342' salience 420

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0077000")
        
    then
        $gda.setCustomTxt02("Q0077000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036239' extends '331342' salience 410

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q2341000")
        
    then
        $gda.setCustomTxt02("Q2341000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036240' extends '331342' salience 400

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q3167000")
        
    then
        $gda.setCustomTxt02("Q3167000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036241' extends '331342' salience 390

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q3168000")
        
    then
        $gda.setCustomTxt02("Q3168000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036242' extends '331342' salience 380

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q3335000")
        
    then
        $gda.setCustomTxt02("Q3335000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036243' extends '331342' salience 370

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q4661000")
        
    then
        $gda.setCustomTxt02("Q4661000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036244' extends '331342' salience 360

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q4662000")
        
    then
        $gda.setCustomTxt02("Q4662000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036245' extends '331342' salience 350

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q4663000")
        
    then
        $gda.setCustomTxt02("Q4663000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036480' extends '331342' salience 340

    when
        
        GrlDetAmounts(this == $gda, actCode == null, posGroupId == "4665010")
        
    then
        $gda.setCustomTxt02("L0250000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1038655' extends '331342' salience 330

    when
        
        GrlDetAmounts(this == $gda, actCode == null, hpePdtType == "OTHER NON PROD PL ITEM")
        
    then
        $gda.setCustomTxt02("L1605000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036472' extends '331342' salience 320

    when
        
        GrlDetAmounts(this == $gda, actCode == null, posGroupId == "321100")
        
    then
        $gda.setCustomTxt02("A0024000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036473' extends '331342' salience 310

    when
        
        GrlDetAmounts(this == $gda, actCode == null, posGroupId == "331000")
        
    then
        $gda.setCustomTxt02("A0024000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036474' extends '331342' salience 300

    when
        
        GrlDetAmounts(this == $gda, actCode == null, posGroupId == "392000")
        
    then
        $gda.setCustomTxt02("A0003000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036475' extends '331342' salience 290

    when
        
        GrlDetAmounts(this == $gda, actCode == null, posGroupId == "411000")
        
    then
        $gda.setCustomTxt02("L0250000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036479' extends '331342' salience 280

    when
        
        GrlDetAmounts(this == $gda, actCode == null, posGroupId == "343210")
        
    then
        $gda.setCustomTxt02("A0024000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036481' extends '331342' salience 270

    when
        
        GrlDetAmounts(this == $gda, actCode == null, posGroupId == "443210")
        
    then
        $gda.setCustomTxt02("L0250000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036546' extends '331342' salience 260

    when
        
        GrlDetAmounts(this == $gda, actCode == null, posGroupId == "321200")
        
    then
        $gda.setCustomTxt02("A0024000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036550' extends '331342' salience 250

    when
        
        GrlDetAmounts(this == $gda, actCode == null, posGroupId matches "5.*")
        
    then
        $gda.setCustomTxt02("L1605000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036552' extends '331342' salience 240

    when
        
        GrlDetAmounts(this == $gda, actCode == null, posGroupId matches "9.*")
        
    then
        $gda.setCustomTxt02("L1605000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036560' extends '331342' salience 230

    when
        
        GrlDetAmounts(this == $gda, actCode == null, posGroupId matches "8.*")
        
    then
        $gda.setCustomTxt02("L1605000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1036562' extends '331342' salience 220

    when
        
        GrlDetAmounts(this == $gda, actCode == null, posGroupId == "1108110")
        
    then
        $gda.setCustomTxt02("A0024000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1038642' extends '331342' salience 210

    when
        
        GrlDetAmounts(this == $gda, actCode == null, posGroupId in ("3110050", "3110051", "3110052", "3110053"))
        
    then
        $gda.setCustomTxt02("A0031000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1038652' extends '331342' salience 200

    when
        
        GrlDetAmounts(this == $gda, actCode == null, intInd == "Y", hpePdtType == "POS MOV", repAssetInd == "N")
        
    then
        $gda.setCustomTxt02("L0251000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1040749' extends '331342' salience 190

    when
        
        GrlDetAmounts(this == $gda, actCode == null, intInd == "Y", posGroupId == "10903", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt02("A0031000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1040750' extends '331342' salience 180

    when
        
        GrlDetAmounts(this == $gda, actCode == null, intInd == "Y", posGroupId == "10903", repAssetInd == "N")
        
    then
        $gda.setCustomTxt02("L0252000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1038643' extends '331342' salience 170

    when
        
        GrlDetAmounts(this == $gda, actCode == null, hpePdtType == "CCY FORW", hacAmtCl == "12", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt02("A3178000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1038644' extends '331342' salience 160

    when
        
        GrlDetAmounts(this == $gda, actCode == null, hpePdtType == "CCY FORW", hacAmtCl == "12", repAssetInd == "N")
        
    then
        $gda.setCustomTxt02("L3182000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1038645' extends '331342' salience 150

    when
        
        GrlDetAmounts(this == $gda, actCode == null, intInd == "Y", hpePdtType in ("CUST ACCT", "NOSTRO", "OTHER PAYABLES", "OTHER RECEIVABLES"), hacAmtCl == "01", repAssetInd == "N")
        
    then
        $gda.setCustomTxt02("L0242000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1038646' extends '331342' salience 140

    when
        
        GrlDetAmounts(this == $gda, actCode == null, intInd == "Y", hpePdtType in ("CUST ACCT", "NOSTRO", "OTHER PAYABLES", "OTHER RECEIVABLES"), hacAmtCl == "01", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt02("A0027000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1038651' extends '331342' salience 130

    when
        
        GrlDetAmounts(this == $gda, actCode == null, intInd == "Y", hpePdtType == "POS MOV", hacAmtCl == "01", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt02("A0025000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1038653' extends '331342' salience 120

    when
        
        GrlDetAmounts(this == $gda, actCode == null, intInd == "Y", hpePdtType == "SPOT FX", hacAmtCl == "08", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt02("A0007000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1038654' extends '331342' salience 110

    when
        
        GrlDetAmounts(this == $gda, actCode == null, intInd == "Y", hpePdtType == "SPOT FX", hacAmtCl == "08", repAssetInd == "N")
        
    then
        $gda.setCustomTxt02("L0230000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1040751' extends '331342' salience 100

    when
        
        GrlDetAmounts(this == $gda, actCode == null, (posGroupId matches "311020.*" || posGroupId == "3110210" || posGroupId == "3110211" || posGroupId == "3110212" || posGroupId == "3110213" || posGroupId matches "311010.*" || posGroupId == "3110110" || posGroupId == "3110111" || posGroupId == "3110112" || posGroupId == "3110113" || posGroupId == "3110030" || posGroupId == "3110040"), repAssetInd == "Y")
        
    then
        $gda.setCustomTxt02("A0031000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1040752' extends '331342' salience 90

    when
        
        GrlDetAmounts(this == $gda, actCode == null, (posGroupId matches "311020.*" || posGroupId == "3110210" || posGroupId == "3110211" || posGroupId == "3110212" || posGroupId == "3110213" || posGroupId matches "311010.*" || posGroupId == "3110110" || posGroupId == "3110111" || posGroupId == "3110112" || posGroupId == "3110113" || posGroupId == "3110030" || posGroupId == "3110040"), repAssetInd == "N")
        
    then
        $gda.setCustomTxt02("L0252000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1038647' extends '331342' salience 80

    when
        
        GrlDetAmounts(this == $gda, actCode == null, intInd == "Y", hpePdtType in ("LOAN", "DEPOSIT"), hacAmtCl == "01", repAssetInd == "N", contingInd == "N")
        
    then
        $gda.setCustomTxt02("L0242000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1038648' extends '331342' salience 70

    when
        
        GrlDetAmounts(this == $gda, actCode == null, intInd == "Y", hpePdtType in ("LOAN", "DEPOSIT"), hacAmtCl == "01", repAssetInd == "Y", contingInd == "N")
        
    then
        $gda.setCustomTxt02("A0027000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1038649' extends '331342' salience 60

    when
        
        GrlDetAmounts(this == $gda, actCode == null, intInd == "Y", hpePdtType in ("LOAN", "DEPOSIT"), hacAmtCl in ("02", "03"), repAssetInd == "N", contingInd == "N")
        
    then
        $gda.setCustomTxt02("L0229000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1038650' extends '331342' salience 50

    when
        
        GrlDetAmounts(this == $gda, actCode == null, intInd == "Y", hpePdtType in ("LOAN", "DEPOSIT"), hacAmtCl in ("02", "03"), repAssetInd == "Y", contingInd == "N")
        
    then
        $gda.setCustomTxt02("A0003000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1094731' extends '331342' salience 40

    when
        
        GrlDetAmounts(this == $gda, actCode == null, intInd == "N", repAssetInd == "Y", contingInd == "N", prodSubTypeLoc == "SSPA", hscAcctSubcl == "1999")
        
    then
        $gda.setCustomTxt02("A0031000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1094732' extends '331342' salience 30

    when
        
        GrlDetAmounts(this == $gda, actCode == null, intInd == "N", repAssetInd == "Y", contingInd == "N", prodSubTypeLoc == "AINR", hscAcctSubcl == "1999")
        
    then
        $gda.setCustomTxt02("A0003000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1094733' extends '331342' salience 20

    when
        
        GrlDetAmounts(this == $gda, actCode == null, intInd == "N", repAssetInd == "N", contingInd == "N", prodSubTypeLoc == "AINP", hscAcctSubcl == "1999")
        
    then
        $gda.setCustomTxt02("L0229000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end

rule '1094734' extends '331342' salience 10

    when
        
        GrlDetAmounts(this == $gda, actCode == null, intInd == "N", repAssetInd == "N", contingInd == "N", prodSubTypeLoc == "BPLP", hscAcctSubcl == "1999")
        
    then
        $gda.setCustomTxt02("Q0066000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2865");
        
end


