package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '326957'
	when
		$gda : GrlDetAmounts(( ( hpePdtType in ( "SPOT FX" , "CCY FORW" ) && lseHlyRelId == "0239" ) && ( intInd == "Y" ) ))
	then
        
end





rule '98805' extends '326957' salience 50

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setActCode(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1541");
        
end


