package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '326977'
	when
		$gda : GrlDetAmounts(( ( hpePdtType in ( "SPOT FX" , "CCY FORW" ) && lseHlyRelId == "0239" ) && ( intInd == "Y" ) ))
	then
        
end





rule '98806' extends '326977' salience 40

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setRteCode(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1542");
        
end


