package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '334540'
	when
		$gda : GrlDetAmounts(ratingIng != null)
	then
        
end





rule '1650823' extends '334540' salience 21950

    when
        
        GrlDetAmounts(this == $gda, ratingIng in ("1", "2", "3", "4"))
        
    then
        $gda.setEbaCredQualStepIss("CQS 1");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5212");
        
end

rule '1650824' extends '334540' salience 21940

    when
        
        GrlDetAmounts(this == $gda, ratingIng in ("5", "6", "7"))
        
    then
        $gda.setEbaCredQualStepIss("CQS 2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5212");
        
end

rule '1650825' extends '334540' salience 21930

    when
        
        GrlDetAmounts(this == $gda, ratingIng in ("8", "9", "10"))
        
    then
        $gda.setEbaCredQualStepIss("CQS 3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5212");
        
end

rule '1650826' extends '334540' salience 21920

    when
        
        GrlDetAmounts(this == $gda, ratingIng in ("11", "12", "13"))
        
    then
        $gda.setEbaCredQualStepIss("CQS 4");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5212");
        
end

rule '1650827' extends '334540' salience 21910

    when
        
        GrlDetAmounts(this == $gda, ratingIng in ("14", "15", "16"))
        
    then
        $gda.setEbaCredQualStepIss("CQS 5");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5212");
        
end

rule '1650828' extends '334540' salience 21900

    when
        
        GrlDetAmounts(this == $gda, ratingIng not in ("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16"))
        
    then
        $gda.setEbaCredQualStepIss("CQS 6");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5212");
        
end


