package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '332283'
	when
		$gda : GrlDetAmounts(liquidityCd != null && cpyReyCode == null)
	then
        
end





rule '1150314' extends '332283' salience 1570

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "1.01.*")
        
    then
        $gda.setCustomTxt01("1.01");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150315' extends '332283' salience 1560

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "2.01.*")
        
    then
        $gda.setCustomTxt01("2.01");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150316' extends '332283' salience 1550

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "2.02.*")
        
    then
        $gda.setCustomTxt01("2.02_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150317' extends '332283' salience 1540

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "2.03.*")
        
    then
        $gda.setCustomTxt01("2.03_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150318' extends '332283' salience 1530

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "2.04.*")
        
    then
        $gda.setCustomTxt01("2.04_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150319' extends '332283' salience 1520

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "3.01.*")
        
    then
        $gda.setCustomTxt01("3.01");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150320' extends '332283' salience 1510

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "3.02.*")
        
    then
        $gda.setCustomTxt01("3.02_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150321' extends '332283' salience 1500

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "4.01.*")
        
    then
        $gda.setCustomTxt01("4.01");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150322' extends '332283' salience 1490

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "4.02.*")
        
    then
        $gda.setCustomTxt01("4.02");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150323' extends '332283' salience 1480

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "4.11.*")
        
    then
        $gda.setCustomTxt01("4.11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150324' extends '332283' salience 1470

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "4.12.*")
        
    then
        $gda.setCustomTxt01("4.12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150325' extends '332283' salience 1460

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "4.13.*")
        
    then
        $gda.setCustomTxt01("4.13");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150326' extends '332283' salience 1450

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "4.14.*")
        
    then
        $gda.setCustomTxt01("4.14");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150327' extends '332283' salience 1440

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "4.21.*")
        
    then
        $gda.setCustomTxt01("4.21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150328' extends '332283' salience 1430

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "4.22.*")
        
    then
        $gda.setCustomTxt01("4.21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150329' extends '332283' salience 1420

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "4.23.*")
        
    then
        $gda.setCustomTxt01("4.23");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150330' extends '332283' salience 1410

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "4.24.*")
        
    then
        $gda.setCustomTxt01("4.24");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150331' extends '332283' salience 1400

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "4.25.*")
        
    then
        $gda.setCustomTxt01("4.25");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150332' extends '332283' salience 1390

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "4.26.*")
        
    then
        $gda.setCustomTxt01("4.26");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150333' extends '332283' salience 1380

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "4.31.*")
        
    then
        $gda.setCustomTxt01("4.31");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150334' extends '332283' salience 1370

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "4.32.*")
        
    then
        $gda.setCustomTxt01("4.32");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150335' extends '332283' salience 1360

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "4.33.*")
        
    then
        $gda.setCustomTxt01("4.33");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150336' extends '332283' salience 1350

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "4.34.*")
        
    then
        $gda.setCustomTxt01("4.34");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150337' extends '332283' salience 1340

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "4.35.*")
        
    then
        $gda.setCustomTxt01("4.35");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150338' extends '332283' salience 1330

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "4.36.*")
        
    then
        $gda.setCustomTxt01("4.36");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150339' extends '332283' salience 1320

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.11.*")
        
    then
        $gda.setCustomTxt01("5.11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150340' extends '332283' salience 1310

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.12.*")
        
    then
        $gda.setCustomTxt01("5.12_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150342' extends '332283' salience 1300

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.13.*")
        
    then
        $gda.setCustomTxt01("5.13_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150343' extends '332283' salience 1290

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.14.*")
        
    then
        $gda.setCustomTxt01("5.13_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150345' extends '332283' salience 1280

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.21.*")
        
    then
        $gda.setCustomTxt01("5.21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150346' extends '332283' salience 1270

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.22.*")
        
    then
        $gda.setCustomTxt01("5.22_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150347' extends '332283' salience 1260

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.23.*")
        
    then
        $gda.setCustomTxt01("5.23_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150348' extends '332283' salience 1250

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.24.*")
        
    then
        $gda.setCustomTxt01("5.23_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150350' extends '332283' salience 1240

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.31.*")
        
    then
        $gda.setCustomTxt01("5.31");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150351' extends '332283' salience 1230

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.32.*")
        
    then
        $gda.setCustomTxt01("5.32_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150352' extends '332283' salience 1220

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.33.*")
        
    then
        $gda.setCustomTxt01("5.33_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150353' extends '332283' salience 1210

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.34.*")
        
    then
        $gda.setCustomTxt01("5.33_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150355' extends '332283' salience 1200

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.42.*")
        
    then
        $gda.setCustomTxt01("5.42_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150356' extends '332283' salience 1190

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.43.*")
        
    then
        $gda.setCustomTxt01("5.43_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150357' extends '332283' salience 1180

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.44.*")
        
    then
        $gda.setCustomTxt01("5.43_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150359' extends '332283' salience 1170

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.51.*")
        
    then
        $gda.setCustomTxt01("5.51");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150360' extends '332283' salience 1160

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.41.*")
        
    then
        $gda.setCustomTxt01("5.41");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150361' extends '332283' salience 1150

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.52.*")
        
    then
        $gda.setCustomTxt01("5.43_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150362' extends '332283' salience 1140

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.53.*")
        
    then
        $gda.setCustomTxt01("5.43_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150363' extends '332283' salience 1130

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.54.*")
        
    then
        $gda.setCustomTxt01("5.43_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150364' extends '332283' salience 1120

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.55.*")
        
    then
        $gda.setCustomTxt01("5.43_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150365' extends '332283' salience 1110

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.61.*")
        
    then
        $gda.setCustomTxt01("5.61");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150366' extends '332283' salience 1100

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.62.*")
        
    then
        $gda.setCustomTxt01("5.62");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150367' extends '332283' salience 1090

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.63.*")
        
    then
        $gda.setCustomTxt01("5.63");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150368' extends '332283' salience 1080

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.64.*")
        
    then
        $gda.setCustomTxt01("5.64");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150369' extends '332283' salience 1070

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "6.01.*")
        
    then
        $gda.setCustomTxt01("6.01_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150370' extends '332283' salience 1060

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "6.02.*")
        
    then
        $gda.setCustomTxt01("6.02_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150371' extends '332283' salience 1050

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "6.11.*")
        
    then
        $gda.setCustomTxt01("6.11_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150372' extends '332283' salience 1040

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "6.12.*")
        
    then
        $gda.setCustomTxt01("6.11_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150373' extends '332283' salience 1030

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "6.13.*")
        
    then
        $gda.setCustomTxt01("6.12_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150374' extends '332283' salience 1020

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "6.21.*")
        
    then
        $gda.setCustomTxt01("6.22_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150375' extends '332283' salience 1010

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "6.22.*")
        
    then
        $gda.setCustomTxt01("6.21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150376' extends '332283' salience 1000

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "6.23.*")
        
    then
        $gda.setCustomTxt01("6.22_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150377' extends '332283' salience 990

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "6.24.*")
        
    then
        $gda.setCustomTxt01("6.21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150378' extends '332283' salience 980

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "7.01.*")
        
    then
        $gda.setCustomTxt01("7.01");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150379' extends '332283' salience 970

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "7.02.*")
        
    then
        $gda.setCustomTxt01("7.02");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150380' extends '332283' salience 960

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "7.03.*")
        
    then
        $gda.setCustomTxt01("7.03_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150381' extends '332283' salience 950

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "7.04.*")
        
    then
        $gda.setCustomTxt01("7.04");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150382' extends '332283' salience 940

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "8.01.*")
        
    then
        $gda.setCustomTxt01("8.01");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150383' extends '332283' salience 930

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "9.01.*")
        
    then
        $gda.setCustomTxt01("9.01");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150384' extends '332283' salience 920

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "9.12.*")
        
    then
        $gda.setCustomTxt01("9.12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150385' extends '332283' salience 910

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "9.14.*")
        
    then
        $gda.setCustomTxt01("9.14");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150386' extends '332283' salience 900

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "11.01.*")
        
    then
        $gda.setCustomTxt01("11.01");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150387' extends '332283' salience 890

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "11.02.*")
        
    then
        $gda.setCustomTxt01("11.02_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150388' extends '332283' salience 880

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "11.03.*")
        
    then
        $gda.setCustomTxt01("11.02_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150389' extends '332283' salience 870

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "11.04.*")
        
    then
        $gda.setCustomTxt01("11.02_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150390' extends '332283' salience 860

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "12.01.*")
        
    then
        $gda.setCustomTxt01("12.01_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150391' extends '332283' salience 850

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "12.02.*")
        
    then
        $gda.setCustomTxt01("12.01_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150392' extends '332283' salience 840

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "12.03.*")
        
    then
        $gda.setCustomTxt01("12.01_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150393' extends '332283' salience 830

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "12.04.*")
        
    then
        $gda.setCustomTxt01("12.02_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150394' extends '332283' salience 820

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "12.05.*")
        
    then
        $gda.setCustomTxt01("12.01_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150395' extends '332283' salience 810

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "13.11.*")
        
    then
        $gda.setCustomTxt01("13.11_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150396' extends '332283' salience 800

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "13.12.*")
        
    then
        $gda.setCustomTxt01("13.12_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150397' extends '332283' salience 790

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "13.21.*")
        
    then
        $gda.setCustomTxt01("13.21_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150398' extends '332283' salience 780

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "13.22.*")
        
    then
        $gda.setCustomTxt01("13.22_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150399' extends '332283' salience 770

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "13.31.*")
        
    then
        $gda.setCustomTxt01("13.21_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150400' extends '332283' salience 760

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "13.32.*")
        
    then
        $gda.setCustomTxt01("13.22_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150401' extends '332283' salience 750

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "13.41.*")
        
    then
        $gda.setCustomTxt01("13.31_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150402' extends '332283' salience 740

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "13.42.*")
        
    then
        $gda.setCustomTxt01("13.32_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150403' extends '332283' salience 730

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "13.51.*")
        
    then
        $gda.setCustomTxt01("13.33_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150404' extends '332283' salience 720

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "13.52.*")
        
    then
        $gda.setCustomTxt01("13.33_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150405' extends '332283' salience 710

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "14.01.*")
        
    then
        $gda.setCustomTxt01("14.01_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150406' extends '332283' salience 700

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "14.02.*")
        
    then
        $gda.setCustomTxt01("14.02_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150407' extends '332283' salience 690

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "14.11.*")
        
    then
        $gda.setCustomTxt01("14.11_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150408' extends '332283' salience 680

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "14.12.*")
        
    then
        $gda.setCustomTxt01("14.11_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150409' extends '332283' salience 670

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "14.13.*")
        
    then
        $gda.setCustomTxt01("14.12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150410' extends '332283' salience 660

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "14.21.*")
        
    then
        $gda.setCustomTxt01("14.22_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150411' extends '332283' salience 650

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "14.22.*")
        
    then
        $gda.setCustomTxt01("14.21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150412' extends '332283' salience 640

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "14.23.*")
        
    then
        $gda.setCustomTxt01("14.22_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150413' extends '332283' salience 630

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "14.24.*")
        
    then
        $gda.setCustomTxt01("14.21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150414' extends '332283' salience 620

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "15.11.*")
        
    then
        $gda.setCustomTxt01("15.11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150415' extends '332283' salience 610

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "15.12.*")
        
    then
        $gda.setCustomTxt01("15.12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150416' extends '332283' salience 600

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "15.21.*")
        
    then
        $gda.setCustomTxt01("15.21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150417' extends '332283' salience 590

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "15.31.*")
        
    then
        $gda.setCustomTxt01("15.21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150418' extends '332283' salience 580

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "15.32.*")
        
    then
        $gda.setCustomTxt01("15.31");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150419' extends '332283' salience 570

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "15.41.*")
        
    then
        $gda.setCustomTxt01("15.31");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150420' extends '332283' salience 560

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "15.42.*")
        
    then
        $gda.setCustomTxt01("15.41");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150421' extends '332283' salience 550

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "15.43.*")
        
    then
        $gda.setCustomTxt01("15.42");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150422' extends '332283' salience 540

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "15.51.*")
        
    then
        $gda.setCustomTxt01("15.31");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150423' extends '332283' salience 530

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "15.52.*")
        
    then
        $gda.setCustomTxt01("15.41");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150424' extends '332283' salience 520

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "15.53.*")
        
    then
        $gda.setCustomTxt01("15.42");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150425' extends '332283' salience 510

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "16.01.*")
        
    then
        $gda.setCustomTxt01("16.01");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150426' extends '332283' salience 500

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "17.01.*")
        
    then
        $gda.setCustomTxt01("17.01");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150427' extends '332283' salience 490

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "17.02.*")
        
    then
        $gda.setCustomTxt01("17.02");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150428' extends '332283' salience 480

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "18.01.*")
        
    then
        $gda.setCustomTxt01("18.01");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150429' extends '332283' salience 470

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "18.02.*")
        
    then
        $gda.setCustomTxt01("18.01");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150430' extends '332283' salience 460

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "18.03.*")
        
    then
        $gda.setCustomTxt01("18.01");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150431' extends '332283' salience 450

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "18.04.*")
        
    then
        $gda.setCustomTxt01("18.01");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150432' extends '332283' salience 440

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "18.05.*")
        
    then
        $gda.setCustomTxt01("18.01");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150433' extends '332283' salience 430

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "18.06.*")
        
    then
        $gda.setCustomTxt01("18.02_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150434' extends '332283' salience 420

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "18.07.*")
        
    then
        $gda.setCustomTxt01("18.03");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150435' extends '332283' salience 410

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "18.08.*")
        
    then
        $gda.setCustomTxt01("18.04");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150436' extends '332283' salience 400

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "18.09.*")
        
    then
        $gda.setCustomTxt01("18.05");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150438' extends '332283' salience 390

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "19.03.*")
        
    then
        $gda.setCustomTxt01("19.03");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1173485' extends '332283' salience 380

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "8.12.*")
        
    then
        $gda.setCustomTxt01("9.14");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1173486' extends '332283' salience 370

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "8.11.*")
        
    then
        $gda.setCustomTxt01("9.14");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1181683' extends '332283' salience 360

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "19.01.*")
        
    then
        $gda.setCustomTxt01("19.03");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150344' extends '332283' salience 350

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.15.*", repAssetInd == "N")
        
    then
        $gda.setCustomTxt01("17.01_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150349' extends '332283' salience 340

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.25.*", repAssetInd == "N")
        
    then
        $gda.setCustomTxt01("17.01_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150354' extends '332283' salience 330

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.35.*", repAssetInd == "N")
        
    then
        $gda.setCustomTxt01("17.01_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150358' extends '332283' salience 320

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.45.*", repAssetInd == "N")
        
    then
        $gda.setCustomTxt01("17.01_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150437' extends '332283' salience 310

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "19.03.*", actCode in ("L0234000", "L0238000", "L0252000", "L0255000"))
        
    then
        $gda.setCustomTxt01("15.42");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1152460' extends '332283' salience 300

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.15.*", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("9.01_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1152461' extends '332283' salience 290

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.25.*", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("9.01_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1152462' extends '332283' salience 280

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.35.*", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("9.01_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1152463' extends '332283' salience 270

    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.45.*", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("9.01_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end

rule '1150341' extends '332283' salience 260
no-loop
    when
        
        GrlDetAmounts(this == $gda, liquidityCd matches "5.13.*", getCase0_1150341() == "on_demand", pdtCode == "004400")
        
    then
        $gda.setCustomTxt01("5.11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3574");
        
end


