package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '331676'
	when
		$gda : GrlDetAmounts(( ( hpePdtType == "EQUITY SWAP" && hacAmtCl == "10" ) || ( hscAcctSubcl == "3017" && hacAmtCl == "01" ) ) && intInd == "N" && icInd == "N" && htyTradCat in ( "01" , "02" ))
	then
        
end





rule '1099083' extends '331676' salience 48970

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setDerivativesCombiCd(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1024016' extends '331676' salience 48960
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("66.510_1_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1024017' extends '331676' salience 48950
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_2_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1024018' extends '331676' salience 48940
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_3_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1024019' extends '331676' salience 48930
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_4_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1024020' extends '331676' salience 48920
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_5_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1024021' extends '331676' salience 48910
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_6_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1023972' extends '331676' salience 48900
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("66.510_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1023974' extends '331676' salience 48890
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1023976' extends '331676' salience 48880
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1023978' extends '331676' salience 48870
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1023980' extends '331676' salience 48860
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1023982' extends '331676' salience 48850
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1023997' extends '331676' salience 48840
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("66.510_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1023998' extends '331676' salience 48830
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("66.510_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1024000' extends '331676' salience 48820
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1024001' extends '331676' salience 48810
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1024002' extends '331676' salience 48800
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1024003' extends '331676' salience 48790
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1024004' extends '331676' salience 48780
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1024005' extends '331676' salience 48770
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1024006' extends '331676' salience 48760
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1024007' extends '331676' salience 48750
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1024008' extends '331676' salience 48740
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1024009' extends '331676' salience 48730
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1099077' extends '331676' salience 48720
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("66.510_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1099078' extends '331676' salience 48710
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1099079' extends '331676' salience 48700
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1099080' extends '331676' salience 48690
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1099081' extends '331676' salience 48680
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1099082' extends '331676' salience 48670
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1023973' extends '331676' salience 48660
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("66.510_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1023975' extends '331676' salience 48650
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1023977' extends '331676' salience 48640
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1023979' extends '331676' salience 48630
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1023981' extends '331676' salience 48620
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1023983' extends '331676' salience 48610
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("66.510_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1023999' extends '331676' salience 48600
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "B", getCase0_1022341() == "short_term", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("66.510_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1099071' extends '331676' salience 48590
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "<1_year", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("66.510_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1099072' extends '331676' salience 48580
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "1-<2_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("66.510_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1099073' extends '331676' salience 48570
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "2-<3_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("66.510_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1099074' extends '331676' salience 48560
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "3-<4_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("66.510_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1099075' extends '331676' salience 48550
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "4-<5_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("66.510_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end

rule '1099076' extends '331676' salience 48540
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == ">5_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("66.510_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3163");
        
end


