package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '331698'
	when
		$gda : GrlDetAmounts(( ( hpePdtType == "FRA" && hacAmtCl == "10" ) || ( hscAcctSubcl == "3002" && hacAmtCl == "01" ) ) && intInd == "N" && icInd == "N" && htyTradCat in ( "01" , "02" ))
	then
        
end





rule '1101486' extends '331698' salience 62630

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setDerivativesCombiCd(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022142' extends '331698' salience 62620
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("66.120_1_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022143' extends '331698' salience 62610
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_2_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022144' extends '331698' salience 62600
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_3_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022145' extends '331698' salience 62590
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_4_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022146' extends '331698' salience 62580
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_5_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022147' extends '331698' salience 62570
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_6_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022099' extends '331698' salience 62560
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("66.120_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022101' extends '331698' salience 62550
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022103' extends '331698' salience 62540
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022105' extends '331698' salience 62530
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022107' extends '331698' salience 62520
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022109' extends '331698' salience 62510
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022123' extends '331698' salience 62500
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("66.120_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022124' extends '331698' salience 62490
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("66.120_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022126' extends '331698' salience 62480
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022127' extends '331698' salience 62470
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022128' extends '331698' salience 62460
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022129' extends '331698' salience 62450
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022130' extends '331698' salience 62440
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022131' extends '331698' salience 62430
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022132' extends '331698' salience 62420
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022133' extends '331698' salience 62410
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022134' extends '331698' salience 62400
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022135' extends '331698' salience 62390
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1101474' extends '331698' salience 62380
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "<1_year", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("66.120_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1101475' extends '331698' salience 62370
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "1-<2_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("66.120_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1101476' extends '331698' salience 62360
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "2-<3_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("66.120_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1101477' extends '331698' salience 62350
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "3-<4_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("66.120_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1101478' extends '331698' salience 62340
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "4-<5_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("66.120_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1101479' extends '331698' salience 62330
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == ">5_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("66.120_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1101480' extends '331698' salience 62320
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("66.120_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1101481' extends '331698' salience 62310
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1101482' extends '331698' salience 62300
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1101483' extends '331698' salience 62290
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1101484' extends '331698' salience 62280
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1101485' extends '331698' salience 62270
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022098' extends '331698' salience 62260
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("66.120_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022100' extends '331698' salience 62250
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022102' extends '331698' salience 62240
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022104' extends '331698' salience 62230
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022106' extends '331698' salience 62220
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022108' extends '331698' salience 62210
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("66.120_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end

rule '1022125' extends '331698' salience 62200
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "B", getCase0_1022341() == "short_term", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("66.120_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3186");
        
end


