package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '331068'
	when
		$gda : GrlDetAmounts(( hpePdtType in ( "OTHER UNDERL SWAP" , "OTHER UNDERL OPT" , "OTHER UNDERL FORW" ) || ( hscAcctSubcl in ( "3021" , "3022" , "3023" , "3024" ) ) ) && hacAmtCl == "10" && intInd == "N" && icInd == "N" && htyTradCat in ( "01" , "02" ))
	then
        
end





rule '1025119' extends '331068' salience 44240

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setDerivativesCombiCd(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024923' extends '331068' salience 44230
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.820_1_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024924' extends '331068' salience 44220
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_2_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024925' extends '331068' salience 44210
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_3_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024926' extends '331068' salience 44200
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_4_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024927' extends '331068' salience 44190
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_5_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024928' extends '331068' salience 44180
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_6_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024985' extends '331068' salience 44170
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.810_1_R_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024986' extends '331068' salience 44160
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_2_R_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024987' extends '331068' salience 44150
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_3_R_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024988' extends '331068' salience 44140
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_4_R_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024989' extends '331068' salience 44130
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_5_R_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024990' extends '331068' salience 44120
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_6_R_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024991' extends '331068' salience 44110
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.810_1_R_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024992' extends '331068' salience 44100
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_2_R_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024993' extends '331068' salience 44090
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_3_R_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024994' extends '331068' salience 44080
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_4_R_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024995' extends '331068' salience 44070
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_5_R_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024996' extends '331068' salience 44060
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_6_R_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025120' extends '331068' salience 44050
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3024", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.830_1");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025121' extends '331068' salience 44040
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3024", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.830_2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025122' extends '331068' salience 44030
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3024", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.830_3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025123' extends '331068' salience 44020
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3024", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.830_4");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025124' extends '331068' salience 44010
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3024", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.830_5");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025125' extends '331068' salience 44000
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3024", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.830_6");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025126' extends '331068' salience 43990
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FUT", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.830_1");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025127' extends '331068' salience 43980
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FUT", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.830_2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025128' extends '331068' salience 43970
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FUT", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.830_3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025129' extends '331068' salience 43960
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FUT", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.830_4");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025130' extends '331068' salience 43950
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FUT", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.830_5");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025131' extends '331068' salience 43940
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FUT", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.830_6");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024929' extends '331068' salience 43930
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.820_1_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024930' extends '331068' salience 43920
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_2_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024931' extends '331068' salience 43910
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_3_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024932' extends '331068' salience 43900
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_4_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024933' extends '331068' salience 43890
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_5_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024934' extends '331068' salience 43880
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_6_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024997' extends '331068' salience 43870
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.845_1_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024998' extends '331068' salience 43860
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_2_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024999' extends '331068' salience 43850
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_3_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025000' extends '331068' salience 43840
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_4_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025001' extends '331068' salience 43830
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_5_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025002' extends '331068' salience 43820
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_6_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025003' extends '331068' salience 43810
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.845_1_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025004' extends '331068' salience 43800
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_2_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025005' extends '331068' salience 43790
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_3_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025006' extends '331068' salience 43780
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_4_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025007' extends '331068' salience 43770
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_5_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025008' extends '331068' salience 43760
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_6_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025059' extends '331068' salience 43750
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.845_1_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025060' extends '331068' salience 43740
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_2_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025061' extends '331068' salience 43730
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_3_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025062' extends '331068' salience 43720
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_4_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025063' extends '331068' salience 43710
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_5_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025064' extends '331068' salience 43700
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_6_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025065' extends '331068' salience 43690
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.845_1_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025066' extends '331068' salience 43680
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_2_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025067' extends '331068' salience 43670
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_3_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025068' extends '331068' salience 43660
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_4_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025069' extends '331068' salience 43650
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_5_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025070' extends '331068' salience 43640
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_6_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025095' extends '331068' salience 43630
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.840_1_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025096' extends '331068' salience 43620
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_2_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025097' extends '331068' salience 43610
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_3_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025098' extends '331068' salience 43600
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_4_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025099' extends '331068' salience 43590
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_5_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025100' extends '331068' salience 43580
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_6_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025101' extends '331068' salience 43570
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.840_1_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025102' extends '331068' salience 43560
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_2_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025103' extends '331068' salience 43550
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_3_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025104' extends '331068' salience 43540
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_4_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025105' extends '331068' salience 43530
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_5_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025106' extends '331068' salience 43520
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_6_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025107' extends '331068' salience 43510
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.840_1_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025108' extends '331068' salience 43500
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_2_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025109' extends '331068' salience 43490
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_3_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025110' extends '331068' salience 43480
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_4_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025111' extends '331068' salience 43470
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_5_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025112' extends '331068' salience 43460
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_6_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025113' extends '331068' salience 43450
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.840_1_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025114' extends '331068' salience 43440
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_2_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025115' extends '331068' salience 43430
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_3_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025116' extends '331068' salience 43420
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_4_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025117' extends '331068' salience 43410
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_5_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025118' extends '331068' salience 43400
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_6_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024874' extends '331068' salience 43390
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.820_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024876' extends '331068' salience 43380
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024878' extends '331068' salience 43370
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024880' extends '331068' salience 43360
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024882' extends '331068' salience 43350
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024884' extends '331068' salience 43340
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024897' extends '331068' salience 43330
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.820_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024898' extends '331068' salience 43320
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.820_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024900' extends '331068' salience 43310
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024901' extends '331068' salience 43300
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024902' extends '331068' salience 43290
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024903' extends '331068' salience 43280
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024904' extends '331068' salience 43270
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024905' extends '331068' salience 43260
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024906' extends '331068' salience 43250
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024907' extends '331068' salience 43240
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024908' extends '331068' salience 43230
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024909' extends '331068' salience 43220
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024935' extends '331068' salience 43210
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.810_1_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024937' extends '331068' salience 43200
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_2_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024939' extends '331068' salience 43190
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_3_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024941' extends '331068' salience 43180
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_4_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024943' extends '331068' salience 43170
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_5_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024945' extends '331068' salience 43160
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_6_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024947' extends '331068' salience 43150
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.810_1_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024949' extends '331068' salience 43140
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_2_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024951' extends '331068' salience 43130
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_3_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024953' extends '331068' salience 43120
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_4_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024955' extends '331068' salience 43110
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_5_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024957' extends '331068' salience 43100
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_6_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024959' extends '331068' salience 43090
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.810_1_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024960' extends '331068' salience 43080
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.810_1_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024962' extends '331068' salience 43070
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_2_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024963' extends '331068' salience 43060
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_2_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024964' extends '331068' salience 43050
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_3_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024965' extends '331068' salience 43040
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_3_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024966' extends '331068' salience 43030
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_4_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024967' extends '331068' salience 43020
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_4_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024968' extends '331068' salience 43010
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_5_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024969' extends '331068' salience 43000
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_5_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024970' extends '331068' salience 42990
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_6_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024971' extends '331068' salience 42980
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_6_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024972' extends '331068' salience 42970
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.810_1_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024973' extends '331068' salience 42960
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.810_1_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024975' extends '331068' salience 42950
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_2_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024976' extends '331068' salience 42940
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_2_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024977' extends '331068' salience 42930
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_3_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024978' extends '331068' salience 42920
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_3_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024979' extends '331068' salience 42910
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_4_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024980' extends '331068' salience 42900
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_4_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024981' extends '331068' salience 42890
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_5_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024982' extends '331068' salience 42880
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_5_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024983' extends '331068' salience 42870
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_6_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024984' extends '331068' salience 42860
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_6_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024873' extends '331068' salience 42850
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.820_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024875' extends '331068' salience 42840
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024877' extends '331068' salience 42830
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024879' extends '331068' salience 42820
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024881' extends '331068' salience 42810
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024883' extends '331068' salience 42800
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024886' extends '331068' salience 42790
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.820_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024888' extends '331068' salience 42780
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024890' extends '331068' salience 42770
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024892' extends '331068' salience 42760
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024894' extends '331068' salience 42750
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024896' extends '331068' salience 42740
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024899' extends '331068' salience 42730
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3022", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "B", getCase0_1022801() == "short_term", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.820_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024910' extends '331068' salience 42720
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.820_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024911' extends '331068' salience 42710
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.820_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024913' extends '331068' salience 42700
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024914' extends '331068' salience 42690
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024915' extends '331068' salience 42680
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024916' extends '331068' salience 42670
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024917' extends '331068' salience 42660
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024918' extends '331068' salience 42650
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024919' extends '331068' salience 42640
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024920' extends '331068' salience 42630
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024921' extends '331068' salience 42620
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024922' extends '331068' salience 42610
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024936' extends '331068' salience 42600
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.810_1_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024938' extends '331068' salience 42590
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_2_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024940' extends '331068' salience 42580
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_3_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024942' extends '331068' salience 42570
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_4_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024944' extends '331068' salience 42560
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_5_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024946' extends '331068' salience 42550
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_6_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024948' extends '331068' salience 42540
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.810_1_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024950' extends '331068' salience 42530
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_2_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024952' extends '331068' salience 42520
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_3_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024954' extends '331068' salience 42510
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_4_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024956' extends '331068' salience 42500
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_5_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024958' extends '331068' salience 42490
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.810_6_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024961' extends '331068' salience 42480
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3021", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "B", getCase0_1022801() == "short_term", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.810_1_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024974' extends '331068' salience 42470
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL SWAP", buyInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "B", getCase0_1022801() == "short_term", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.810_1_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025010' extends '331068' salience 42460
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.845_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025012' extends '331068' salience 42450
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025014' extends '331068' salience 42440
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025016' extends '331068' salience 42430
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025018' extends '331068' salience 42420
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025020' extends '331068' salience 42410
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025022' extends '331068' salience 42400
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.845_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025024' extends '331068' salience 42390
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025026' extends '331068' salience 42380
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025028' extends '331068' salience 42370
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025030' extends '331068' salience 42360
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025032' extends '331068' salience 42350
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025033' extends '331068' salience 42340
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.845_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025034' extends '331068' salience 42330
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.845_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025036' extends '331068' salience 42320
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025037' extends '331068' salience 42310
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025038' extends '331068' salience 42300
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025039' extends '331068' salience 42290
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025040' extends '331068' salience 42280
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025041' extends '331068' salience 42270
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025042' extends '331068' salience 42260
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025043' extends '331068' salience 42250
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025044' extends '331068' salience 42240
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025045' extends '331068' salience 42230
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025046' extends '331068' salience 42220
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.845_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025047' extends '331068' salience 42210
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.845_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025049' extends '331068' salience 42200
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025050' extends '331068' salience 42190
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025051' extends '331068' salience 42180
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025052' extends '331068' salience 42170
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025053' extends '331068' salience 42160
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025054' extends '331068' salience 42150
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025055' extends '331068' salience 42140
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025056' extends '331068' salience 42130
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025057' extends '331068' salience 42120
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025058' extends '331068' salience 42110
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025072' extends '331068' salience 42100
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.840_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025074' extends '331068' salience 42090
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025076' extends '331068' salience 42080
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025078' extends '331068' salience 42070
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025080' extends '331068' salience 42060
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025082' extends '331068' salience 42050
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025084' extends '331068' salience 42040
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.840_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025086' extends '331068' salience 42030
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025088' extends '331068' salience 42020
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025090' extends '331068' salience 42010
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025092' extends '331068' salience 42000
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025094' extends '331068' salience 41990
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025132' extends '331068' salience 41980
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.840_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025133' extends '331068' salience 41970
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.840_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025135' extends '331068' salience 41960
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025136' extends '331068' salience 41950
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025137' extends '331068' salience 41940
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025138' extends '331068' salience 41930
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025139' extends '331068' salience 41920
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025140' extends '331068' salience 41910
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025141' extends '331068' salience 41900
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025142' extends '331068' salience 41890
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025143' extends '331068' salience 41880
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025144' extends '331068' salience 41870
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025145' extends '331068' salience 41860
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.840_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025146' extends '331068' salience 41850
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.840_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025148' extends '331068' salience 41840
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025149' extends '331068' salience 41830
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025150' extends '331068' salience 41820
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025151' extends '331068' salience 41810
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025152' extends '331068' salience 41800
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025153' extends '331068' salience 41790
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025154' extends '331068' salience 41780
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025155' extends '331068' salience 41770
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025156' extends '331068' salience 41760
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025157' extends '331068' salience 41750
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024885' extends '331068' salience 41740
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.820_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024887' extends '331068' salience 41730
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024889' extends '331068' salience 41720
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024891' extends '331068' salience 41710
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024893' extends '331068' salience 41700
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024895' extends '331068' salience 41690
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.820_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1024912' extends '331068' salience 41680
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL FORW", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "B", getCase0_1022801() == "short_term", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.820_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025009' extends '331068' salience 41670
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.845_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025011' extends '331068' salience 41660
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025013' extends '331068' salience 41650
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025015' extends '331068' salience 41640
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025017' extends '331068' salience 41630
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025019' extends '331068' salience 41620
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025021' extends '331068' salience 41610
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.845_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025023' extends '331068' salience 41600
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025025' extends '331068' salience 41590
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025027' extends '331068' salience 41580
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025029' extends '331068' salience 41570
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025031' extends '331068' salience 41560
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.845_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025035' extends '331068' salience 41550
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "B", getCase0_1022801() == "short_term", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.845_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025048' extends '331068' salience 41540
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "B", getCase0_1022801() == "short_term", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.845_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025071' extends '331068' salience 41530
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.840_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025073' extends '331068' salience 41520
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025075' extends '331068' salience 41510
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025077' extends '331068' salience 41500
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025079' extends '331068' salience 41490
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025081' extends '331068' salience 41480
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025083' extends '331068' salience 41470
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.840_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025085' extends '331068' salience 41460
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025087' extends '331068' salience 41450
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025089' extends '331068' salience 41440
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025091' extends '331068' salience 41430
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025093' extends '331068' salience 41420
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("66.840_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025134' extends '331068' salience 41410
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "3023", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "B", getCase0_1022801() == "short_term", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.840_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end

rule '1025147' extends '331068' salience 41400
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "OTHER UNDERL OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "B", getCase0_1022801() == "short_term", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("66.840_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2691");
        
end


