package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '331681'
	when
		$gda : GrlDetAmounts(( hpePdtType == "FRA" || hscAcctSubcl == "3002" ) && hacAmtCl == "10" && intInd == "N" && icInd == "N" && htyTradCat == "03")
	then
        
end





rule '1100142' extends '331681' salience 39320

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setDerivativesCombiCd(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021757' extends '331681' salience 39310
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.120_1_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021758' extends '331681' salience 39300
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_2_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021759' extends '331681' salience 39290
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_3_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021760' extends '331681' salience 39280
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_4_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021761' extends '331681' salience 39270
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_5_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021762' extends '331681' salience 39260
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_6_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021714' extends '331681' salience 39250
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.120_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021716' extends '331681' salience 39240
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021718' extends '331681' salience 39230
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021720' extends '331681' salience 39220
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021722' extends '331681' salience 39210
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021724' extends '331681' salience 39200
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021738' extends '331681' salience 39190
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.120_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021739' extends '331681' salience 39180
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.120_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021741' extends '331681' salience 39170
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021742' extends '331681' salience 39160
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021743' extends '331681' salience 39150
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021744' extends '331681' salience 39140
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021745' extends '331681' salience 39130
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021746' extends '331681' salience 39120
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021747' extends '331681' salience 39110
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021748' extends '331681' salience 39100
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021749' extends '331681' salience 39090
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021750' extends '331681' salience 39080
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1100130' extends '331681' salience 39070
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.120_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1100131' extends '331681' salience 39060
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1100132' extends '331681' salience 39050
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1100133' extends '331681' salience 39040
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1100134' extends '331681' salience 39030
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1100135' extends '331681' salience 39020
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021713' extends '331681' salience 39010
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.120_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021715' extends '331681' salience 39000
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021717' extends '331681' salience 38990
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021719' extends '331681' salience 38980
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021721' extends '331681' salience 38970
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021723' extends '331681' salience 38960
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("67.120_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1021740' extends '331681' salience 38950
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "B", getCase0_1022801() == "short_term", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.120_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1100136' extends '331681' salience 38940
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "<1_year", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.120_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1100137' extends '331681' salience 38930
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "1-<2_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.120_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1100138' extends '331681' salience 38920
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "2-<3_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.120_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1100139' extends '331681' salience 38910
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "3-<4_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.120_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1100140' extends '331681' salience 38900
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "4-<5_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.120_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end

rule '1100141' extends '331681' salience 38890
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == ">5_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.120_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3171");
        
end


