package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '331684'
	when
		$gda : GrlDetAmounts(( ( hpePdtType == "EQUITY FORW" && hacAmtCl == "10" ) || ( hscAcctSubcl == "3018" && hacAmtCl == "01" ) ) && intInd == "N" && icInd == "N" && htyTradCat == "03")
	then
        
end





rule '1024239' extends '331684' salience 21160
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.520_1_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024240' extends '331684' salience 21150
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_2_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024241' extends '331684' salience 21140
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_3_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024242' extends '331684' salience 21130
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_4_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024243' extends '331684' salience 21120
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_5_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024244' extends '331684' salience 21110
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_6_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024196' extends '331684' salience 21100
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCEN", "GCEN"), hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.520_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024198' extends '331684' salience 21090
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCEN", "GCEN"), hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024200' extends '331684' salience 21080
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCEN", "GCEN"), hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024202' extends '331684' salience 21070
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCEN", "GCEN"), hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024204' extends '331684' salience 21060
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCEN", "GCEN"), hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024206' extends '331684' salience 21050
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCEN", "GCEN"), hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024220' extends '331684' salience 21040
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.520_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024221' extends '331684' salience 21030
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCRI", "BEXC", "BGVO", "BHOL", "BJVT", "BLIM", "BMLD", "BMOR", "BSPV"), hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.520_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024223' extends '331684' salience 21020
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024224' extends '331684' salience 21010
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCRI", "BEXC", "BGVO", "BHOL", "BJVT", "BLIM", "BMLD", "BMOR", "BSPV"), hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024225' extends '331684' salience 21000
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024226' extends '331684' salience 20990
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCRI", "BEXC", "BGVO", "BHOL", "BJVT", "BLIM", "BMLD", "BMOR", "BSPV"), hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024227' extends '331684' salience 20980
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024228' extends '331684' salience 20970
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCRI", "BEXC", "BGVO", "BHOL", "BJVT", "BLIM", "BMLD", "BMOR", "BSPV"), hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024229' extends '331684' salience 20960
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024230' extends '331684' salience 20950
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCRI", "BEXC", "BGVO", "BHOL", "BJVT", "BLIM", "BMLD", "BMOR", "BSPV"), hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024231' extends '331684' salience 20940
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024232' extends '331684' salience 20930
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCRI", "BEXC", "BGVO", "BHOL", "BJVT", "BLIM", "BMLD", "BMOR", "BSPV"), hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024195' extends '331684' salience 20920
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCEN", "GCEN"), hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.520_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024197' extends '331684' salience 20910
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCEN", "GCEN"), hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024199' extends '331684' salience 20900
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCEN", "GCEN"), hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024201' extends '331684' salience 20890
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCEN", "GCEN"), hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024203' extends '331684' salience 20880
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCEN", "GCEN"), hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024205' extends '331684' salience 20870
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCEN", "GCEN"), hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("67.520_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end

rule '1024222' extends '331684' salience 20860
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() in ("BCRI", "BEXC", "BGVO", "BHOL", "BJVT", "BLIM", "BMLD", "BMOR", "BSPV"), hzeZoneCtryReg == "B", getCase0_1022341() == "short_term", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.520_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3175");
        
end


