package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '331685'
	when
		$gda : GrlDetAmounts(( ( hpePdtType == "EQUITY OPT" && hacAmtCl == "10" ) || ( hscAcctSubcl == "3019" && hacAmtCl == "01" ) ) && intInd == "N" && icInd == "N" && htyTradCat == "03")
	then
        
end





rule '1024313' extends '331685' salience 20850
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022297() == "<1_year", quotedInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.545_1_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024314' extends '331685' salience 20840
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022297() == "1-<2_years", quotedInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.545_2_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024315' extends '331685' salience 20830
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022297() == "2-<3_years", quotedInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.545_3_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024316' extends '331685' salience 20820
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022297() == "3-<4_years", quotedInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.545_4_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024317' extends '331685' salience 20810
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022297() == "4-<5_years", quotedInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.545_5_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024318' extends '331685' salience 20800
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022297() == ">5_years", quotedInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.545_6_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024375' extends '331685' salience 20790
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022297() == "<1_year", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_1_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024376' extends '331685' salience 20780
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022297() == "1-<2_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_2_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024377' extends '331685' salience 20770
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022297() == "2-<3_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_3_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024378' extends '331685' salience 20760
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022297() == "3-<4_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_4_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024379' extends '331685' salience 20750
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022297() == "4-<5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_5_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024380' extends '331685' salience 20740
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022297() == ">5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_6_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024413' extends '331685' salience 20730
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022297() == "<1_year", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_1_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024414' extends '331685' salience 20720
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022297() == "1-<2_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_2_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024415' extends '331685' salience 20710
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022297() == "2-<3_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_3_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024416' extends '331685' salience 20700
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022297() == "3-<4_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_4_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024417' extends '331685' salience 20690
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022297() == "4-<5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_5_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024418' extends '331685' salience 20680
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022297() == ">5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_6_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024425' extends '331685' salience 20670
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022297() == "<1_year", quotedInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.540_1_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024426' extends '331685' salience 20660
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022297() == "1-<2_years", quotedInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.540_2_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024427' extends '331685' salience 20650
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022297() == "2-<3_years", quotedInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.540_3_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024428' extends '331685' salience 20640
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022297() == "3-<4_years", quotedInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.540_4_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024429' extends '331685' salience 20630
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022297() == "4-<5_years", quotedInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.540_5_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024430' extends '331685' salience 20620
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022297() == ">5_years", quotedInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.540_6_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024332' extends '331685' salience 20610
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024334' extends '331685' salience 20600
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024336' extends '331685' salience 20590
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024338' extends '331685' salience 20580
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024340' extends '331685' salience 20570
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024342' extends '331685' salience 20560
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024356' extends '331685' salience 20550
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024357' extends '331685' salience 20540
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024359' extends '331685' salience 20530
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024360' extends '331685' salience 20520
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024361' extends '331685' salience 20510
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024362' extends '331685' salience 20500
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024363' extends '331685' salience 20490
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024364' extends '331685' salience 20480
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024365' extends '331685' salience 20470
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024366' extends '331685' salience 20460
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024367' extends '331685' salience 20450
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024368' extends '331685' salience 20440
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024394' extends '331685' salience 20430
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024396' extends '331685' salience 20420
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024398' extends '331685' salience 20410
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024400' extends '331685' salience 20400
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024402' extends '331685' salience 20390
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024404' extends '331685' salience 20380
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024444' extends '331685' salience 20370
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024445' extends '331685' salience 20360
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024446' extends '331685' salience 20350
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024447' extends '331685' salience 20340
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024448' extends '331685' salience 20330
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024449' extends '331685' salience 20320
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024450' extends '331685' salience 20310
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024451' extends '331685' salience 20300
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024452' extends '331685' salience 20290
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024453' extends '331685' salience 20280
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024454' extends '331685' salience 20270
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024455' extends '331685' salience 20260
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100778' extends '331685' salience 20250
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "<1_year", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100779' extends '331685' salience 20240
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "1-<2_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100780' extends '331685' salience 20230
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "2-<3_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100781' extends '331685' salience 20220
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "3-<4_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100782' extends '331685' salience 20210
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "4-<5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100783' extends '331685' salience 20200
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == ">5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100784' extends '331685' salience 20190
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "<1_year", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100785' extends '331685' salience 20180
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "1-<2_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100786' extends '331685' salience 20170
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "2-<3_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100787' extends '331685' salience 20160
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "3-<4_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100788' extends '331685' salience 20150
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "4-<5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100789' extends '331685' salience 20140
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == ">5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024331' extends '331685' salience 20130
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "<1_year", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024333' extends '331685' salience 20120
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "1-<2_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024335' extends '331685' salience 20110
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "2-<3_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024337' extends '331685' salience 20100
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "3-<4_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024339' extends '331685' salience 20090
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "4-<5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024341' extends '331685' salience 20080
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == ">5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024358' extends '331685' salience 20070
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "B", getCase0_1022341() == "short_term", getCase0_1022297() == "<1_year", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024393' extends '331685' salience 20060
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "<1_year", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024395' extends '331685' salience 20050
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "1-<2_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024397' extends '331685' salience 20040
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "2-<3_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024399' extends '331685' salience 20030
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "3-<4_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024401' extends '331685' salience 20020
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "4-<5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024403' extends '331685' salience 20010
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == ">5_years", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1024406' extends '331685' salience 20000
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "B", getCase0_1022341() == "short_term", getCase0_1022297() == "<1_year", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100790' extends '331685' salience 19990
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "<1_year", euCtryInd == "Y", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100791' extends '331685' salience 19980
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "1-<2_years", euCtryInd == "Y", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100792' extends '331685' salience 19970
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "2-<3_years", euCtryInd == "Y", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100793' extends '331685' salience 19960
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "3-<4_years", euCtryInd == "Y", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100794' extends '331685' salience 19950
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "4-<5_years", euCtryInd == "Y", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100795' extends '331685' salience 19940
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == ">5_years", euCtryInd == "Y", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.540_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100796' extends '331685' salience 19930
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "<1_year", euCtryInd == "Y", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100797' extends '331685' salience 19920
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "1-<2_years", euCtryInd == "Y", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100798' extends '331685' salience 19910
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "2-<3_years", euCtryInd == "Y", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100799' extends '331685' salience 19900
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "3-<4_years", euCtryInd == "Y", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100800' extends '331685' salience 19890
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "4-<5_years", euCtryInd == "Y", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end

rule '1100801' extends '331685' salience 19880
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == ">5_years", euCtryInd == "Y", quotedInd == "N")
        
    then
        $gda.setDerivativesCombiCd("67.545_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3176");
        
end


