package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '334438'
	when
		$gda : GrlDetAmounts(hpePdtType == "CFD" && hacAmtCl == "10" && intInd == "N" && icInd == "N" && htyTradCat == "03")
	then
        
end





rule '1621185' extends '334438' salience 21600

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setDerivativesCombiCd(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621187' extends '334438' salience 21590
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.510_1_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621188' extends '334438' salience 21580
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_2_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621189' extends '334438' salience 21570
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_3_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621190' extends '334438' salience 21560
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_4_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621191' extends '334438' salience 21550
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_5_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621192' extends '334438' salience 21540
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_6_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621179' extends '334438' salience 21530
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.510_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621180' extends '334438' salience 21520
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621181' extends '334438' salience 21510
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621182' extends '334438' salience 21500
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621183' extends '334438' salience 21490
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621184' extends '334438' salience 21480
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "MULTILATERAL_DEVELOPMENT_BANKS", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621193' extends '334438' salience 21470
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.510_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621195' extends '334438' salience 21460
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621197' extends '334438' salience 21450
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621199' extends '334438' salience 21440
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621201' extends '334438' salience 21430
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621203' extends '334438' salience 21420
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621205' extends '334438' salience 21410
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.510_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621207' extends '334438' salience 21400
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621208' extends '334438' salience 21390
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621209' extends '334438' salience 21380
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621210' extends '334438' salience 21370
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621211' extends '334438' salience 21360
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621212' extends '334438' salience 21350
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.510_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621213' extends '334438' salience 21340
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621214' extends '334438' salience 21330
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621215' extends '334438' salience 21320
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621216' extends '334438' salience 21310
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621217' extends '334438' salience 21300
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621174' extends '334438' salience 21290
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "1-<2_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.510_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621175' extends '334438' salience 21280
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "2-<3_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.510_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621176' extends '334438' salience 21270
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "3-<4_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.510_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621177' extends '334438' salience 21260
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "4-<5_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.510_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621178' extends '334438' salience 21250
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == ">5_years", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.510_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621186' extends '334438' salience 21240
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "LOCAL_GOVERNMENTS", getCase0_1022297() == "<1_year", euCtryInd == "Y")
        
    then
        $gda.setDerivativesCombiCd("67.510_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621194' extends '334438' salience 21230
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.510_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621196' extends '334438' salience 21220
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "1-<2_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621198' extends '334438' salience 21210
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "2-<3_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621200' extends '334438' salience 21200
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "3-<4_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621202' extends '334438' salience 21190
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == "4-<5_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621204' extends '334438' salience 21180
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022297() == ">5_years")
        
    then
        $gda.setDerivativesCombiCd("67.510_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end

rule '1621206' extends '334438' salience 21170
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "B", getCase0_1022341() == "short_term", getCase0_1022297() == "<1_year")
        
    then
        $gda.setDerivativesCombiCd("67.510_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5119");
        
end


