package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '331066'
	when
		$gda : GrlDetAmounts(hpePdtType in ( "GOLD FORW" , "GOLD OPT" , "GOLD SWAP" ) && hacAmtCl == "10" && intInd == "N" && icInd == "N" && htyTradCat == "03")
	then
        
end





rule '1024860' extends '331066' salience 19360

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setDerivativesCombiCd(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024792' extends '331066' salience 19350
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.710_1_R_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024793' extends '331066' salience 19340
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_2_R_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024794' extends '331066' salience 19330
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_3_R_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024795' extends '331066' salience 19320
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_4_R_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024796' extends '331066' salience 19310
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_5_R_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024797' extends '331066' salience 19300
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_6_R_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024761' extends '331066' salience 19290
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.720_1_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024762' extends '331066' salience 19280
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_2_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024763' extends '331066' salience 19270
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_3_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024764' extends '331066' salience 19260
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_4_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024765' extends '331066' salience 19250
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_5_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024766' extends '331066' salience 19240
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_6_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024798' extends '331066' salience 19230
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.745_1_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024799' extends '331066' salience 19220
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_2_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024800' extends '331066' salience 19210
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_3_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024801' extends '331066' salience 19200
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_4_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024802' extends '331066' salience 19190
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_5_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024803' extends '331066' salience 19180
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_6_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024829' extends '331066' salience 19170
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.745_1_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024830' extends '331066' salience 19160
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_2_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024831' extends '331066' salience 19150
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_3_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024832' extends '331066' salience 19140
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_4_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024833' extends '331066' salience 19130
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_5_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024834' extends '331066' salience 19120
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_6_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024848' extends '331066' salience 19110
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.740_1_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024849' extends '331066' salience 19100
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_2_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024850' extends '331066' salience 19090
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_3_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024851' extends '331066' salience 19080
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_4_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024852' extends '331066' salience 19070
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_5_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024853' extends '331066' salience 19060
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_6_84");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024854' extends '331066' salience 19050
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.740_1_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024855' extends '331066' salience 19040
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_2_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024856' extends '331066' salience 19030
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_3_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024857' extends '331066' salience 19020
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_4_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024858' extends '331066' salience 19010
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_5_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024859' extends '331066' salience 19000
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_6_EX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024767' extends '331066' salience 18990
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.710_1_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024769' extends '331066' salience 18980
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_2_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024771' extends '331066' salience 18970
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_3_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024773' extends '331066' salience 18960
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_4_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024775' extends '331066' salience 18950
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_5_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024777' extends '331066' salience 18940
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_6_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024779' extends '331066' salience 18930
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.710_1_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024780' extends '331066' salience 18920
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.710_1_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024782' extends '331066' salience 18910
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_2_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024783' extends '331066' salience 18900
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_2_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024784' extends '331066' salience 18890
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_3_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024785' extends '331066' salience 18880
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_3_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024786' extends '331066' salience 18870
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_4_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024787' extends '331066' salience 18860
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_4_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024788' extends '331066' salience 18850
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_5_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024789' extends '331066' salience 18840
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_5_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024790' extends '331066' salience 18830
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_6_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024791' extends '331066' salience 18820
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_6_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024737' extends '331066' salience 18810
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.720_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024739' extends '331066' salience 18800
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024741' extends '331066' salience 18790
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024743' extends '331066' salience 18780
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024745' extends '331066' salience 18770
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024747' extends '331066' salience 18760
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024748' extends '331066' salience 18750
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.720_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024749' extends '331066' salience 18740
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.720_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024751' extends '331066' salience 18730
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024752' extends '331066' salience 18720
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024753' extends '331066' salience 18710
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024754' extends '331066' salience 18700
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024755' extends '331066' salience 18690
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024756' extends '331066' salience 18680
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024757' extends '331066' salience 18670
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024758' extends '331066' salience 18660
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024759' extends '331066' salience 18650
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024760' extends '331066' salience 18640
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024768' extends '331066' salience 18630
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.710_1_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024770' extends '331066' salience 18620
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_2_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024772' extends '331066' salience 18610
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_3_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024774' extends '331066' salience 18600
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_4_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024776' extends '331066' salience 18590
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_5_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024778' extends '331066' salience 18580
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.710_6_R_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024781' extends '331066' salience 18570
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD SWAP", buyInd == "Y", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "B", getCase0_1022801() == "short_term", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.710_1_R_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024805' extends '331066' salience 18560
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.745_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024807' extends '331066' salience 18550
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024809' extends '331066' salience 18540
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024811' extends '331066' salience 18530
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024813' extends '331066' salience 18520
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024815' extends '331066' salience 18510
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024816' extends '331066' salience 18500
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.745_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024817' extends '331066' salience 18490
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.745_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024819' extends '331066' salience 18480
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024820' extends '331066' salience 18470
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024821' extends '331066' salience 18460
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024822' extends '331066' salience 18450
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024823' extends '331066' salience 18440
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024824' extends '331066' salience 18430
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024825' extends '331066' salience 18420
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024826' extends '331066' salience 18410
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024827' extends '331066' salience 18400
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024828' extends '331066' salience 18390
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024836' extends '331066' salience 18380
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.740_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024838' extends '331066' salience 18370
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024840' extends '331066' salience 18360
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024842' extends '331066' salience 18350
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024844' extends '331066' salience 18340
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024846' extends '331066' salience 18330
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024861' extends '331066' salience 18320
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.740_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024862' extends '331066' salience 18310
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.740_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024863' extends '331066' salience 18300
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024864' extends '331066' salience 18290
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_2_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024865' extends '331066' salience 18280
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024866' extends '331066' salience 18270
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_3_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024867' extends '331066' salience 18260
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024868' extends '331066' salience 18250
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_4_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024869' extends '331066' salience 18240
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024870' extends '331066' salience 18230
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_5_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024871' extends '331066' salience 18220
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "LOCAL_GOVERNMENTS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024872' extends '331066' salience 18210
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "A", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_6_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024736' extends '331066' salience 18200
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.720_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024738' extends '331066' salience 18190
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024740' extends '331066' salience 18180
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024742' extends '331066' salience 18170
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024744' extends '331066' salience 18160
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024746' extends '331066' salience 18150
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.720_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024750' extends '331066' salience 18140
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD FORW", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "B", getCase0_1022801() == "short_term", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.720_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024804' extends '331066' salience 18130
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.745_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024806' extends '331066' salience 18120
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024808' extends '331066' salience 18110
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024810' extends '331066' salience 18100
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024812' extends '331066' salience 18090
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024814' extends '331066' salience 18080
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.745_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024818' extends '331066' salience 18070
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "N", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "B", getCase0_1022801() == "short_term", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.745_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024835' extends '331066' salience 18060
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.740_1_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024837' extends '331066' salience 18050
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_one_and_two_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_2_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024839' extends '331066' salience 18040
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_two_and_three_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_3_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024841' extends '331066' salience 18030
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_three_and_four_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_4_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024843' extends '331066' salience 18020
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "between_four_and_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_5_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024845' extends '331066' salience 18010
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "CENTRAL BANKS_CENTRAL GOVERNMENTS", hzeZoneCtryReg == "B", locFundInd == "Y", getCase0_1022856() == "more_than_five_years")
        
    then
        $gda.setDerivativesCombiCd("67.740_6_80");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end

rule '1024847' extends '331066' salience 18000
no-loop
    when
        
        GrlDetAmounts(this == $gda, hpePdtType == "GOLD OPT", buyInd == "Y", quotedInd == "N", getCase0_1022323() == "OTHER_BANKS", hzeZoneCtryReg == "B", getCase0_1022801() == "short_term", getCase0_1022856() == "between_three_and_twelve_months")
        
    then
        $gda.setDerivativesCombiCd("67.740_1_83");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2690");
        
end


