package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '332542'
	when
		$gda : GrlDetAmounts(hpePdtType == "REPO" && intInd == "N")
	then
        
end





rule '1175879' extends '332542' salience 1530

    when
        
        GrlDetAmounts(this == $gda, hacAmtCl in ("11", "19"))
        
    then
        $gda.setLegType("S");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3682");
        
end

rule '1175880' extends '332542' salience 1520

    when
        
        GrlDetAmounts(this == $gda, hacAmtCl in ("01", "02", "03", "12", "16"))
        
    then
        $gda.setLegType("C");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3682");
        
end

rule '1175881' extends '332542' salience 1510

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl in ("11", "19"), sblSecVsSecInd == "Y")
        
    then
        $gda.setLegType("L");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3682");
        
end

rule '1175882' extends '332542' salience 1500

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("11", "19"), sblSecVsSecInd == "Y")
        
    then
        $gda.setLegType("B");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3682");
        
end


