package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlPlYtd;




dialect  "mvel"


rule '338640'
	when
		$gpy : GrlPlYtd(hpnPlCl in ( "6000" , "7000" ) && ldeDeptCd matches ( "SG001%" ) && nvl ( massLine , 0 ) not in ( "Corporate Tax Financial Accounting" , "Specific Debtor Provisions" , "IBNR Debtor Provisions" ))
	then
        
end





rule '2014524' extends '338640' salience 4870

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E10370010", "E10370011", "E10370020", "E10370021"))
        
    then
        $gpy.setLocMassLine("Advertising & promotion");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014525' extends '338640' salience 4860

    when
        
        GrlPlYtd(this == $gpy, ownUse03 == "E11940020")
        
    then
        $gpy.setLocMassLine("Amortisation of Club Membership");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014526' extends '338640' salience 4850

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8291000")
        
    then
        $gpy.setLocMassLine("Bank Levy");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014528' extends '338640' salience 4840

    when
        
        GrlPlYtd(this == $gpy, ownUse03 == "E10050010")
        
    then
        $gpy.setLocMassLine("CDC BCP");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014529' extends '338640' salience 4830

    when
        
        GrlPlYtd(this == $gpy, ownUse03 == "E11970020")
        
    then
        $gpy.setLocMassLine("CDC Desktop Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014533' extends '338640' salience 4820

    when
        
        GrlPlYtd(this == $gpy, ownUse03 == "E10050020")
        
    then
        $gpy.setLocMassLine("CDC Occupancy");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014535' extends '338640' salience 4810

    when
        
        GrlPlYtd(this == $gpy, ownUse03 == "E12570110")
        
    then
        $gpy.setLocMassLine("CDC-Leasing");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014537' extends '338640' salience 4800

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0183000")
        
    then
        $gpy.setLocMassLine("Communication Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014546' extends '338640' salience 4790

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0126000")
        
    then
        $gpy.setLocMassLine("Contracted staff");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014547' extends '338640' salience 4780

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0109000")
        
    then
        $gpy.setLocMassLine("Corporate Taxes");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014548' extends '338640' salience 4770

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0138000")
        
    then
        $gpy.setLocMassLine("Courier charges");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014549' extends '338640' salience 4760

    when
        
        GrlPlYtd(this == $gpy, actCode == "E6684000")
        
    then
        $gpy.setLocMassLine("Deferred cash bonus");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014550' extends '338640' salience 4750

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0112000")
        
    then
        $gpy.setLocMassLine("Deferred Tax");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014551' extends '338640' salience 4740

    when
        
        GrlPlYtd(this == $gpy, ownUse03 == "E11980010")
        
    then
        $gpy.setLocMassLine("Depr - Bank Owned Cars");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014552' extends '338640' salience 4730

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0176000")
        
    then
        $gpy.setLocMassLine("Depr - Computer SW");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014553' extends '338640' salience 4720

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0078000")
        
    then
        $gpy.setLocMassLine("Depr - Leasehold Improvement");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014554' extends '338640' salience 4710

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E11970010", "E11970030", "E11970040", "E11970050"))
        
    then
        $gpy.setLocMassLine("Depr - Mainframe and Personnel Computers (For CDC)");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014555' extends '338640' salience 4700

    when
        
        GrlPlYtd(this == $gpy, ownUse03 == "E11990010")
        
    then
        $gpy.setLocMassLine("Depr - Office Equipment");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014556' extends '338640' salience 4690

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0182000")
        
    then
        $gpy.setLocMassLine("Depr - Other EDP Equipment");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014557' extends '338640' salience 4680

    when
        
        GrlPlYtd(this == $gpy, ownUse03 == "E11930010")
        
    then
        $gpy.setLocMassLine("Depr - Other Fixed Assets");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014558' extends '338640' salience 4670

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E12040010", "E12040020", "E12040030"))
        
    then
        $gpy.setLocMassLine("Depr - Property Leases (IFRS 16)");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014559' extends '338640' salience 4660

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E10370030", "E10370040"))
        
    then
        $gpy.setLocMassLine("Donations");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014560' extends '338640' salience 4650

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E12570100", "E12570101"))
        
    then
        $gpy.setLocMassLine("EDP Expenses Not Specified");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014561' extends '338640' salience 4640

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E12270030", "E12270031"))
        
    then
        $gpy.setLocMassLine("EE - Hotel");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014562' extends '338640' salience 4630

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E12270040", "E12270041"))
        
    then
        $gpy.setLocMassLine("EE - Other Course Related Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014563' extends '338640' salience 4620

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E12270070", "E12270071", "E12270080", "E12270081", "E12270090", "E12270091", "E12270100"))
        
    then
        $gpy.setLocMassLine("EE - Other Course Related Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014564' extends '338640' salience 4610

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E12270050", "E12270060", "E12270051"))
        
    then
        $gpy.setLocMassLine("EE - Seminar & Course Fee");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014565' extends '338640' salience 4600

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E12270010", "E12270020"))
        
    then
        $gpy.setLocMassLine("EE - Travel Airfare");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014573' extends '338640' salience 4590

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7997000")
        
    then
        $gpy.setLocMassLine("Expenses for leased cars (own staff)");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014574' extends '338640' salience 4580

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8003000")
        
    then
        $gpy.setLocMassLine("External Auditor Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014575' extends '338640' salience 4570

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8002000")
        
    then
        $gpy.setLocMassLine("External Outsource Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014576' extends '338640' salience 4560

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8236000")
        
    then
        $gpy.setLocMassLine("Fair Value Expenses Deferred Bonus");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014577' extends '338640' salience 4550

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E12540010", "E12540020"))
        
    then
        $gpy.setLocMassLine("Fair Value LT Sustainable Performance Plan");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014578' extends '338640' salience 4540

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E12540030", "E12540040"))
        
    then
        $gpy.setLocMassLine("Fair Value Performance Shares Equity Settled");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014579' extends '338640' salience 4530

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8296000")
        
    then
        $gpy.setLocMassLine("Fair Value Upfront Shares Equity Settled");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014581' extends '338640' salience 4520

    when
        
        GrlPlYtd(this == $gpy, ownUse03 == "E12349910")
        
    then
        $gpy.setLocMassLine("Group Staff Department Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014582' extends '338640' salience 4510

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0174000")
        
    then
        $gpy.setLocMassLine("IC Services Bought");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014584' extends '338640' salience 4500

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0175000")
        
    then
        $gpy.setLocMassLine("IC Services Sold");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014585' extends '338640' salience 4490

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E11940010", "E12810010"))
        
    then
        $gpy.setLocMassLine("Impairment");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014588' extends '338640' salience 4480

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9520000")
        
    then
        $gpy.setLocMassLine("IT Equipment - Software Maintenance");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014589' extends '338640' salience 4470

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0124000")
        
    then
        $gpy.setLocMassLine("IT Purchases - Hardware");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014595' extends '338640' salience 4460

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7998000")
        
    then
        $gpy.setLocMassLine("Maintenance Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014596' extends '338640' salience 4450

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8001000")
        
    then
        $gpy.setLocMassLine("Management Consultancy");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014598' extends '338640' salience 4440

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000")
        
    then
        $gpy.setLocMassLine("Miscellaneous expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014599' extends '338640' salience 4430

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E10050030", "E10050031", "E10050050", "E10050051", "E12040040"))
        
    then
        $gpy.setLocMassLine("Office Rent");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014600' extends '338640' salience 4420

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E10050040", "E10050041"))
        
    then
        $gpy.setLocMassLine("Office Rent - DRC");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014601' extends '338640' salience 4410

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E10050060", "E10050061", "E12040050"))
        
    then
        $gpy.setLocMassLine("Office Rental");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014602' extends '338640' salience 4400

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E8000000", "E0079000"))
        
    then
        $gpy.setLocMassLine("Office Running Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014604' extends '338640' salience 4390

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9778000")
        
    then
        $gpy.setLocMassLine("Other Lease Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014605' extends '338640' salience 4380

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0130000")
        
    then
        $gpy.setLocMassLine("Other MDS");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014607' extends '338640' salience 4370

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8004000")
        
    then
        $gpy.setLocMassLine("Other Professional Svcs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014609' extends '338640' salience 4360

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0181000")
        
    then
        $gpy.setLocMassLine("Other Welfare & Benefits");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014611' extends '338640' salience 4350

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9819000")
        
    then
        $gpy.setLocMassLine("Outsourcing charges");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014613' extends '338640' salience 4340

    when
        
        GrlPlYtd(this == $gpy, ownUse03 == "E10330021")
        
    then
        $gpy.setLocMassLine("Pension Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014614' extends '338640' salience 4330

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E10320010", "E10330020"))
        
    then
        $gpy.setLocMassLine("Pension Fund");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014616' extends '338640' salience 4320

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0162000")
        
    then
        $gpy.setLocMassLine("Postage charges");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014619' extends '338640' salience 4310

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9794000")
        
    then
        $gpy.setLocMassLine("Recruitment cost");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014620' extends '338640' salience 4300

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E12570120", "E12570121"))
        
    then
        $gpy.setLocMassLine("Rental - EDP Equipt");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014621' extends '338640' salience 4290

    when
        
        GrlPlYtd(this == $gpy, ownUse03 == "E10330010")
        
    then
        $gpy.setLocMassLine("Retirement Allowance");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014624' extends '338640' salience 4280

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0173000")
        
    then
        $gpy.setLocMassLine("Salaries & Wages");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014628' extends '338640' salience 4270

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8644000")
        
    then
        $gpy.setLocMassLine("Single Resolution Mechanism");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014630' extends '338640' salience 4260

    when
        
        GrlPlYtd(this == $gpy, ownUse03 in ("E10370050", "E10370070", "E10370060", "E10370051"))
        
    then
        $gpy.setLocMassLine("Sponsorship");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014634' extends '338640' salience 4250

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0149000")
        
    then
        $gpy.setLocMassLine("Stationery & office supplies");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014635' extends '338640' salience 4240

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0177000")
        
    then
        $gpy.setLocMassLine("Subscriptions and membership fees");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014636' extends '338640' salience 4230

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0172000")
        
    then
        $gpy.setLocMassLine("Sundry Restructuring Expense");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014640' extends '338640' salience 4220

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7996000")
        
    then
        $gpy.setLocMassLine("Travel - Others");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014642' extends '338640' salience 4210

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0096000")
        
    then
        $gpy.setLocMassLine("Upfront Cash Bonus");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014645' extends '338640' salience 4200

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setLocMassLine("99.999");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014527' extends '338640' salience 4190

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0130000", ownUse03 in ("E12930010", "E12930011"))
        
    then
        $gpy.setLocMassLine("Bloomberg");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014530' extends '338640' salience 4180

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0130000", ownUse03 == "E12930020")
        
    then
        $gpy.setLocMassLine("CDC MDS-Bloomberg");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014531' extends '338640' salience 4170

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0130000", ownUse03 in ("E12930022", "E12930023", "E12930024", "E12930025", "E12930027", "E12930028"))
        
    then
        $gpy.setLocMassLine("CDC MDS-Other MDS");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014532' extends '338640' salience 4160

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0130000", ownUse03 == "E12930026")
        
    then
        $gpy.setLocMassLine("CDC MDS-Reuters");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014534' extends '338640' salience 4150

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0183000", ownUse03 in ("E14920020", "E14920050", "E14920030", "E14920040"))
        
    then
        $gpy.setLocMassLine("CDC Telecom & Network Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014536' extends '338640' salience 4140

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000", ownUse03 == "E14890140")
        
    then
        $gpy.setLocMassLine("Charges between departments");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014538' extends '338640' salience 4130

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0183000", ownUse03 in ("E14920060", "E14920070", "E14920071", "E14920130", "E14920131"))
        
    then
        $gpy.setLocMassLine("Communication Expenses - Data");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014539' extends '338640' salience 4120

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0183000", ownUse03 in ("E14920090", "E14920091"))
        
    then
        $gpy.setLocMassLine("Communication Expenses - International Leased Line Charges");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014540' extends '338640' salience 4110

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0183000", ownUse03 in ("E14920080", "E14920081"))
        
    then
        $gpy.setLocMassLine("Communication Expenses - Internet Charges");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014541' extends '338640' salience 4100

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0183000", ownUse03 == "E14920100")
        
    then
        $gpy.setLocMassLine("Communication Expenses - Local Leased Line Charges");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014542' extends '338640' salience 4090

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0183000", ownUse03 in ("E14920010", "E14920011", "E14920111", "E14920120", "E14920121", "E14920110"))
        
    then
        $gpy.setLocMassLine("Communication Expenses - Mobile Charges");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014543' extends '338640' salience 4080

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0183000", ownUse03 in ("E14920140", "E14920170", "E14920161", "E14920160", "E14920141"))
        
    then
        $gpy.setLocMassLine("Communication Expenses - Others");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014544' extends '338640' salience 4070

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0183000", ownUse03 in ("E14920150", "E14920151", "E14920180", "E14920181", "E14920190", "E14920191", "E14920202", "E14920200", "E14920201"))
        
    then
        $gpy.setLocMassLine("Communication Expenses - Voice");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014545' extends '338640' salience 4060

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000", ownUse03 == "E14890170")
        
    then
        $gpy.setLocMassLine("Consumption Tax");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014566' extends '338640' salience 4050

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7996000", ownUse03 in ("E14980200", "E14980201"))
        
    then
        $gpy.setLocMassLine("Entertainment Internal");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014567' extends '338640' salience 4040

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7996000", ownUse03 in ("E14980100", "E14980101", "E14980300", "E14980301"))
        
    then
        $gpy.setLocMassLine("Entertainment of Clients");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014568' extends '338640' salience 4030

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0181000", ownUse03 == "E14900070")
        
    then
        $gpy.setLocMassLine("Expats Child Education");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014569' extends '338640' salience 4020

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0181000", ownUse03 == "E14900020")
        
    then
        $gpy.setLocMassLine("Expats Home Leave");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014570' extends '338640' salience 4010

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0181000", ownUse03 in ("E14900010", "E14900011", "E14900030", "E14900040", "E14900041", "E14900060", "E14900061", "E14900080", "E14900081"))
        
    then
        $gpy.setLocMassLine("Expats Housing & Related Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014571' extends '338640' salience 4000

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0181000", ownUse03 in ("E14900050", "E14900051"))
        
    then
        $gpy.setLocMassLine("Expats Relocation");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014572' extends '338640' salience 3990

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7996000")
        
    then
        $gpy.setLocMassLine("Expenses - Bank Owned Cars");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014580' extends '338640' salience 3980

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0173000", ownUse03 in ("E14720100", "E14720110"))
        
    then
        $gpy.setLocMassLine("Gratifications");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014583' extends '338640' salience 3970

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0174000", ownUse03 == "E12649921")
        
    then
        $gpy.setLocMassLine("IC Services Bought NL Direct Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014586' extends '338640' salience 3960

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0130000", ownUse03 == "E12930101")
        
    then
        $gpy.setLocMassLine("Information Services Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014587' extends '338640' salience 3950

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0124000", ownUse03 in ("E12570060", "E12570061", "E12570070", "E12570080", "E12570090"))
        
    then
        $gpy.setLocMassLine("IT Equipment - Hardware Maintenance");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014590' extends '338640' salience 3940

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0124000", ownUse03 == "E12570020")
        
    then
        $gpy.setLocMassLine("IT Purchases - Hardware (Server)");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014591' extends '338640' salience 3930

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9520000", ownUse03 in ("E14830010", "E14830011"))
        
    then
        $gpy.setLocMassLine("IT Purchases - Software");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014592' extends '338640' salience 3920

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0154000", ownUse03 in ("E14820060", "E14820070"))
        
    then
        $gpy.setLocMassLine("Labour & Medical Insurance");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014593' extends '338640' salience 3910

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8004000", ownUse03 in ("E13630020", "E13630021"))
        
    then
        $gpy.setLocMassLine("Legal Professional Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014594' extends '338640' salience 3900

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0154000", ownUse03 in ("E14820010", "E14820020", "E14820030", "E14820040"))
        
    then
        $gpy.setLocMassLine("Local Provident Fund & Social Securities");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014597' extends '338640' salience 3890

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0181000", ownUse03 == "E14900140")
        
    then
        $gpy.setLocMassLine("Medical & dental fees");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014603' extends '338640' salience 3880

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000", ownUse03 in ("E14890081", "E14890181", "E14890180"))
        
    then
        $gpy.setLocMassLine("Other Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014606' extends '338640' salience 3870

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0181000", ownUse03 == "E14900340")
        
    then
        $gpy.setLocMassLine("Other Personnel Related Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014608' extends '338640' salience 3860

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000", ownUse03 in ("E14890150", "E14890152", "E14890153"))
        
    then
        $gpy.setLocMassLine("Other Tax");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014610' extends '338640' salience 3850

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8004000", ownUse03 in ("E13630010", "E13630011"))
        
    then
        $gpy.setLocMassLine("Outsource - IT");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014612' extends '338640' salience 3840

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000", ownUse03 in ("E14890090", "E14890091"))
        
    then
        $gpy.setLocMassLine("Outsourcing charges");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014615' extends '338640' salience 3830

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0154000", ownUse03 == "E14820050")
        
    then
        $gpy.setLocMassLine("Personal Income Tax");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014617' extends '338640' salience 3820

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000", ownUse03 in ("E14890110", "E14890111"))
        
    then
        $gpy.setLocMassLine("Printing");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014618' extends '338640' salience 3810

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0079000", ownUse03 == "E10040060")
        
    then
        $gpy.setLocMassLine("Property Tax");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014622' extends '338640' salience 3800

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0130000", ownUse03 in ("E12930161", "E12930160"))
        
    then
        $gpy.setLocMassLine("Reuters");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014623' extends '338640' salience 3790

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000", ownUse03 == "E14890120")
        
    then
        $gpy.setLocMassLine("Risk Management Programme Insurance");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014625' extends '338640' salience 3780

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8004000", ownUse03 in ("E13630050", "E13630051"))
        
    then
        $gpy.setLocMassLine("Secretarial Fees");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014626' extends '338640' salience 3770

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0181000", ownUse03 == "E14900320")
        
    then
        $gpy.setLocMassLine("Service Award");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014627' extends '338640' salience 3760

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0173000", ownUse03 == "E14720140")
        
    then
        $gpy.setLocMassLine("Severance cost");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014629' extends '338640' salience 3750

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9520000", ownUse03 in ("E14830021", "E14830051"))
        
    then
        $gpy.setLocMassLine("Software Expenses not Capitalised");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014631' extends '338640' salience 3740

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0173000", ownUse03 == "E14720130")
        
    then
        $gpy.setLocMassLine("Staff costs allocated to projects");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014632' extends '338640' salience 3730

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0181000", ownUse03 in ("E14900120", "E14900130", "E14900280"))
        
    then
        $gpy.setLocMassLine("Staff insurance");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014633' extends '338640' salience 3720

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0181000", ownUse03 == "E14900260")
        
    then
        $gpy.setLocMassLine("Staff Social Club Membership/Subscription");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014637' extends '338640' salience 3710

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8004000", ownUse03 in ("E13630060", "E13630061"))
        
    then
        $gpy.setLocMassLine("Tax Professional Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014638' extends '338640' salience 3700

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7996000", ownUse03 in ("E14980010", "E14980011", "E14980020"))
        
    then
        $gpy.setLocMassLine("Travel - Airfares");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014639' extends '338640' salience 3690

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7996000", ownUse03 in ("E14980400", "E14980401"))
        
    then
        $gpy.setLocMassLine("Travel - Hotel");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014641' extends '338640' salience 3680

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0181000", ownUse03 in ("E14900090", "E14900330"))
        
    then
        $gpy.setLocMassLine("Unused Leave");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014643' extends '338640' salience 3670

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0173000", ownUse03 == "E14720120")
        
    then
        $gpy.setLocMassLine("Voluntary Unpaid Leave");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end

rule '2014644' extends '338640' salience 3660

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000", ownUse03 == "E14890160")
        
    then
        $gpy.setLocMassLine("Withholding Tax");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8604");
        
end


