package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlPlYtd;




dialect  "mvel"


rule '330097'
	when
		$gpy : GrlPlYtd(hpnPlCl in ( "6000" , "7000" ))
	then
        
end





rule '1144529' extends '330097' salience 1500

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setMassLine("99.999");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144496' extends '330097' salience 1490

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7997000")
        
    then
        $gpy.setMassLine("Lease Cars Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144497' extends '330097' salience 1480

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8003000")
        
    then
        $gpy.setMassLine("Audit Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144498' extends '330097' salience 1470

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8001000")
        
    then
        $gpy.setMassLine("Management Consultants");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144499' extends '330097' salience 1460

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0372000")
        
    then
        $gpy.setMassLine("Impairments on Securities");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144506' extends '330097' salience 1450

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0087000", "E0171000"))
        
    then
        $gpy.setMassLine("Loss allowances");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144511' extends '330097' salience 1440

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0114000", "E3148000", "E3149000", "E3150000", "E3159000", "E3162000", "E3163000", "E3164000", "E3165000", "E3166000", "E4030000", "E4169000"))
        
    then
        $gpy.setMassLine("Intangible Amortisation and Other Impairments");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144512' extends '330097' salience 1430

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4875000")
        
    then
        $gpy.setMassLine("Interest External Paid (Core)");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144516' extends '330097' salience 1420

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E6683000", "E6686000", "E6688000", "E6689000", "E6690000", "E6691000", "E6692000", "E6693000", "E6694000", "E6695000", "E6696000", "E6697000", "E6698000", "E6699000", "E6700000", "E6701000", "E6702000", "E6703000", "E6704000", "E7504000", "I0026000"))
        
    then
        $gpy.setMassLine("Intangible Amortisation and Other Impairments");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144518' extends '330097' salience 1410

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0176000")
        
    then
        $gpy.setMassLine("Depreciation Software");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144521' extends '330097' salience 1400

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0123000")
        
    then
        $gpy.setMassLine("Depreciation Hardware");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144522' extends '330097' salience 1390

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0079000", "E7999000", "E8000000"))
        
    then
        $gpy.setMassLine("Other Accommodation Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144525' extends '330097' salience 1380

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0109000", "E0112000", "E4877000"))
        
    then
        $gpy.setMassLine("Corporate Tax Financial Accounting");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144526' extends '330097' salience 1370

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0120000", "E0184000", "E8629000"))
        
    then
        $gpy.setMassLine(Warning: selecting from Non-Controlling: data will not be available in source topic.
 full statement: Net Result from Non-Controlling Interests);
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144527' extends '330097' salience 1360

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0126000")
        
    then
        $gpy.setMassLine("Third Party Staff Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144531' extends '330097' salience 1350

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0147000", "E0148000", "E0149000"))
        
    then
        $gpy.setMassLine("Office Supplies and Equipment");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144532' extends '330097' salience 1340

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0113000", "E0117000", "E0118000", "E0119000", "E0137000", "E2343000", "E2344000", "E2345000", "E2346000", "E4876000", "E8636000", "E9019000", "E9802000"))
        
    then
        $gpy.setMassLine("Other Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144533' extends '330097' salience 1330

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0141000")
        
    then
        $gpy.setMassLine("Hardware Expenses not Capitalised");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144535' extends '330097' salience 1320

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0154000")
        
    then
        $gpy.setMassLine("Payroll Taxes and Social Security");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144536' extends '330097' salience 1310

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0159000", "E4566000"))
        
    then
        $gpy.setMassLine("Pension Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144539' extends '330097' salience 1300

    when
        
        GrlPlYtd(this == $gpy, (actCode == "E0084000" || actCode == "E0085000" || actCode == "E0169000" || actCode matches "E3944.*" || actCode matches "E3945.*" || actCode == "E4599000" || actCode == "E8006000" || actCode == "E8007000" || actCode == "E8069000" || actCode == "E8070000"))
        
    then
        $gpy.setMassLine("Loss allowances");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144543' extends '330097' salience 1290

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0183000", "E0182000"))
        
    then
        $gpy.setMassLine("Communication Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144544' extends '330097' salience 1280

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0078000")
        
    then
        $gpy.setMassLine("Depr - Leasehold Improvements");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144545' extends '330097' salience 1270

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0125000")
        
    then
        $gpy.setMassLine("Employee Education");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144547' extends '330097' salience 1260

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0133000", "E3350000", "E8229000", "E8230000", "E8231000", "E8232000", "E8266000"))
        
    then
        $gpy.setMassLine("Group Overhead Staff FA");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144549' extends '330097' salience 1250

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0174000")
        
    then
        $gpy.setMassLine("IC Services Bought Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144550' extends '330097' salience 1240

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0175000")
        
    then
        $gpy.setMassLine("Intercompany Services Sold");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144553' extends '330097' salience 1230

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0127000")
        
    then
        $gpy.setMassLine("Capitalisation Own Developed Software");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144554' extends '330097' salience 1220

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0124000")
        
    then
        $gpy.setMassLine("Hardware Expenses not Capitalised");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144555' extends '330097' salience 1210

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0128000")
        
    then
        $gpy.setMassLine("Third Party Staff IT");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144630' extends '330097' salience 1200

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8236000")
        
    then
        $gpy.setMassLine("Expenses related to Deferred Equity/Shares");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1147559' extends '330097' salience 1190

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E3161000", "E3905000", "E4032000", "E8242000"))
        
    then
        $gpy.setMassLine("Impairments on Securities");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1148627' extends '330097' salience 1180

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0129000")
        
    then
        $gpy.setMassLine("Office Rental");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1148629' extends '330097' salience 1170

    when
        
        GrlPlYtd(this == $gpy, actCode == "E6705000")
        
    then
        $gpy.setMassLine("Depreciation Software");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1148631' extends '330097' salience 1160

    when
        
        GrlPlYtd(this == $gpy, actCode == "E4390000")
        
    then
        $gpy.setMassLine("99.999");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1148632' extends '330097' salience 1150

    when
        
        GrlPlYtd(this == $gpy, actCode == "E4388000")
        
    then
        $gpy.setMassLine("99.999");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1148633' extends '330097' salience 1140

    when
        
        GrlPlYtd(this == $gpy, actCode == "E4389000")
        
    then
        $gpy.setMassLine("99.999");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1148634' extends '330097' salience 1130

    when
        
        GrlPlYtd(this == $gpy, actCode == "E4391000")
        
    then
        $gpy.setMassLine("99.999");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1148635' extends '330097' salience 1120

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0135000")
        
    then
        $gpy.setMassLine("Income Allocated BIS Capital");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1148825' extends '330097' salience 1110

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E3151000", "E3152000", "E3153000", "E3341000"))
        
    then
        $gpy.setMassLine("Other Operational Lease Income");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1148826' extends '330097' salience 1100

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E3158000", "E3160000", "E3949000", "E4151000"))
        
    then
        $gpy.setMassLine("Other (Income)");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1159948' extends '330097' salience 1090

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8291000")
        
    then
        $gpy.setMassLine("Bank Levies Local");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1160832' extends '330097' salience 1080

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0130000")
        
    then
        $gpy.setMassLine("Information Services Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1181684' extends '330097' salience 1070

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8296000")
        
    then
        $gpy.setMassLine("Expenses related to Upfront Equity/Shares");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1617338' extends '330097' salience 1060

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8634000")
        
    then
        $gpy.setMassLine("99.999");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1617339' extends '330097' salience 1050

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8635000")
        
    then
        $gpy.setMassLine("99.999");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1621328' extends '330097' salience 1040

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8337000")
        
    then
        $gpy.setMassLine("Deposit Related Taxes");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1652856' extends '330097' salience 1030

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8664000")
        
    then
        $gpy.setMassLine("VAT on Head Office Charges");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1690868' extends '330097' salience 1020

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8941000")
        
    then
        $gpy.setMassLine("Corporate Tax Financial Accounting");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1731040' extends '330097' salience 1010

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0165000")
        
    then
        $gpy.setMassLine("Other Accommodation Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1731041' extends '330097' salience 1000

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0157000", "E0158000"))
        
    then
        $gpy.setMassLine("Payment Transfer Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1731042' extends '330097' salience 990

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0138000")
        
    then
        $gpy.setMassLine("Freight Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1737205' extends '330097' salience 980

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0210000")
        
    then
        $gpy.setMassLine("Interest Expense on Other Non-Trading Derivatives");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1742370' extends '330097' salience 970

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9520000")
        
    then
        $gpy.setMassLine("Software Expenses not Capitalised");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1742371' extends '330097' salience 960

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9521000")
        
    then
        $gpy.setMassLine("IT Subcontracting");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1742372' extends '330097' salience 950

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9517000")
        
    then
        $gpy.setMassLine("Commercial Activities");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1742373' extends '330097' salience 940

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9518000")
        
    then
        $gpy.setMassLine("Legal Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1742374' extends '330097' salience 930

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9519000")
        
    then
        $gpy.setMassLine("Maintenance Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1742375' extends '330097' salience 920

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E9515000", "E9810000", "E9819000"))
        
    then
        $gpy.setMassLine("Outsourcing");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1742376' extends '330097' salience 910

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9516000")
        
    then
        $gpy.setMassLine("Other Subcontracting");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1742532' extends '330097' salience 900

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9534000")
        
    then
        $gpy.setMassLine("Incentives - Cashback");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1742533' extends '330097' salience 890

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9535000")
        
    then
        $gpy.setMassLine("Incentives - MGM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1742534' extends '330097' salience 880

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9536000")
        
    then
        $gpy.setMassLine("Incentives - Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1742680' extends '330097' salience 870

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7998000")
        
    then
        $gpy.setMassLine("Maintenance Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1742681' extends '330097' salience 860

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8628000")
        
    then
        $gpy.setMassLine("VAT Reclaim and Recovery");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1742682' extends '330097' salience 850

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0139000", "E7509000"))
        
    then
        $gpy.setMassLine("Provisioned Litigation and Other Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1742683' extends '330097' salience 840

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0172000")
        
    then
        $gpy.setMassLine("Reorganisation Provisions");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1742684' extends '330097' salience 830

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8339000")
        
    then
        $gpy.setMassLine("Contribution Regulatory Institutions");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1742685' extends '330097' salience 820

    when
        
        GrlPlYtd(this == $gpy, actCode == "E2583000")
        
    then
        $gpy.setMassLine("Depreciation Tangible Fixed Assets");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1772451' extends '330097' salience 810

    when
        
        GrlPlYtd(this == $gpy, actCode == "E3091000")
        
    then
        $gpy.setMassLine("Loss allowances");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1783229' extends '330097' salience 800

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9794000")
        
    then
        $gpy.setMassLine("Recruitment Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1806045' extends '330097' salience 790

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E9778000", "E9780000"))
        
    then
        $gpy.setMassLine("Other Lease Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1806046' extends '330097' salience 780

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E9781000", "E9782000", "E9783000", "E9784000", "E9785000", "E9786000"))
        
    then
        $gpy.setMassLine("Intangible Amortisation and Other Impairments");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1806113' extends '330097' salience 770

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9775000")
        
    then
        $gpy.setMassLine("Office Rental");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1806114' extends '330097' salience 760

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9776000")
        
    then
        $gpy.setMassLine("Lease Cars Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1902582' extends '330097' salience 750

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E9777000", "E9779000"))
        
    then
        $gpy.setMassLine("Office Supplies and Equipment");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1979657' extends '330097' salience 740

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9817000")
        
    then
        $gpy.setMassLine("Litigation Expenses not Provisioned");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1987987' extends '330097' salience 730

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0187000")
        
    then
        $gpy.setMassLine("Travel related Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144500' extends '330097' salience 720

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000", hsoPlSubcl == "6543")
        
    then
        $gpy.setMassLine("Claims");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144503' extends '330097' salience 710

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000", hsoPlSubcl == "6539")
        
    then
        $gpy.setMassLine("Postal Charges");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144505' extends '330097' salience 700

    when
        
        GrlPlYtd(this == $gpy, actCode == "E3903000", hsoPlSubcl != "6401")
        
    then
        $gpy.setMassLine("Expenses related to Deferred Equity/Shares");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144507' extends '330097' salience 690

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0096000", hsoPlSubcl == "6107")
        
    then
        $gpy.setMassLine("Bonus Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144513' extends '330097' salience 680

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0166000")
        
    then
        $gpy.setMassLine("Investment Income");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144515' extends '330097' salience 670

    when
        
        GrlPlYtd(this == $gpy, intInd == "Y", actCode == null, hsoPlSubcl == "6521")
        
    then
        $gpy.setMassLine("Intercompany Services Sold");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144520' extends '330097' salience 660

    when
        
        GrlPlYtd(this == $gpy, actCode == "E6684000", hsoPlSubcl == "6538")
        
    then
        $gpy.setMassLine("Deferred cash bonuses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144524' extends '330097' salience 650

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0177000", hsoPlSubcl == "6513")
        
    then
        $gpy.setMassLine("Subscriptions");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144528' extends '330097' salience 640

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7996000", hsoPlSubcl == "6512")
        
    then
        $gpy.setMassLine("Travel related Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144530' extends '330097' salience 630

    when
        
        GrlPlYtd(this == $gpy, actCode == "E4621000", hsoPlSubcl == "6501")
        
    then
        $gpy.setMassLine("Office Rental");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144537' extends '330097' salience 620

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E8004000", "E0164000"), hsoPlSubcl != "6536")
        
    then
        $gpy.setMassLine("Other Professional Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144540' extends '330097' salience 610

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0108000", "E0122000", "E0173000", "E7483000"), hsoPlSubcl not in ("6404", "6405"))
        
    then
        $gpy.setMassLine("Salaries and Wages");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144541' extends '330097' salience 600

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0173000", hsoPlSubcl == "6404")
        
    then
        $gpy.setMassLine("Severance Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144542' extends '330097' salience 590

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0096000", hsoPlSubcl == "6102")
        
    then
        $gpy.setMassLine("Upfront cash bonuses WB Pool");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144546' extends '330097' salience 580

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6515")
        
    then
        $gpy.setMassLine("Marketing");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144551' extends '330097' salience 570

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000", hsoPlSubcl not in ("6519", "6539", "6543", "6560", "6561"))
        
    then
        $gpy.setMassLine("Other Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144552' extends '330097' salience 560

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000", hsoPlSubcl == "6519")
        
    then
        $gpy.setMassLine("Other Taxes");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144556' extends '330097' salience 550

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8004000", hsoPlSubcl == "6536")
        
    then
        $gpy.setMassLine("Outsourcing");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1144629' extends '330097' salience 540

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0131000", "E0136000", "E0181000"), hsoPlSubcl not in ("6401", "6542"))
        
    then
        $gpy.setMassLine("Other Personnel Related Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1147557' extends '330097' salience 530

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0174000", cpyBeyNumber == "U2211")
        
    then
        $gpy.setMassLine("IC Services Bought NL Direct Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1147558' extends '330097' salience 520

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0174000", cpyBeyNumber == "U0039")
        
    then
        $gpy.setMassLine("IC Services Bought Belgium");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1148588' extends '330097' salience 510
no-loop
    when
        
        GrlPlYtd(this == $gpy, actCode == "E0174000", getCase0_1148588() == "Regional")
        
    then
        $gpy.setMassLine("IC Services Bought Regional");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1148630' extends '330097' salience 500

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7461000", hsoPlSubcl == "6551")
        
    then
        $gpy.setMassLine("DIP Local");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1148636' extends '330097' salience 490

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0162000", hsoPlSubcl == "6527")
        
    then
        $gpy.setMassLine("Postal Charges");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1148638' extends '330097' salience 480

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0140000", hsoPlSubcl == "7111")
        
    then
        $gpy.setMassLine("Pension Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1148938' extends '330097' salience 470

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0181000", hsoPlSubcl == "6401")
        
    then
        $gpy.setMassLine("Recruitment Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1148939' extends '330097' salience 460

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0181000", hsoPlSubcl == "6542")
        
    then
        $gpy.setMassLine("Other Personnel Related Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1148945' extends '330097' salience 450

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6540")
        
    then
        $gpy.setMassLine("Events/Relationship Marketing");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1148946' extends '330097' salience 440

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6541")
        
    then
        $gpy.setMassLine("Internal Communication");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1159179' extends '330097' salience 430

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0174000", cpyBeyNumber == "U0618")
        
    then
        $gpy.setMassLine("IC Services Bought NL Direct Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1159185' extends '330097' salience 420

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0124000", hsoPlSubcl in ("6503", "6504"))
        
    then
        $gpy.setMassLine("Hardware Expenses not Capitalised");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1159186' extends '330097' salience 410

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0124000", hsoPlSubcl == "6505")
        
    then
        $gpy.setMassLine("Capitalisation Own Developed Software");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1159187' extends '330097' salience 400

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0127000", hsoPlSubcl in ("6505", "6506"))
        
    then
        $gpy.setMassLine("Capitalisation Own Developed Software");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1159188' extends '330097' salience 390

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0127000", hsoPlSubcl in ("6503", "6504"))
        
    then
        $gpy.setMassLine("Hardware Expenses not Capitalised");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1160833' extends '330097' salience 380

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0130000", hsoPlSubcl == "6511")
        
    then
        $gpy.setMassLine("Information Services Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1175151' extends '330097' salience 370

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0124000", hsoPlSubcl == "6506")
        
    then
        $gpy.setMassLine("Software Expenses not Capitalised");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1182293' extends '330097' salience 360

    when
        
        GrlPlYtd(this == $gpy, actCode == "E6684000", hsoPlSubcl == "6108")
        
    then
        $gpy.setMassLine("Deferred cash bonuses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1186642' extends '330097' salience 350

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E8337000", "E0180000"), hsoPlSubcl == "6560")
        
    then
        $gpy.setMassLine("VAT on Head Office Charges");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1192842' extends '330097' salience 340

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000", hsoPlSubcl == "6561")
        
    then
        $gpy.setMassLine("Other Taxes");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1620385' extends '330097' salience 330

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3174000")
        
    then
        $gpy.setMassLine("Realised gains and FV changes on investments (excl. IoS)");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1621330' extends '330097' salience 320

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0124000", hsoPlSubcl == "6544")
        
    then
        $gpy.setMassLine("Hardware Expenses not Capitalised");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1703716' extends '330097' salience 310

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8644000", hsoPlSubcl == "6564")
        
    then
        $gpy.setMassLine("Single Resolution Mechanism Dutch N.V.");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1731043' extends '330097' salience 300

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8002000", hsoPlSubcl != "6536")
        
    then
        $gpy.setMassLine("Other Consulting");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1736845' extends '330097' salience 290

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8644000", hsoPlSubcl == "6567")
        
    then
        $gpy.setMassLine("Single Resolution Mechanism Local");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1769899' extends '330097' salience 280

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E1112000", "E1113000"))
        
    then
        $gpy.setMassLine("Modification gains and losses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1769900' extends '330097' salience 270

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E8070000", "E8071000", "E8072000", "E8073000", "E8074000", "E8811000", "E8812000", "E9244000", "E9245000", "E9246000", "E9247000", "E9248000", "E9249000", "E9250000", "E9251000", "E9252000", "E9253000", "E9254000", "E9255000", "E9256000", "E9257000", "E9258000", "E9259000"))
        
    then
        $gpy.setMassLine("Loss allowances");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1777528' extends '330097' salience 260

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6577")
        
    then
        $gpy.setMassLine("Creative ATL & BTL");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1777529' extends '330097' salience 250

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6578")
        
    then
        $gpy.setMassLine("Production ATL");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1777530' extends '330097' salience 240

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6579")
        
    then
        $gpy.setMassLine("Creative - Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1777531' extends '330097' salience 230

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6580")
        
    then
        $gpy.setMassLine("TV");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1777532' extends '330097' salience 220

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6581")
        
    then
        $gpy.setMassLine("Radio");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1777533' extends '330097' salience 210

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6582")
        
    then
        $gpy.setMassLine("Outdoor / Digital OOH");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1777534' extends '330097' salience 200

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6583")
        
    then
        $gpy.setMassLine("Press");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1777535' extends '330097' salience 190

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6584")
        
    then
        $gpy.setMassLine("Online Advertising");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1777536' extends '330097' salience 180

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6585")
        
    then
        $gpy.setMassLine("Online Performance");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1777537' extends '330097' salience 170

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6586")
        
    then
        $gpy.setMassLine("Media Agency / Consulting");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1777538' extends '330097' salience 160

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6587")
        
    then
        $gpy.setMassLine("Media Agency / Consulting");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1777539' extends '330097' salience 150

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6588")
        
    then
        $gpy.setMassLine("Media - Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1777540' extends '330097' salience 140

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6589")
        
    then
        $gpy.setMassLine("Marketing Research");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1777541' extends '330097' salience 130

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6590")
        
    then
        $gpy.setMassLine("Direct & POS Mktg");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1777542' extends '330097' salience 120

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6591")
        
    then
        $gpy.setMassLine("Sponsoring Contract");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1777543' extends '330097' salience 110

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6592")
        
    then
        $gpy.setMassLine("Sponsoring Activation");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1777544' extends '330097' salience 100

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6593")
        
    then
        $gpy.setMassLine("Gifts - Donations");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1778840' extends '330097' salience 90

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0174000", cpyBeyNumber == "U2741")
        
    then
        $gpy.setMassLine("IC Services Bought Belgium");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1863970' extends '330097' salience 80

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7461000", hsoPlSubcl == "6597")
        
    then
        $gpy.setMassLine("DIP Dutch N.V.");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1864191' extends '330097' salience 70

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0174000", cpyBeyNumber == "U2959")
        
    then
        $gpy.setMassLine("IC Services Bought NL Direct Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1983208' extends '330097' salience 60

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0177000", hsoPlSubcl == "6804")
        
    then
        $gpy.setMassLine("Memberships");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1983210' extends '330097' salience 50

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7996000", hsoPlSubcl == "6805")
        
    then
        $gpy.setMassLine("Representation Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1983211' extends '330097' salience 40

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6802")
        
    then
        $gpy.setMassLine("Production BTL");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1983212' extends '330097' salience 30

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6803")
        
    then
        $gpy.setMassLine("Celebrity Fee");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1987986' extends '330097' salience 20

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0174000", cpyBeyNumber == "U3039")
        
    then
        $gpy.setMassLine("IC Services Bought Belgium");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end

rule '1148637' extends '330097' salience 10

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0122000", hsoPlSubcl == "7112")
        
    then
        $gpy.setMassLine("Pension Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1983");
        
end


