package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlFacCovers;

global String dateFormat;

dialect  "mvel"


rule '331019'
	when
		$gfc : GrlFacCovers( repDate != null )
	then
end


rule '1710425' extends '331019' salience 10

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gfc.setPrdId($gfc.formatDate($gfc.getRepDate(),dateFormat));
        
end