package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlPlYtd;




dialect  "mvel"


rule '331799'
	when
		$gpy : GrlPlYtd(hpnPlCl in ( "6000" , "7000" ) && hsoPlSubcl != 7401)
	then
        
end





rule '1104988' extends '331799' salience 1190

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setLocMassLine(massLine );
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104931' extends '331799' salience 1180

    when
        
        GrlPlYtd(this == $gpy, massLine == "Salaries and Wages")
        
    then
        $gpy.setLocMassLine("Salaries and Wages Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104932' extends '331799' salience 1170

    when
        
        GrlPlYtd(this == $gpy, massLine == "Payroll Taxes and Social Security")
        
    then
        $gpy.setLocMassLine("Payroll Taxes and Social Security Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104933' extends '331799' salience 1160

    when
        
        GrlPlYtd(this == $gpy, massLine == "Pension Costs")
        
    then
        $gpy.setLocMassLine("Pension Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104934' extends '331799' salience 1150

    when
        
        GrlPlYtd(this == $gpy, massLine == "Severance Costs")
        
    then
        $gpy.setLocMassLine("Severance Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104935' extends '331799' salience 1140

    when
        
        GrlPlYtd(this == $gpy, massLine == "Third Party Staff IT")
        
    then
        $gpy.setLocMassLine("Third Party Staff IT");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104936' extends '331799' salience 1130

    when
        
        GrlPlYtd(this == $gpy, massLine == "Third Party Staff Other")
        
    then
        $gpy.setLocMassLine("Third Party Staff Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104937' extends '331799' salience 1120

    when
        
        GrlPlYtd(this == $gpy, massLine == "Employee Education")
        
    then
        $gpy.setLocMassLine("Employee Education");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104938' extends '331799' salience 1110

    when
        
        GrlPlYtd(this == $gpy, massLine == "Recruitment Costs")
        
    then
        $gpy.setLocMassLine("Recruitment Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104945' extends '331799' salience 1100

    when
        
        GrlPlYtd(this == $gpy, massLine == "Hardware Expenses not Capitalised")
        
    then
        $gpy.setLocMassLine("Leasing/Renting Locally Selected Hardware");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104946' extends '331799' salience 1090

    when
        
        GrlPlYtd(this == $gpy, massLine == "Depreciation Hardware")
        
    then
        $gpy.setLocMassLine("Depreciation Locally Selected Hardware");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104949' extends '331799' salience 1080

    when
        
        GrlPlYtd(this == $gpy, massLine == "Depreciation Software")
        
    then
        $gpy.setLocMassLine("Depreciation Locally Selected Software");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104951' extends '331799' salience 1070

    when
        
        GrlPlYtd(this == $gpy, massLine == "Outsourcing")
        
    then
        $gpy.setLocMassLine(Warning: selecting from Locally: data will not be available in source topic.
 full statement: IT Outsourcing from Locally Selected Suppliers);
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104963' extends '331799' salience 1060

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setLocMassLine("Events/Relationship Marketing");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104964' extends '331799' salience 1050

    when
        
        GrlPlYtd(this == $gpy, massLine == "Internal Communication")
        
    then
        $gpy.setLocMassLine("Internal Communication");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104981' extends '331799' salience 1040

    when
        
        GrlPlYtd(this == $gpy, massLine == "Corporate Tax Financial Accounting")
        
    then
        $gpy.setLocMassLine("Tax on Profits current year");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104990' extends '331799' salience 1030

    when
        
        GrlPlYtd(this == $gpy, massLine == "Intercompany Services Sold")
        
    then
        $gpy.setLocMassLine("IC Services Sold Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104991' extends '331799' salience 1020

    when
        
        GrlPlYtd(this == $gpy, massLine == "Bonus Other")
        
    then
        $gpy.setLocMassLine("Bonus Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1107657' extends '331799' salience 1010

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Personnel Related Costs")
        
    then
        $gpy.setLocMassLine("Other Staff Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1122483' extends '331799' salience 1000

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Taxes")
        
    then
        $gpy.setLocMassLine("All Other Taxes");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1143268' extends '331799' salience 990

    when
        
        GrlPlYtd(this == $gpy, massLine == "Audit Expenses")
        
    then
        $gpy.setLocMassLine("Audit Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1145082' extends '331799' salience 980

    when
        
        GrlPlYtd(this == $gpy, massLine == "Depr - Leasehold Improvements", ownUse05 not in ("LH-BUILDING", "LH-BUILD-N"))
        
    then
        $gpy.setLocMassLine("Depr - Office Leasehold Improvements");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1148251' extends '331799' salience 970

    when
        
        GrlPlYtd(this == $gpy, massLine == "IC Services Bought Belgium")
        
    then
        $gpy.setLocMassLine("IC Services Bought Belgium");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1178713' extends '331799' salience 960

    when
        
        GrlPlYtd(this == $gpy, massLine == "Group Overhead Staff FA")
        
    then
        $gpy.setLocMassLine("Group Overhead Staff FA");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1182307' extends '331799' salience 950

    when
        
        GrlPlYtd(this == $gpy, massLine == "Deferred cash bonuses")
        
    then
        $gpy.setLocMassLine("Deferred cash bonuses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1700844' extends '331799' salience 940

    when
        
        GrlPlYtd(this == $gpy, massLine == "IC Services Bought Other")
        
    then
        $gpy.setLocMassLine("IC Services Bought Other - Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1700845' extends '331799' salience 930

    when
        
        GrlPlYtd(this == $gpy, massLine == "IC Services Bought Regional")
        
    then
        $gpy.setLocMassLine("IC Services Bought Regional - Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1700852' extends '331799' salience 920

    when
        
        GrlPlYtd(this == $gpy, massLine == "VAT on Head Office Charges")
        
    then
        $gpy.setLocMassLine("Taxes on Invoiced Intercompany Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1700859' extends '331799' salience 910

    when
        
        GrlPlYtd(this == $gpy, massLine == "Information Services Expenses", ownUse05 == null)
        
    then
        $gpy.setLocMassLine("Other Information Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1700860' extends '331799' salience 900

    when
        
        GrlPlYtd(this == $gpy, massLine == "Lease Cars Expenses", ownUse05 == null)
        
    then
        $gpy.setLocMassLine("T&R - Lease Cars Related Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1700861' extends '331799' salience 890

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Rental", ownUse05 == null)
        
    then
        $gpy.setLocMassLine("Office Rental - Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1700862' extends '331799' salience 880

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Supplies and Equipment", ownUse05 == null)
        
    then
        $gpy.setLocMassLine("Office Equipment Depreciation");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1700863' extends '331799' salience 870

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Accommodation Expenses", ownUse05 == null)
        
    then
        $gpy.setLocMassLine("Other Accommodation - Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1700865' extends '331799' salience 860

    when
        
        GrlPlYtd(this == $gpy, ownUse05 == null)
        
    then
        $gpy.setLocMassLine("Other Locally Selected Hardware expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1700866' extends '331799' salience 850

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Professional Services", ownUse05 == null)
        
    then
        $gpy.setLocMassLine("Other Prof Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1700867' extends '331799' salience 840

    when
        
        GrlPlYtd(this == $gpy, massLine == "Travel related Costs", ownUse05 == null)
        
    then
        $gpy.setLocMassLine("T&R - Travel");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1700868' extends '331799' salience 830

    when
        
        GrlPlYtd(this == $gpy, massLine in ("Subscriptions", "Memberships"), ownUse05 == null)
        
    then
        $gpy.setLocMassLine("Subscriptions");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1700869' extends '331799' salience 820

    when
        
        GrlPlYtd(this == $gpy, massLine == "Communication Expenses", ownUse05 == null)
        
    then
        $gpy.setLocMassLine("Communications - Data");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1732832' extends '331799' salience 810

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Consulting")
        
    then
        $gpy.setLocMassLine("Consultancy Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1732833' extends '331799' salience 800

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setLocMassLine("Interest Internal Received (Reference) other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1772534' extends '331799' salience 790

    when
        
        GrlPlYtd(this == $gpy, massLine == "Software Expenses not Capitalised")
        
    then
        $gpy.setLocMassLine("Leasing/Renting Centrally Selected Software");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1836694' extends '331799' salience 780

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Lease Expenses")
        
    then
        $gpy.setLocMassLine("Depreciation Other Assets");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104939' extends '331799' salience 770

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Personnel Related Costs", ownUse06 == "STFC")
        
    then
        $gpy.setLocMassLine("Unused Holidays");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104940' extends '331799' salience 760

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Personnel Related Costs", ownUse06 == "GESE")
        
    then
        $gpy.setLocMassLine("Other Staff Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104941' extends '331799' salience 750

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Personnel Related Costs", ownUse05 matches "EXP.*", ownUse06 == "SCOT")
        
    then
        $gpy.setLocMassLine("Expats Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104942' extends '331799' salience 740

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Personnel Related Costs", (ownUse05 == "LUNCH" || ownUse05 matches "LUNCH-.*"), ownUse06 == "SCOT")
        
    then
        $gpy.setLocMassLine("Lunch Vouchers");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104943' extends '331799' salience 730

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Personnel Related Costs", ownUse05 in ("OTHER", "OTHER-N", "LUNCH", "OTH-STF-EX-D", "OTH-STF-EX-N"), ownUse06 == "SCOT")
        
    then
        $gpy.setLocMassLine("Other Staff Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104953' extends '331799' salience 720

    when
        
        GrlPlYtd(this == $gpy, massLine == "Communication Expenses", (ownUse05 == "ROMTELECOM" || ownUse05 == "ROMTELE-ACCR" || ownUse05 == "SPRINT-MAIL" || ownUse05 == "SPRIN-MAILN" || ownUse05 == "SPRINT-MAILN" || ownUse05 == "INGGLOBAL" || ownUse05 == "OTHER" || ownUse05 == "OTHER-ACCR" || ownUse05 == "OTHER-N" || ownUse05 == "SWIFT" || ownUse05 == "SWIFT-ACCR" || ownUse05 matches "TEL-OTH-.*"), ownUse06 == "GECM")
        
    then
        $gpy.setLocMassLine("Communications - Data");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104954' extends '331799' salience 710

    when
        
        GrlPlYtd(this == $gpy, massLine == "Communication Expenses", (ownUse05 == "DHL" || ownUse05 == "COURIER" || ownUse05 == "MAIL-ACCR" || ownUse05 matches "POSTAL-CHG.*" || ownUse05 matches "COURIER-.*" || ownUse05 matches "POSTAL-BST.*"), ownUse06 == "GECM")
        
    then
        $gpy.setLocMassLine("Communications - Courier & Postal");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104955' extends '331799' salience 700

    when
        
        GrlPlYtd(this == $gpy, massLine == "Communication Expenses", (ownUse05 matches "MOBILPHONE.*" || ownUse05 == "MOBILPH-ACCR" || ownUse05 == "NSRL-ROMTELE" || ownUse05 == "TELEPH-OTHER" || ownUse05 == "TELEPHOTERN" || ownUse05 == "ROMTELECOM-N"), ownUse06 == "GECM")
        
    then
        $gpy.setLocMassLine("Communications - Phones");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104956' extends '331799' salience 690

    when
        
        GrlPlYtd(this == $gpy, massLine == "Information Services Expenses", ownUse05 not in ("REUTERS", "REUTERS-N", "BLOOMBERG"), ownUse06 == "GECM")
        
    then
        $gpy.setLocMassLine("Trading Floor Systems");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104957' extends '331799' salience 680

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Rental", (ownUse05 == "OFFICE-RENT" || ownUse05 matches "OFF-RENT.*" || ownUse05 == "OF-RENT-ACCR"), ownUse06 == "GEOR")
        
    then
        $gpy.setLocMassLine("Office Rental - Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104958' extends '331799' salience 670

    when
        
        GrlPlYtd(this == $gpy, massLine == "Depr - Leasehold Improvements", ownUse05 in ("LH-BUILDING", "LH-BUILD-N"), ownUse06 == "DPLI")
        
    then
        $gpy.setLocMassLine("Depr - Office Leasehold Improvements");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104960' extends '331799' salience 660

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Accommodation Expenses", (ownUse05 == "SECURITY" || ownUse05 matches "SECURITY-.*" || ownUse05 == "SECURIT-ACCR"), ownUse06 == "GEAC")
        
    then
        $gpy.setLocMassLine("Other Accommodation - Security");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104961' extends '331799' salience 650

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Accommodation Expenses", (ownUse05 == "INSURANCE" || ownUse05 == "MAINTEN-ACCR" || ownUse05 == "MAINTENANCE" || ownUse05 == "MAINTEN-N" || ownUse05 == "MAINT-SEC" || ownUse05 matches "MNT-SEC.*" || ownUse05 == "CLEAN-SVCS" || ownUse05 == "CLEAN-SVCS-N" || ownUse05 == "CLEAN-ACCR" || ownUse05 == "CLEAN-SVCS" || ownUse05 == "CLEAN-SVCS-N" || ownUse05 == "ELECTR-ACCR" || ownUse05 == "ELECTRICITY" || ownUse05 == "ELECTR-N" || ownUse05 == "GAS" || ownUse05 matches "GAS-.*" || ownUse05 == "HEATING" || ownUse05 matches "HEATING-.*"), ownUse06 == "GEAC")
        
    then
        $gpy.setLocMassLine("Other Accommodation - Utilities");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104965' extends '331799' salience 640

    when
        
        GrlPlYtd(this == $gpy, massLine == "Travel related Costs", ownUse05 == "BANK-CARS", ownUse06 == "DPBC")
        
    then
        $gpy.setLocMassLine("T&R - Cars Related Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104966' extends '331799' salience 630

    when
        
        GrlPlYtd(this == $gpy, massLine == "Travel related Costs", (ownUse05 == "BANK-CARS" || ownUse05 == "BANK-CAR-L-N" || ownUse05 == "BANK-CARS-L" || ownUse05 == "BANK-CARS-N" || ownUse05 == "CARS-PARTS" || ownUse05 == "FUEL" || ownUse05 == "INSURE-CARS" || ownUse05 == "INSURE-CAR-N" || ownUse05 == "INSURE-CAR-L" || ownUse05 matches "BANKCARS.*" || ownUse05 matches "CARSPART.*" || ownUse05 == "FUEL-L"), ownUse06 == "GETR")
        
    then
        $gpy.setLocMassLine("T&R - Cars Related Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104967' extends '331799' salience 620

    when
        
        GrlPlYtd(this == $gpy, massLine == "Travel related Costs", (ownUse05 matches "REPRES.*" || ownUse05 == "NSRL-REPRES" || ownUse05 == "CARDS-REINV"), ownUse06 == "GETR")
        
    then
        $gpy.setLocMassLine("T&R - Representation");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104968' extends '331799' salience 610

    when
        
        GrlPlYtd(this == $gpy, massLine == "Travel related Costs", (ownUse05 matches "TRAV-REP.*" || ownUse05 matches "TRAVREP.*" || ownUse05 == "RENT-CAR" || ownUse05 matches "TRAV-N.*" || ownUse05 == "TRV-REG-FG-N" || ownUse05 == "TRAVREPFGN-N" || ownUse05 == "TRAVEL-ACCR"), ownUse06 == "GETR")
        
    then
        $gpy.setLocMassLine("T&R - Travel");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104969' extends '331799' salience 600

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Professional Services", (ownUse05 matches "EXT-AUDIT.*" || ownUse05 matches "AUDIT.*"), ownUse06 == "GEEA")
        
    then
        $gpy.setLocMassLine("Consultancy Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104970' extends '331799' salience 590

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Professional Services", ownUse05 in ("INTERN-CONS", "INTERN-CONSN", "CONS-SVCS-IT", "CONSULT-ACCR"), ownUse06 == "GEOS")
        
    then
        $gpy.setLocMassLine("Consultancy Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104971' extends '331799' salience 580

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Professional Services", ownUse05 in ("LEGAL-ACCR", "LEGAL", "LEGAL-FEE", "LEGAL-FEES", "LEGAL-N"), ownUse06 == "GEOS")
        
    then
        $gpy.setLocMassLine("Legal Fees");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104972' extends '331799' salience 570

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Professional Services", ownUse05 == "TAX-ADVICE", ownUse06 == "GEOS")
        
    then
        $gpy.setLocMassLine("Tax Advice");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104973' extends '331799' salience 560

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Professional Services", ownUse05 in ("PROF-SVCS", "PROFSVCS-HON", "PROF-SVCS-N", "PROF-SVCSIT", "PROF-SVCS", "PROF-SV-ACCR", "PROF-SVCS-HO", "OTHERS", "OTHERS-N", "OTH-SERVICES", "RESEARCH", "ROMCARD", "CONS-SVCS-HR", "CONSSVCS-FIN", "CONSVCS-HR-N", "CONTROL-IP", "EXTRAROL-IP", "OTH-SERV-L", "OTH-SERV-N"), ownUse06 == "GEOS")
        
    then
        $gpy.setLocMassLine("Other Prof Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104975' extends '331799' salience 550

    when
        
        GrlPlYtd(this == $gpy, massLine in ("Subscriptions", "Memberships"), ownUse05 in ("MEMBERSHIP", "MEMBERSHIP-N"), ownUse06 == "GESM")
        
    then
        $gpy.setLocMassLine("Memberships");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104976' extends '331799' salience 540

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Supplies and Equipment", ownUse06 == "DPFA")
        
    then
        $gpy.setLocMassLine("Office Equipment Depreciation");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104977' extends '331799' salience 530

    when
        
        GrlPlYtd(this == $gpy, massLine == "Postal Charges", (ownUse05 == "CARDPRINTING" || ownUse05 == "PRINTINGS" || ownUse05 matches "PRINT-.*"), ownUse06 == "GESE")
        
    then
        $gpy.setLocMassLine("Bulk Printing/Scanning");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104979' extends '331799' salience 520

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Supplies and Equipment", (ownUse05 == "MAINTENANCE" || ownUse05 == "MAINTENANCEN" || ownUse05 == "MAINTENAN-N" || ownUse05 == "RENT-EQUIPM" || ownUse05 == "TECH-EQUIP" || ownUse05 matches "RENT-EQU.*" || ownUse05 == "RENT-EQ-ACCR"), ownUse06 == "GESE")
        
    then
        $gpy.setLocMassLine("Office Equipment Depreciation");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104980' extends '331799' salience 510

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Supplies and Equipment", ownUse05 == "OFF-SUPPLY", ownUse06 == "NOFA")
        
    then
        $gpy.setLocMassLine("Office Equipment Depreciation");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104983' extends '331799' salience 500

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Expenses", ownUse05 in ("ARCHIVE-RENT", "ARCHIVE"))
        
    then
        $gpy.setLocMassLine("Archiving");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104984' extends '331799' salience 490

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Expenses", ownUse05 in ("VALUE-TRANS", "VAL-TRA-ACCR"))
        
    then
        $gpy.setLocMassLine("Value Transport");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1104985' extends '331799' salience 480

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Expenses", ownUse05 not in ("ARCHIVE-RENT", "ARCHIVE", "VALUE-TRANS", "VAL-TRA-ACCR"), ownUse06 != "DPFA")
        
    then
        $gpy.setLocMassLine("Sundry Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1105036' extends '331799' salience 470

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Personnel Related Costs", ownUse05 in ("MEDICAL-SERV", "MEDSERV-ACCR"), ownUse06 == "SCOT")
        
    then
        $gpy.setLocMassLine("Medical Care");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1107659' extends '331799' salience 460

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Supplies and Equipment", (ownUse05 matches "MATER-.*" || ownUse05 matches "MATERIAL.*" || ownUse05 matches "OFF-SUPP-.*" || ownUse05 matches "OFF-SUP-.*" || ownUse05 matches "OP-MAT.*" || ownUse05 == "OTH-PARTS" || ownUse05 matches "STATION-.*" || ownUse05 == "PAPER-ACCR" || ownUse05 == "TONNER-ACCR" || ownUse05 == "DIGIPASS" || ownUse05 == "MATERIALS" || ownUse05 == "OFFCE-SUPPLY" || ownUse05 == "PAPER" || ownUse05 == "POS-OFFICES" || ownUse05 == "STATIONARY" || ownUse05 == "TONNER" || ownUse05 == "POSS" || ownUse05 == "CARDPRINTING" || ownUse05 == "PRINT-ACCR" || ownUse05 == "PRINTING-AST" || ownUse05 == "PRINTINGS"), ownUse06 == "GESE")
        
    then
        $gpy.setLocMassLine("Office Equipment Depreciation");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1122480' extends '331799' salience 450

    when
        
        GrlPlYtd(this == $gpy, massLine == "Postal Charges", ownUse05 in ("PRINT-AST-N", "PRINTING-AST", "PRINTINGS"))
        
    then
        $gpy.setLocMassLine("Office and Other Printing/Scanning");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1122484' extends '331799' salience 440

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Professional Services", ownUse05 == "SCANNING", ownUse06 == "GEOS")
        
    then
        $gpy.setLocMassLine("Other Prof Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1143270' extends '331799' salience 430

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Personnel Related Costs", ownUse05 == "SOCIAL-STAFF", ownUse06 == "SCOT")
        
    then
        $gpy.setLocMassLine("Other Staff Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1143271' extends '331799' salience 420

    when
        
        GrlPlYtd(this == $gpy, massLine == "Lease Cars Expenses", ownUse05 == "OTHTAXCARS-L", ownUse06 == "GETX")
        
    then
        $gpy.setLocMassLine("T&R - Lease Cars Related Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1143272' extends '331799' salience 410

    when
        
        GrlPlYtd(this == $gpy, massLine == "Lease Cars Expenses", ownUse05 in ("BANK-CARS-L", "BANK-CAR-L-N", "FUEL-L", "FUEL-L-N", "INSURE-CAR-L", "INSU-CAR-L-N"), ownUse06 == "GETR")
        
    then
        $gpy.setLocMassLine("T&R - Lease Cars Related Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1143273' extends '331799' salience 400

    when
        
        GrlPlYtd(this == $gpy, massLine == "Lease Cars Expenses", ownUse05 == "HANDL-FEE", ownUse06 == "GEOT")
        
    then
        $gpy.setLocMassLine("T&R - Lease Cars Related Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1143702' extends '331799' salience 390

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Professional Services", ownUse05 in ("INSURE-WHS", "INSURANCE"), ownUse06 == "GEOS")
        
    then
        $gpy.setLocMassLine("Other Prof Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1143703' extends '331799' salience 380

    when
        
        GrlPlYtd(this == $gpy, massLine == "Travel related Costs", ownUse05 in ("FUEL", "FUEL-N", "FUEL-L-N", "FUEL-ACCR"), ownUse06 == "GETR")
        
    then
        $gpy.setLocMassLine("T&R - Cars Related Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1143704' extends '331799' salience 370

    when
        
        GrlPlYtd(this == $gpy, massLine in ("Subscriptions", "Memberships"), ownUse05 in ("SUBSCRIPT-N", "SUBSCRIPTION"), ownUse06 == "GESM")
        
    then
        $gpy.setLocMassLine("Subscriptions");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1143705' extends '331799' salience 360

    when
        
        GrlPlYtd(this == $gpy, massLine == "Software Expenses not Capitalised", ownUse05 in ("MAINT-SOFT", "MAINT-SOFT-N", "MNTSOFT-ACCR"), ownUse06 == "SSEX")
        
    then
        $gpy.setLocMassLine("Leasing/Renting Locally Selected Software");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1143716' extends '331799' salience 350

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Personnel Related Costs", ownUse05 in ("PRV-STFHOL-R", "REL-STFHOL-R"), ownUse06 == "SCSW")
        
    then
        $gpy.setLocMassLine("Unused Holidays");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1145069' extends '331799' salience 340

    when
        
        GrlPlYtd(this == $gpy, massLine == "Management Consultants")
        
    then
        $gpy.setLocMassLine("Management Consultants");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1145073' extends '331799' salience 330

    when
        
        GrlPlYtd(this == $gpy, massLine == "Travel related Costs", ownUse05 matches "OTHTAXCARS.*", ownUse06 == "GETX")
        
    then
        $gpy.setLocMassLine("T&R - Cars Related Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1145074' extends '331799' salience 320

    when
        
        GrlPlYtd(this == $gpy, massLine == "Travel related Costs", ownUse05 == "BANK-CARSL", ownUse06 == "DPBC")
        
    then
        $gpy.setLocMassLine("T&R - Cars Related Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1145077' extends '331799' salience 310

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Expenses", ownUse06 == "DPFA")
        
    then
        $gpy.setLocMassLine("Depr Other Fixed Assets");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1145080' extends '331799' salience 300

    when
        
        GrlPlYtd(this == $gpy, massLine == "Software Expenses not Capitalised", ownUse05 not in ("MAINT-SOFT", "MAINT-SOFT-N", "MNTSOFT-ACCR"), ownUse06 == "SSEX")
        
    then
        $gpy.setLocMassLine("Leasing/Renting Centrally Selected Software");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1145081' extends '331799' salience 290

    when
        
        GrlPlYtd(this == $gpy, massLine == "Software Expenses not Capitalised", ownUse05 in ("SOFTWARE", "SOFTWARE-N"), ownUse06 == "SSEX")
        
    then
        $gpy.setLocMassLine("Other Locally Selected Software expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1145084' extends '331799' salience 280

    when
        
        GrlPlYtd(this == $gpy, massLine == "Information Services Expenses", ownUse05 in ("REUTERS", "REUTERS-N", "BLOOMBERG"), ownUse06 == "GECM")
        
    then
        $gpy.setLocMassLine("Other Information Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1145085' extends '331799' salience 270

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Rental", (ownUse05 != "OFFICE-RENT" && ownUse05 not matches "OFF-RENT.*" && ownUse05 != "OF-RENT-ACCR"), ownUse06 == "GEOR")
        
    then
        $gpy.setLocMassLine("Office Rental - Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1145086' extends '331799' salience 260

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Accommodation Expenses", (ownUse05 == "OFFICE-SVCS" || ownUse05 == "OFFICE-SVS-N" || ownUse05 == "UTILITIES" || ownUse05 matches "UTILITIES.*" || ownUse05 == "UTILI-NONDE" || ownUse05 matches "UTILIT.*" || ownUse05 matches "WATER-SVCS.*"), ownUse06 == "GEAC")
        
    then
        $gpy.setLocMassLine("Other Accommodation - Utilities");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1145087' extends '331799' salience 250

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Accommodation Expenses", ownUse06 == "GESE")
        
    then
        $gpy.setLocMassLine("Other Accommodation - Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1145088' extends '331799' salience 240

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Accommodation Expenses", ownUse06 == "GETR")
        
    then
        $gpy.setLocMassLine("Other Accommodation - Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1145248' extends '331799' salience 230

    when
        
        GrlPlYtd(this == $gpy, ownUse05 in ("MAINT-HARD", "MAINT-HARD-N", "MATERIALS-IT", "OFF-SUPPLYIT"), ownUse06 == "GEEE")
        
    then
        $gpy.setLocMassLine("Other Locally Selected Hardware expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1112966' extends '331799' salience 220

    when
        
        GrlPlYtd(this == $gpy, massLine == "Communication Expenses", ownUse05 in ("TELEPH-OTHER", "TELEPHOTERN", "TELEPHOTHERN"), ownUse02 == "WLAN", ownUse06 == "GECM")
        
    then
        $gpy.setLocMassLine("Communications - Data");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1145083' extends '331799' salience 210

    when
        
        GrlPlYtd(this == $gpy, massLine == "Communication Expenses", ownUse05 in ("TELEPH-OTHER", "TELEPHOTERN", "TELEPHOTHERN"), ownUse02 != "WLAN", ownUse06 == "GECM")
        
    then
        $gpy.setLocMassLine("Communications - Phones");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end

rule '1178714' extends '331799' salience 200

    when
        
        GrlPlYtd(this == $gpy, massLine == "Group Overhead Staff FA", ownUse05 == "GROUP-EXP-HO", ownUse02 == "WHOC", ownUse06 == "HOCH")
        
    then
        $gpy.setLocMassLine("Group Overhead Staff FA");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3247");
        
end


