package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlPlYtd;




dialect  "mvel"


rule '324803'
	when
		$gpy : GrlPlYtd(actCode == null)
	then
        
end





rule '1036948' extends '324803' salience 5140

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setCustomTxt20("TO BE ELIMINATED");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036944' extends '324803' salience 5130

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004995", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036945' extends '324803' salience 5120

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == null, lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("NULL ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036946' extends '324803' salience 5110

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6011001", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036947' extends '324803' salience 5100

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004994", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037100' extends '324803' salience 5090

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004995", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037101' extends '324803' salience 5080

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == null, lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("NULL ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037102' extends '324803' salience 5070

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6011001", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037103' extends '324803' salience 5060

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004994", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037255' extends '324803' salience 5050

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004994", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037256' extends '324803' salience 5040

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == null, lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("NULL ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037257' extends '324803' salience 5030

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004995", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037258' extends '324803' salience 5020

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6011001", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036878' extends '324803' salience 5010

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "AL3", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036879' extends '324803' salience 5000

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "EQIN", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036882' extends '324803' salience 4990

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000302", rlnRelIdCtpy == "INGBCAPCONYK", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036883' extends '324803' salience 4980

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "AL4", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036884' extends '324803' salience 4970

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "AL3", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036885' extends '324803' salience 4960

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5019002", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036886' extends '324803' salience 4950

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000302", rlnRelIdCtpy == "SA2", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036887' extends '324803' salience 4940

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5011001", rlnRelIdCtpy == "INGFIN", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036888' extends '324803' salience 4930

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5019999", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036889' extends '324803' salience 4920

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5999999", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036890' extends '324803' salience 4910

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "MARNIXAFC", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036891' extends '324803' salience 4900

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "MARNIXAFC", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036892' extends '324803' salience 4890

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "STAB", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036893' extends '324803' salience 4880

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "STAC", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036894' extends '324803' salience 4870

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5019012", rlnRelIdCtpy == "EGMON", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036895' extends '324803' salience 4860

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5011001", rlnRelIdCtpy == "INGBCAPCONYK", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036896' extends '324803' salience 4850

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "IRDD", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036897' extends '324803' salience 4840

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "NCM", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036898' extends '324803' salience 4830

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5011001", rlnRelIdCtpy == "NSE", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036899' extends '324803' salience 4820

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "NCM", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036900' extends '324803' salience 4810

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6019002", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036901' extends '324803' salience 4800

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "MFI", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036902' extends '324803' salience 4790

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "NFI", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036903' extends '324803' salience 4780

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "NSE", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036904' extends '324803' salience 4770

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "REH", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036905' extends '324803' salience 4760

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000512", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("OTHER ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036906' extends '324803' salience 4750

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5129018", rlnRelIdCtpy == "MIC", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("OTHER ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036907' extends '324803' salience 4740

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6019101", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("OTHER ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036908' extends '324803' salience 4730

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "NFD", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036909' extends '324803' salience 4720

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "NFI", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036910' extends '324803' salience 4710

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000518", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036911' extends '324803' salience 4700

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000516", rlnRelIdCtpy == "INGBCAPCONYK", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036912' extends '324803' salience 4690

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "TRM", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036913' extends '324803' salience 4680

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "BUNAO", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036914' extends '324803' salience 4670

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "EQSW", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036915' extends '324803' salience 4660

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "EXPR", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036916' extends '324803' salience 4650

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "FECI", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036917' extends '324803' salience 4640

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036918' extends '324803' salience 4630

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "MBSA", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036919' extends '324803' salience 4620

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "MFI", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036920' extends '324803' salience 4610

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "EQSW", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036921' extends '324803' salience 4600

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036923' extends '324803' salience 4590

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "7990001", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036924' extends '324803' salience 4580

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004996", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036925' extends '324803' salience 4570

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "EVVDEL", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036926' extends '324803' salience 4560

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "STREXPORTS", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036927' extends '324803' salience 4550

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5999999", rlnRelIdCtpy == "NFI", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036928' extends '324803' salience 4540

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5062001", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036929' extends '324803' salience 4530

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5020003", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036930' extends '324803' salience 4520

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5020002", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036931' extends '324803' salience 4510

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000518", rlnRelIdCtpy matches ".*U4O6HK4", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036932' extends '324803' salience 4500

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6019901", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036933' extends '324803' salience 4490

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "MMAR", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036934' extends '324803' salience 4480

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "IBFP", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036935' extends '324803' salience 4470

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "IPFC", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036936' extends '324803' salience 4460

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "EGMONTAFC", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036937' extends '324803' salience 4450

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000302", rlnRelIdCtpy == "INGFDG", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036938' extends '324803' salience 4440

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "EGMONTAFC", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036939' extends '324803' salience 4430

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "IRDD", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036940' extends '324803' salience 4420

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5019012", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036941' extends '324803' salience 4410

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "NFI", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036942' extends '324803' salience 4400

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "SA2", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037034' extends '324803' salience 4390

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "AL3", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037035' extends '324803' salience 4380

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "EQIN", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037036' extends '324803' salience 4370

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6019151", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("NIM ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037037' extends '324803' salience 4360

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5019151", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("NIM ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037038' extends '324803' salience 4350

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000302", rlnRelIdCtpy == "INGBCAPCONYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037039' extends '324803' salience 4340

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "AL4", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037040' extends '324803' salience 4330

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "AL3", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037041' extends '324803' salience 4320

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5019002", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037042' extends '324803' salience 4310

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000302", rlnRelIdCtpy == "SA2", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037043' extends '324803' salience 4300

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5011001", rlnRelIdCtpy == "INGFIN", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037044' extends '324803' salience 4290

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5019999", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037045' extends '324803' salience 4280

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5999999", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037046' extends '324803' salience 4270

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "MARNIXAFC", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037047' extends '324803' salience 4260

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "MARNIXAFC", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037048' extends '324803' salience 4250

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "STAB", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037049' extends '324803' salience 4240

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "STAC", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037050' extends '324803' salience 4230

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5019012", rlnRelIdCtpy == "EGMON", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037051' extends '324803' salience 4220

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5011001", rlnRelIdCtpy == "INGBCAPCONYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037052' extends '324803' salience 4210

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "IRDD", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037053' extends '324803' salience 4200

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "NCM", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037054' extends '324803' salience 4190

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5011001", rlnRelIdCtpy == "NSE", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037055' extends '324803' salience 4180

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "NCM", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037056' extends '324803' salience 4170

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6019002", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037057' extends '324803' salience 4160

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "MFI", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037058' extends '324803' salience 4150

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "NFI", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037059' extends '324803' salience 4140

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "NSE", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037060' extends '324803' salience 4130

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "REH", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037061' extends '324803' salience 4120

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000512", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("OTHER ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037062' extends '324803' salience 4110

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5129018", rlnRelIdCtpy == "MIC", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("OTHER ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037063' extends '324803' salience 4100

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6019101", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("OTHER ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037064' extends '324803' salience 4090

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "NFD", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037065' extends '324803' salience 4080

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "NFI", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037066' extends '324803' salience 4070

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000518", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037067' extends '324803' salience 4060

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000516", rlnRelIdCtpy == "INGBCAPCONYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037068' extends '324803' salience 4050

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "TRM", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037069' extends '324803' salience 4040

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "BUNAO", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037070' extends '324803' salience 4030

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "EQSW", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037071' extends '324803' salience 4020

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "EXPR", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037072' extends '324803' salience 4010

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "FECI", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037073' extends '324803' salience 4000

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037074' extends '324803' salience 3990

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "MBSA", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037075' extends '324803' salience 3980

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "MFI", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037076' extends '324803' salience 3970

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "EQSW", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037077' extends '324803' salience 3960

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037078' extends '324803' salience 3950

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5019150", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("NIM ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037079' extends '324803' salience 3940

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "7990001", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037080' extends '324803' salience 3930

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004996", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037081' extends '324803' salience 3920

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "EVVDEL", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037082' extends '324803' salience 3910

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "STREXPORTS", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037083' extends '324803' salience 3900

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5999999", rlnRelIdCtpy == "NFI", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037084' extends '324803' salience 3890

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5062001", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037085' extends '324803' salience 3880

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5020003", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037086' extends '324803' salience 3870

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5020002", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037087' extends '324803' salience 3860

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000518", rlnRelIdCtpy matches ".*U4O6HK4", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037088' extends '324803' salience 3850

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6019901", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037089' extends '324803' salience 3840

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "MMAR", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037090' extends '324803' salience 3830

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "IBFP", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037091' extends '324803' salience 3820

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "IPFC", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037092' extends '324803' salience 3810

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "EGMONTAFC", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037093' extends '324803' salience 3800

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000302", rlnRelIdCtpy == "INGFDG", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037094' extends '324803' salience 3790

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "EGMONTAFC", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037095' extends '324803' salience 3780

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "IRDD", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037096' extends '324803' salience 3770

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5019012", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037097' extends '324803' salience 3760

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "NFI", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037098' extends '324803' salience 3750

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "SA2", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037099' extends '324803' salience 3740

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6019150", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("NIM ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037189' extends '324803' salience 3730

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "EXPR", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037190' extends '324803' salience 3720

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "EQSW", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037191' extends '324803' salience 3710

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "MFI", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037192' extends '324803' salience 3700

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037193' extends '324803' salience 3690

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "EQSW", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037194' extends '324803' salience 3680

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "AL4", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037195' extends '324803' salience 3670

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5019999", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037196' extends '324803' salience 3660

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5999999", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037197' extends '324803' salience 3650

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5011001", rlnRelIdCtpy == "INGFIN", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037198' extends '324803' salience 3640

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000302", rlnRelIdCtpy == "SA2", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037199' extends '324803' salience 3630

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5019002", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037200' extends '324803' salience 3620

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037201' extends '324803' salience 3610

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "MBSA", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037202' extends '324803' salience 3600

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "MFI", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037203' extends '324803' salience 3590

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "NFI", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037204' extends '324803' salience 3580

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "NSE", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037205' extends '324803' salience 3570

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "REH", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037206' extends '324803' salience 3560

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "STREXPORTS", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037207' extends '324803' salience 3550

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "EVVDEL", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037208' extends '324803' salience 3540

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004996", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037209' extends '324803' salience 3530

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "7990001", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037214' extends '324803' salience 3520

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000512", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("OTHER ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037215' extends '324803' salience 3510

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5011001", rlnRelIdCtpy == "INGBCAPCONYK", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037216' extends '324803' salience 3500

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "IRDD", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037217' extends '324803' salience 3490

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "NCM", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037218' extends '324803' salience 3480

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5011001", rlnRelIdCtpy == "NSE", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037219' extends '324803' salience 3470

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "NCM", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037220' extends '324803' salience 3460

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000518", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037221' extends '324803' salience 3450

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000516", rlnRelIdCtpy == "INGBCAPCONYK", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037222' extends '324803' salience 3440

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "TRM", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037223' extends '324803' salience 3430

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "BUNAO", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037224' extends '324803' salience 3420

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "IRDD", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037225' extends '324803' salience 3410

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "EGMONTAFC", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037226' extends '324803' salience 3400

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "AL3", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037227' extends '324803' salience 3390

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5019012", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037228' extends '324803' salience 3380

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "NFI", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037229' extends '324803' salience 3370

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "SA2", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037230' extends '324803' salience 3360

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "EQIN", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037231' extends '324803' salience 3350

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "AL3", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037232' extends '324803' salience 3340

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000302", rlnRelIdCtpy == "INGBCAPCONYK", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037233' extends '324803' salience 3330

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6019002", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037234' extends '324803' salience 3320

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "NFI", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037235' extends '324803' salience 3310

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "NFD", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037236' extends '324803' salience 3300

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6019101", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("OTHER ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037237' extends '324803' salience 3290

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5129018", rlnRelIdCtpy == "MIC", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("OTHER ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037238' extends '324803' salience 3280

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5999999", rlnRelIdCtpy == "NFI", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037240' extends '324803' salience 3270

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5020003", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037241' extends '324803' salience 3260

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5020002", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037242' extends '324803' salience 3250

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000518", rlnRelIdCtpy matches ".*U4O6HK4", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037243' extends '324803' salience 3240

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6019901", rlnRelIdCtpy == "INGFINNYK", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037244' extends '324803' salience 3230

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "MMAR", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037245' extends '324803' salience 3220

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "IBFP", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037246' extends '324803' salience 3210

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5019012", rlnRelIdCtpy == "EGMON", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037247' extends '324803' salience 3200

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "STAC", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037248' extends '324803' salience 3190

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "STAB", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037249' extends '324803' salience 3180

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "MARNIXAFC", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037250' extends '324803' salience 3170

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "MARNIXAFC", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037251' extends '324803' salience 3160

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "IPFC", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037252' extends '324803' salience 3150

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "EGMONTAFC", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037253' extends '324803' salience 3140

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000302", rlnRelIdCtpy == "INGFDG", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037254' extends '324803' salience 3130

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "FECI", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036834' extends '324803' salience 3120

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6019034", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*NFI", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036835' extends '324803' salience 3110

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5062008", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NCM60305", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036836' extends '324803' salience 3100

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "36013330_US2", ldeDeptCd == "NFD60301", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036837' extends '324803' salience 3090

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000512", locRef matches ".*1$53GHNG", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036838' extends '324803' salience 3080

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "FOUPARCOR", ldeDeptCd == "NFI60301", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036839' extends '324803' salience 3070

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6001602", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NFD60301", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036840' extends '324803' salience 3060

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001505", rlnRelIdCtpy == "SA2", ldeDeptCd == "NFI60301", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036841' extends '324803' salience 3050

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001505", rlnRelIdCtpy == "REFI", ldeDeptCd == "NFI60301", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036842' extends '324803' salience 3040

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001505", rlnRelIdCtpy == "MMAR", ldeDeptCd == "NFI60301", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036843' extends '324803' salience 3030

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001505", rlnRelIdCtpy == "MFI", ldeDeptCd == "NFI60301", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036844' extends '324803' salience 3020

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001505", rlnRelIdCtpy == "INGFIN", ldeDeptCd == "NFI60301", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036845' extends '324803' salience 3010

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NFI60301", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036846' extends '324803' salience 3000

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NCMEFSCM", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036847' extends '324803' salience 2990

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NCM60301", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036848' extends '324803' salience 2980

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "MAR30329", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036849' extends '324803' salience 2970

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000513", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NCM60301", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036850' extends '324803' salience 2960

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "EGM30330", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036851' extends '324803' salience 2950

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000302", rlnRelIdCtpy == "STREXPORTS", ldeDeptCd == "NCM60307", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036852' extends '324803' salience 2940

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000302", rlnRelIdCtpy == "STAC", ldeDeptCd == "NCM60307", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036853' extends '324803' salience 2930

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000302", rlnRelIdCtpy == "PROJ", ldeDeptCd == "NCM60307", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036854' extends '324803' salience 2920

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000302", rlnRelIdCtpy == "NFD", ldeDeptCd == "NCM60307", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036855' extends '324803' salience 2910

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000302", rlnRelIdCtpy == "MELA", ldeDeptCd == "NCM60307", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036856' extends '324803' salience 2900

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000302", rlnRelIdCtpy == "EVVDEL", ldeDeptCd == "NCM60307", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036857' extends '324803' salience 2890

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000302", rlnRelIdCtpy == "ERNS", ldeDeptCd == "NCM60307", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036858' extends '324803' salience 2880

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000302", rlnRelIdCtpy == "ARGENINC", ldeDeptCd == "NCM60307", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036859' extends '324803' salience 2870

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5062052", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NCM60305", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036860' extends '324803' salience 2860

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5062052", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30199", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036861' extends '324803' salience 2850

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5062052", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "SEL30199", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036862' extends '324803' salience 2840

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001505", rlnRelIdCtpy == "REF", ldeDeptCd == "NFI60302", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036863' extends '324803' salience 2830

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NCM30111", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036864' extends '324803' salience 2820

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5062008", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30199", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036865' extends '324803' salience 2810

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5062008", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "SEL30199", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036866' extends '324803' salience 2800

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5060032", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30199", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036867' extends '324803' salience 2790

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5060032", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "SEL30199", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036868' extends '324803' salience 2780

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", locRef == "-", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036869' extends '324803' salience 2770

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", locRef matches ".*8$59BQER", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036870' extends '324803' salience 2760

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", locRef matches ".*1$53GHNG", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036871' extends '324803' salience 2750

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*TP45TUYA", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036872' extends '324803' salience 2740

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*INGFUND", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036873' extends '324803' salience 2730

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*BUNAO", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036874' extends '324803' salience 2720

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*FOUPARCOR", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036875' extends '324803' salience 2710

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6019034", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*-INGREACO", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036876' extends '324803' salience 2700

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*TRMINTCOR", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036877' extends '324803' salience 2690

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004996", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036990' extends '324803' salience 2680

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6019034", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*NFI", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036991' extends '324803' salience 2670

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5062008", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NCM60305", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036992' extends '324803' salience 2660

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "36013330_US", ldeDeptCd == "NFD60301", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036993' extends '324803' salience 2650

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000512", locRef matches ".*1$53GHNG", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036994' extends '324803' salience 2640

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "FOUPARCOR", ldeDeptCd == "NFI60301", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036995' extends '324803' salience 2630

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6001602", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NFD60301", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036996' extends '324803' salience 2620

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001505", rlnRelIdCtpy == "SA2", ldeDeptCd == "NFI60301", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036997' extends '324803' salience 2610

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001505", rlnRelIdCtpy == "REFI", ldeDeptCd == "NFI60301", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036998' extends '324803' salience 2600

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001505", rlnRelIdCtpy == "MMAR", ldeDeptCd == "NFI60301", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036999' extends '324803' salience 2590

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001505", rlnRelIdCtpy == "MFI", ldeDeptCd == "NFI60301", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037000' extends '324803' salience 2580

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001505", rlnRelIdCtpy == "INGFIN", ldeDeptCd == "NFI60301", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037001' extends '324803' salience 2570

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NFI60301", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037002' extends '324803' salience 2560

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NCMEFSCM", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037003' extends '324803' salience 2550

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NCM60301", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037004' extends '324803' salience 2540

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "MAR30329", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037005' extends '324803' salience 2530

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000513", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NCM60301", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037006' extends '324803' salience 2520

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "EGM30330", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037007' extends '324803' salience 2510

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000302", rlnRelIdCtpy == "STREXPORTS", ldeDeptCd == "NCM60307", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037008' extends '324803' salience 2500

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000302", rlnRelIdCtpy == "STAC", ldeDeptCd == "NCM60307", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037009' extends '324803' salience 2490

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000302", rlnRelIdCtpy == "PROJ", ldeDeptCd == "NCM60307", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037010' extends '324803' salience 2480

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000302", rlnRelIdCtpy == "NFD", ldeDeptCd == "NCM60307", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037011' extends '324803' salience 2470

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000302", rlnRelIdCtpy == "MELA", ldeDeptCd == "NCM60307", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037012' extends '324803' salience 2460

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000302", rlnRelIdCtpy == "EVVDEL", ldeDeptCd == "NCM60307", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037013' extends '324803' salience 2450

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000302", rlnRelIdCtpy == "ERNS", ldeDeptCd == "NCM60307", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037014' extends '324803' salience 2440

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000302", rlnRelIdCtpy == "ARGENINC", ldeDeptCd == "NCM60307", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037015' extends '324803' salience 2430

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5062052", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NCM60305", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037016' extends '324803' salience 2420

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5062052", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30199", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037017' extends '324803' salience 2410

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5062052", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "SEL30199", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037018' extends '324803' salience 2400

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001505", rlnRelIdCtpy == "REF", ldeDeptCd == "NFI60302", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037019' extends '324803' salience 2390

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NCM30111", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037020' extends '324803' salience 2380

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5062008", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30199", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037021' extends '324803' salience 2370

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5062008", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "SEL30199", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037022' extends '324803' salience 2360

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5060032", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30199", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037023' extends '324803' salience 2350

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5060032", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "SEL30199", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037024' extends '324803' salience 2340

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", locRef == "-", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037025' extends '324803' salience 2330

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", locRef matches ".*8$59BQER", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037026' extends '324803' salience 2320

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", locRef matches ".*1$53GHNG", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037027' extends '324803' salience 2310

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*TP45TUYA", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037028' extends '324803' salience 2300

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*INGFUND", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037029' extends '324803' salience 2290

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*BUNAO", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037030' extends '324803' salience 2280

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*FOUPARCOR", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037031' extends '324803' salience 2270

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6019034", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*-INGREACO", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037032' extends '324803' salience 2260

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*TRMINTCOR", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037033' extends '324803' salience 2250

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004996", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037145' extends '324803' salience 2240

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001505", rlnRelIdCtpy == "REF", ldeDeptCd == "NFI60302", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037146' extends '324803' salience 2230

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5062052", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "SEL30199", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037147' extends '324803' salience 2220

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5062052", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NCM60305", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037148' extends '324803' salience 2210

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*TRMINTCOR", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037149' extends '324803' salience 2200

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004996", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037150' extends '324803' salience 2190

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6019034", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*NFI", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037151' extends '324803' salience 2180

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", locRef == "-", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037152' extends '324803' salience 2170

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", locRef matches ".*8$59BQER", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037153' extends '324803' salience 2160

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", locRef matches ".*1$53GHNG", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037154' extends '324803' salience 2150

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*TP45TUYA", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037155' extends '324803' salience 2140

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*INGFUND", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037156' extends '324803' salience 2130

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*BUNAO", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037157' extends '324803' salience 2120

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*FOUPARCOR", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037158' extends '324803' salience 2110

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6019034", rlnRelIdCtpy == "INGFINNYK", locRef matches ".*-INGREACO", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037159' extends '324803' salience 2100

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000512", locRef matches ".*1$53GHNG", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037160' extends '324803' salience 2090

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "36013330", ldeDeptCd == "NFD60301", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037161' extends '324803' salience 2080

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NCM30111", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037162' extends '324803' salience 2070

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5062052", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30199", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037163' extends '324803' salience 2060

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001505", rlnRelIdCtpy == "SA2", ldeDeptCd == "NFI60301", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037164' extends '324803' salience 2050

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6001602", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NFD60301", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037165' extends '324803' salience 2040

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "FOUPARCOR", ldeDeptCd == "NFI60301", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037166' extends '324803' salience 2030

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5062008", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NCM60305", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037167' extends '324803' salience 2020

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000513", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NCM60301", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037168' extends '324803' salience 2010

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "MAR30329", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037169' extends '324803' salience 2000

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NCM60301", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037170' extends '324803' salience 1990

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NCMEFSCM", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037171' extends '324803' salience 1980

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NFI60301", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037172' extends '324803' salience 1970

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001505", rlnRelIdCtpy == "INGFIN", ldeDeptCd == "NFI60301", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037173' extends '324803' salience 1960

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001505", rlnRelIdCtpy == "MFI", ldeDeptCd == "NFI60301", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037174' extends '324803' salience 1950

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001505", rlnRelIdCtpy == "MMAR", ldeDeptCd == "NFI60301", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037175' extends '324803' salience 1940

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001505", rlnRelIdCtpy == "REFI", ldeDeptCd == "NFI60301", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037176' extends '324803' salience 1930

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000302", rlnRelIdCtpy == "ARGENINC", ldeDeptCd == "NCM60307", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037177' extends '324803' salience 1920

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000302", rlnRelIdCtpy == "ERNS", ldeDeptCd == "NCM60307", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037178' extends '324803' salience 1910

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000302", rlnRelIdCtpy == "EVVDEL", ldeDeptCd == "NCM60307", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037179' extends '324803' salience 1900

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000302", rlnRelIdCtpy == "MELA", ldeDeptCd == "NCM60307", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037180' extends '324803' salience 1890

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000302", rlnRelIdCtpy == "NFD", ldeDeptCd == "NCM60307", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037181' extends '324803' salience 1880

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000302", rlnRelIdCtpy == "PROJ", ldeDeptCd == "NCM60307", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037182' extends '324803' salience 1870

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000302", rlnRelIdCtpy == "STAC", ldeDeptCd == "NCM60307", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037183' extends '324803' salience 1860

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000302", rlnRelIdCtpy == "STREXPORTS", ldeDeptCd == "NCM60307", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037184' extends '324803' salience 1850

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5060032", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "SEL30199", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037185' extends '324803' salience 1840

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5062008", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30199", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037186' extends '324803' salience 1830

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5062008", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "SEL30199", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037187' extends '324803' salience 1820

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5060032", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30199", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037188' extends '324803' salience 1810

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "EGM30330", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036793' extends '324803' salience 1800

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5019040", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NCM60312", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036794' extends '324803' salience 1790

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5062052", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NCM60312", locRef == "-FOUPARCOR", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036795' extends '324803' salience 1780

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "BUN30199", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036796' extends '324803' salience 1770

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6001602", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NFD60301", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036797' extends '324803' salience 1760

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000519", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "EMD30198", locRef == "-INGFUND", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036798' extends '324803' salience 1750

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "TP45TUYA", ldeDeptCd == "FPC30196", locRef matches ".*TP45TUYA", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036799' extends '324803' salience 1740

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "FOUPARCOR", ldeDeptCd == "NFI30196", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036800' extends '324803' salience 1730

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004994", rlnRelIdCtpy == "REALACQ", ldeDeptCd == "NFI30196", locRef == "QU-REALACQ", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036801' extends '324803' salience 1720

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "SEL30199", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036802' extends '324803' salience 1710

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "TRI30198", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036803' extends '324803' salience 1700

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "TRI30199", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036804' extends '324803' salience 1690

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "N15Y825Y", ldeDeptCd == "MFI60301", locRef matches ".*N15Y825Y", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036805' extends '324803' salience 1680

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NFD60301", locRef == "QU-INGCAP", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036806' extends '324803' salience 1670

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "FOUPARCOR", ldeDeptCd == "NFI30196", locRef matches "QU.*", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036807' extends '324803' salience 1660

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "FPC30196", locRef == "QU-INGCAP", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036808' extends '324803' salience 1650

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "TP45TUYA", ldeDeptCd == "REA30196", locRef matches ".*TP45TUYA", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036809' extends '324803' salience 1640

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6027007", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "LGR30198", locRef == "-INGCAPITAL", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036810' extends '324803' salience 1630

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000519", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "LGR30198", locRef == "-INGFUND", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036811' extends '324803' salience 1620

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "FEPR", ldeDeptCd == "NFI60301", locRef == "I1-FEPR", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036812' extends '324803' salience 1610

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "REFI", ldeDeptCd == "NFI60301", locRef == "I1-REFI", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036813' extends '324803' salience 1600

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "REFI", ldeDeptCd == "NFI60310", locRef == "I1-REFI", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036814' extends '324803' salience 1590

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5000519", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "TRI30198", locRef == "-INGFUND", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036815' extends '324803' salience 1580

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "AL3", ldeDeptCd == "REF60157", locRef == "I1-AL3", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036816' extends '324803' salience 1570

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6004990", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NFI30196", locRef == "-FOUPARCOR", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036817' extends '324803' salience 1560

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001501", rlnRelIdCtpy == "SA2", ldeDeptCd == "NCM60307", locRef == "QU-SA2", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036818' extends '324803' salience 1550

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NFD60301", locRef == "QU-", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036819' extends '324803' salience 1540

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30198", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036820' extends '324803' salience 1530

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30199", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036821' extends '324803' salience 1520

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "LGR30198", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036822' extends '324803' salience 1510

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NFD60301", locRef == "QU-", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036823' extends '324803' salience 1500

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5019040", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30199", locRef == "-STRUCTEXP", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036824' extends '324803' salience 1490

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5019040", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NCM60305", locRef == "-FOUPARCOR", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036825' extends '324803' salience 1480

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6019040", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30199", locRef == "-INGCAPITAL", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036826' extends '324803' salience 1470

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6019040", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "SEL30199", locRef == "-FOUPARCOR", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036827' extends '324803' salience 1460

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30196", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036828' extends '324803' salience 1450

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6019040", rlnRelIdCtpy == "6019040", ldeDeptCd == "NCM60305", locRef == "-", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036829' extends '324803' salience 1440

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5019040", rlnRelIdCtpy == "5019040", ldeDeptCd == "NCM60305", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036830' extends '324803' salience 1430

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "EGM30338", locRef == "QU-INGCAP", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036831' extends '324803' salience 1420

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NCM60305", locRef == "QU-INGCAP", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036832' extends '324803' salience 1410

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NFD60301", locRef == "-INGCAP", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036833' extends '324803' salience 1400

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NFD60301", locRef == "QU-INGCAP", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036880' extends '324803' salience 1390

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6019151", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("NIM ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036881' extends '324803' salience 1380

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5019151", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("NIM ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036922' extends '324803' salience 1370

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "5019150", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("NIM ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036943' extends '324803' salience 1360

    when
        
        GrlPlYtd(this == $gpy, lseId == "14265", plAcctId == "6019150", lseHlyRelId == "0239_US_2")
        
    then
        $gpy.setCustomTxt20("NIM ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036949' extends '324803' salience 1350

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5019040", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NCM60312", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036950' extends '324803' salience 1340

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5062052", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NCM60312", locRef == "-FOUPARCOR", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036951' extends '324803' salience 1330

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "BUN30199", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036952' extends '324803' salience 1320

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6001602", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NFD60301", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036953' extends '324803' salience 1310

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000519", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "EMD30198", locRef == "-INGFUND", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036954' extends '324803' salience 1300

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "TP45TUYA", ldeDeptCd == "FPC30196", locRef matches ".*TP45TUYA", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036955' extends '324803' salience 1290

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "FOUPARCOR", ldeDeptCd == "NFI30196", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036956' extends '324803' salience 1280

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004994", rlnRelIdCtpy == "REALACQ", ldeDeptCd == "NFI30196", locRef == "QU-REALACQ", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036957' extends '324803' salience 1270

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "SEL30199", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036958' extends '324803' salience 1260

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "TRI30198", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036959' extends '324803' salience 1250

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "TRI30199", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036960' extends '324803' salience 1240

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "N15Y825Y", ldeDeptCd == "MFI60301", locRef matches ".*N15Y825Y", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036961' extends '324803' salience 1230

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NFD60301", locRef == "QU-INGCAP", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036962' extends '324803' salience 1220

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "FOUPARCOR", ldeDeptCd == "NFI30196", locRef matches "QU.*", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036963' extends '324803' salience 1210

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "FPC30196", locRef == "QU-INGCAP", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036964' extends '324803' salience 1200

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "TP45TUYA", ldeDeptCd == "REA30196", locRef matches ".*TP45TUYA", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036965' extends '324803' salience 1190

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6027007", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "LGR30198", locRef == "-INGCAPITAL", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036966' extends '324803' salience 1180

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000519", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "LGR30198", locRef == "-INGFUND", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036967' extends '324803' salience 1170

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "FEPR", ldeDeptCd == "NFI60301", locRef == "I1-FEPR", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036968' extends '324803' salience 1160

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "REFI", ldeDeptCd == "NFI60301", locRef == "I1-REFI", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036969' extends '324803' salience 1150

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "REFI", ldeDeptCd == "NFI60310", locRef == "I1-REFI", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036970' extends '324803' salience 1140

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5000519", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "TRI30198", locRef == "-INGFUND", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036971' extends '324803' salience 1130

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "AL3", ldeDeptCd == "REF60157", locRef == "I1-AL3", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036972' extends '324803' salience 1120

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6004990", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NFI30196", locRef == "-FOUPARCOR", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036973' extends '324803' salience 1110

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001501", rlnRelIdCtpy == "SA2", ldeDeptCd == "NCM60307", locRef == "QU-SA2", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036974' extends '324803' salience 1100

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NFD60301", locRef == "QU-", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036975' extends '324803' salience 1090

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30198", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036976' extends '324803' salience 1080

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30199", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036977' extends '324803' salience 1070

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "LGR30198", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036978' extends '324803' salience 1060

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NFD60301", locRef == "QU-", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036979' extends '324803' salience 1050

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5019040", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30199", locRef == "-STRUCTEXP", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036980' extends '324803' salience 1040

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5019040", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NCM60305", locRef == "-FOUPARCOR", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036981' extends '324803' salience 1030

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6019040", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30199", locRef == "-INGCAPITAL", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036982' extends '324803' salience 1020

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6019040", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "SEL30199", locRef == "-FOUPARCOR", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036983' extends '324803' salience 1010

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30196", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036984' extends '324803' salience 1000

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "6019040", rlnRelIdCtpy == "6019040", ldeDeptCd == "NCM60305", locRef == "-", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036985' extends '324803' salience 990

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5019040", rlnRelIdCtpy == "5019040", ldeDeptCd == "NCM60305", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036986' extends '324803' salience 980

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "EGM30338", locRef == "QU-INGCAP", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036987' extends '324803' salience 970

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NCM60305", locRef == "QU-INGCAP", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036988' extends '324803' salience 960

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NFD60301", locRef == "-INGCAP", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1036989' extends '324803' salience 950

    when
        
        GrlPlYtd(this == $gpy, lseId == "13845", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NFD60301", locRef == "QU-INGCAP", lseHlyRelId == "0239_US")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037104' extends '324803' salience 940

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "TRI30199", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037105' extends '324803' salience 930

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30199", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037106' extends '324803' salience 920

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "LGR30198", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037107' extends '324803' salience 910

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "SEL30199", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037108' extends '324803' salience 900

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "TRI30198", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037109' extends '324803' salience 890

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "FOUPARCOR", ldeDeptCd == "NFI30196", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037110' extends '324803' salience 880

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5019040", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NCM60305", locRef == "-FOUPARCOR", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037111' extends '324803' salience 870

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NFD60301", locRef == "QU-", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037112' extends '324803' salience 860

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NFD60301", locRef == "-INGCAP", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037113' extends '324803' salience 850

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "EGM30338", locRef == "QU-INGCAP", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037114' extends '324803' salience 840

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NFI30196", locRef == "-FOUPARCOR", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037115' extends '324803' salience 830

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5062052", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NCM60312", locRef == "-FOUPARCOR", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037116' extends '324803' salience 820

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6019040", rlnRelIdCtpy == "6019040", ldeDeptCd == "NCM60305", locRef == "-", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037117' extends '324803' salience 810

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5019040", rlnRelIdCtpy == "5019040", ldeDeptCd == "NCM60305", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037118' extends '324803' salience 800

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000519", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "TRI30198", locRef == "-INGFUND", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037119' extends '324803' salience 790

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "AL3", ldeDeptCd == "REF60157", locRef == "I1-AL3", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037120' extends '324803' salience 780

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6001602", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NFD60301", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037121' extends '324803' salience 770

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000519", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "EMD30198", locRef == "-INGFUND", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037122' extends '324803' salience 760

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "TP45TUYA", ldeDeptCd == "FPC30196", locRef matches ".*TP45TUYA", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037123' extends '324803' salience 750

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6027007", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "LGR30198", locRef == "-INGCAPITAL", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037124' extends '324803' salience 740

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000519", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "LGR30198", locRef == "-INGFUND", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037125' extends '324803' salience 730

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "FEPR", ldeDeptCd == "NFI60301", locRef == "I1-FEPR", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037126' extends '324803' salience 720

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "REFI", ldeDeptCd == "NFI60301", locRef == "I1-REFI", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037127' extends '324803' salience 710

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "REFI", ldeDeptCd == "NFI60310", locRef == "I1-REFI", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037128' extends '324803' salience 700

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "BUN30199", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037129' extends '324803' salience 690

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5019040", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NCM60312", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037130' extends '324803' salience 680

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", rlnRelIdCtpy == "SA2", ldeDeptCd == "NCM60307", locRef == "QU-SA2", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037131' extends '324803' salience 670

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001505", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NCM60305", locRef == "QU-INGCAP", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037132' extends '324803' salience 660

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "NFD60301", locRef == "QU-INGCAP", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037133' extends '324803' salience 650

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5019040", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30199", locRef == "-STRUCTEXP", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037134' extends '324803' salience 640

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "N15Y825Y", ldeDeptCd == "MFI60301", locRef matches ".*N15Y825Y", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037135' extends '324803' salience 630

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30196", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037136' extends '324803' salience 620

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NFD60301", locRef == "QU-INGCAP", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037137' extends '324803' salience 610

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", rlnRelIdCtpy == "FOUPARCOR", ldeDeptCd == "NFI30196", locRef matches "QU.*", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037138' extends '324803' salience 600

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "FPC30196", locRef == "QU-INGCAP", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037139' extends '324803' salience 590

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "TP45TUYA", ldeDeptCd == "REA30196", locRef matches ".*TP45TUYA", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037140' extends '324803' salience 580

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004994", rlnRelIdCtpy == "REALACQ", ldeDeptCd == "NFI30196", locRef == "QU-REALACQ", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037141' extends '324803' salience 570

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6019040", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30199", locRef == "-INGCAPITAL", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037142' extends '324803' salience 560

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6019040", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "SEL30199", locRef == "-FOUPARCOR", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("LOAN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037143' extends '324803' salience 550

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGCAP", ldeDeptCd == "NFD60301", locRef == "QU-", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037144' extends '324803' salience 540

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", rlnRelIdCtpy == "INGFINNYK", ldeDeptCd == "FPC30198", locRef matches ".*INGCAPITAL", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037210' extends '324803' salience 530

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5019150", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("NIM ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037211' extends '324803' salience 520

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5019151", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("NIM ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037212' extends '324803' salience 510

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6019150", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("NIM ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1037213' extends '324803' salience 500

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6019151", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("NIM ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113351' extends '324803' salience 490

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5060105", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113352' extends '324803' salience 480

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001504", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113353' extends '324803' salience 470

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004994", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113354' extends '324803' salience 460

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6019045", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113355' extends '324803' salience 450

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "7989101", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113356' extends '324803' salience 440

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5019999", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113357' extends '324803' salience 430

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5020001", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113358' extends '324803' salience 420

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5060004", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113359' extends '324803' salience 410

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000502", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113360' extends '324803' salience 400

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000503", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113361' extends '324803' salience 390

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000513", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113362' extends '324803' salience 380

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5000516", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113363' extends '324803' salience 370

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001501", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113364' extends '324803' salience 360

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5060015", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113365' extends '324803' salience 350

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5060031", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113366' extends '324803' salience 340

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5060032", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113367' extends '324803' salience 330

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5060033", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113368' extends '324803' salience 320

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5060039", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113369' extends '324803' salience 310

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5060103", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113370' extends '324803' salience 300

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5062001", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113371' extends '324803' salience 290

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5062033", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113372' extends '324803' salience 280

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5062034", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113373' extends '324803' salience 270

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5062058", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113374' extends '324803' salience 260

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5129007", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113375' extends '324803' salience 250

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5989999", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113376' extends '324803' salience 240

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5999998", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113377' extends '324803' salience 230

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5999999", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113378' extends '324803' salience 220

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6001602", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113379' extends '324803' salience 210

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6004990", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113380' extends '324803' salience 200

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6019004", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113381' extends '324803' salience 190

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6019031", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113382' extends '324803' salience 180

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6019101", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113383' extends '324803' salience 170

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6019999", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113384' extends '324803' salience 160

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6020503", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113385' extends '324803' salience 150

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6020504", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113386' extends '324803' salience 140

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6027003", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113387' extends '324803' salience 130

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6027006", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113388' extends '324803' salience 120

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6027007", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113389' extends '324803' salience 110

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "6027044", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113390' extends '324803' salience 100

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "7045403", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113391' extends '324803' salience 90

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "7989102", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113392' extends '324803' salience 80

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId in ("5129027", "6020006"), lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTRACO ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113393' extends '324803' salience 70

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5001505", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113394' extends '324803' salience 60

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009502", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113395' extends '324803' salience 50

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5009509", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113396' extends '324803' salience 40

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5060001", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113397' extends '324803' salience 30

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5060104", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113398' extends '324803' salience 20

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", plAcctId == "5062008", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("INTFUN ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end

rule '1113600' extends '324803' salience 10

    when
        
        GrlPlYtd(this == $gpy, lseId == "4083", ldeDeptCd matches ".*99999", lseHlyRelId == "0239")
        
    then
        $gpy.setCustomTxt20("DEFAULT ELIM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1237");
        
end


