package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '330411'
	when
		$gda : GrlDetAmounts(( hscAcctSubcl in ( "2720" , "3105" , "3106" , "3107" ) && icInd == "N" && actCode matches "A.*" && ( quotedInd == "N" || quotedInd == null ) ))
	then
        
end





rule '859069' extends '330411' salience 20560

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"))
        
    then
        $gda.setDvMarketstatCd("Table 1B_O20_CCYSWAP_REPDEALER_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859070' extends '330411' salience 20550

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "AUD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_K20_CCYSWAP_REPDEALER_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859071' extends '330411' salience 20540

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "BRL")
        
    then
        $gda.setDvMarketstatCd("Table 1B_L20_CCYSWAP_REPDEALER_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859072' extends '330411' salience 20530

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "CAD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_I20_CCYSWAP_REPDEALER_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859073' extends '330411' salience 20520

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "CHF")
        
    then
        $gda.setDvMarketstatCd("Table 1B_H20_CCYSWAP_REPDEALER_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859074' extends '330411' salience 20510

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "EUR")
        
    then
        $gda.setDvMarketstatCd("Table 1B_E20_CCYSWAP_REPDEALER_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859075' extends '330411' salience 20500

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "GBP")
        
    then
        $gda.setDvMarketstatCd("Table 1B_G20_CCYSWAP_REPDEALER_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859076' extends '330411' salience 20490

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "HKD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_N20_CCYSWAP_REPDEALER_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859077' extends '330411' salience 20480

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "JPY")
        
    then
        $gda.setDvMarketstatCd("Table 1B_F20_CCYSWAP_REPDEALER_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859078' extends '330411' salience 20470

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "PHP")
        
    then
        $gda.setDvMarketstatCd("Table 1B_M20_CCYSWAP_REPDEALER_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859079' extends '330411' salience 20460

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "SEK")
        
    then
        $gda.setDvMarketstatCd("Table 1B_J20_CCYSWAP_REPDEALER_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859080' extends '330411' salience 20450

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "USD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_D20_CCYSWAP_REPDEALER_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859081' extends '330411' salience 20440

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3106", hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"))
        
    then
        $gda.setDvMarketstatCd("Table 1B_O14_CCYFORW_REPDEALER_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859082' extends '330411' salience 20430

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3106", hcuCcyCdOrg == "AUD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_K14_CCYFORW_REPDEALER_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859083' extends '330411' salience 20420

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3106", hcuCcyCdOrg == "BRL")
        
    then
        $gda.setDvMarketstatCd("Table 1B_L14_CCYFORW_REPDEALER_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859084' extends '330411' salience 20410

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3106", hcuCcyCdOrg == "CAD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_I14_CCYFORW_REPDEALER_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859085' extends '330411' salience 20400

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3106", hcuCcyCdOrg == "CHF")
        
    then
        $gda.setDvMarketstatCd("Table 1B_H14_CCYFORW_REPDEALER_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859086' extends '330411' salience 20390

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3106", hcuCcyCdOrg == "EUR")
        
    then
        $gda.setDvMarketstatCd("Table 1B_E14_CCYFORW_REPDEALER_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859087' extends '330411' salience 20380

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3106", hcuCcyCdOrg == "GBP")
        
    then
        $gda.setDvMarketstatCd("Table 1B_G14_CCYFORW_REPDEALER_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859088' extends '330411' salience 20370

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3106", hcuCcyCdOrg == "HKD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_N14_CCYFORW_REPDEALER_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859089' extends '330411' salience 20360

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3106", hcuCcyCdOrg == "JPY")
        
    then
        $gda.setDvMarketstatCd("Table 1B_F14_CCYFORW_REPDEALER_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859090' extends '330411' salience 20350

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3106", hcuCcyCdOrg == "PHP")
        
    then
        $gda.setDvMarketstatCd("Table 1B_M14_CCYFORW_REPDEALER_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859091' extends '330411' salience 20340

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3106", hcuCcyCdOrg == "SEK")
        
    then
        $gda.setDvMarketstatCd("Table 1B_J14_CCYFORW_REPDEALER_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859092' extends '330411' salience 20330

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3106", hcuCcyCdOrg == "USD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_D14_CCYFORW_REPDEALER_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859093' extends '330411' salience 20320

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3107", hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"))
        
    then
        $gda.setDvMarketstatCd("Table 1B_O26_CCYOPT_BOUGHT_REPDEALER_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859094' extends '330411' salience 20310

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3107", hcuCcyCdOrg == "AUD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_K26_CCYOPT_BOUGHT_REPDEALER_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859095' extends '330411' salience 20300

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3107", hcuCcyCdOrg == "BRL")
        
    then
        $gda.setDvMarketstatCd("Table 1B_L26_CCYOPT_BOUGHT_REPDEALER_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859096' extends '330411' salience 20290

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3107", hcuCcyCdOrg == "CAD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_I26_CCYOPT_BOUGHT_REPDEALER_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859097' extends '330411' salience 20280

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3107", hcuCcyCdOrg == "CHF")
        
    then
        $gda.setDvMarketstatCd("Table 1B_H26_CCYOPT_BOUGHT_REPDEALER_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859098' extends '330411' salience 20270

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3107", hcuCcyCdOrg == "EUR")
        
    then
        $gda.setDvMarketstatCd("Table 1B_E26_CCYOPT_BOUGHT_REPDEALER_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859099' extends '330411' salience 20260

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3107", hcuCcyCdOrg == "GBP")
        
    then
        $gda.setDvMarketstatCd("Table 1B_G26_CCYOPT_BOUGHT_REPDEALER_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859100' extends '330411' salience 20250

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3107", hcuCcyCdOrg == "HKD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_N26_CCYOPT_BOUGHT_REPDEALER_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859101' extends '330411' salience 20240

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3107", hcuCcyCdOrg == "JPY")
        
    then
        $gda.setDvMarketstatCd("Table 1B_F26_CCYOPT_BOUGHT_REPDEALER_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859102' extends '330411' salience 20230

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3107", hcuCcyCdOrg == "PHP")
        
    then
        $gda.setDvMarketstatCd("Table 1B_M26_CCYOPT_BOUGHT_REPDEALER_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859103' extends '330411' salience 20220

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3107", hcuCcyCdOrg == "SEK")
        
    then
        $gda.setDvMarketstatCd("Table 1B_J26_CCYOPT_BOUGHT_REPDEALER_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '859104' extends '330411' salience 20210

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "3107", hcuCcyCdOrg == "USD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_D26_CCYOPT_BOUGHT_REPDEALER_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858120' extends '330411' salience 20200

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "EUR", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_E28_CCYOPT_BOUGHT_NONFIN_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858121' extends '330411' salience 20190

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "JPY", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_F28_CCYOPT_BOUGHT_NONFIN_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858122' extends '330411' salience 20180

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "GBP", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_G28_CCYOPT_BOUGHT_NONFIN_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858123' extends '330411' salience 20170

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "CHF", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_H28_CCYOPT_BOUGHT_NONFIN_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858124' extends '330411' salience 20160

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "CAD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_I28_CCYOPT_BOUGHT_NONFIN_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858125' extends '330411' salience 20150

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "SEK", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_J28_CCYOPT_BOUGHT_NONFIN_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858126' extends '330411' salience 20140

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "AUD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_K28_CCYOPT_BOUGHT_NONFIN_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858127' extends '330411' salience 20130

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "BRL", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_L28_CCYOPT_BOUGHT_NONFIN_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858128' extends '330411' salience 20120

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "PHP", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_M28_CCYOPT_BOUGHT_NONFIN_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858129' extends '330411' salience 20110

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "HKD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_N28_CCYOPT_BOUGHT_NONFIN_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858130' extends '330411' salience 20100

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"), finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_O28_CCYOPT_BOUGHT_NONFIN_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858132' extends '330411' salience 20090

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "GBP", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_G27_CCYOPT_BOUGHT_OTHFIN_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858133' extends '330411' salience 20080

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "CHF", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_H27_CCYOPT_BOUGHT_OTHFIN_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858134' extends '330411' salience 20070

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "CAD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_I27_CCYOPT_BOUGHT_OTHFIN_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858135' extends '330411' salience 20060

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "SEK", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_J27_CCYOPT_BOUGHT_OTHFIN_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858136' extends '330411' salience 20050

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "AUD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_K27_CCYOPT_BOUGHT_OTHFIN_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858137' extends '330411' salience 20040

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "BRL", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_L27_CCYOPT_BOUGHT_OTHFIN_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858138' extends '330411' salience 20030

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "PHP", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_M27_CCYOPT_BOUGHT_OTHFIN_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858139' extends '330411' salience 20020

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "HKD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_N27_CCYOPT_BOUGHT_OTHFIN_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858140' extends '330411' salience 20010

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"), finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_O27_CCYOPT_BOUGHT_OTHFIN_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858141' extends '330411' salience 20000

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "USD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_D28_CCYOPT_BOUGHT_NONFIN_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858142' extends '330411' salience 19990

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "JPY", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_F27_CCYOPT_BOUGHT_OTHFIN_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858143' extends '330411' salience 19980

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "SEK", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_J16_CCYFORW_NONFIN_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858144' extends '330411' salience 19970

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "AUD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_K16_CCYFORW_NONFIN_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858145' extends '330411' salience 19960

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "BRL", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_L16_CCYFORW_NONFIN_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858146' extends '330411' salience 19950

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "PHP", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_M16_CCYFORW_NONFIN_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858147' extends '330411' salience 19940

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "HKD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_N16_CCYFORW_NONFIN_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858148' extends '330411' salience 19930

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"), finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_O16_CCYFORW_NONFIN_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858149' extends '330411' salience 19920

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "USD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_D20_CCYSWAP_REPDEALER_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858150' extends '330411' salience 19910

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "EUR")
        
    then
        $gda.setDvMarketstatCd("Table 1B_E20_CCYSWAP_REPDEALER_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858151' extends '330411' salience 19900

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "JPY")
        
    then
        $gda.setDvMarketstatCd("Table 1B_F20_CCYSWAP_REPDEALER_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858152' extends '330411' salience 19890

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "GBP")
        
    then
        $gda.setDvMarketstatCd("Table 1B_G20_CCYSWAP_REPDEALER_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858153' extends '330411' salience 19880

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "CHF")
        
    then
        $gda.setDvMarketstatCd("Table 1B_H20_CCYSWAP_REPDEALER_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858154' extends '330411' salience 19870

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "CAD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_I20_CCYSWAP_REPDEALER_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858155' extends '330411' salience 19860

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "SEK")
        
    then
        $gda.setDvMarketstatCd("Table 1B_J20_CCYSWAP_REPDEALER_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858156' extends '330411' salience 19850

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "AUD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_K20_CCYSWAP_REPDEALER_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858157' extends '330411' salience 19840

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "BRL")
        
    then
        $gda.setDvMarketstatCd("Table 1B_L20_CCYSWAP_REPDEALER_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858158' extends '330411' salience 19830

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "PHP")
        
    then
        $gda.setDvMarketstatCd("Table 1B_M20_CCYSWAP_REPDEALER_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858159' extends '330411' salience 19820

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "HKD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_N20_CCYSWAP_REPDEALER_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858160' extends '330411' salience 19810

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"))
        
    then
        $gda.setDvMarketstatCd("Table 1B_O20_CCYSWAP_REPDEALER_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858161' extends '330411' salience 19800

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "USD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_D21_CCYSWAP_OTHFIN_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858162' extends '330411' salience 19790

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "EUR", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_E21_CCYSWAP_OTHFIN_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858163' extends '330411' salience 19780

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "JPY", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_F21_CCYSWAP_OTHFIN_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858164' extends '330411' salience 19770

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "GBP", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_G21_CCYSWAP_OTHFIN_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858165' extends '330411' salience 19760

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "CHF", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_H21_CCYSWAP_OTHFIN_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858166' extends '330411' salience 19750

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "CAD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_I21_CCYSWAP_OTHFIN_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858167' extends '330411' salience 19740

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "SEK", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_J21_CCYSWAP_OTHFIN_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858168' extends '330411' salience 19730

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "AUD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_K21_CCYSWAP_OTHFIN_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858169' extends '330411' salience 19720

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "BRL", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_L21_CCYSWAP_OTHFIN_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858170' extends '330411' salience 19710

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "PHP", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_M21_CCYSWAP_OTHFIN_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858171' extends '330411' salience 19700

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "HKD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_N21_CCYSWAP_OTHFIN_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858172' extends '330411' salience 19690

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"), finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_O21_CCYSWAP_OTHFIN_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858173' extends '330411' salience 19680

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "USD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_D22_CCYSWAP_NONFIN_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858174' extends '330411' salience 19670

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "EUR", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_E22_CCYSWAP_NONFIN_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858175' extends '330411' salience 19660

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "JPY", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_F22_CCYSWAP_NONFIN_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858176' extends '330411' salience 19650

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "GBP", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_G22_CCYSWAP_NONFIN_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858177' extends '330411' salience 19640

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "CHF", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_H22_CCYSWAP_NONFIN_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858178' extends '330411' salience 19630

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "CAD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_I22_CCYSWAP_NONFIN_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858179' extends '330411' salience 19620

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "SEK", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_J22_CCYSWAP_NONFIN_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858180' extends '330411' salience 19610

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "AUD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_K22_CCYSWAP_NONFIN_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858181' extends '330411' salience 19600

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "BRL", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_L22_CCYSWAP_NONFIN_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858182' extends '330411' salience 19590

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "PHP", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_M22_CCYSWAP_NONFIN_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858183' extends '330411' salience 19580

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg == "HKD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_N22_CCYSWAP_NONFIN_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858184' extends '330411' salience 19570

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl in ("2720", "3105"), hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"), finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_O22_CCYSWAP_NONFIN_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858185' extends '330411' salience 19560

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3107", hcuCcyCdOrg == "USD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_D26_CCYOPT_BOUGHT_REPDEALER_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858186' extends '330411' salience 19550

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3107", hcuCcyCdOrg == "EUR")
        
    then
        $gda.setDvMarketstatCd("Table 1B_E26_CCYOPT_BOUGHT_REPDEALER_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858187' extends '330411' salience 19540

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3107", hcuCcyCdOrg == "JPY")
        
    then
        $gda.setDvMarketstatCd("Table 1B_F26_CCYOPT_BOUGHT_REPDEALER_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858188' extends '330411' salience 19530

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3107", hcuCcyCdOrg == "GBP")
        
    then
        $gda.setDvMarketstatCd("Table 1B_G26_CCYOPT_BOUGHT_REPDEALER_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858189' extends '330411' salience 19520

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3107", hcuCcyCdOrg == "CHF")
        
    then
        $gda.setDvMarketstatCd("Table 1B_H26_CCYOPT_BOUGHT_REPDEALER_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858190' extends '330411' salience 19510

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3107", hcuCcyCdOrg == "CAD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_I26_CCYOPT_BOUGHT_REPDEALER_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858191' extends '330411' salience 19500

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3107", hcuCcyCdOrg == "SEK")
        
    then
        $gda.setDvMarketstatCd("Table 1B_J26_CCYOPT_BOUGHT_REPDEALER_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858192' extends '330411' salience 19490

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3107", hcuCcyCdOrg == "AUD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_K26_CCYOPT_BOUGHT_REPDEALER_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858193' extends '330411' salience 19480

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3107", hcuCcyCdOrg == "BRL")
        
    then
        $gda.setDvMarketstatCd("Table 1B_L26_CCYOPT_BOUGHT_REPDEALER_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858194' extends '330411' salience 19470

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3107", hcuCcyCdOrg == "PHP")
        
    then
        $gda.setDvMarketstatCd("Table 1B_M26_CCYOPT_BOUGHT_REPDEALER_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858195' extends '330411' salience 19460

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3107", hcuCcyCdOrg == "HKD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_N26_CCYOPT_BOUGHT_REPDEALER_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858196' extends '330411' salience 19450

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3107", hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"))
        
    then
        $gda.setDvMarketstatCd("Table 1B_O26_CCYOPT_BOUGHT_REPDEALER_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858197' extends '330411' salience 19440

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "USD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_D27_CCYOPT_BOUGHT_OTHFIN_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858198' extends '330411' salience 19430

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3107", hcuCcyCdOrg == "EUR", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_E27_CCYOPT_BOUGHT_OTHFIN_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858199' extends '330411' salience 19420

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "CAD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_I16_CCYFORW_NONFIN_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858200' extends '330411' salience 19410

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3106", hcuCcyCdOrg == "USD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_D14_CCYFORW_REPDEALER_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858201' extends '330411' salience 19400

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3106", hcuCcyCdOrg == "EUR")
        
    then
        $gda.setDvMarketstatCd("Table 1B_E14_CCYFORW_REPDEALER_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858202' extends '330411' salience 19390

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3106", hcuCcyCdOrg == "JPY")
        
    then
        $gda.setDvMarketstatCd("Table 1B_F14_CCYFORW_REPDEALER_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858203' extends '330411' salience 19380

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3106", hcuCcyCdOrg == "GBP")
        
    then
        $gda.setDvMarketstatCd("Table 1B_G14_CCYFORW_REPDEALER_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858204' extends '330411' salience 19370

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3106", hcuCcyCdOrg == "CHF")
        
    then
        $gda.setDvMarketstatCd("Table 1B_H14_CCYFORW_REPDEALER_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858205' extends '330411' salience 19360

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3106", hcuCcyCdOrg == "CAD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_I14_CCYFORW_REPDEALER_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858206' extends '330411' salience 19350

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3106", hcuCcyCdOrg == "SEK")
        
    then
        $gda.setDvMarketstatCd("Table 1B_J14_CCYFORW_REPDEALER_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858207' extends '330411' salience 19340

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3106", hcuCcyCdOrg == "AUD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_K14_CCYFORW_REPDEALER_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858208' extends '330411' salience 19330

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3106", hcuCcyCdOrg == "BRL")
        
    then
        $gda.setDvMarketstatCd("Table 1B_L14_CCYFORW_REPDEALER_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858209' extends '330411' salience 19320

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3106", hcuCcyCdOrg == "PHP")
        
    then
        $gda.setDvMarketstatCd("Table 1B_M14_CCYFORW_REPDEALER_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858210' extends '330411' salience 19310

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3106", hcuCcyCdOrg == "HKD")
        
    then
        $gda.setDvMarketstatCd("Table 1B_N14_CCYFORW_REPDEALER_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858211' extends '330411' salience 19300

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hscAcctSubcl == "3106", hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"))
        
    then
        $gda.setDvMarketstatCd("Table 1B_O14_CCYFORW_REPDEALER_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858212' extends '330411' salience 19290

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "USD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_D15_CCYFORW_OTHFIN_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858213' extends '330411' salience 19280

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "EUR", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_E15_CCYFORW_OTHFIN_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858214' extends '330411' salience 19270

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "JPY", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_F15_CCYFORW_OTHFIN_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858215' extends '330411' salience 19260

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "GBP", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_G15_CCYFORW_OTHFIN_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858216' extends '330411' salience 19250

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "CHF", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_H15_CCYFORW_OTHFIN_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858217' extends '330411' salience 19240

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "CAD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_I15_CCYFORW_OTHFIN_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858218' extends '330411' salience 19230

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "SEK", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_J15_CCYFORW_OTHFIN_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858219' extends '330411' salience 19220

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "AUD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_K15_CCYFORW_OTHFIN_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858220' extends '330411' salience 19210

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "BRL", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_L15_CCYFORW_OTHFIN_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858221' extends '330411' salience 19200

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "PHP", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_M15_CCYFORW_OTHFIN_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858222' extends '330411' salience 19190

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "HKD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_N15_CCYFORW_OTHFIN_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858223' extends '330411' salience 19180

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"), finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 1B_O15_CCYFORW_OTHFIN_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858224' extends '330411' salience 19170

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "USD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_D16_CCYFORW_NONFIN_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858225' extends '330411' salience 19160

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "EUR", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_E16_CCYFORW_NONFIN_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858226' extends '330411' salience 19150

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "JPY", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_F16_CCYFORW_NONFIN_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858227' extends '330411' salience 19140

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "GBP", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_G16_CCYFORW_NONFIN_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end

rule '858228' extends '330411' salience 19130

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hscAcctSubcl == "3106", hcuCcyCdOrg == "CHF", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 1B_H16_CCYFORW_NONFIN_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2260");
        
end


