package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '326497'
	when
		$gda : GrlDetAmounts(( ( hpePdtType in ( "BOND OPTION" , "INTR RATE OPT" , "SWAPTION" ) && hacAmtCl == "12" && icInd == "N" && buyInd == "Y" && posFairValInd == "Y" && ( quotedInd == "N" || quotedInd == null ) ) || ( hpePdtType == "IRS" && hacAmtCl in ( "03" , "12" ) && hsnSwapCl in ( "01" , "02" , "03" , "20" ) && icInd == "N" && posFairValInd == "Y" && ( quotedInd == "N" || quotedInd == null ) ) || ( hpePdtType == "FRA" && hacAmtCl in ( "03" , "12" ) && icInd == "N" && posFairValInd == "Y" && ( quotedInd == "N" || quotedInd == null ) ) ))
	then
        
end





rule '97205' extends '326497' salience 10620

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "FRA", hcuCcyCdOrg == "USD")
        
    then
        $gda.setDvMarketstatCd("Table 2B_D13_FRA_REPDEALER_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97206' extends '326497' salience 10610

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "FRA", hcuCcyCdOrg == "EUR")
        
    then
        $gda.setDvMarketstatCd("Table 2B_E13_FRA_REPDEALER_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97207' extends '326497' salience 10600

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "FRA", hcuCcyCdOrg == "JPY")
        
    then
        $gda.setDvMarketstatCd("Table 2B_F13_FRA_REPDEALER_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97208' extends '326497' salience 10590

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "FRA", hcuCcyCdOrg == "GBP")
        
    then
        $gda.setDvMarketstatCd("Table 2B_G13_FRA_REPDEALER_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97209' extends '326497' salience 10580

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "FRA", hcuCcyCdOrg == "CHF")
        
    then
        $gda.setDvMarketstatCd("Table 2B_H13_FRA_REPDEALER_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97210' extends '326497' salience 10570

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "FRA", hcuCcyCdOrg == "CAD")
        
    then
        $gda.setDvMarketstatCd("Table 2B_I13_FRA_REPDEALER_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97211' extends '326497' salience 10560

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "FRA", hcuCcyCdOrg == "SEK")
        
    then
        $gda.setDvMarketstatCd("Table 2B_J13_FRA_REPDEALER_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97212' extends '326497' salience 10550

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "FRA", hcuCcyCdOrg == "AUD")
        
    then
        $gda.setDvMarketstatCd("Table 2B_K13_FRA_REPDEALER_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97213' extends '326497' salience 10540

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "FRA", hcuCcyCdOrg == "BRL")
        
    then
        $gda.setDvMarketstatCd("Table 2B_L13_FRA_REPDEALER_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97214' extends '326497' salience 10530

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "FRA", hcuCcyCdOrg == "PHP")
        
    then
        $gda.setDvMarketstatCd("Table 2B_M13_FRA_REPDEALER_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97215' extends '326497' salience 10520

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "FRA", hcuCcyCdOrg == "HKD")
        
    then
        $gda.setDvMarketstatCd("Table 2B_N13_FRA_REPDEALER_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97216' extends '326497' salience 10510

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "FRA", hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"))
        
    then
        $gda.setDvMarketstatCd("Table 2B_O13_FRA_REPDEALER_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97217' extends '326497' salience 10500

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "USD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_D14_FRA_OTHFIN_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97218' extends '326497' salience 10490

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "EUR", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_E14_FRA_OTHFIN_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97219' extends '326497' salience 10480

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "JPY", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_F14_FRA_OTHFIN_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97220' extends '326497' salience 10470

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "GBP", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_G14_FRA_OTHFIN_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97221' extends '326497' salience 10460

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "CHF", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_H14_FRA_OTHFIN_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97222' extends '326497' salience 10450

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "CAD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_I14_FRA_OTHFIN_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97223' extends '326497' salience 10440

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "SEK", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_J14_FRA_OTHFIN_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97224' extends '326497' salience 10430

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "AUD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_K14_FRA_OTHFIN_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97225' extends '326497' salience 10420

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "BRL", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_L14_FRA_OTHFIN_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97226' extends '326497' salience 10410

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "PHP", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_M14_FRA_OTHFIN_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97227' extends '326497' salience 10400

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "HKD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_N14_FRA_OTHFIN_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97228' extends '326497' salience 10390

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"), finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_O14_FRA_OTHFIN_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97229' extends '326497' salience 10380

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "USD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_D15_FRA_NONFIN_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97230' extends '326497' salience 10370

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "EUR", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_E15_FRA_NONFIN_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97231' extends '326497' salience 10360

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "JPY", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_F15_FRA_NONFIN_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97232' extends '326497' salience 10350

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "GBP", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_G15_FRA_NONFIN_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97233' extends '326497' salience 10340

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "CHF", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_H15_FRA_NONFIN_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97234' extends '326497' salience 10330

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "CAD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_I15_FRA_NONFIN_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97235' extends '326497' salience 10320

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "SEK", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_J15_FRA_NONFIN_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97236' extends '326497' salience 10310

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "AUD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_K15_FRA_NONFIN_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97237' extends '326497' salience 10300

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "BRL", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_L15_FRA_NONFIN_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97238' extends '326497' salience 10290

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "PHP", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_M15_FRA_NONFIN_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97239' extends '326497' salience 10280

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg == "HKD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_N15_FRA_NONFIN_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97240' extends '326497' salience 10270

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "FRA", hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"), finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_O15_FRA_NONFIN_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97241' extends '326497' salience 10260

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "IRS", hcuCcyCdOrg == "USD")
        
    then
        $gda.setDvMarketstatCd("Table 2B_D19_IRS_REPDEALER_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97242' extends '326497' salience 10250

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "IRS", hcuCcyCdOrg == "EUR")
        
    then
        $gda.setDvMarketstatCd("Table 2B_E19_IRS_REPDEALER_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97243' extends '326497' salience 10240

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "IRS", hcuCcyCdOrg == "JPY")
        
    then
        $gda.setDvMarketstatCd("Table 2B_F19_IRS_REPDEALER_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97244' extends '326497' salience 10230

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "IRS", hcuCcyCdOrg == "GBP")
        
    then
        $gda.setDvMarketstatCd("Table 2B_G19_IRS_REPDEALER_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97245' extends '326497' salience 10220

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "IRS", hcuCcyCdOrg == "CHF")
        
    then
        $gda.setDvMarketstatCd("Table 2B_H19_IRS_REPDEALER_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97246' extends '326497' salience 10210

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "IRS", hcuCcyCdOrg == "CAD")
        
    then
        $gda.setDvMarketstatCd("Table 2B_I19_IRS_REPDEALER_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97247' extends '326497' salience 10200

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "IRS", hcuCcyCdOrg == "SEK")
        
    then
        $gda.setDvMarketstatCd("Table 2B_J19_IRS_REPDEALER_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97248' extends '326497' salience 10190

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "IRS", hcuCcyCdOrg == "AUD")
        
    then
        $gda.setDvMarketstatCd("Table 2B_K19_IRS_REPDEALER_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97249' extends '326497' salience 10180

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "IRS", hcuCcyCdOrg == "BRL")
        
    then
        $gda.setDvMarketstatCd("Table 2B_L19_IRS_REPDEALER_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97250' extends '326497' salience 10170

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "IRS", hcuCcyCdOrg == "PHP")
        
    then
        $gda.setDvMarketstatCd("Table 2B_M19_IRS_REPDEALER_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97251' extends '326497' salience 10160

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "IRS", hcuCcyCdOrg == "HKD")
        
    then
        $gda.setDvMarketstatCd("Table 2B_N19_IRS_REPDEALER_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97252' extends '326497' salience 10150

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType == "IRS", hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"))
        
    then
        $gda.setDvMarketstatCd("Table 2B_O19_IRS_REPDEALER_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97253' extends '326497' salience 10140

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "USD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_D20_IRS_OTHFIN_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97254' extends '326497' salience 10130

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "EUR", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_E20_IRS_OTHFIN_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97255' extends '326497' salience 10120

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "JPY", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_F20_IRS_OTHFIN_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97256' extends '326497' salience 10110

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "GBP", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_G20_IRS_OTHFIN_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97257' extends '326497' salience 10100

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "CHF", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_H20_IRS_OTHFIN_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97258' extends '326497' salience 10090

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "CAD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_I20_IRS_OTHFIN_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97259' extends '326497' salience 10080

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "SEK", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_J20_IRS_OTHFIN_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97260' extends '326497' salience 10070

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "AUD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_K20_IRS_OTHFIN_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97261' extends '326497' salience 10060

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "BRL", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_L20_IRS_OTHFIN_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97262' extends '326497' salience 10050

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "PHP", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_M20_IRS_OTHFIN_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97263' extends '326497' salience 10040

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "HKD", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_N20_IRS_OTHFIN_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97264' extends '326497' salience 10030

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"), finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_O20_IRS_OTHFIN_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97265' extends '326497' salience 10020

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "USD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_D21_IRS_NONFIN_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97266' extends '326497' salience 10010

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "EUR", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_E21_IRS_NONFIN_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97267' extends '326497' salience 10000

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "JPY", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_F21_IRS_NONFIN_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97268' extends '326497' salience 9990

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "GBP", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_G21_IRS_NONFIN_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97269' extends '326497' salience 9980

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "CHF", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_H21_IRS_NONFIN_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97270' extends '326497' salience 9970

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "CAD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_I21_IRS_NONFIN_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97271' extends '326497' salience 9960

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "SEK", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_J21_IRS_NONFIN_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97272' extends '326497' salience 9950

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "AUD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_K21_IRS_NONFIN_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97273' extends '326497' salience 9940

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "BRL", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_L21_IRS_NONFIN_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97274' extends '326497' salience 9930

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "PHP", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_M21_IRS_NONFIN_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97275' extends '326497' salience 9920

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg == "HKD", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_N21_IRS_NONFIN_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97276' extends '326497' salience 9910

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType == "IRS", hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"), finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_O21_IRS_NONFIN_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97277' extends '326497' salience 9900

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "USD", buyInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_D25_INTRRATEOPT_BOUGHT_REPDEALER_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97278' extends '326497' salience 9890

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "EUR", buyInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_E25_INTRRATEOPT_BOUGHT_REPDEALER_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97279' extends '326497' salience 9880

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "JPY", buyInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_F25_INTRRATEOPT_BOUGHT_REPDEALER_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97280' extends '326497' salience 9870

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "GBP", buyInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_G25_INTRRATEOPT_BOUGHT_REPDEALER_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97281' extends '326497' salience 9860

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "CHF", buyInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_H25_INTRRATEOPT_BOUGHT_REPDEALER_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97282' extends '326497' salience 9850

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "CAD", buyInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_I25_INTRRATEOPT_BOUGHT_REPDEALER_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97283' extends '326497' salience 9840

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "SEK", buyInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_J25_INTRRATEOPT_BOUGHT_REPDEALER_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97284' extends '326497' salience 9830

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "AUD", buyInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_K25_INTRRATEOPT_BOUGHT_REPDEALER_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97285' extends '326497' salience 9820

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "BRL", buyInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_L25_INTRRATEOPT_BOUGHT_REPDEALER_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97286' extends '326497' salience 9810

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "PHP", buyInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_M25_INTRRATEOPT_BOUGHT_REPDEALER_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97287' extends '326497' salience 9800

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "HKD", buyInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_N25_INTRRATEOPT_BOUGHT_REPDEALER_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97288' extends '326497' salience 9790

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "Y", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"), buyInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_O25_INTRRATEOPT_BOUGHT_REPDEALER_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97289' extends '326497' salience 9780

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "USD", buyInd == "Y", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_D26_INTRRATEOPT_BOUGHT_OTHFIN_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97290' extends '326497' salience 9770

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "EUR", buyInd == "Y", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_E26_INTRRATEOPT_BOUGHT_OTHFIN_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97291' extends '326497' salience 9760

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "JPY", buyInd == "Y", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_F26_INTRRATEOPT_BOUGHT_OTHFIN_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97292' extends '326497' salience 9750

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "GBP", buyInd == "Y", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_G26_INTRRATEOPT_BOUGHT_OTHFIN_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97293' extends '326497' salience 9740

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "CHF", buyInd == "Y", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_H26_INTRRATEOPT_BOUGHT_OTHFIN_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97294' extends '326497' salience 9730

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "CAD", buyInd == "Y", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_I26_INTRRATEOPT_BOUGHT_OTHFIN_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97295' extends '326497' salience 9720

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "SEK", buyInd == "Y", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_J26_INTRRATEOPT_BOUGHT_OTHFIN_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97296' extends '326497' salience 9710

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "AUD", buyInd == "Y", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_K26_INTRRATEOPT_BOUGHT_OTHFIN_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97297' extends '326497' salience 9700

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "BRL", buyInd == "Y", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_L26_INTRRATEOPT_BOUGHT_OTHFIN_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97298' extends '326497' salience 9690

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "PHP", buyInd == "Y", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_M26_INTRRATEOPT_BOUGHT_OTHFIN_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97299' extends '326497' salience 9680

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "HKD", buyInd == "Y", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_N26_INTRRATEOPT_BOUGHT_OTHFIN_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97300' extends '326497' salience 9670

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"), buyInd == "Y", finInstInd == "Y")
        
    then
        $gda.setDvMarketstatCd("Table 2B_O26_INTRRATEOPT_BOUGHT_OTHFIN_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97301' extends '326497' salience 9660

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "USD", buyInd == "Y", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_D27_INTRRATEOPT_BOUGHT_NONFIN_USD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97302' extends '326497' salience 9650

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "EUR", buyInd == "Y", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_E27_INTRRATEOPT_BOUGHT_NONFIN_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97303' extends '326497' salience 9640

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "JPY", buyInd == "Y", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_F27_INTRRATEOPT_BOUGHT_NONFIN_JPY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97304' extends '326497' salience 9630

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "GBP", buyInd == "Y", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_G27_INTRRATEOPT_BOUGHT_NONFIN_GBP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97305' extends '326497' salience 9620

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "CHF", buyInd == "Y", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_H27_INTRRATEOPT_BOUGHT_NONFIN_CHF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97306' extends '326497' salience 9610

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "CAD", buyInd == "Y", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_I27_INTRRATEOPT_BOUGHT_NONFIN_CAD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97307' extends '326497' salience 9600

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "SEK", buyInd == "Y", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_J27_INTRRATEOPT_BOUGHT_NONFIN_SEK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97308' extends '326497' salience 9590

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "AUD", buyInd == "Y", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_K27_INTRRATEOPT_BOUGHT_NONFIN_AUD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97309' extends '326497' salience 9580

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "BRL", buyInd == "Y", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_L27_INTRRATEOPT_BOUGHT_NONFIN_BRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97310' extends '326497' salience 9570

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "PHP", buyInd == "Y", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_M27_INTRRATEOPT_BOUGHT_NONFIN_PHP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97311' extends '326497' salience 9560

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg == "HKD", buyInd == "Y", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_N27_INTRRATEOPT_BOUGHT_NONFIN_HKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end

rule '97312' extends '326497' salience 9550

    when
        
        GrlDetAmounts(this == $gda, repDealerInd == "N", hpePdtType in ("BOND OPT", "INTR RATE OPT", "SWAPTION"), hcuCcyCdOrg not in ("USD", "EUR", "JPY", "GBP", "CHF", "CAD", "SEK", "AUD", "BRL", "PHP", "HKD"), buyInd == "Y", finInstInd == "N")
        
    then
        $gda.setDvMarketstatCd("Table 2B_O27_INTRRATEOPT_BOUGHT_NONFIN_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1475");
        
end


