package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '335554'
	when
		$gda : GrlDetAmounts(actCode == "B0610000" && icInd == "N")
	then
        
end





rule '1710834' extends '335554' salience 4930

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeCtpy not matches "B.*")
        
    then
        $gda.setRteCode("018");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5930");
        
end

rule '1710835' extends '335554' salience 4920

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeCtpy matches "B.*")
        
    then
        $gda.setRteCode("019");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5930");
        
end

rule '1710837' extends '335554' salience 4910
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1783220() == "one_year_or_less", hzeZoneCtryCov == "B", hceCovType in ("2005", "2008", "2011", "2021"))
        
    then
        $gda.setRteCode("048");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5930");
        
end

rule '1710836' extends '335554' salience 4900
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1783220() == "one_year_or_less", hzeZoneCtryCov == "B", covRelType in ("BCRI", "BEXC", "BGVO", "BHOL", "BJVT", "BLIM", "BSPV", "BGOF", "BGPR", "BPRO", "BRPR"), hceCovType in ("2024", "2030"))
        
    then
        $gda.setRteCode("048");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5930");
        
end


