package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '335568'
	when
		$gda : GrlDetAmounts(ownUse07 in ( "A0003000003" , "A0003000092" , "A0003000094" , "A0003000095" , "A0027000014000P0049044" , "A3931000012200B0036049" , "A002300000470000010007" , "A002300000470000011024" , "A002300000470000015007" , "A0027000009400P0049011" , "A0024000063" , "A8939000009400P0049011" , "A8939000009400P0049090" , "A8939000009400P0049091" , "A798700002900000015089" ) && lseHlyRelId in ( "0212" , "0212_RET" , "9614" , "9661" ))
	then
        
end





rule '1711110' extends '335568' salience 210

    when
        
        GrlDetAmounts(this == $gda, lseHlyRelId in ("0212", "0212_RET", "9614", "9661"), ownUse07 == "A002300000470000010007")
        
    then
        $gda.setRteCode("007");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5944");
        
end

rule '1711111' extends '335568' salience 200

    when
        
        GrlDetAmounts(this == $gda, lseHlyRelId in ("0212", "0212_RET", "9614", "9661"), ownUse07 == "A002300000470000011024")
        
    then
        $gda.setRteCode("024");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5944");
        
end

rule '1711112' extends '335568' salience 190

    when
        
        GrlDetAmounts(this == $gda, lseHlyRelId in ("0212", "0212_RET", "9614", "9661"), ownUse07 == "A002300000470000015007")
        
    then
        $gda.setRteCode("007");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5944");
        
end

rule '1711113' extends '335568' salience 180

    when
        
        GrlDetAmounts(this == $gda, lseHlyRelId in ("0212", "0212_RET", "9614", "9661"), ownUse07 == "A0027000009400P0049011")
        
    then
        $gda.setRteCode("011");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5944");
        
end

rule '1711114' extends '335568' salience 170

    when
        
        GrlDetAmounts(this == $gda, lseHlyRelId in ("0212", "0212_RET", "9614", "9661"), ownUse07 == "A0003000092")
        
    then
        $gda.setRteCode("092");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5944");
        
end

rule '1711115' extends '335568' salience 160

    when
        
        GrlDetAmounts(this == $gda, lseHlyRelId in ("0212", "0212_RET", "9614", "9661"), ownUse07 == "A0003000094")
        
    then
        $gda.setRteCode("094");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5944");
        
end

rule '1711116' extends '335568' salience 150

    when
        
        GrlDetAmounts(this == $gda, lseHlyRelId in ("0212", "0212_RET", "9614", "9661"), ownUse07 == "A0003000095")
        
    then
        $gda.setRteCode("095");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5944");
        
end

rule '1711117' extends '335568' salience 140

    when
        
        GrlDetAmounts(this == $gda, lseHlyRelId in ("0212", "0212_RET", "9614", "9661"), ownUse07 == "A0003000003")
        
    then
        $gda.setRteCode("003");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5944");
        
end

rule '1711118' extends '335568' salience 130

    when
        
        GrlDetAmounts(this == $gda, lseHlyRelId in ("0212", "0212_RET", "9614", "9661"), ownUse07 == "A3931000012200B0036049")
        
    then
        $gda.setRteCode("049");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5944");
        
end

rule '1711119' extends '335568' salience 120

    when
        
        GrlDetAmounts(this == $gda, lseHlyRelId in ("0212", "0212_RET", "9614", "9661"), ownUse07 == "A8939000009400P0049011")
        
    then
        $gda.setRteCode("011");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5944");
        
end

rule '1711120' extends '335568' salience 110

    when
        
        GrlDetAmounts(this == $gda, lseHlyRelId in ("0212", "0212_RET", "9614", "9661"), ownUse07 == "A8939000009400P0049090")
        
    then
        $gda.setRteCode("090");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5944");
        
end

rule '1711121' extends '335568' salience 100

    when
        
        GrlDetAmounts(this == $gda, lseHlyRelId in ("0212", "0212_RET", "9614", "9661"), ownUse07 == "A8939000009400P0049091")
        
    then
        $gda.setRteCode("091");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5944");
        
end

rule '1711122' extends '335568' salience 90

    when
        
        GrlDetAmounts(this == $gda, lseHlyRelId in ("0212", "0212_RET", "9614", "9661"), ownUse07 == "A798700002900000015089")
        
    then
        $gda.setRteCode("089");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5944");
        
end

rule '1711123' extends '335568' salience 80

    when
        
        GrlDetAmounts(this == $gda, lseHlyRelId in ("0212", "0212_RET", "9614", "9661"), ownUse07 == "A0024000063")
        
    then
        $gda.setRteCode("063");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5944");
        
end


