package com.ing.gfrs.rules;
global com.ing.gfrs.logical.apis.GreLrCustRefLogicalApi greLrCustRefLogicalApi;
global com.ing.gfrs.logical.apis.ChoExchangeRatesLogicalApi choExchangeRatesLogicalApi;
global com.ing.gfrs.logical.apis.GreHrCcyTransLogicalApi greHrCcyTransLogicalApi;
global com.ing.gfrs.logical.apis.GreVCpyBeyReyDrlLogicalApi greVCpyBeyReyDrlLogicalApi;
global com.ing.gfrs.logical.apis.GplVExchRatesDrlLogicalApi gplVExchRatesDrlLogicalApi;
global com.ing.gfrs.logical.apis.GreVBeyReyDrlLogicalApi greVBeyReyDrlLogicalApi;
global com.ing.gfrs.logical.apis.GrlAdjustmentsLogicalApi grlAdjustmentsLogicalApi;
global String dateFormat;



