package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '332318'
	when
		$gda : GrlDetAmounts(actCode in ( "A4412000" , "A7986000" ) && hcuCcyCdOrg == "PLN")
	then
        
end





rule '1154396' extends '332318' salience 10

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setLiquidityCd("7.03_P");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3590");
        
end


