package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '333917'
	when
		$gda : GrlDetAmounts(hpePdtType == "REPO" && intInd == "N")
	then
        
end





rule '1559368' extends '333917' salience 80240

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", eval(nvl(this.getsblsecvssecind(), 'n')) == "Y")
        
    then
        $gda.setLcrProduct("Stock Lending");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4676");
        
end

rule '1559369' extends '333917' salience 80230

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", eval(nvl(this.getsblsecvssecind(), 'n')) == "N")
        
    then
        $gda.setLcrProduct("Repo");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4676");
        
end

rule '1559370' extends '333917' salience 80220

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", eval(nvl(this.getsblsecvssecind(), 'n')) == "N")
        
    then
        $gda.setLcrProduct("Reverse Repo");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4676");
        
end

rule '1559371' extends '333917' salience 80210

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", eval(nvl(this.getsblsecvssecind(), 'n')) == "Y")
        
    then
        $gda.setLcrProduct("Stock Borrowing");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4676");
        
end

rule '1559366' extends '333917' salience 80200

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", eval(nvl(this.getsblsecvssecind(), 'n')) == "N", nettingUpd == "UPD")
        
    then
        $gda.setLcrProduct("Reverse Repo");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4676");
        
end

rule '1559367' extends '333917' salience 80190

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", eval(nvl(this.getsblsecvssecind(), 'n')) == "N", nettingUpd == "UPD")
        
    then
        $gda.setLcrProduct("Repo");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4676");
        
end


