package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '333921'
	when
		$gda : GrlDetAmounts(substr ( actCode , 1 , 1 ) in ( "A" , "L" ) && lcrProduct == "Repo" && intInd == "N" && hacAmtCl in ( "01" , "02" , "03" , "20" ))
	then
        
end





rule '1559889' extends '333921' salience 36160

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setNsfrCd("99");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559853' extends '333921' salience 36150
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("BIS", "Central Bank", "Sovereign", "Local Government", "PSE", "EFSF", "ESM", "EU", "IMF", "MDB", "SME", "Other"), liqCredQual == "E", getCase0_1558960() == "less_than_30_days")
        
    then
        $gda.setNsfrCd("C61.0070.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559854' extends '333921' salience 36140
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("BIS", "Central Bank", "Sovereign", "Local Government", "PSE", "EFSF", "ESM", "EU", "IMF", "MDB", "SME", "Other"), liqCredQual == "E", getCase0_1558960() == "between_30 days_and_three_months")
        
    then
        $gda.setNsfrCd("C61.0070.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559855' extends '333921' salience 36130
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("BIS", "Central Bank", "Sovereign", "Local Government", "PSE", "EFSF", "ESM", "EU", "IMF", "MDB", "SME", "Other"), liqCredQual == "E", getCase0_1558960() == "between_three_and_six_months")
        
    then
        $gda.setNsfrCd("C61.0070.020");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559856' extends '333921' salience 36120
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("BIS", "Central Bank", "Sovereign", "Local Government", "PSE", "EFSF", "ESM", "EU", "IMF", "MDB", "SME", "Other"), liqCredQual == "E", getCase0_1558960() == "between_six_and_nine_months")
        
    then
        $gda.setNsfrCd("C61.0070.030");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559857' extends '333921' salience 36110
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("BIS", "Central Bank", "Sovereign", "Local Government", "PSE", "EFSF", "ESM", "EU", "IMF", "MDB", "SME", "Other"), liqCredQual == "E", getCase0_1558960() == "between_nine_and_twelve_months")
        
    then
        $gda.setNsfrCd("C61.0070.040");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559858' extends '333921' salience 36100
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("BIS", "Central Bank", "Sovereign", "Local Government", "PSE", "EFSF", "ESM", "EU", "IMF", "MDB", "SME", "Other"), liqCredQual == "E", getCase0_1558960() == "more_than_one_year")
        
    then
        $gda.setNsfrCd("C61.0070.050");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559859' extends '333921' salience 36090
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("BIS", "Central Bank", "Sovereign", "Local Government", "PSE", "EFSF", "ESM", "EU", "IMF", "MDB", "SME", "Other"), liqCredQual == "H", getCase0_1558960() == "less_than_30_days")
        
    then
        $gda.setNsfrCd("C61.0080.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559860' extends '333921' salience 36080
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("BIS", "Central Bank", "Sovereign", "Local Government", "PSE", "EFSF", "ESM", "EU", "IMF", "MDB", "SME", "Other"), liqCredQual == "H", getCase0_1558960() == "between_30 days_and_three_months")
        
    then
        $gda.setNsfrCd("C61.0080.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559861' extends '333921' salience 36070
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("BIS", "Central Bank", "Sovereign", "Local Government", "PSE", "EFSF", "ESM", "EU", "IMF", "MDB", "SME", "Other"), liqCredQual == "H", getCase0_1558960() == "between_three_and_six_months")
        
    then
        $gda.setNsfrCd("C61.0080.020");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559862' extends '333921' salience 36060
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("BIS", "Central Bank", "Sovereign", "Local Government", "PSE", "EFSF", "ESM", "EU", "IMF", "MDB", "SME", "Other"), liqCredQual == "H", getCase0_1558960() == "between_six_and_nine_months")
        
    then
        $gda.setNsfrCd("C61.0080.030");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559863' extends '333921' salience 36050
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("BIS", "Central Bank", "Sovereign", "Local Government", "PSE", "EFSF", "ESM", "EU", "IMF", "MDB", "SME", "Other"), liqCredQual == "H", getCase0_1558960() == "between_nine_and_twelve_months")
        
    then
        $gda.setNsfrCd("C61.0080.040");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559864' extends '333921' salience 36040
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("BIS", "Central Bank", "Sovereign", "Local Government", "PSE", "EFSF", "ESM", "EU", "IMF", "MDB", "SME", "Other"), liqCredQual == "H", getCase0_1558960() == "more_than_one_year")
        
    then
        $gda.setNsfrCd("C61.0080.050");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559865' extends '333921' salience 36030
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("BIS", "Central Bank", "Sovereign", "Local Government", "PSE", "EFSF", "ESM", "EU", "IMF", "MDB", "SME", "Other"), liqCredQual == "O", getCase0_1558960() == "less_than_30_days")
        
    then
        $gda.setNsfrCd("C61.0090.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559866' extends '333921' salience 36020
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("BIS", "Central Bank", "Sovereign", "Local Government", "PSE", "EFSF", "ESM", "EU", "IMF", "MDB", "SME", "Other"), liqCredQual == "O", getCase0_1558960() == "between_30 days_and_three_months")
        
    then
        $gda.setNsfrCd("C61.0090.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559867' extends '333921' salience 36010
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("BIS", "Central Bank", "Sovereign", "Local Government", "PSE", "EFSF", "ESM", "EU", "IMF", "MDB", "SME", "Other"), liqCredQual == "O", getCase0_1558960() == "between_three_and_six_months")
        
    then
        $gda.setNsfrCd("C61.0090.020");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559868' extends '333921' salience 36000
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("BIS", "Central Bank", "Sovereign", "Local Government", "PSE", "EFSF", "ESM", "EU", "IMF", "MDB", "SME", "Other"), liqCredQual == "O", getCase0_1558960() == "between_six_and_nine_months")
        
    then
        $gda.setNsfrCd("C61.0090.030");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559869' extends '333921' salience 35990
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("BIS", "Central Bank", "Sovereign", "Local Government", "PSE", "EFSF", "ESM", "EU", "IMF", "MDB", "SME", "Other"), liqCredQual == "O", getCase0_1558960() == "between_nine_and_twelve_months")
        
    then
        $gda.setNsfrCd("C61.0090.040");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559870' extends '333921' salience 35980
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("BIS", "Central Bank", "Sovereign", "Local Government", "PSE", "EFSF", "ESM", "EU", "IMF", "MDB", "SME", "Other"), liqCredQual == "O", getCase0_1558960() == "more_than_one_year")
        
    then
        $gda.setNsfrCd("C61.0090.050");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559871' extends '333921' salience 35970
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("Credit Institution", "Financial Holding", "Financial Institution", "Insurance Undertaking", "Investment Firm", "Mixed Holding", "SSPE"), liqCredQual == "E", getCase0_1558960() == "less_than_30_days")
        
    then
        $gda.setNsfrCd("C61.0140.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559872' extends '333921' salience 35960
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("Credit Institution", "Financial Holding", "Financial Institution", "Insurance Undertaking", "Investment Firm", "Mixed Holding", "SSPE"), liqCredQual == "E", getCase0_1558960() == "between_30 days_and_three_months")
        
    then
        $gda.setNsfrCd("C61.0140.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559873' extends '333921' salience 35950
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("Credit Institution", "Financial Holding", "Financial Institution", "Insurance Undertaking", "Investment Firm", "Mixed Holding", "SSPE"), liqCredQual == "E", getCase0_1558960() == "between_three_and_six_months")
        
    then
        $gda.setNsfrCd("C61.0140.020");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559874' extends '333921' salience 35940
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("Credit Institution", "Financial Holding", "Financial Institution", "Insurance Undertaking", "Investment Firm", "Mixed Holding", "SSPE"), liqCredQual == "E", getCase0_1558960() == "between_six_and_nine_months")
        
    then
        $gda.setNsfrCd("C61.0140.030");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559875' extends '333921' salience 35930
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("Credit Institution", "Financial Holding", "Financial Institution", "Insurance Undertaking", "Investment Firm", "Mixed Holding", "SSPE"), liqCredQual == "E", getCase0_1558960() == "between_nine_and_twelve_months")
        
    then
        $gda.setNsfrCd("C61.0140.040");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559876' extends '333921' salience 35920
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("Credit Institution", "Financial Holding", "Financial Institution", "Insurance Undertaking", "Investment Firm", "Mixed Holding", "SSPE"), liqCredQual == "E", getCase0_1558960() == "more_than_one_year")
        
    then
        $gda.setNsfrCd("C61.0140.050");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559877' extends '333921' salience 35910
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("Credit Institution", "Financial Holding", "Financial Institution", "Insurance Undertaking", "Investment Firm", "Mixed Holding", "SSPE"), liqCredQual == "H", getCase0_1558960() == "less_than_30_days")
        
    then
        $gda.setNsfrCd("C61.0150.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559878' extends '333921' salience 35900
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("Credit Institution", "Financial Holding", "Financial Institution", "Insurance Undertaking", "Investment Firm", "Mixed Holding", "SSPE"), liqCredQual == "H", getCase0_1558960() == "between_30 days_and_three_months")
        
    then
        $gda.setNsfrCd("C61.0150.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559879' extends '333921' salience 35890
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("Credit Institution", "Financial Holding", "Financial Institution", "Insurance Undertaking", "Investment Firm", "Mixed Holding", "SSPE"), liqCredQual == "H", getCase0_1558960() == "between_three_and_six_months")
        
    then
        $gda.setNsfrCd("C61.0150.020");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559880' extends '333921' salience 35880
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("Credit Institution", "Financial Holding", "Financial Institution", "Insurance Undertaking", "Investment Firm", "Mixed Holding", "SSPE"), liqCredQual == "H", getCase0_1558960() == "between_six_and_nine_months")
        
    then
        $gda.setNsfrCd("C61.0150.030");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559881' extends '333921' salience 35870
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("Credit Institution", "Financial Holding", "Financial Institution", "Insurance Undertaking", "Investment Firm", "Mixed Holding", "SSPE"), liqCredQual == "H", getCase0_1558960() == "between_nine_and_twelve_months")
        
    then
        $gda.setNsfrCd("C61.0150.040");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559882' extends '333921' salience 35860
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("Credit Institution", "Financial Holding", "Financial Institution", "Insurance Undertaking", "Investment Firm", "Mixed Holding", "SSPE"), liqCredQual == "H", getCase0_1558960() == "more_than_one_year")
        
    then
        $gda.setNsfrCd("C61.0150.050");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559883' extends '333921' salience 35850
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("Credit Institution", "Financial Holding", "Financial Institution", "Insurance Undertaking", "Investment Firm", "Mixed Holding", "SSPE"), liqCredQual == "O", getCase0_1558960() == "less_than_30_days")
        
    then
        $gda.setNsfrCd("C61.0160.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559884' extends '333921' salience 35840
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("Credit Institution", "Financial Holding", "Financial Institution", "Insurance Undertaking", "Investment Firm", "Mixed Holding", "SSPE"), liqCredQual == "O", getCase0_1558960() == "between_30 days_and_three_months")
        
    then
        $gda.setNsfrCd("C61.0160.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559885' extends '333921' salience 35830
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("Credit Institution", "Financial Holding", "Financial Institution", "Insurance Undertaking", "Investment Firm", "Mixed Holding", "SSPE"), liqCredQual == "O", getCase0_1558960() == "between_three_and_six_months")
        
    then
        $gda.setNsfrCd("C61.0160.020");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559886' extends '333921' salience 35820
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("Credit Institution", "Financial Holding", "Financial Institution", "Insurance Undertaking", "Investment Firm", "Mixed Holding", "SSPE"), liqCredQual == "O", getCase0_1558960() == "between_six_and_nine_months")
        
    then
        $gda.setNsfrCd("C61.0160.030");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559887' extends '333921' salience 35810
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("Credit Institution", "Financial Holding", "Financial Institution", "Insurance Undertaking", "Investment Firm", "Mixed Holding", "SSPE"), liqCredQual == "O", getCase0_1558960() == "between_nine_and_twelve_months")
        
    then
        $gda.setNsfrCd("C61.0160.040");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end

rule '1559888' extends '333921' salience 35800
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrCtpyType in ("Credit Institution", "Financial Holding", "Financial Institution", "Insurance Undertaking", "Investment Firm", "Mixed Holding", "SSPE"), liqCredQual == "O", getCase0_1558960() == "more_than_one_year")
        
    then
        $gda.setNsfrCd("C61.0160.050");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4680");
        
end


