package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '334419'
	when
		$gda : GrlDetAmounts(substr ( actCode , 1 , 1 ) in ( "A" , "L" ) && ( lcrProduct matches "Own Issued.*" ) && intInd == "N" && hacAmtCl != "03")
	then
        
end





rule '1560000' extends '334419' salience 1270

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setNsfrCd("99");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1559994' extends '334419' salience 1260
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "L.*", getCase0_1558960() == "less_than_30_days")
        
    then
        $gda.setNsfrCd("C61.0230.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1559995' extends '334419' salience 1250
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "L.*", getCase0_1558960() == "between_three_and_six_months")
        
    then
        $gda.setNsfrCd("C61.0230.020");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1559996' extends '334419' salience 1240
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "L.*", getCase0_1558960() == "between_six_and_nine_months")
        
    then
        $gda.setNsfrCd("C61.0230.030");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1559997' extends '334419' salience 1230
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "L.*", getCase0_1558960() == "between_nine_and_twelve_months")
        
    then
        $gda.setNsfrCd("C61.0230.040");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1559998' extends '334419' salience 1220
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "L.*", getCase0_1558960() == "more_than_one_year")
        
    then
        $gda.setNsfrCd("C61.0230.050");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1559999' extends '334419' salience 1210
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "L.*", getCase0_1558960() == "between_30 days_and_three_months")
        
    then
        $gda.setNsfrCd("C61.0230.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560019' extends '334419' salience 1200
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", getCase0_1558960() == "less_than_30_days")
        
    then
        $gda.setNsfrCd("C61.0230.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560020' extends '334419' salience 1190
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", getCase0_1558960() == "between_30 days_and_three_months")
        
    then
        $gda.setNsfrCd("C61.0230.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560021' extends '334419' salience 1180
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", getCase0_1558960() == "between_three_and_six_months")
        
    then
        $gda.setNsfrCd("C61.0230.020");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560022' extends '334419' salience 1170
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", getCase0_1558960() == "between_six_and_nine_months")
        
    then
        $gda.setNsfrCd("C61.0230.030");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560023' extends '334419' salience 1160
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", getCase0_1558960() == "between_nine_and_twelve_months")
        
    then
        $gda.setNsfrCd("C61.0230.040");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560024' extends '334419' salience 1150
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", getCase0_1558960() == "more_than_one_year")
        
    then
        $gda.setNsfrCd("C61.0230.050");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560025' extends '334419' salience 1140
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "Y", actCode matches "A.*", getCase0_1558960() == "less_than_30_days")
        
    then
        $gda.setNsfrCd("C61.0230.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560026' extends '334419' salience 1130
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "Y", actCode matches "A.*", getCase0_1558960() == "between_30 days_and_three_months")
        
    then
        $gda.setNsfrCd("C61.0230.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560027' extends '334419' salience 1120
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "Y", actCode matches "A.*", getCase0_1558960() == "between_three_and_six_months")
        
    then
        $gda.setNsfrCd("C61.0230.020");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560028' extends '334419' salience 1110
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "Y", actCode matches "A.*", getCase0_1558960() == "between_six_and_nine_months")
        
    then
        $gda.setNsfrCd("C61.0230.030");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560029' extends '334419' salience 1100
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "Y", actCode matches "A.*", getCase0_1558960() == "between_nine_and_twelve_months")
        
    then
        $gda.setNsfrCd("C61.0230.040");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560030' extends '334419' salience 1090
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "Y", actCode matches "A.*", getCase0_1558960() == "more_than_one_year")
        
    then
        $gda.setNsfrCd("C61.0230.050");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560001' extends '334419' salience 1080
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", credQualStepIss == "1", getCase0_1558960() == "less_than_30_days")
        
    then
        $gda.setNsfrCd("C61.0230.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560002' extends '334419' salience 1070
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", credQualStepIss == "1", getCase0_1558960() == "between_30 days_and_three_months")
        
    then
        $gda.setNsfrCd("C61.0230.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560003' extends '334419' salience 1060
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", credQualStepIss == "1", getCase0_1558960() == "between_three_and_six_months")
        
    then
        $gda.setNsfrCd("C61.0230.020");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560004' extends '334419' salience 1050
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", credQualStepIss == "1", getCase0_1558960() == "between_six_and_nine_months")
        
    then
        $gda.setNsfrCd("C61.0230.030");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560005' extends '334419' salience 1040
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", credQualStepIss == "1", getCase0_1558960() == "between_nine_and_twelve_months")
        
    then
        $gda.setNsfrCd("C61.0230.040");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560006' extends '334419' salience 1030
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", credQualStepIss == "1", getCase0_1558960() == "more_than_one_year")
        
    then
        $gda.setNsfrCd("C61.0230.050");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560007' extends '334419' salience 1020
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", credQualStepIss == "2", getCase0_1558960() == "less_than_30_days")
        
    then
        $gda.setNsfrCd("C61.0230.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560008' extends '334419' salience 1010
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", credQualStepIss == "2", getCase0_1558960() == "between_30 days_and_three_months")
        
    then
        $gda.setNsfrCd("C61.0230.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560009' extends '334419' salience 1000
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", credQualStepIss == "2", getCase0_1558960() == "between_three_and_six_months")
        
    then
        $gda.setNsfrCd("C61.0230.020");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560010' extends '334419' salience 990
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", credQualStepIss == "2", getCase0_1558960() == "between_six_and_nine_months")
        
    then
        $gda.setNsfrCd("C61.0230.030");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560011' extends '334419' salience 980
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", credQualStepIss == "2", getCase0_1558960() == "between_nine_and_twelve_months")
        
    then
        $gda.setNsfrCd("C61.0230.040");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560012' extends '334419' salience 970
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", credQualStepIss == "2", getCase0_1558960() == "more_than_one_year")
        
    then
        $gda.setNsfrCd("C61.0230.050");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560013' extends '334419' salience 960
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", credQualStepIss == "3", getCase0_1558960() == "less_than_30_days")
        
    then
        $gda.setNsfrCd("C61.0230.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560014' extends '334419' salience 950
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", credQualStepIss == "3", getCase0_1558960() == "between_30 days_and_three_months")
        
    then
        $gda.setNsfrCd("C61.0230.010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560015' extends '334419' salience 940
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", credQualStepIss == "3", getCase0_1558960() == "between_three_and_six_months")
        
    then
        $gda.setNsfrCd("C61.0230.020");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560016' extends '334419' salience 930
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", credQualStepIss == "3", getCase0_1558960() == "between_six_and_nine_months")
        
    then
        $gda.setNsfrCd("C61.0230.030");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560017' extends '334419' salience 920
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", credQualStepIss == "3", getCase0_1558960() == "between_nine_and_twelve_months")
        
    then
        $gda.setNsfrCd("C61.0230.040");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end

rule '1560018' extends '334419' salience 910
no-loop
    when
        
        GrlDetAmounts(this == $gda, eval(nvl(this.getencumberedind(), 'n')) == "N", actCode matches "A.*", credQualStepIss == "3", getCase0_1558960() == "more_than_one_year")
        
    then
        $gda.setNsfrCd("C61.0230.050");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5101");
        
end


