package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '333923'
	when
		$gda : GrlDetAmounts(( substr ( actCode , 1 , 1 ) in ( "A" , "L" ) && actCode in ( "A0027000" , "A0057000" , "A3329000" , "A3332000" , "A8805000" , "A8806000" , "A8807000" , "A9260000" , "A9457000" , "A9459000" , "A9750000" , "L0242000" , "L1425000" , "L3343000" , "L3933000" , "L9261000" , "L9751000" ) && pdtCode in ( "027800" , "027900" ) || ( hpePdtType == "REPO" ) && hacAmtCl in ( "11" , "19" ) ) && intInd == "N")
	then
        
end





rule '1582747' extends '333923' salience 79160

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setLiqCredQual("O");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4682");
        
end

rule '1584544' extends '333923' salience 79150

    when
        
        GrlDetAmounts(this == $gda, lcrUnderlyingProduct == "Other Equity Securities", lcrIssuerType in ("Other", "PSE", "SME"))
        
    then
        $gda.setLiqCredQual("H");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4682");
        
end

rule '1582743' extends '333923' salience 79140
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrUnderlyingProduct == "Covered Bond", getCase0_1559259() == "Y", credQualStepIss in ("1", "2", "3"))
        
    then
        $gda.setLiqCredQual("H");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4682");
        
end

rule '1582744' extends '333923' salience 79130
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrUnderlyingProduct == "RMBS", getCase0_1559259() == "Y", credQualStepIss in ("1", "2", "3"))
        
    then
        $gda.setLiqCredQual("H");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4682");
        
end

rule '1582746' extends '333923' salience 79120
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrUnderlyingProduct == "ABS", getCase0_1559259() == "Y", credQualStepIss in ("1", "2", "3"))
        
    then
        $gda.setLiqCredQual("H");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4682");
        
end

rule '1582742' extends '333923' salience 79110
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrUnderlyingProduct == "Corporate Bond", getCase0_1559259() == "Y", lcrIssuerType in ("Other", "PSE", "SME", "Credit Institution"), credQualStepIss in ("1", "2", "3"))
        
    then
        $gda.setLiqCredQual("H");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4682");
        
end

rule '1582748' extends '333923' salience 79100
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrUnderlyingProduct in ("Corporate Bond", "Commercial Paper", "Covered Bond", "RMBS", "ABS"), getCase0_1559259() == "Y", lcrIssuerType in ("Sovereign", "Local Government", "Central Bank", "PSE", "IMF", "BIS", "ECB", "MDB", "EU", "EFSF", "ESM"), credRiskWghtIss == "0")
        
    then
        $gda.setLiqCredQual("E");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4682");
        
end

rule '1582754' extends '333923' salience 79090
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrUnderlyingProduct in ("Corporate Bond", "Commercial Paper", "Covered Bond", "RMBS", "ABS"), getCase0_1559259() == "Y", lcrIssuerType in ("PSE", "MDB"), credRiskWghtIss == "20")
        
    then
        $gda.setLiqCredQual("H");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4682");
        
end

rule '1582741' extends '333923' salience 79080
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrUnderlyingProduct in ("Corporate Bond", "Commercial Paper", "Covered Bond", "RMBS", "ABS"), getCase0_1559259() == "Y", lcrIssuerType in ("Other", "SME"), lcrGuarType in ("Local Government", "PSE", "MDB"), credRiskWghtGuar == "20")
        
    then
        $gda.setLiqCredQual("H");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4682");
        
end

rule '1582745' extends '333923' salience 79070
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrUnderlyingProduct in ("Corporate Bond", "Commercial Paper", "Covered Bond", "RMBS", "ABS"), getCase0_1559259() == "Y", lcrIssuerType == "Credit institution", issSetUpByGovInd == "Y", credQualStepIss in ("1", "2", "3"))
        
    then
        $gda.setLiqCredQual("H");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4682");
        
end

rule '1582749' extends '333923' salience 79060
no-loop
    when
        
        GrlDetAmounts(this == $gda, lcrUnderlyingProduct in ("Corporate Bond", "Commercial Paper", "Covered Bond", "RMBS", "ABS"), getCase0_1559259() == "Y", lcrIssuerType in ("Other", "SME", "Credit Institution", "PSE", "Local Government"), lcrGuarType in ("Sovereign", "Local Government", "Central Bank", "PSE", "IMF", "BIS", "ECB", "MDB", "EU", "EFSF", "ESM"), credRiskWghtGuar == "0")
        
    then
        $gda.setLiqCredQual("E");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4682");
        
end

rule '1582752' extends '333923' salience 79050
no-loop
    when
        
        /*MANUAL adjustment here, because of error: Table gre_hr_ctry_ccy does not have an entry within the refDataApi within the dbConfig file*/
        GrlDetAmounts(this == $gda, lcrUnderlyingProduct in ("Corporate Bond", "Commercial Paper", "Covered Bond", "RMBS", "ABS"), getCase0_1559259() == "Y", lcrIssuerType in ("Sovereign", "Central Bank"), credRiskWghtIss == "20")
        
    then
        $gda.setLiqCredQual("H");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4682");
        
end

rule '1582750' extends '333923' salience 79040
no-loop
    when
        
        /*MANUAL adjustment here, because of error: Table gre_hr_ctry_ccy does not have an entry within the refDataApi within the dbConfig file*/
        GrlDetAmounts(this == $gda, lcrUnderlyingProduct in ("Corporate Bond", "Commercial Paper", "Covered Bond", "RMBS", "ABS"), getCase0_1559259() == "Y", lcrIssuerType in ("Sovereign", "Central Bank"), credRiskWghtIss in ("20", "50", "100", "150"), incLiqRiskIssInd == "Y")
        
    then
        $gda.setLiqCredQual("E");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4682");
        
end

rule '1582753' extends '333923' salience 79030
no-loop
    when
        
        /*MANUAL adjustment here, because of error: Table gre_hr_ctry_ccy does not have an entry within the refDataApi within the dbConfig file*/
        GrlDetAmounts(this == $gda, lcrUnderlyingProduct in ("Corporate Bond", "Commercial Paper", "Covered Bond", "RMBS", "ABS"), getCase0_1559259() == "Y", lcrIssuerType in ("Other", "SME", "Credit Institution", "Local Government"), lcrGuarType in ("Sovereign", "Central Bank"), credRiskWghtGuar == "20")
        
    then
        $gda.setLiqCredQual("H");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4682");
        
end

rule '1584542' extends '333923' salience 79020
no-loop
    when
        
        /*MANUAL adjustment here, because of error: Table gre_hr_ctry_ccy does not have an entry within the refDataApi within the dbConfig file*/
        GrlDetAmounts(this == $gda, lcrUnderlyingProduct in ("Corporate Bond", "Commercial Paper", "Covered Bond", "RMBS", "ABS"), getCase0_1559259() == "Y", lcrIssuerType in ("Sovereign", "Central Bank"), credRiskWghtIss == "20", incLiqRiskIssInd == "N")
        
    then
        $gda.setLiqCredQual("H");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4682");
        
end

rule '1582751' extends '333923' salience 79010
no-loop
    when
        
        /*MANUAL adjustment here, because of error: Table gre_hr_ctry_ccy does not have an entry within the refDataApi within the dbConfig file*/
        GrlDetAmounts(this == $gda, lcrUnderlyingProduct in ("Corporate Bond", "Commercial Paper", "Covered Bond", "RMBS", "ABS"), getCase0_1559259() == "Y", lcrIssuerType in ("Other", "SME", "Credit Institution", "PSE", "Local Government"), lcrGuarType in ("Sovereign", "Central Bank"), credRiskWghtGuar in ("20", "50", "100", "150"), incLiqRiskGuarInd == "Y")
        
    then
        $gda.setLiqCredQual("E");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4682");
        
end

rule '1584543' extends '333923' salience 79000
no-loop
    when
        
        /*MANUAL adjustment here, because of error: Table gre_hr_ctry_ccy does not have an entry within the refDataApi within the dbConfig file*/
        GrlDetAmounts(this == $gda, lcrUnderlyingProduct in ("Corporate Bond", "Commercial Paper", "Covered Bond", "RMBS", "ABS"), getCase0_1559259() == "Y", lcrIssuerType in ("Other", "SME", "Credit Institution", "PSE", "Local Government"), lcrGuarType in ("Sovereign", "Central Bank"), credRiskWghtGuar == "20", incLiqRiskGuarInd == "Y")
        
    then
        $gda.setLiqCredQual("H");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4682");
        
end


