package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '333941'
	when
		$gda : GrlDetAmounts(hreRelTypeIssuer != null && intInd == "N")
	then
        
end





rule '1567550' extends '333941' salience 93900

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setIssSetUpByGovInd("N");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4700");
        
end


