package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '336879'
	when
		$gda : GrlDetAmounts(hpePdtType == "REPO" && hacAmtCl in ( "01" , "02" , "03" , "12" , "16" ) && contingInd == "N" && intInd == "N")
	then
        
end





rule '1770830' extends '336879' salience 39850

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setActCode(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770813' extends '336879' salience 39840

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "12", htyTradCat == "03")
        
    then
        $gda.setActCode("A0027000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770814' extends '336879' salience 39830

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl == "12", htyTradCat in ("01", "02"))
        
    then
        $gda.setActCode("L1425000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770818' extends '336879' salience 39820

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl == "12", htyTradCat == "03")
        
    then
        $gda.setActCode("L0242000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770820' extends '336879' salience 39810

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "16", htyTradCat == "03")
        
    then
        $gda.setActCode("A3931000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770821' extends '336879' salience 39800

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl == "16", htyTradCat == "03")
        
    then
        $gda.setActCode("L3334000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770826' extends '336879' salience 39790

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("01", "02", "03"), htyTradCat in ("01", "02"))
        
    then
        $gda.setActCode("A0057000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770827' extends '336879' salience 39780

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl in ("01", "02", "03"), htyTradCat in ("01", "02"))
        
    then
        $gda.setActCode("L1425000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770828' extends '336879' salience 39770

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("01", "02", "03"), htyTradCat == "03")
        
    then
        $gda.setActCode("A0027000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770829' extends '336879' salience 39760

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl in ("01", "02", "03"), htyTradCat == "03")
        
    then
        $gda.setActCode("L0242000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770832' extends '336879' salience 39750

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "12", htyTradCat in ("01", "02"))
        
    then
        $gda.setActCode("A0057000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770811' extends '336879' salience 39740

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "12", htyTradCat == "03", volTradeInd == "Y")
        
    then
        $gda.setActCode("A3329000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770812' extends '336879' salience 39730

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "12", htyTradCat == "03", hedgeInd == "Y")
        
    then
        $gda.setActCode("A3332000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770816' extends '336879' salience 39720

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl == "12", htyTradCat == "03", volTradeInd == "Y")
        
    then
        $gda.setActCode("L3343000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770817' extends '336879' salience 39710

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl == "12", htyTradCat == "03", hedgeInd == "Y")
        
    then
        $gda.setActCode("L3933000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770822' extends '336879' salience 39700

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl in ("01", "02", "03"), htyTradCat == "03", volTradeInd == "Y")
        
    then
        $gda.setActCode("L3343000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770823' extends '336879' salience 39690

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("01", "02", "03"), htyTradCat == "03", hedgeInd == "Y")
        
    then
        $gda.setActCode("A3332000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770824' extends '336879' salience 39680

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl in ("01", "02", "03"), htyTradCat == "03", hedgeInd == "Y")
        
    then
        $gda.setActCode("L3933000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770825' extends '336879' salience 39670

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("01", "02", "03"), htyTradCat == "03", volTradeInd == "Y")
        
    then
        $gda.setActCode("A3329000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770810' extends '336879' salience 39660

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "12", htyTradCat == "03", hedgeInd == "Y", fvAdjInd == "Y")
        
    then
        $gda.setActCode("A3931000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770815' extends '336879' salience 39650

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl == "12", htyTradCat == "03", hedgeInd == "Y", fvAdjInd == "Y")
        
    then
        $gda.setActCode("L3334000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770819' extends '336879' salience 39640

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl in ("01", "02", "03"), htyTradCat == "03", hedgeInd == "Y", fvAdjInd == "Y")
        
    then
        $gda.setActCode("L3334000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1770831' extends '336879' salience 39630

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("01", "02", "03"), htyTradCat == "03", hedgeInd == "Y", fvAdjInd == "Y")
        
    then
        $gda.setActCode("A3931000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1772535' extends '336879' salience 39620

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("01", "02", "03", "12"), htyTradCat == "03", himIfrs9MeasCl == "FVPL", lseHlyRelId in ("0204", "0207", "0239", "0239_US", "9225"))
        
    then
        $gda.setActCode("A9750000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end

rule '1772536' extends '336879' salience 39610

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl in ("01", "02", "03", "12"), htyTradCat == "03", himIfrs9MeasCl == "FVPL", lseHlyRelId in ("0204", "0207", "0239", "0239_US", "9225"))
        
    then
        $gda.setActCode("L9751000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6986");
        
end


