package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '335541'
	when
		$gda : GrlDetAmounts(hpePdtType in ( "NIF AND RUF" , "UNUSED FAC AMT" , "CFY" ) && intInd == "N" && hacAmtCl == "09" && drawAllowedInd == "Y" && credFacInd == "Y" && rootFacInd == "Y")
	then
        
end





rule '1710690' extends '335541' salience 39600

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setActCode(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5917");
        
end

rule '1710689' extends '335541' salience 39590

    when
        
        GrlDetAmounts(this == $gda, hfeFacType not in ("072", "230", "340", "450", "516", "518"))
        
    then
        $gda.setActCode("B0596000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5917");
        
end


