package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '335565'
	when
		$gda : GrlDetAmounts(ownUse07 in ( "A798700002900000015089" ) && lseHlyRelId in ( "0212" , "0212_RET" , "9661" , "9614" ))
	then
        
end





rule '1711103' extends '335565' salience 280

    when
        
        GrlDetAmounts(this == $gda, lseHlyRelId in ("0212", "0212_RET", "9614", "9661"), ownUse07 matches "A7987000.*")
        
    then
        $gda.setActCode("A7987000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5941");
        
end

rule '1711104' extends '335565' salience 270

    when
        
        GrlDetAmounts(this == $gda, lseHlyRelId in ("0212A", "0212_RETA", "9614A", "9661A"), ownUse07 matches "A8939000.*")
        
    then
        $gda.setActCode("A8939000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5941");
        
end


