package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;


dialect  "mvel"


rule '330767'
	when
		$gda : GrlDetAmounts(hpePdtType == "REPO" && hacAmtCl in ( "01" , "02" , "03" , "12" , "16" ) && contingInd == "N" && intInd == "N")
	then
end


rule '924607' extends '330767' salience 17320

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setScyActCode(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '1028183' extends '330767' salience 17310

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl in ("02", "03"), htyTradCat in ("01", "02"))
        
    then
        $gda.setScyActCode("L1425000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '1131621' extends '330767' salience 17300

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl == "12", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyActCode("L1425000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '1152398' extends '330767' salience 17290

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("02", "03"), htyTradCat == "03")
        
    then
        $gda.setScyActCode("A0027000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '924606' extends '330767' salience 17280

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl in ("02", "03"), htyTradCat == "03")
        
    then
        $gda.setScyActCode("L0242000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '924605' extends '330767' salience 17270

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("02", "03"), htyTradCat in ("01", "02"))
        
    then
        $gda.setScyActCode("A0057000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '924603' extends '330767' salience 17260

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl == "01", htyTradCat == "03")
        
    then
        $gda.setScyActCode("L0242000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '924602' extends '330767' salience 17250

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "01", htyTradCat == "03")
        
    then
        $gda.setScyActCode("A0027000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '924601' extends '330767' salience 17240

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl == "01", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyActCode("L1425000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '924600' extends '330767' salience 17230

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "01", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyActCode("A0057000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '1131627' extends '330767' salience 17220

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl == "12", htyTradCat == "03")
        
    then
        $gda.setScyActCode("L0242000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '1131620' extends '330767' salience 17210

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "12", htyTradCat == "03")
        
    then
        $gda.setScyActCode("A0027000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '924592' extends '330767' salience 17200

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "16", htyTradCat == "03")
        
    then
        $gda.setScyActCode("A3931000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '924593' extends '330767' salience 17190

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl == "16", htyTradCat == "03")
        
    then
        $gda.setScyActCode("L3334000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '1131616' extends '330767' salience 17180

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "12", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyActCode("A0057000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '1131618' extends '330767' salience 17170

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "12", htyTradCat == "03", volTradeInd == "Y")
        
    then
        $gda.setScyActCode("A3329000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '924598' extends '330767' salience 17160

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "01", htyTradCat == "03", volTradeInd == "Y")
        
    then
        $gda.setScyActCode("A3329000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '924597' extends '330767' salience 17150

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl == "01", htyTradCat == "03", hedgeInd == "Y")
        
    then
        $gda.setScyActCode("L3933000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '924596' extends '330767' salience 17140

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "01", htyTradCat == "03", hedgeInd == "Y")
        
    then
        $gda.setScyActCode("A3332000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '924595' extends '330767' salience 17130

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl == "01", htyTradCat == "03", volTradeInd == "Y")
        
    then
        $gda.setScyActCode("L3343000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '1152404' extends '330767' salience 17120

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl in ("02", "03"), htyTradCat == "03", hedgeInd == "Y")
        
    then
        $gda.setScyActCode("L3933000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '1131625' extends '330767' salience 17110

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl == "12", htyTradCat == "03", hedgeInd == "Y")
        
    then
        $gda.setScyActCode("L3933000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '1131624' extends '330767' salience 17100

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl == "12", htyTradCat == "03", volTradeInd == "Y")
        
    then
        $gda.setScyActCode("L3343000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '1152399' extends '330767' salience 17090

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("02", "03"), htyTradCat == "03", volTradeInd == "Y")
        
    then
        $gda.setScyActCode("A3329000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '1131619' extends '330767' salience 17080

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "12", htyTradCat == "03", hedgeInd == "Y")
        
    then
        $gda.setScyActCode("A3332000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '1152401' extends '330767' salience 17070

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("02", "03"), htyTradCat == "03", hedgeInd == "Y")
        
    then
        $gda.setScyActCode("A3332000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '1152402' extends '330767' salience 17060

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl in ("02", "03"), htyTradCat == "03", volTradeInd == "Y")
        
    then
        $gda.setScyActCode("L3343000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '1152403' extends '330767' salience 17050

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl in ("02", "03"), htyTradCat == "03", hedgeInd == "Y", fvAdjInd == "Y")
        
    then
        $gda.setScyActCode("L3334000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '1152400' extends '330767' salience 17040

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("02", "03"), htyTradCat == "03", hedgeInd == "Y", fvAdjInd == "Y")
        
    then
        $gda.setScyActCode("A3931000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '924590' extends '330767' salience 17030

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "01", htyTradCat == "03", hedgeInd == "Y", fvAdjInd == "Y")
        
    then
        $gda.setScyActCode("A3931000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '924591' extends '330767' salience 17020

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl == "01", htyTradCat == "03", hedgeInd == "Y", fvAdjInd == "Y")
        
    then
        $gda.setScyActCode("L3334000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '1131623' extends '330767' salience 17010

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hacAmtCl == "12", htyTradCat == "03", hedgeInd == "Y", fvAdjInd == "Y")
        
    then
        $gda.setScyActCode("L3334000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end

rule '1131617' extends '330767' salience 17000

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "12", htyTradCat == "03", hedgeInd == "Y", fvAdjInd == "Y")
        
    then
        $gda.setScyActCode("A3931000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2527");
        
end


