package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;


dialect  "mvel"


rule '330764'
	when
		$gda : GrlDetAmounts(hpePdtType == "STOCK DISC BILL PRM NOTE" && intInd == "N" && hacAmtCl in ( "01" , "05" , "16" , "18" ) && contingInd == "N")
	then
end


rule '923788' extends '330764' salience 27380

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setScyActCode(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2524");
        
end

rule '923786' extends '330764' salience 27370

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", htyTradCat == "03", hacAmtCl in ("01", "05", "18"))
        
    then
        $gda.setScyActCode("L0242000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2524");
        
end

rule '923785' extends '330764' salience 27360

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", htyTradCat in ("01", "02"), hacAmtCl in ("01", "05", "18"))
        
    then
        $gda.setScyActCode("L1425000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2524");
        
end

rule '923784' extends '330764' salience 27350

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", htyTradCat == "03", hacAmtCl in ("01", "05", "18"))
        
    then
        $gda.setScyActCode("A0027000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2524");
        
end

rule '923787' extends '330764' salience 27340

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", htyTradCat in ("01", "02"), hacAmtCl in ("01", "05", "18"))
        
    then
        $gda.setScyActCode("A0057000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2524");
        
end

rule '923777' extends '330764' salience 27330

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", htyTradCat == "03", hacAmtCl == "16")
        
    then
        $gda.setScyActCode("A3931000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2524");
        
end

rule '923778' extends '330764' salience 27320

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", htyTradCat == "03", hacAmtCl == "16")
        
    then
        $gda.setScyActCode("L3334000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2524");
        
end

rule '923782' extends '330764' salience 27310

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", htyTradCat == "03", hedgeInd == "Y", hacAmtCl in ("01", "05", "18"))
        
    then
        $gda.setScyActCode("L3933000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2524");
        
end

rule '923781' extends '330764' salience 27300

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", htyTradCat == "03", volTradeInd == "Y", hacAmtCl in ("01", "05", "18"))
        
    then
        $gda.setScyActCode("A3329000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2524");
        
end

rule '923780' extends '330764' salience 27290

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", htyTradCat == "03", volTradeInd == "Y", hacAmtCl in ("01", "05", "18"))
        
    then
        $gda.setScyActCode("L3343000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2524");
        
end

rule '923783' extends '330764' salience 27280

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", htyTradCat == "03", hedgeInd == "Y", hacAmtCl in ("01", "05", "18"))
        
    then
        $gda.setScyActCode("A3332000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2524");
        
end

rule '923775' extends '330764' salience 27270

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", htyTradCat == "03", hedgeInd == "Y", fvAdjInd == "Y")
        
    then
        $gda.setScyActCode("A3931000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2524");
        
end

rule '923776' extends '330764' salience 27260

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", htyTradCat == "03", hedgeInd == "Y", fvAdjInd == "Y")
        
    then
        $gda.setScyActCode("L3334000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2524");
        
end


