package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;


dialect  "mvel"


rule '330685'
	when
		$gda : GrlDetAmounts(hpePdtType in ( "CUST ACCT" , "NOSTRO" ) && intInd == "N" && contingInd == "N" && hacAmtCl == "03")
	then
end


rule '918801' extends '330685' salience 18840

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setScyActCode(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2441");
        
end

rule '918799' extends '330685' salience 18830

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hanAcctCl == "SAVINGS")
        
    then
        $gda.setScyActCode("L2569000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2441");
        
end

rule '918802' extends '330685' salience 18820

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y")
        
    then
        $gda.setScyActCode("A0003000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2441");
        
end

rule '918798' extends '330685' salience 18810

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hanAcctCl != "SAVINGS", htyTradCat == "03")
        
    then
        $gda.setScyActCode("L0229000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2441");
        
end

rule '918800' extends '330685' salience 18800

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hanAcctCl != "SAVINGS", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyActCode("L3351000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2441");
        
end


