package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlPlYtd;


global com.ing.gfrs.logical.apis.GreLrCustRefLogicalApi greLrCustRefLogicalApi;


dialect  "mvel"


rule '337322'
	when
		$gpy : GrlPlYtd(( ( actCode in ( "I0143000" , "I0197000" , "I1331000" , "I1332000" , "I0199000" , "I3349000" , "I3923000" , "I3924000" , "I3925000" , "I3926000" , "I3928000" , "I3937000" , "I3938000" , "I3946000" , "I3947000" , "I4405000" , "I4406000" , "I4408000" , "I8630000" , "I8631000" , "I8632000" , "I9758000" , "I9759000" , "I9760000" , "I9761000" ) || ( actCode == "I7671000" && pdtCode in ( "004200" , "004300" , "004400" , "009400" , "012200" , "012700" , "013600" , "014000" , "015200" , "027800" , "027900" , "028000" , "031400" , "031500" , "031800" ) ) ) && nvl ( pdtCode , "X" ) not in ( "005100" , "005900" , "006100" , "007300" , "015500" , "030000" , "030100" , "030200" , "030300" , "030400" , "030500" , "030600" , "030700" , "030800" , "030900" , "031000" , "031100" ) ))
	then
        
end





rule '1807100' extends '337322' salience 14940

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807105' extends '337322' salience 14930

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ACCT")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807108' extends '337322' salience 14920

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "BCRI")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807109' extends '337322' salience 14910

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "BDIP")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807110' extends '337322' salience 14900

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "BEXC")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807111' extends '337322' salience 14890

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "BGOF")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807112' extends '337322' salience 14880

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "BGOG")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807113' extends '337322' salience 14870

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "BGPR")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807114' extends '337322' salience 14860

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "BGVO")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807115' extends '337322' salience 14850

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "BHOL")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807116' extends '337322' salience 14840

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "BJVT")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807117' extends '337322' salience 14830

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "BLEV")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807118' extends '337322' salience 14820

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "BLIM")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807119' extends '337322' salience 14810

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "BMLD")
        
    then
        $gpy.setCustomTxtHo04("B0037");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807120' extends '337322' salience 14800

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "BPRO")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807121' extends '337322' salience 14790

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "BRPR")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807122' extends '337322' salience 14780

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "BSPM")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807123' extends '337322' salience 14770

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "BSPV")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807125' extends '337322' salience 14760

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CBEA")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807126' extends '337322' salience 14750

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CEXC")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807127' extends '337322' salience 14740

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CFIN")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807128' extends '337322' salience 14730

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CGOG")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807129' extends '337322' salience 14720

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CGVO")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807131' extends '337322' salience 14710

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CIPB")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807132' extends '337322' salience 14700

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CJVT")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807133' extends '337322' salience 14690

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CLEV")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807134' extends '337322' salience 14680

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CLIM")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807135' extends '337322' salience 14670

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CNPO")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807136' extends '337322' salience 14660

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "COMB")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807137' extends '337322' salience 14650

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "COMN")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807138' extends '337322' salience 14640

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CPOL")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807139' extends '337322' salience 14630

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CPRJ")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807140' extends '337322' salience 14620

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CPTR")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807141' extends '337322' salience 14610

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CREG")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807142' extends '337322' salience 14600

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CSPV")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807143' extends '337322' salience 14590

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CTCF")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807144' extends '337322' salience 14580

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CTMP")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807145' extends '337322' salience 14570

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FAMT")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807146' extends '337322' salience 14560

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FBEA")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807147' extends '337322' salience 14550

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FBIC")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807148' extends '337322' salience 14540

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FBRO")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807149' extends '337322' salience 14530

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FCCP")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807150' extends '337322' salience 14520

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FCHO")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807151' extends '337322' salience 14510

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FCLF")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807152' extends '337322' salience 14500

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FCLH")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807153' extends '337322' salience 14490

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FDIP")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807154' extends '337322' salience 14480

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FECA")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807155' extends '337322' salience 14470

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FECO")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807156' extends '337322' salience 14460

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FETF")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807157' extends '337322' salience 14450

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FEXC")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807158' extends '337322' salience 14440

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FEXO")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807159' extends '337322' salience 14430

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FFIN")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807160' extends '337322' salience 14420

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FFUA")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807161' extends '337322' salience 14410

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FGOG")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807162' extends '337322' salience 14400

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FGVO")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807163' extends '337322' salience 14390

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FHOL")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807164' extends '337322' salience 14380

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FINS")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807165' extends '337322' salience 14370

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FIPB")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807166' extends '337322' salience 14360

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FJVT")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807167' extends '337322' salience 14350

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FLEV")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807168' extends '337322' salience 14340

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FLIF")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807169' extends '337322' salience 14330

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FLIM")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807170' extends '337322' salience 14320

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FOFM")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807171' extends '337322' salience 14310

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FOHF")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807172' extends '337322' salience 14300

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FOPF")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807173' extends '337322' salience 14290

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FPEF")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807174' extends '337322' salience 14280

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FPOO")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807175' extends '337322' salience 14270

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FREG")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807176' extends '337322' salience 14260

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FSPM")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807177' extends '337322' salience 14250

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FSPO")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807178' extends '337322' salience 14240

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FSPV")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807179' extends '337322' salience 14230

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FTRU")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807180' extends '337322' salience 14220

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FUND")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807181' extends '337322' salience 14210

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FUSB")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807182' extends '337322' salience 14200

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FXCE")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807183' extends '337322' salience 14190

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "FXCH")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807184' extends '337322' salience 14180

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "GAMT")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807185' extends '337322' salience 14170

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "GCEN")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807186' extends '337322' salience 14160

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "GCFI")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807187' extends '337322' salience 14150

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "GCPL")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807188' extends '337322' salience 14140

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "GLFI")
        
    then
        $gpy.setCustomTxtHo04("G0009");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807189' extends '337322' salience 14130

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "GLOC")
        
    then
        $gpy.setCustomTxtHo04("G0009");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807190' extends '337322' salience 14120

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "GLOL")
        
    then
        $gpy.setCustomTxtHo04("G0009");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807191' extends '337322' salience 14110

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "GLPL")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807192' extends '337322' salience 14100

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "GNFP")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807193' extends '337322' salience 14090

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "GNFU")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807194' extends '337322' salience 14080

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "GOSN")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807195' extends '337322' salience 14070

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "GPSC")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807196' extends '337322' salience 14060

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "GPSL")
        
    then
        $gpy.setCustomTxtHo04("G0009");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807197' extends '337322' salience 14050

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "GSNO")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807198' extends '337322' salience 14040

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "GSOC")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807199' extends '337322' salience 14030

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "IIPB")
        
    then
        $gpy.setCustomTxtHo04("P0049");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807200' extends '337322' salience 14020

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "IMND")
        
    then
        $gpy.setCustomTxtHo04("P0049");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807201' extends '337322' salience 14010

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "INDV")
        
    then
        $gpy.setCustomTxtHo04("P0049");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807202' extends '337322' salience 14000

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "IREP")
        
    then
        $gpy.setCustomTxtHo04("P0049");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807203' extends '337322' salience 13990

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ISTF")
        
    then
        $gpy.setCustomTxtHo04("P0049");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807205' extends '337322' salience 13980

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KBEA")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807206' extends '337322' salience 13970

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KEXC")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807207' extends '337322' salience 13960

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KFIN")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807208' extends '337322' salience 13950

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KGVO")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807210' extends '337322' salience 13940

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KIPB")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807211' extends '337322' salience 13930

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KJVT")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807212' extends '337322' salience 13920

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KLEV")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807213' extends '337322' salience 13910

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KLIM")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807214' extends '337322' salience 13900

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KNPO")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807215' extends '337322' salience 13890

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KOMB")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807216' extends '337322' salience 13880

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KOMN")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807217' extends '337322' salience 13870

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KPOL")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807218' extends '337322' salience 13860

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KPTR")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807219' extends '337322' salience 13850

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KREG")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807220' extends '337322' salience 13840

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KSPV")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807221' extends '337322' salience 13830

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KTCF")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807222' extends '337322' salience 13820

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KTMP")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807224' extends '337322' salience 13810

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "RBEA")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807225' extends '337322' salience 13800

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "REIF")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807226' extends '337322' salience 13790

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "REXC")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807227' extends '337322' salience 13780

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "RGVO")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807228' extends '337322' salience 13770

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "RJVT")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807230' extends '337322' salience 13760

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "RLIM")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807231' extends '337322' salience 13750

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ROMB")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807232' extends '337322' salience 13740

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "RPRJ")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807233' extends '337322' salience 13730

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "RPTL")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807234' extends '337322' salience 13720

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "RPTP")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807235' extends '337322' salience 13710

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "RPTR")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807237' extends '337322' salience 13700

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "RREG")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807239' extends '337322' salience 13690

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "RSPV")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807241' extends '337322' salience 13680

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "SBEA")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807242' extends '337322' salience 13670

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "SEXC")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807243' extends '337322' salience 13660

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "SFIN")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807244' extends '337322' salience 13650

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "SGVO")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807246' extends '337322' salience 13640

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "SIPB")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807247' extends '337322' salience 13630

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "SJVT")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807248' extends '337322' salience 13620

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "SLEV")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807249' extends '337322' salience 13610

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "SLIM")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807250' extends '337322' salience 13600

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "SNPO")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807251' extends '337322' salience 13590

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "SOMB")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807252' extends '337322' salience 13580

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "SOMN")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807253' extends '337322' salience 13570

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "SPOL")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807254' extends '337322' salience 13560

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "SPTR")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807255' extends '337322' salience 13550

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "SREG")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807256' extends '337322' salience 13540

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "SSPV")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807257' extends '337322' salience 13530

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "STCF")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807258' extends '337322' salience 13520

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "STMP")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807259' extends '337322' salience 13510

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "VGRP")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807267' extends '337322' salience 13500

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZABG")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807272' extends '337322' salience 13490

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZABS")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807277' extends '337322' salience 13480

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZAIN")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807282' extends '337322' salience 13470

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZCMB")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807287' extends '337322' salience 13460

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZCMG")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807292' extends '337322' salience 13450

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZMBG")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807297' extends '337322' salience 13440

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZMBS")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807302' extends '337322' salience 13430

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZMIN")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807307' extends '337322' salience 13420

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZRMB")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807312' extends '337322' salience 13410

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZSEC")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1884712' extends '337322' salience 13400

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CHOL")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1884713' extends '337322' salience 13390

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "SHOL")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1884714' extends '337322' salience 13380

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KHOL")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807106' extends '337322' salience 13370

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "BCEN", residentInd == "Y")
        
    then
        $gpy.setCustomTxtHo04("B0034");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807107' extends '337322' salience 13360

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "BCEN", residentInd == "N")
        
    then
        $gpy.setCustomTxtHo04("B0035");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807130' extends '337322' salience 13350
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "CHOL", (getCase0_1715410() == "522298" || getCase0_1715410() matches "5223.*" || getCase0_1715410() matches "523.*"))
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807209' extends '337322' salience 13340
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "KHOL", (getCase0_1715410() == "522298" || getCase0_1715410() matches "5223.*" || getCase0_1715410() matches "523.*"))
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807229' extends '337322' salience 13330

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "RLIM", greLrCustRefLogicalApi.getCustomCd(gridId,"STNDRD","CPY-ISS","N") == "RLIM-OFI")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807236' extends '337322' salience 13320

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "RREG", greLrCustRefLogicalApi.getCustomCd(gridId,"STNDRD","CPY-ISS","N") == "RREG-OFI")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807238' extends '337322' salience 13310

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "RSPV", greLrCustRefLogicalApi.getCustomCd(gridId,"STNDRD","CPY-ISS","N") == "RSPV-OFI")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807245' extends '337322' salience 13300
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "SHOL", (getCase0_1715410() == "522298" || getCase0_1715410() matches "5223.*" || getCase0_1715410() matches "523.*"))
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1813181' extends '337322' salience 13290

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType matches "C.*", greLrCustRefLogicalApi.getCustomCd(gridId,"STNDRD","CPY-ISS","N") == "CORP-OFI")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807101' extends '337322' salience 13280
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ACCT", hieInduType == "522110", getCase0_1807102() == "K")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807102' extends '337322' salience 13270
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ACCT", hieInduType == "921190", getCase0_1807102() == "O")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807103' extends '337322' salience 13260
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ACCT", hieInduType != "921190", getCase0_1807102() == "O")
        
    then
        $gpy.setCustomTxtHo04("G0009");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807104' extends '337322' salience 13250
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ACCT", hieInduType != "522110", getCase0_1807102() == "K")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807260' extends '337322' salience 13240
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType matches "Z.*", icInd == "Y", getCase0_1715401() == "BANK")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807261' extends '337322' salience 13230
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType matches "Z.*", icInd == "Y", getCase0_1715401() == "OFI")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807262' extends '337322' salience 13220
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType matches "Z.*", icInd == "Y", getCase0_1715401() == "OTHER")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807263' extends '337322' salience 13210
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZABG", hieInduType == "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807264' extends '337322' salience 13200
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZABG", hieInduType == "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807265' extends '337322' salience 13190
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZABG", hieInduType != "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0009");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807266' extends '337322' salience 13180
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZABG", hieInduType != "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807268' extends '337322' salience 13170
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZABS", hieInduType == "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807269' extends '337322' salience 13160
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZABS", hieInduType == "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807270' extends '337322' salience 13150
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZABS", hieInduType != "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0009");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807271' extends '337322' salience 13140
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZABS", hieInduType != "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807273' extends '337322' salience 13130
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZAIN", hieInduType == "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807274' extends '337322' salience 13120
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZAIN", hieInduType == "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807275' extends '337322' salience 13110
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZAIN", hieInduType != "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0009");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807276' extends '337322' salience 13100
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZAIN", hieInduType != "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807278' extends '337322' salience 13090
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZCMB", hieInduType == "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807279' extends '337322' salience 13080
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZCMB", hieInduType == "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807280' extends '337322' salience 13070
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZCMB", hieInduType != "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0009");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807281' extends '337322' salience 13060
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZCMB", hieInduType != "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807283' extends '337322' salience 13050
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZCMG", hieInduType == "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807284' extends '337322' salience 13040
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZCMG", hieInduType == "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807285' extends '337322' salience 13030
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZCMG", hieInduType != "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0009");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807286' extends '337322' salience 13020
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZCMG", hieInduType != "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807288' extends '337322' salience 13010
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZMBG", hieInduType == "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807289' extends '337322' salience 13000
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZMBG", hieInduType == "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807290' extends '337322' salience 12990
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZMBG", hieInduType != "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0009");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807291' extends '337322' salience 12980
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZMBG", hieInduType != "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807293' extends '337322' salience 12970
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZMBS", hieInduType == "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807294' extends '337322' salience 12960
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZMBS", hieInduType == "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807295' extends '337322' salience 12950
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZMBS", hieInduType != "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0009");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807296' extends '337322' salience 12940
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZMBS", hieInduType != "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807298' extends '337322' salience 12930
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZMIN", hieInduType == "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807299' extends '337322' salience 12920
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZMIN", hieInduType == "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807300' extends '337322' salience 12910
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZMIN", hieInduType != "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0009");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807301' extends '337322' salience 12900
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZMIN", hieInduType != "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807303' extends '337322' salience 12890
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZRMB", hieInduType == "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807304' extends '337322' salience 12880
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZRMB", hieInduType == "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807305' extends '337322' salience 12870
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZRMB", hieInduType != "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0009");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807306' extends '337322' salience 12860
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZRMB", hieInduType != "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807308' extends '337322' salience 12850
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZSEC", hieInduType == "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807309' extends '337322' salience 12840
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZSEC", hieInduType == "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0008");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807310' extends '337322' salience 12830
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZSEC", hieInduType != "921190", getCase0_1807102() == "O", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("G0009");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807311' extends '337322' salience 12820
no-loop
    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType == "ZSEC", hieInduType != "522110", getCase0_1807102() == "K", icInd == "N")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807730' extends '337322' salience 12810

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType matches "F.*", icInd == "Y")
        
    then
        $gpy.setCustomTxtHo04("P0039");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807731' extends '337322' salience 12800

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType matches "C.*", icInd == "Y")
        
    then
        $gpy.setCustomTxtHo04("P0045");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end

rule '1807732' extends '337322' salience 12790

    when
        
        GrlPlYtd(this == $gpy, intInd == "N", hreRelType matches "B.*", icInd == "Y")
        
    then
        $gpy.setCustomTxtHo04("B0036");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7350");
        
end


