package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '338187'
	when
		$gda : GrlDetAmounts()
	then
        
end





rule '1982323' extends '338187' salience 20

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxtHo52(Warning: selecting from cia_owner.cho_multi_tree_explosions: data will not be available in source topic.
 full statement: {( select  '|' || regexp_substr(mle.label,'[^|]+',1,1) || '-' ||
  regexp_substr(mle.label,'[^|]+',1,2) || '-' ||
  regexp_substr(mle.label,'[^|]+',1,3)   || '|'
   from  cia_owner.cho_multi_tree_explosions mle WHERE mle.mtr_name = 'FINREP DPM 2.9 COMBOS'
AND  '|' || sel_tab.act_code || '|' || sel_tab.pdt_code || '|' || sel_tab.cgp_code ||'|' ||sel_tab.rte_code ||'|'  =
 '|'   ||mle.act_code   ||'|'   ||mle.pdt_code   ||'|'   ||mle.cgp_code   ||'|'   ||mle.rte_code   || '|'
and mle.ldr_code = 'ACTUALS'
and sel_tab.ldr_code = 'ACTUALS'
and mle.act_code = sel_tab.act_code
AND ((NVL(mle.INTERCOMPANY_IND,'B') = 'Y' AND sel_tab.cpy_rey_code IS NOT NULL) OR (NVL(mle.INTERCOMPANY_IND,'B')  <> 'Y'))
AND regexp_substr(mle.label,'[^|]+',1,1) = 'F.04.03.01'
and regexp_substr(mle.label,'[^|]+',1,2) not in ('020','030','040','050','110','180','190')
and regexp_substr(mle.label,'[^|]+',1,3) in ('050','060','070'))});
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"8180");
        
end


