package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlPlYtd;




dialect  "mvel"


rule '327936'
	when
		$gpy : GrlPlYtd()
	then
        
end





rule '326115' extends '327936' salience 6260

    when
        
        GrlPlYtd(this == $gpy, hpnPlCl == "1000")
        
    then
        $gpy.setCustomTxt01("1");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1622");
        
end

rule '326116' extends '327936' salience 6250

    when
        
        GrlPlYtd(this == $gpy, hpnPlCl == "2000")
        
    then
        $gpy.setCustomTxt01("2");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1622");
        
end

rule '326117' extends '327936' salience 6240

    when
        
        GrlPlYtd(this == $gpy, hpnPlCl == "3000")
        
    then
        $gpy.setCustomTxt01("3");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1622");
        
end

rule '326118' extends '327936' salience 6230

    when
        
        GrlPlYtd(this == $gpy, hpnPlCl == "4000")
        
    then
        $gpy.setCustomTxt01("4");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1622");
        
end

rule '326119' extends '327936' salience 6220

    when
        
        GrlPlYtd(this == $gpy, hpnPlCl == "5000")
        
    then
        $gpy.setCustomTxt01("5");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1622");
        
end

rule '326120' extends '327936' salience 6210

    when
        
        GrlPlYtd(this == $gpy, hpnPlCl == "6000")
        
    then
        $gpy.setCustomTxt01("6");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1622");
        
end

rule '326121' extends '327936' salience 6200

    when
        
        GrlPlYtd(this == $gpy, hpnPlCl == "7000")
        
    then
        $gpy.setCustomTxt01("7");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1622");
        
end

rule '326122' extends '327936' salience 6190

    when
        
        GrlPlYtd(this == $gpy, hpnPlCl == "8000")
        
    then
        $gpy.setCustomTxt01("8");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1622");
        
end


