package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlPlYtd;




dialect  "mvel"


rule '327937'
	when
		$gpy : GrlPlYtd()
	then
        
end





rule '326123' extends '327937' salience 6180

    when
        
        GrlPlYtd(this == $gpy, hreRelType in ("CHOL", "CJVT", "CLIM", "CREG", "CSPV"))
        
    then
        $gpy.setCustomTxt02("11002");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326124' extends '327937' salience 6170

    when
        
        GrlPlYtd(this == $gpy, hreRelType == "BCEN")
        
    then
        $gpy.setCustomTxt02("12100");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326125' extends '327937' salience 6160

    when
        
        GrlPlYtd(this == $gpy, hreRelType in ("BHOL", "IPBC", "IPBF", "IPBI", "VGRP"))
        
    then
        $gpy.setCustomTxt02("12221");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326126' extends '327937' salience 6150

    when
        
        GrlPlYtd(this == $gpy, hreRelType == "FGIR")
        
    then
        $gpy.setCustomTxt02("12223");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326127' extends '327937' salience 6140

    when
        
        GrlPlYtd(this == $gpy, hreRelType in ("BCRI", "CLEA", "FLEA"))
        
    then
        $gpy.setCustomTxt02("12224");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326128' extends '327937' salience 6130

    when
        
        GrlPlYtd(this == $gpy, hreRelType in ("BJVT", "BLIM", "BMLD", "BSPV"))
        
    then
        $gpy.setCustomTxt02("12225");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326129' extends '327937' salience 6120

    when
        
        GrlPlYtd(this == $gpy, hreRelType == "BMOR")
        
    then
        $gpy.setCustomTxt02("12226");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326130' extends '327937' salience 6110

    when
        
        GrlPlYtd(this == $gpy, hreRelType == "FOIB")
        
    then
        $gpy.setCustomTxt02("12227");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326131' extends '327937' salience 6100

    when
        
        GrlPlYtd(this == $gpy, hreRelType == "FDEF")
        
    then
        $gpy.setCustomTxt02("12312");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326132' extends '327937' salience 6090

    when
        
        GrlPlYtd(this == $gpy, hreRelType in ("CDEF", "CFIN", "CPRJ", "FBSC", "FHOL", "FJVT", "FLIM", "FOFC", "FOTH", "FREG", "FSEC", "FSPV", "FTRU"))
        
    then
        $gpy.setCustomTxt02("12322");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326133' extends '327937' salience 6080

    when
        
        GrlPlYtd(this == $gpy, hreRelType in ("FCLH", "FXCH", "FBRO"))
        
    then
        $gpy.setCustomTxt02("12410");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326134' extends '327937' salience 6070

    when
        
        GrlPlYtd(this == $gpy, hreRelType == "FPEF")
        
    then
        $gpy.setCustomTxt02("12510");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326135' extends '327937' salience 6060

    when
        
        GrlPlYtd(this == $gpy, hreRelType in ("FINS", "FLIF", "VING"))
        
    then
        $gpy.setCustomTxt02("12520");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326136' extends '327937' salience 6050

    when
        
        GrlPlYtd(this == $gpy, hreRelType in ("GCEN", "GSNO"))
        
    then
        $gpy.setCustomTxt02("13113");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326137' extends '327937' salience 6040

    when
        
        GrlPlYtd(this == $gpy, hreRelType == "GLOL")
        
    then
        $gpy.setCustomTxt02("13130");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326138' extends '327937' salience 6030

    when
        
        GrlPlYtd(this == $gpy, hreRelType == "COMB")
        
    then
        $gpy.setCustomTxt02("14100");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326139' extends '327937' salience 6020

    when
        
        GrlPlYtd(this == $gpy, hreRelType in ("INDV", "ISTF", "ISTN"))
        
    then
        $gpy.setCustomTxt02("14200");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326140' extends '327937' salience 6010

    when
        
        GrlPlYtd(this == $gpy, hreRelType in ("CHAR", "CNPC"))
        
    then
        $gpy.setCustomTxt02("15000");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326141' extends '327937' salience 6000

    when
        
        GrlPlYtd(this == $gpy, hreRelType in ("FABS", "FMBS", "FOFF", "FOFM", "FOHF", "FOUF", "FUND", "HOUS", "XCCY", "XCTY", "XDPT", "XSBR", "XXXX"))
        
    then
        $gpy.setCustomTxt02("16000");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '326788' extends '327937' salience 5990

    when
        
        GrlPlYtd(this == $gpy, hreRelType == null)
        
    then
        $gpy.setCustomTxt02(null);
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end

rule '327305' extends '327937' salience 5980

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setCustomTxt02("not in LoV");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"1624");
        
end


