package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlPlYtd;




dialect  "mvel"


rule '337157'
	when
		$gpy : GrlPlYtd(massLine != "99.999")
	then
        
end





rule '1783545' extends '337157' salience 600

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setLocMassLine(massLine );
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783546' extends '337157' salience 590

    when
        
        GrlPlYtd(this == $gpy, massLine == "Communication Expenses", plAcctId in ("7150611003", "7150611004"))
        
    then
        $gpy.setLocMassLine("Cards SMS Alert Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783547' extends '337157' salience 580

    when
        
        GrlPlYtd(this == $gpy, massLine == "Communication Expenses", plAcctId in ("7150601001", "7150601002"))
        
    then
        $gpy.setLocMassLine("Data transmissions");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783548' extends '337157' salience 570

    when
        
        GrlPlYtd(this == $gpy, massLine == "Communication Expenses", plAcctId in ("7150611001", "7150611002"))
        
    then
        $gpy.setLocMassLine("Telephony");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783549' extends '337157' salience 560

    when
        
        GrlPlYtd(this == $gpy, massLine == "Hardware Expenses not Capitalised", plAcctId in ("7150561001", "7150561104", "7150561303", "7150561304"))
        
    then
        $gpy.setLocMassLine("Hardware Expenses not Capitalised_SUB");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783550' extends '337157' salience 550

    when
        
        GrlPlYtd(this == $gpy, massLine == "Hardware Expenses not Capitalised", plAcctId in ("7150561103", "7150561205"))
        
    then
        $gpy.setLocMassLine("Maintanance - Hardware & Software");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783551' extends '337157' salience 540

    when
        
        GrlPlYtd(this == $gpy, massLine == "Provisioned Litigation and Other Expenses", plAcctId in ("7160791003", "7160791004", "7190901013"))
        
    then
        $gpy.setLocMassLine("Fraud cost");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783552' extends '337157' salience 530

    when
        
        GrlPlYtd(this == $gpy, massLine == "Provisioned Litigation and Other Expenses", plAcctId == "7190901009")
        
    then
        $gpy.setLocMassLine("Litigation and Other Provisions_SUB");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783553' extends '337157' salience 520

    when
        
        GrlPlYtd(this == $gpy, massLine == "Provisioned Litigation and Other Expenses", plAcctId in ("7160791001", "7160791002", "7190901012"))
        
    then
        $gpy.setLocMassLine("Litigation expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783554' extends '337157' salience 510

    when
        
        GrlPlYtd(this == $gpy, massLine == "Provisioned Litigation and Other Expenses", plAcctId in ("7160791005", "7160791006"))
        
    then
        $gpy.setLocMassLine("Operational issues");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783555' extends '337157' salience 500

    when
        
        GrlPlYtd(this == $gpy, massLine == "Maintenance Costs", plAcctId in ("7150651001", "7150651002"))
        
    then
        $gpy.setLocMassLine("Building maintenance");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783556' extends '337157' salience 490

    when
        
        GrlPlYtd(this == $gpy, massLine == "Maintenance Costs", plAcctId == "7150671002")
        
    then
        $gpy.setLocMassLine("Reception");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783557' extends '337157' salience 480

    when
        
        GrlPlYtd(this == $gpy, massLine == "Maintenance Costs", plAcctId in ("7150691001", "7150561208"))
        
    then
        $gpy.setLocMassLine("Security services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783558' extends '337157' salience 470

    when
        
        GrlPlYtd(this == $gpy, massLine == "Marketing", plAcctId in ("7150851002", "7150851008"))
        
    then
        $gpy.setLocMassLine("Advertising production");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783559' extends '337157' salience 460

    when
        
        GrlPlYtd(this == $gpy, massLine == "Marketing", plAcctId == "7150861002")
        
    then
        $gpy.setLocMassLine("Agency Fee - Web");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783560' extends '337157' salience 450

    when
        
        GrlPlYtd(this == $gpy, massLine == "Marketing", plAcctId == "7150851004")
        
    then
        $gpy.setLocMassLine("Cinema");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783561' extends '337157' salience 440

    when
        
        GrlPlYtd(this == $gpy, massLine == "Marketing", plAcctId == "7150891004")
        
    then
        $gpy.setLocMassLine("Corporate Responsibility");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783562' extends '337157' salience 430

    when
        
        GrlPlYtd(this == $gpy, massLine == "Marketing", plAcctId in ("5010064020", "7150901002", "7150901004"))
        
    then
        $gpy.setLocMassLine("Direct marketing");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783563' extends '337157' salience 420

    when
        
        GrlPlYtd(this == $gpy, massLine == "Marketing", plAcctId in ("7150791002", "7150791003", "7150791004", "7150791005", "7150791006", "7150791007", "7150791008", "7150791009", "7150791010", "7150791011", "7150791012"))
        
    then
        $gpy.setLocMassLine("Fulfillment");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783564' extends '337157' salience 410

    when
        
        GrlPlYtd(this == $gpy, massLine == "Marketing", plAcctId in ("7150911002", "7150911003", "7150911004", "7150921002"))
        
    then
        $gpy.setLocMassLine("Marketing_SUB");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783565' extends '337157' salience 400

    when
        
        GrlPlYtd(this == $gpy, massLine == "Marketing", plAcctId == "7150931013")
        
    then
        $gpy.setLocMassLine("Public relations");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783566' extends '337157' salience 390

    when
        
        GrlPlYtd(this == $gpy, massLine == "Marketing", plAcctId == "7150861003")
        
    then
        $gpy.setLocMassLine("Webmarketing Applications");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783567' extends '337157' salience 380

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Rental", plAcctId in ("7150631003", "7150631004"))
        
    then
        $gpy.setLocMassLine("Rents - branches");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783568' extends '337157' salience 370

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Rental", plAcctId in ("7150621001", "7180891202"))
        
    then
        $gpy.setLocMassLine("Rents - offices");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783569' extends '337157' salience 360

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Rental", plAcctId in ("7150621002", "7150631002", "7150931012"))
        
    then
        $gpy.setLocMassLine("Rents - other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783570' extends '337157' salience 350

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Rental", plAcctId == "7150631001")
        
    then
        $gpy.setLocMassLine("Rents - spazi commerciali");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783571' extends '337157' salience 340

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Supplies and Equipment", plAcctId == "7170891351")
        
    then
        $gpy.setLocMassLine("Depreciation alterations and installations");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783572' extends '337157' salience 330

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Supplies and Equipment", plAcctId == "7170891001")
        
    then
        $gpy.setLocMassLine("Depreciation furniture");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783573' extends '337157' salience 320

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Supplies and Equipment", plAcctId in ("7150701001", "7150701002", " 7150641003"))
        
    then
        $gpy.setLocMassLine("Office equipment and stationary");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783574' extends '337157' salience 310

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Accommodation Expenses", plAcctId == "7150681001")
        
    then
        $gpy.setLocMassLine("Catering");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783575' extends '337157' salience 300

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Accommodation Expenses", plAcctId == "7150671001")
        
    then
        $gpy.setLocMassLine("Cleaning");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783576' extends '337157' salience 290

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Accommodation Expenses", plAcctId in ("7150651003", "7150681003"))
        
    then
        $gpy.setLocMassLine("Other Accommodation Expenses_SUB");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783577' extends '337157' salience 280

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Accommodation Expenses", plAcctId == "7150641004")
        
    then
        $gpy.setLocMassLine("Rents - other ATM");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783578' extends '337157' salience 270

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Accommodation Expenses", plAcctId == "7150661001")
        
    then
        $gpy.setLocMassLine("Utilities (Italy)");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783579' extends '337157' salience 260

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Consulting", plAcctId == "7150561201")
        
    then
        $gpy.setLocMassLine("Architecture services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783580' extends '337157' salience 250

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Consulting", plAcctId in ("7150781001", "7150781004", "7150781005"))
        
    then
        $gpy.setLocMassLine("Other Consulting_SUB");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783581' extends '337157' salience 240

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Expenses", plAcctId in ("7150931003", "7150931004"))
        
    then
        $gpy.setLocMassLine("Insurance");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783582' extends '337157' salience 230

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Expenses", plAcctId in ("7150691002", "7150741002", "7150751002", "7150751003", "7150751006", "7150801002", "7150831002", "7150931001", "7150931005", "7150931007", "7150931008", "7150931011", "7150931016", "7150941010", "7150941013", "7160798200", "7160798201", "7160798202", "7190901001", "7190901003", "7190901004", "7190901005", "7190901011", "7190911006", "7190911008", "7190911015", "7190911016", "7190911018", "7190911022", "7190911031", "7190911033"))
        
    then
        $gpy.setLocMassLine("Sundry expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783583' extends '337157' salience 220

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Personnel Related Costs", plAcctId == "7150408208")
        
    then
        $gpy.setLocMassLine("Entertainment and events");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783584' extends '337157' salience 210

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Personnel Related Costs", plAcctId in ("7150408204", "7150408209", "7150408211", "7190911007"))
        
    then
        $gpy.setLocMassLine("Expats cost");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783585' extends '337157' salience 200

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Personnel Related Costs", plAcctId in ("7150408144", "7150849033", "7150408143", "7150408201", "7150408202", "7150408205", "7150408206", "7150408207", "7150408212"))
        
    then
        $gpy.setLocMassLine("Other Personnel Related Costi_SUB");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783586' extends '337157' salience 190

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Professional Services", plAcctId == "7150821001")
        
    then
        $gpy.setLocMassLine("Credit collection");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783587' extends '337157' salience 180

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Professional Services", plAcctId == "7150831001")
        
    then
        $gpy.setLocMassLine("Credit scoring");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783588' extends '337157' salience 170

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Professional Services", plAcctId == "7150781002")
        
    then
        $gpy.setLocMassLine("Notary fees");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783589' extends '337157' salience 160

    when
        
        GrlPlYtd(this == $gpy, massLine == "Outsourcing", plAcctId == "7150741001")
        
    then
        $gpy.setLocMassLine("Call center outsourcing");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783590' extends '337157' salience 150

    when
        
        GrlPlYtd(this == $gpy, massLine == "Outsourcing", plAcctId == "7150751001")
        
    then
        $gpy.setLocMassLine("Operations outsourcing");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783591' extends '337157' salience 140

    when
        
        GrlPlYtd(this == $gpy, massLine == "Outsourcing", plAcctId in ("7150561301", "7150561302", "7150751004", "7150751005", "7150781003"))
        
    then
        $gpy.setLocMassLine("Outsourcing Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783592' extends '337157' salience 130

    when
        
        GrlPlYtd(this == $gpy, massLine == "Salaries and Wages", plAcctId == "7150408041")
        
    then
        $gpy.setLocMassLine("Overtime");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783593' extends '337157' salience 120

    when
        
        GrlPlYtd(this == $gpy, massLine == "Salaries and Wages", plAcctId == "7150408101")
        
    then
        $gpy.setLocMassLine("Premio aziendale");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1783594' extends '337157' salience 110

    when
        
        GrlPlYtd(this == $gpy, massLine == "Salaries and Wages", plAcctId in ("7150408001", "7150408002", "7190919031"))
        
    then
        $gpy.setLocMassLine("Salaries");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1900589' extends '337157' salience 100

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "7150561206")
        
    then
        $gpy.setLocMassLine("Monitoring & Incident Management");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1900590' extends '337157' salience 90

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "7150561209")
        
    then
        $gpy.setLocMassLine("Software Customization");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1900591' extends '337157' salience 80

    when
        
        GrlPlYtd(this == $gpy, plAcctId in ("7150561305", "7150561210"))
        
    then
        $gpy.setLocMassLine("Software Testing");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1900592' extends '337157' salience 70

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "7150561202")
        
    then
        $gpy.setLocMassLine("Hardware & Software set-up");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1900593' extends '337157' salience 60

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "7150561207")
        
    then
        $gpy.setLocMassLine("Problem Management");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1900594' extends '337157' salience 50

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "7150561212")
        
    then
        $gpy.setLocMassLine("Project Feasibility");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1900595' extends '337157' salience 40

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "7150561211")
        
    then
        $gpy.setLocMassLine("Other fees");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1900596' extends '337157' salience 30

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "7150561203")
        
    then
        $gpy.setLocMassLine("Infrastructure Development");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1900597' extends '337157' salience 20

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "7150561204")
        
    then
        $gpy.setLocMassLine("Infrastructure Management");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end

rule '1954775' extends '337157' salience 10

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Supplies and Equipment", plAcctId in ("7150641002", "7180891204"))
        
    then
        $gpy.setLocMassLine("Office Supplies and Equipment_SUB");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"7189");
        
end


