package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '333032'
	when
		$gda : GrlDetAmounts(MANUALLY adjust this subselect: hac_amt_cl = '11' and act_code is null AND AJT_ID IS NULL AND ( lse_hly_rel_id , smn_rey_code , smn_bey_number , isin_cd ) in (select lse_hly_rel_id dat_lse_hly_rel_id , smn_rey_code dat_smn_rey_code , smn_bey_number dat_smn_bey_number , isin_cd dat_isin_cd from GRL_DET_AMOUNTS where hac_amt_cl = '11' AND start_date < rep_date group by lse_hly_rel_id , smn_rey_code , smn_bey_number , isin_cd having sum(CHO_DET_AMT_EUR) >= 0 ))
	then
        
end





rule '1356182' extends '333032' salience 380

    when
        
        /*MANUAL adjustment here, because of error: Not a case statement or nvl/nvl2 statement but some other special statement: write code to handle this!:{'N'}*/
        
    then
        $gda.setEncumberedInd("N");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3914");
        
end


