package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '332561'
	when
		$gda : GrlDetAmounts(actCode != null || hacAmtCl in ( "11" ))
	then
        
end





rule '1176608' extends '332561' salience 6530

    when
        
        GrlDetAmounts(this == $gda, actCode in ("A3145000", "A3146000", "A3147000"))
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("P&E - ASSETS UNDER OPERATING LEASE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176609' extends '332561' salience 6520

    when
        
        GrlDetAmounts(this == $gda, actCode in ("A3145000", "A3146000"))
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("P&E - ASSETS UNDER OPERATING LEASE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176610' extends '332561' salience 6510

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3179000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD DERIVATIVES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176612' extends '332561' salience 6500

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0001000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("OTHER ACCR. ASSETS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176614' extends '332561' salience 6490

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0003000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176615' extends '332561' salience 6480

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0005000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("ACCRUED RENTS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176616' extends '332561' salience 6470

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0006000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("P&E - EQUIPMENT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176618' extends '332561' salience 6460

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0007000")
        
    then
        $gda.setIlaapCat1("OTHER - WHOLESALE ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FX SPOT (ASSETS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176619' extends '332561' salience 6450

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0009000")
        
    then
        $gda.setIlaapCat1("CASH AND CASH BALANCES CENTRAL BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CASH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176620' extends '332561' salience 6440

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0011000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CORP TAX REC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176621' extends '332561' salience 6430

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0012000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("P&E - DATA PROC EQUIPM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176622' extends '332561' salience 6420

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0014000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("DEF TAX ASS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176623' extends '332561' salience 6410

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0015000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("INTANGIBLE FIXED ASSETS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176624' extends '332561' salience 6400

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0016000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("INTANGIBLE FIXED ASSETS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176628' extends '332561' salience 6390

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0019000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("P&E - INVESTMENT PROPERTY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176629' extends '332561' salience 6380

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0020000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("P&E - INVESTMENT PROPERTY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176630' extends '332561' salience 6370

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0021000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("P&E - PROPERTY IN OWN USE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176631' extends '332561' salience 6360

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0022000")
        
    then
        $gda.setIlaapCat1("OTHER - WHOLESALE ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("INVESTMENTS - ASSOCIATES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176633' extends '332561' salience 6350

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0024000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("IT TB CLD EX SEC TR-DT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176635' extends '332561' salience 6340

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0025000")
        
    then
        $gda.setIlaapCat1("OTHER - WHOLESALE ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("IT TB CLD IRO SEC TR-DT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176642' extends '332561' salience 6330

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0028000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("P&E - EQUIPMENT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176643' extends '332561' salience 6320

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0029000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("P&E - EQUIPMENT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176645' extends '332561' salience 6310

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0031000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("OTHER RECEIVABLES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176646' extends '332561' salience 6300

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0032000")
        
    then
        $gda.setIlaapCat1("EQUITY ASSETS");
        $gda.setIlaapCat3("EQT");
        $gda.setIlaapCat2("EQ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176647' extends '332561' salience 6290

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0032800")
        
    then
        $gda.setIlaapCat1("EQUITY ASSETS");
        $gda.setIlaapCat3("EQT");
        $gda.setIlaapCat2("EQ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176648' extends '332561' salience 6280

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0033000")
        
    then
        $gda.setIlaapCat1("EQUITY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("WORKING CAPITAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176649' extends '332561' salience 6270

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0035000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("OTHER ASSETS2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176650' extends '332561' salience 6260

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0038000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("OTHER ASSETS2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176651' extends '332561' salience 6250

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0039000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("OTHER ASSETS2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176653' extends '332561' salience 6240

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0040000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("OTHER ASSETS2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176655' extends '332561' salience 6230

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0045000")
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("LOAN LOSS PROVISION");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176656' extends '332561' salience 6220

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0046000")
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("LOAN LOSS PROVISION");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176658' extends '332561' salience 6210

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0050000")
        
    then
        $gda.setIlaapCat1("OTHER - WHOLESALE ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("REC FR ASSOCIATES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176659' extends '332561' salience 6200

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0051000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("INTANGIBLE FIXED ASSETS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176660' extends '332561' salience 6190

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0052000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("P&E - EQUIPMENT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176661' extends '332561' salience 6180

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0053000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("OTHER TAX REC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176662' extends '332561' salience 6170

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0056000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("PROPERTY DEVELOPED FOR SALE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176665' extends '332561' salience 6160

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0057000")
        
    then
        $gda.setIlaapCat1("OTHER - WHOLESALE ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("TRD LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176666' extends '332561' salience 6150

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0058000")
        
    then
        $gda.setIlaapCat1("OTHER - WHOLESALE ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("TRD DEBT SECURITIES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176668' extends '332561' salience 6140

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0061000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("VAT RECEIVABLE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176669' extends '332561' salience 6130

    when
        
        GrlDetAmounts(this == $gda, actCode == "A2549000")
        
    then
        $gda.setIlaapCat1("EQUITY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("INV IN GR COMP WITHIN BR (IC)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176670' extends '332561' salience 6120

    when
        
        GrlDetAmounts(this == $gda, actCode == "A2729000")
        
    then
        $gda.setIlaapCat1("EQUITY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("MINORITY INTEREST (INTERNAL)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176671' extends '332561' salience 6110

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3176000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD DERIVATIVES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176673' extends '332561' salience 6100

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3178000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD DERIVATIVES - OTHER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176675' extends '332561' salience 6090

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3282000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("TRD DERIVATIVES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176678' extends '332561' salience 6080

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3291000")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("DEBT SECURITIES (HTM)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176683' extends '332561' salience 6070

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000")
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FVO LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176686' extends '332561' salience 6060

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3331000")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FVO SECURITIES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176690' extends '332561' salience 6050

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000")
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("HEDGE PART LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176692' extends '332561' salience 6040

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3333000")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("DEBT SECURITIES (AFS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176694' extends '332561' salience 6030

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3906000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("HO ONLY DERIV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176695' extends '332561' salience 6020

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3908000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176696' extends '332561' salience 6010

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3910000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176698' extends '332561' salience 6000

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3914000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176700' extends '332561' salience 5990

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3916000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176704' extends '332561' salience 5980

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000")
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("VALUE ADJ HEDGED PART LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176707' extends '332561' salience 5970

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4112000")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("DEBT SECURITIES (HTM)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176708' extends '332561' salience 5960

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4144000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("PROPERTY UNDER DEV(ASS)NON-POC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176709' extends '332561' salience 5950

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4145000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("P&E - PROPERTY IN OWN USE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176710' extends '332561' salience 5940

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4152000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("PROPERTY UNDER DEV(ASS) POC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176711' extends '332561' salience 5930

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4257000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("DIVIDEND TAX RECEIVABLES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176712' extends '332561' salience 5920

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4392000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("PENSION ASSETS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176716' extends '332561' salience 5910

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4412000")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SECURITIES (AMORT COST)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176719' extends '332561' salience 5900

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4564000")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SECURITIES (AMORT COST)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176722' extends '332561' salience 5890

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4565000")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SECURITIES (AMORT COST)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176723' extends '332561' salience 5880

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4598000")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("PROV SECURITIES (AMORT COST)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176724' extends '332561' salience 5870

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4620000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("INTANGIBLE FIXED ASSETS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176725' extends '332561' salience 5860

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4884000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CORP TAX REC DFU");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176726' extends '332561' salience 5850

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4887000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2(Warning: selecting from FORECLOSURES: data will not be available in source topic.
 full statement: PROPERTY FROM FORECLOSURES);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176727' extends '332561' salience 5840

    when
        
        GrlDetAmounts(this == $gda, actCode == "A5437000")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("BAL.BASE ENTITY (DR) ONE FAR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176728' extends '332561' salience 5830

    when
        
        GrlDetAmounts(this == $gda, actCode == "A6682000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("INTANGIBLE FIXED ASSETS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176729' extends '332561' salience 5820

    when
        
        GrlDetAmounts(this == $gda, actCode == "A6685000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("BONUS PREPAYMENTS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176730' extends '332561' salience 5810

    when
        
        GrlDetAmounts(this == $gda, actCode == "A7985000")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("DEBT SECURITIES (HTM)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176731' extends '332561' salience 5800

    when
        
        GrlDetAmounts(this == $gda, actCode == "A7986000")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SECURITIES (AMORT COST)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176732' extends '332561' salience 5790

    when
        
        GrlDetAmounts(this == $gda, actCode == "A7987000")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SECURITIES (AMORT COST)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176733' extends '332561' salience 5780

    when
        
        GrlDetAmounts(this == $gda, actCode == "A7988000")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SECURITIES (AMORT COST)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176734' extends '332561' salience 5770

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8005000")
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("PROVISION FOR NPV FOREGONE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176736' extends '332561' salience 5760

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8008000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("ASSETS HELD FOR SALE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176737' extends '332561' salience 5750

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8241000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("LEASECARS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176738' extends '332561' salience 5740

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8267000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CVA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176739' extends '332561' salience 5730

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8268000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("BID/OFFER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176740' extends '332561' salience 5720

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8269000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("TRANSFER RISK ADJ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176741' extends '332561' salience 5710

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8270000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("MODEL RISK ADJ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176743' extends '332561' salience 5700

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8294000")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("AMORT IC TRANSFER LNS & ADV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176745' extends '332561' salience 5690

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8295000")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("AMORT IC TRANSFER HTM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176746' extends '332561' salience 5680

    when
        
        GrlDetAmounts(this == $gda, actCode matches "A998.*")
        
    then
        $gda.setIlaapCat1("EQUITY ASSETS");
        $gda.setIlaapCat3("EQT");
        $gda.setIlaapCat2("EQ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176748' extends '332561' salience 5670

    when
        
        GrlDetAmounts(this == $gda, actCode matches "B.*")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("OFF BAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176749' extends '332561' salience 5660

    when
        
        GrlDetAmounts(this == $gda, actCode matches "E.*")
        
    then
        $gda.setIlaapCat1("NET RESULT CURRENT YR");
        $gda.setIlaapCat3("NET RESULT CURRENT YEAR");
        $gda.setIlaapCat2("NET RESULT CURR YR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176750' extends '332561' salience 5650

    when
        
        GrlDetAmounts(this == $gda, actCode matches "I.*")
        
    then
        $gda.setIlaapCat1("NET RESULT CURRENT YR");
        $gda.setIlaapCat3("NET RESULT CURR YR");
        $gda.setIlaapCat2("NET RESULT CURRENT YEAR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176751' extends '332561' salience 5640

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0229000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176753' extends '332561' salience 5630

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0230000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("FX SPOT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176754' extends '332561' salience 5620

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0233000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("COMM & OVERR COMM (LB)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176755' extends '332561' salience 5610

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0234000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("CORP TAX PAY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176757' extends '332561' salience 5600

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0237000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("OTHER ABS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176758' extends '332561' salience 5590

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0238000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("DEF TAX LB");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176759' extends '332561' salience 5580

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0239000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("DIV PAY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176763' extends '332561' salience 5570

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000")
        
    then
        $gda.setIlaapCat1("CORPORATE DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("NTRD FUNDS ENTRUSTED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176764' extends '332561' salience 5560

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0243000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("OTHER GEN PROV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176765' extends '332561' salience 5550

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0244000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("POST RETIREMENT - OTHER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176766' extends '332561' salience 5540

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0245000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("INCOME TAX PAYABLE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176767' extends '332561' salience 5530

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0246000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("INFO TECH PROV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176768' extends '332561' salience 5520

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0249000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("INT & RENTS REC IN ADV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176769' extends '332561' salience 5510

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0250000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("IT TB CLD EX SEC TR-CR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176771' extends '332561' salience 5500

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0251000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("IT TB CLD IRO SEC TR-CR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176772' extends '332561' salience 5490

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0252000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("OTHER LIAB");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176773' extends '332561' salience 5480

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0253000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("OTHER STAFF RELATED LIABS LT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176774' extends '332561' salience 5470

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0254000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("PAY ON GOODS/SERV SUPPL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176775' extends '332561' salience 5460

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0255000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("OTHER PAY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176776' extends '332561' salience 5450

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0256000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("POST RETIREMENT - PENSION");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176777' extends '332561' salience 5440

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0257000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("PENS PAYABLE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176778' extends '332561' salience 5430

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0258000")
        
    then
        $gda.setIlaapCat1("EQUITY");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("WORKING CAPITAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176779' extends '332561' salience 5420

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0267000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("REORG/RELOC PROV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176780' extends '332561' salience 5410

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0269000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("TRD SHORT POSITION SEC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176781' extends '332561' salience 5400

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0271000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SOC SEC CONTR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176783' extends '332561' salience 5390

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0272000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SUBORDINATED LOANS - OTHER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176785' extends '332561' salience 5380

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0273000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("OTHER TAX PAY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176786' extends '332561' salience 5370

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0277000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("VAT PAYABLE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176790' extends '332561' salience 5360

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1425000")
        
    then
        $gda.setIlaapCat1("CORPORATE DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("TRD FUNDS ENTRUSTED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176791' extends '332561' salience 5350

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1607000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("CONTROL ACCOUNT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176792' extends '332561' salience 5340

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1615000")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("INTERNAL FUNDS TRANSFER (CR)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176793' extends '332561' salience 5330

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2529000")
        
    then
        $gda.setIlaapCat1("EQUITY");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("WORKING CAPITAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176794' extends '332561' salience 5320

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2530000")
        
    then
        $gda.setIlaapCat1("EQUITY");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("WORKING CAPITAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176795' extends '332561' salience 5310

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2531000")
        
    then
        $gda.setIlaapCat1("EQUITY");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("WORKING CAPITAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176796' extends '332561' salience 5300

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2532000")
        
    then
        $gda.setIlaapCat1("EQUITY");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("WORKING CAPITAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176797' extends '332561' salience 5290

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2533000")
        
    then
        $gda.setIlaapCat1("EQUITY");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("WORKING CAPITAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176798' extends '332561' salience 5280

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2550000")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("OTHER PAY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176799' extends '332561' salience 5270

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2569000")
        
    then
        $gda.setIlaapCat1("SIGHT-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176800' extends '332561' salience 5260

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2571000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("BONUS ACCRUAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176801' extends '332561' salience 5250

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2730000")
        
    then
        $gda.setIlaapCat1("EQUITY");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("THIRD-PARTY INTEREST(INTERNAL)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176802' extends '332561' salience 5240

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3180000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("CASH FLOW HEDGES (LIABS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176803' extends '332561' salience 5230

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3181000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("FAIR VALUE HEDGES (LIABS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176804' extends '332561' salience 5220

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3182000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("OTH-NON TR DERIVAT (LIABS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176805' extends '332561' salience 5210

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3183000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("HDG NET INV FRGN ENT (LIABS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176806' extends '332561' salience 5200

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3283000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("TRD DERIVATIVES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176810' extends '332561' salience 5190

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3334000")
        
    then
        $gda.setIlaapCat1("CORPORATE DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("VALUE ADJ HEDGED PART FUNDS ENTR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176811' extends '332561' salience 5180

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3340000")
        
    then
        $gda.setIlaapCat1("EQUITY");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("WORKING CAPITAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176815' extends '332561' salience 5170

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3343000")
        
    then
        $gda.setIlaapCat1("CORPORATE DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("FVO FUNDS ENTR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176817' extends '332561' salience 5160

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3345000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("DEBT SECURITIES IN ISSUE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176818' extends '332561' salience 5150

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3346000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("FVO DEBT SECURITIES IN ISSUE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176820' extends '332561' salience 5140

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3348000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("FVO SUBORDINATED LIABILIITES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176821' extends '332561' salience 5130

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3351000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176822' extends '332561' salience 5120

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3873000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("LITIGATION PROVISIONS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176823' extends '332561' salience 5110

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3892000")
        
    then
        $gda.setIlaapCat1("EQUITY");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("WORKING CAPITAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176824' extends '332561' salience 5100

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3893000")
        
    then
        $gda.setIlaapCat1("EQUITY");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("WORKING CAPITAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176825' extends '332561' salience 5090

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3899000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SHARE BASED PAYMENT PLANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176826' extends '332561' salience 5080

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3907000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("HO ONLY DERIV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176827' extends '332561' salience 5070

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3909000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176828' extends '332561' salience 5060

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3911000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176829' extends '332561' salience 5050

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3913000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176830' extends '332561' salience 5040

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3915000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176831' extends '332561' salience 5030

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3917000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176835' extends '332561' salience 5020

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3933000")
        
    then
        $gda.setIlaapCat1("CORPORATE DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("HEDGED PART FUND ENT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176837' extends '332561' salience 5010

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3934000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("DEBT SECURITIES IN ISSUE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176839' extends '332561' salience 5000

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3935000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SUBORDINATED LOANS - OTHER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176842' extends '332561' salience 4990

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3936000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SUBORDINATED LOANS - OTHER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176844' extends '332561' salience 4980

    when
        
        GrlDetAmounts(this == $gda, actCode == "L4146000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("PROPERTY UNDER DEV(LB) POC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176845' extends '332561' salience 4970

    when
        
        GrlDetAmounts(this == $gda, actCode == "L4147000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("PROPERTY UNDER DEV(LB)NON-POC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176846' extends '332561' salience 4960

    when
        
        GrlDetAmounts(this == $gda, actCode == "L4150000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("PROPERTY UNDER DELOPM-ADVANCES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176847' extends '332561' salience 4950

    when
        
        GrlDetAmounts(this == $gda, actCode == "L4258000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("DIVIDEND TAX PAYABLES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176848' extends '332561' salience 4940

    when
        
        GrlDetAmounts(this == $gda, actCode == "L4467000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("FVO SUB LIAB DUE TO CH CR RATE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176849' extends '332561' salience 4930

    when
        
        GrlDetAmounts(this == $gda, actCode == "L4597000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("PROV ONEROUS CONTRACTS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176850' extends '332561' salience 4920

    when
        
        GrlDetAmounts(this == $gda, actCode == "L4885000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("CORP TAX PAY DFU");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176851' extends '332561' salience 4910

    when
        
        GrlDetAmounts(this == $gda, actCode == "L4888000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("STAFF RELATED LIABS SHORT TERM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176852' extends '332561' salience 4900

    when
        
        GrlDetAmounts(this == $gda, actCode == "L5438000")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("BAL.BASE ENTITY (CR) ONE FAR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176853' extends '332561' salience 4890

    when
        
        GrlDetAmounts(this == $gda, actCode == "L6687000")
        
    then
        $gda.setIlaapCat1("EQUITY");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("WORKING CAPITAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176854' extends '332561' salience 4880

    when
        
        GrlDetAmounts(this == $gda, actCode == "L7510000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("PROVISION TERMINATION BENEFITS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176855' extends '332561' salience 4870

    when
        
        GrlDetAmounts(this == $gda, actCode == "L8009000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("LIABILITIES HELD FOR SALE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176856' extends '332561' salience 4860

    when
        
        GrlDetAmounts(this == $gda, actCode == "L8276000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("DVA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176857' extends '332561' salience 4850

    when
        
        GrlDetAmounts(this == $gda, actCode == "L8277000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("OWN CREDIT ADJUST ON FVO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176858' extends '332561' salience 4840

    when
        
        GrlDetAmounts(this == $gda, actCode == "L8292000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("BANK LEVY (FSC) PAYABLE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176859' extends '332561' salience 4830

    when
        
        GrlDetAmounts(this == $gda, actCode == "L9998000")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("INTERCOMPANY LIABILITIES2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176860' extends '332561' salience 4820

    when
        
        GrlDetAmounts(this == $gda, actCode == "L9999000")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("INTERCOMPANY LIABILITIES2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176861' extends '332561' salience 4810

    when
        
        GrlDetAmounts(this == $gda, actCode matches "Q.*")
        
    then
        $gda.setIlaapCat1("EQUITY");
        $gda.setIlaapCat3("EQT");
        $gda.setIlaapCat2("EQ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176862' extends '332561' salience 4800

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0073000")
        
    then
        $gda.setIlaapCat1("EQUITY");
        $gda.setIlaapCat3("EQT");
        $gda.setIlaapCat2("EQ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176863' extends '332561' salience 4790

    when
        
        GrlDetAmounts(this == $gda, actCode == "R9000000")
        
    then
        $gda.setIlaapCat1("EQUITY");
        $gda.setIlaapCat3("EQT");
        $gda.setIlaapCat2("EQ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176864' extends '332561' salience 4780

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1605000")
        
    then
        $gda.setIlaapCat1("EQUITY");
        $gda.setIlaapCat3("EQT");
        $gda.setIlaapCat2("WORKING CAPITAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1179216' extends '332561' salience 4770

    when
        
        GrlDetAmounts(this == $gda, actCode == "L8333000")
        
    then
        $gda.setIlaapCat1("EQUITY");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("ACTUARIAL GL ON PENSION DBP BR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1184155' extends '332561' salience 4760

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8334000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("MODEL RISK RES CVA/DVA DERIVAT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1184157' extends '332561' salience 4750

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3177000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD DERIVATIVES - OTHER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187021' extends '332561' salience 4740

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3912000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187022' extends '332561' salience 4730

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8327000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("BANK LEVY (FSC) RECEIVABLE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187023' extends '332561' salience 4720

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8328000")
        
    then
        $gda.setIlaapCat1("OTHER - WHOLESALE ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("INV JOINT VENTURE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187024' extends '332561' salience 4710

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8349000")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CUMM CH FV DUE TO CR RISK DSEC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187029' extends '332561' salience 4700

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8350000")
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CUMM CH FV DUE TO CR RISK LOAN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1248077' extends '332561' salience 4690

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1606000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("CONTROL ACCOUNT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1587870' extends '332561' salience 4680

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8609000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES BOUGHT - UNSECURED");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("TRD - DEBT SECURITES OWN ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1621282' extends '332561' salience 4670

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8650000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CVA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1621283' extends '332561' salience 4660

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8651000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("BID/OFFER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1621284' extends '332561' salience 4650

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8652000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("TRANSFER RISK ADJ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1621285' extends '332561' salience 4640

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8653000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("MODEL RISK ADJ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1621286' extends '332561' salience 4630

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8654000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("MODEL RISK RES CVA/DVA DERIVAT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1649318' extends '332561' salience 4620

    when
        
        GrlDetAmounts(this == $gda, actCode == "L8658000")
        
    then
        $gda.setIlaapCat1("DERIVATIVES LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("DVA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1676308' extends '332561' salience 4610

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8867000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("OTHER ASSETS2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1690824' extends '332561' salience 4600

    when
        
        GrlDetAmounts(this == $gda, actCode == "L8940000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("OTHER TAX PAY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1697903' extends '332561' salience 4590

    when
        
        GrlDetAmounts(this == $gda, actCode == "A9003000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("OTHER ASSETS2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1697907' extends '332561' salience 4580

    when
        
        GrlDetAmounts(this == $gda, actCode == "L9004000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("OTHER LIAB");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1701637' extends '332561' salience 4570

    when
        
        GrlDetAmounts(this == $gda, actCode == "A9011000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("VAT RECEIVABLE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1701638' extends '332561' salience 4560

    when
        
        GrlDetAmounts(this == $gda, actCode == "L9012000")
        
    then
        $gda.setIlaapCat1("OTHER LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("VAT PAYABLE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1701782' extends '332561' salience 4550

    when
        
        GrlDetAmounts(this == $gda, actCode == "A9016000")
        
    then
        $gda.setIlaapCat1("OTHER ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("MODEL RISK ADJ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1701788' extends '332561' salience 4540

    when
        
        GrlDetAmounts(this == $gda, actCode == "L8622000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SUBORDINATED LOANS - OTHER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1701789' extends '332561' salience 4530

    when
        
        GrlDetAmounts(this == $gda, actCode == "L9013000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SUBORDINATED LOANS - OTHER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1701790' extends '332561' salience 4520

    when
        
        GrlDetAmounts(this == $gda, actCode == "L9014000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SUBORDINATED LOANS - OTHER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176537' extends '332561' salience 4510

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0058000", pdtCode == "004700")
        
    then
        $gda.setIlaapCat1("OTHER - WHOLESALE ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("TRD EQUITY SECURITIES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176551' extends '332561' salience 4500

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000", pdtCode == "013600")
        
    then
        $gda.setIlaapCat1("OTHER - WHOLESALE ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FINANCIAL LEASE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176553' extends '332561' salience 4490

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", pdtCode == "013600")
        
    then
        $gda.setIlaapCat1("OTHER - WHOLESALE ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FINANCIAL LEASE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176564' extends '332561' salience 4480

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0057000", pdtCode == "027800")
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("RREPO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176566' extends '332561' salience 4470

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000", pdtCode == "027800")
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("RREPO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176582' extends '332561' salience 4460

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0057000", pdtCode == "027900")
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SBL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176584' extends '332561' salience 4450

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000", pdtCode == "027900")
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SBL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176593' extends '332561' salience 4440

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0237000", pdtCode == "005900")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("BONDS SHORT (EXCL CDS AND CP)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176595' extends '332561' salience 4430

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3934000", pdtCode == "029000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - SECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("COVERED BONDS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176596' extends '332561' salience 4420

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0237000", pdtCode == "030300")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("RMBS-PRIME NON US");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176603' extends '332561' salience 4410

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0023000", pdtCode in ("004700", "004800"))
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("INVESTMENTS - OTHER SECURITIES (AFS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176611' extends '332561' salience 4400

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0001000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("OTHER ACCR. ASSETS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176613' extends '332561' salience 4390

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0003000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176626' extends '332561' salience 4380

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0017000", cgpCode == "00017")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES BOUGHT - UNSECURED");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("DEBT SECURITIES (AFS) OWN ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176627' extends '332561' salience 4370

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0017000", cgpCode != "00017")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("DEBT SECURITIES (AFS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176632' extends '332561' salience 4360

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0024000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("IT TB CLD EX SEC TR-DT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176637' extends '332561' salience 4350

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", cgpCode in ("B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("LOANS TO / DEPOSITS AT BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD LOANS AND ADVANCES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176639' extends '332561' salience 4340

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", cgpCode in ("P0039", "P0045"))
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD LOANS AND ADVANCES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176640' extends '332561' salience 4330

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", cgpCode matches "G.*")
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD LOANS AND ADVANCES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176641' extends '332561' salience 4320

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("CONSUMER LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD LOANS AND ADVANCES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176644' extends '332561' salience 4310

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0031000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("OTHER RECEIVABLES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176652' extends '332561' salience 4300

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0040000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("OTHER PREPAYMENTS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176654' extends '332561' salience 4290

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0045000", (rteCode matches "07.*" || rteCode == "80"))
        
    then
        $gda.setIlaapCat1("LOANS TO / DEPOSITS AT BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("LOAN LOSS PROVISION");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176657' extends '332561' salience 4280

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0050000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("REC FR ASSOCIATES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176663' extends '332561' salience 4270

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0057000", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("OTHER - RETAIL ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("TRD LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176664' extends '332561' salience 4260

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0057000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("TRD LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176667' extends '332561' salience 4250

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0058000", cgpCode == "00017")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES BOUGHT - UNSECURED");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("TRD - DEBT SECURITES OWN ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176672' extends '332561' salience 4240

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3178000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD DERIVATIVES - OTHER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176674' extends '332561' salience 4230

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3282000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("TRD DERIVATIVES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176677' extends '332561' salience 4220

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3291000", cgpCode == "00017")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES BOUGHT - UNSECURED");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("DEBT SECURITIES (HTM) OWN ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176679' extends '332561' salience 4210

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000", cgpCode in ("B0035", "B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("LOANS TO / DEPOSITS AT BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FVO LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176681' extends '332561' salience 4200

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("CONSUMER LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FVO LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176685' extends '332561' salience 4190

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3331000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FVO SECURITIES - OWN ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176687' extends '332561' salience 4180

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", cgpCode in ("B0035", "B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("LOANS TO / DEPOSITS AT BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("HEDGE PART LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176688' extends '332561' salience 4170

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", cgpCode == "B0034")
        
    then
        $gda.setIlaapCat1("CASH AND CASH BALANCES CENTRAL BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("HEDGE PART LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176689' extends '332561' salience 4160

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("CONSUMER LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("HEDGE PART LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176691' extends '332561' salience 4150

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3333000", cgpCode == "00017")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES BOUGHT - UNSECURED");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("DEBT SECURITIES (AFS) OWN ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176693' extends '332561' salience 4140

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3906000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("HO ONLY DERIV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176697' extends '332561' salience 4130

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3914000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176699' extends '332561' salience 4120

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3916000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176701' extends '332561' salience 4110

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", cgpCode in ("B0036", "B0037", "B0038"))
        
    then
        $gda.setIlaapCat1("LOANS TO / DEPOSITS AT BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("VALUE ADJ HEDGED PART LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176702' extends '332561' salience 4100

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", cgpCode == "B0034")
        
    then
        $gda.setIlaapCat1("CASH AND CASH BALANCES CENTRAL BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("VALUE ADJ HEDGED PART LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176703' extends '332561' salience 4090

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("CONSUMER LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("VALUE ADJ HEDGED PART LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176705' extends '332561' salience 4080

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3943000", (rteCode matches "07.*" || rteCode == "080"))
        
    then
        $gda.setIlaapCat1("LOANS TO / DEPOSITS AT BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("LOAN LOSS PROVISION");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176706' extends '332561' salience 4070

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3943000", rteCode in ("081", "082", "083", "084", "085", "086", "087", "088"))
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("LOAN LOSS PROVISION");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176713' extends '332561' salience 4060

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4412000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SECURITIES (AMORT COST)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176718' extends '332561' salience 4050

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4564000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SECURITIES (AMORT COST)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176721' extends '332561' salience 4040

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4565000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SECURITIES (AMORT COST)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176735' extends '332561' salience 4030

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8008000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("ASSETS HELD FOR SALE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176742' extends '332561' salience 4020

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8294000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("AMORT IC TRANSFER LNS & ADV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176744' extends '332561' salience 4010

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8295000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("AMORT IC TRANSFER HTM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176747' extends '332561' salience 4000

    when
        
        GrlDetAmounts(this == $gda, actCode matches "B.*", rteCode == "010")
        
    then
        $gda.setIlaapCat1("IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("OFF BAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176752' extends '332561' salience 3990

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0230000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("FX SPOT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176756' extends '332561' salience 3980

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0237000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("OTHER ABS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176760' extends '332561' salience 3970

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", cgpCode in ("B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("BANK DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("NTRD FUNDS ENTRUSTED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176761' extends '332561' salience 3960

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", cgpCode in ("B0034", "B0035"))
        
    then
        $gda.setIlaapCat1("CENTRAL BANK DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("NTRD FUNDS ENTRUSTED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176770' extends '332561' salience 3950

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0251000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("IT TB CLD IRO SEC TR-CR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176782' extends '332561' salience 3940

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0272000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SUBORDINATED LOANS - OTHER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176784' extends '332561' salience 3930

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0272000", rteCode in ("069", "105"))
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SUBORDINATED LOANS - TIER 1");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176787' extends '332561' salience 3920

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1425000", cgpCode in ("B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("BANK DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("TRD FUNDS ENTRUSTED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176788' extends '332561' salience 3910

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1425000", cgpCode in ("B0034", "B0035"))
        
    then
        $gda.setIlaapCat1("CENTRAL BANK DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("TRD FUNDS ENTRUSTED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176807' extends '332561' salience 3900

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3334000", cgpCode in ("B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("BANK DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("VALUE ADJ HEDGED PART FUNDS ENTR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176808' extends '332561' salience 3890

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3334000", cgpCode in ("B0034", "B0035"))
        
    then
        $gda.setIlaapCat1("CENTRAL BANK DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("VALUE ADJ HEDGED PART FUNDS ENTR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176812' extends '332561' salience 3880

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3343000", cgpCode in ("B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("BANK DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("FVO FUNDS ENTR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176813' extends '332561' salience 3870

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3343000", cgpCode in ("B0034", "B0035"))
        
    then
        $gda.setIlaapCat1("CENTRAL BANK DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("FVO FUNDS ENTR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176816' extends '332561' salience 3860

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3345000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("DEBT SECURITIES IN ISSUE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176819' extends '332561' salience 3850

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3348000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("FVO SUBORDINATED LIABILIITES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176832' extends '332561' salience 3840

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3933000", cgpCode in ("B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("BANK DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("HEDGED PART FUND ENT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176833' extends '332561' salience 3830

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3933000", cgpCode in ("B0034", "B0035"))
        
    then
        $gda.setIlaapCat1("CENTRAL BANK DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("HEDGED PART FUND ENT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176836' extends '332561' salience 3820

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3934000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("DEBT SECURITIES IN ISSUE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176838' extends '332561' salience 3810

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3935000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SUBORDINATED LOANS - OTHER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176840' extends '332561' salience 3800

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3935000", rteCode in ("069", "105"))
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SUBORDINATED LOANS - TIER 1");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176841' extends '332561' salience 3790

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3936000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SUBORDINATED LOANS - OTHER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176843' extends '332561' salience 3780

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3936000", rteCode in ("069", "105"))
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SUBORDINATED LOANS - TIER 1");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1186431' extends '332561' salience 3770

    when
        
        GrlDetAmounts(this == $gda, actCode == null, hacAmtCl == "11")
        
    then
        $gda.setIlaapCat1("REPO - SEC LEG NEAR");
        $gda.setIlaapCat2("REPO - SEC LEG NEAR2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1186432' extends '332561' salience 3760

    when
        
        GrlDetAmounts(this == $gda, actCode == null, hacAmtCl == "19")
        
    then
        $gda.setIlaapCat1("REPO - SEC LEG FAR");
        $gda.setIlaapCat2("REPO - SEC LEG FAR2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187005' extends '332561' salience 3750

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0023000", pdtCode not in ("004700", "004800"))
        
    then
        $gda.setIlaapCat1("OTHER - WHOLESALE ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("INVESTMENT IN NON-ASSOCIATES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187018' extends '332561' salience 3740

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3291000", cgpCode in ("00018", "00019"))
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("DEBT SECURITIES (HTM)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187019' extends '332561' salience 3730

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3331000", cgpCode in ("00018", "00019"))
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FVO SECURITIES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187020' extends '332561' salience 3720

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3333000", cgpCode in ("00018", "00019"))
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("DEBT SECURITIES (AFS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187025' extends '332561' salience 3710

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8349000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CUMM CH FV DUE TO CR RISK DSEC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187026' extends '332561' salience 3700

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8350000", cgpCode in ("B0035", "B0036", "B0037", "B0038"))
        
    then
        $gda.setIlaapCat1("LOANS TO / DEPOSITS AT BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CUMM CH FV DUE TO CR RISK LOAN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187027' extends '332561' salience 3690

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8350000", cgpCode == "B0034")
        
    then
        $gda.setIlaapCat1("CASH AND CASH BALANCES CENTRAL BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CUMM CH FV DUE TO CR RISK LOAN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187028' extends '332561' salience 3680

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8350000", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("CONSUMER LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CUMM CH FV DUE TO CR RISK LOAN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187037' extends '332561' salience 3670

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0237000", pdtCode == "029000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - SECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("COVERED BONDS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187038' extends '332561' salience 3660

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0237000", pdtCode == "031100")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("OTHER ABS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187039' extends '332561' salience 3650

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0237000", pdtCode == "031200")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("COMMERCIAL PAPER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187041' extends '332561' salience 3640

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0237000", pdtCode == "006100")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("CERT OF DEPOSIT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187072' extends '332561' salience 3630

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0595000", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("GUARANTEES CREDIT SUBSTITUTE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1210869' extends '332561' salience 3620

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8294000", rteCode == "130")
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("AMORT IC TRANSFER LNS & ADV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1210870' extends '332561' salience 3610

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8295000", rteCode == "130")
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("AMORT IC TRANSFER HTM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1230805' extends '332561' salience 3600

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3345000", pdtCode == "029000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - SECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("COVERED BONDS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1342782' extends '332561' salience 3590

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0046000", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("CONSUMER LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("LOAN LOSS PROVISION");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1361198' extends '332561' salience 3580

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3346000", pdtCode == "029000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - SECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("COVERED BONDS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1364502' extends '332561' salience 3570

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0046000", cgpCode matches "B.*")
        
    then
        $gda.setIlaapCat1("LOANS TO / DEPOSITS AT BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("LOAN LOSS PROVISION");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1364506' extends '332561' salience 3560

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8349000", rteCode == "00017")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES BOUGHT - UNSECURED");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CUMM CH FV DUE TO CR RISK DSEC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1364508' extends '332561' salience 3550

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("TERM-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("NTRD FUNDS ENTRUSTED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1364510' extends '332561' salience 3540

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1425000", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("TERM-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("TRD FUNDS ENTRUSTED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1364512' extends '332561' salience 3530

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3334000", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("TERM-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("VALUE ADJ HEDGED PART FUNDS ENTR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1364514' extends '332561' salience 3520

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3343000", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("TERM-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("FVO FUNDS ENTR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1364515' extends '332561' salience 3510

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3933000", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("TERM-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("HEDGED PART FUND ENT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1420952' extends '332561' salience 3500

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0007000", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("OTHER - RETAIL ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FX SPOT (ASSETS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1420953' extends '332561' salience 3490

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0025000", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("OTHER - RETAIL ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("IT TB CLD IRO SEC TR-DT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1487159' extends '332561' salience 3480

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0046000", cgpCode in ("P0039", "P0045", "G0008", "G0009"))
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("LOAN LOSS PROVISION");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1487161' extends '332561' salience 3470

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0046000", cgpCode matches "0.*")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("LOAN LOSS PROVISION");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1582360' extends '332561' salience 3460

    when
        
        GrlDetAmounts(this == $gda, actCode == "L8277000", pdtCode in ("005900", "007300", "002900", "006100", "015100"))
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("OWN CREDIT ADJUST ON FVO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1582361' extends '332561' salience 3450

    when
        
        GrlDetAmounts(this == $gda, actCode == "L8277000", pdtCode == "029000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - SECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("OWN CREDIT ADJUST ON FVO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1587876' extends '332561' salience 3440

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8609000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("TRD - DEBT SECURITES OWN ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1587877' extends '332561' salience 3430

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0237000", pdtCode == "031000")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("ABCP (ASSET BACKED COMM PAPER)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1589353' extends '332561' salience 3420

    when
        
        GrlDetAmounts(this == $gda, actCode == "L8333000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("ACTUARIAL GL ON PENSION DBP BR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1592484' extends '332561' salience 3410

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3334000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("VALUE ADJ HEDGED PART FUNDS ENTR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1604481' extends '332561' salience 3400

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0251000", rteCode == "075")
        
    then
        $gda.setIlaapCat1("BANK DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("IT TB CLD IRO SEC TR-CR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1604482' extends '332561' salience 3390

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0251000", rteCode == "076")
        
    then
        $gda.setIlaapCat1("CORPORATE DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("IT TB CLD IRO SEC TR-CR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1614309' extends '332561' salience 3380

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", cgpCode in ("G0008", "G0009", "P0039", "P0045"))
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD LOANS AND ADVANCES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1614760' extends '332561' salience 3370

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2569000", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("TERM-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1614761' extends '332561' salience 3360

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2569000", cgpCode in ("B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("BANK DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1615991' extends '332561' salience 3350

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0595000", pdtCode == "014100")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("GUARANTEES CREDIT SUBSTITUTE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1621127' extends '332561' salience 3340

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3346000", pdtCode == "031200")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("COMMERCIAL PAPER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1676309' extends '332561' salience 3330

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3346000", pdtCode == "031600")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("DEBT SECURITIES IN ISSUE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1676311' extends '332561' salience 3320

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0237000", pdtCode == "031600")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("DEBT SECURITIES IN ISSUE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1690821' extends '332561' salience 3310

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0058000", pdtCode == "004800")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("INVESTMENTS - OTHER SECURITIES (AFS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1701785' extends '332561' salience 3300

    when
        
        GrlDetAmounts(this == $gda, actCode == "A9018000", pdtCode not in ("004700", "004800"))
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("DEBT SECURITIES (AFS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1701786' extends '332561' salience 3290

    when
        
        GrlDetAmounts(this == $gda, actCode == "A9018000", pdtCode in ("004700", "004800"))
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("EQUITY SECURITIES (AFS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176536' extends '332561' salience 3280

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0017000", pdtCode == "004700", cgpCode != "00017")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("EQUITY SECURITIES (AFS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176538' extends '332561' salience 3270

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0017000", pdtCode == "004800", cgpCode != "00017")
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("EQUITY SECURITIES (AFS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176539' extends '332561' salience 3260

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000", pdtCode == "008200", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("CONSUMER LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("INSURANCE POLICY LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176540' extends '332561' salience 3250

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "009400", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("MORTGAGES");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD LOANS AND ADVANCES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176541' extends '332561' salience 3240

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000", pdtCode == "009400", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("MORTGAGES");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FVO LOANS -  MORTGAGES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176542' extends '332561' salience 3230

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", pdtCode == "009400", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("MORTGAGES");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("HEDGE PART LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176543' extends '332561' salience 3220

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", pdtCode == "009400", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("MORTGAGES");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("VALUE ADJ HEDGED PART LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176545' extends '332561' salience 3210

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "013600", cgpCode in ("B0035", "B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("OTHER - WHOLESALE ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FINANCIAL LEASE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176547' extends '332561' salience 3200

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "013600", cgpCode in ("P0039", "P0045"))
        
    then
        $gda.setIlaapCat1("OTHER - WHOLESALE ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FINANCIAL LEASE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176548' extends '332561' salience 3190

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "013600", cgpCode matches "G.*")
        
    then
        $gda.setIlaapCat1("OTHER - WHOLESALE ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FINANCIAL LEASE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176549' extends '332561' salience 3180

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "013600", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("OTHER - RETAIL ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FINANCIAL LEASE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176550' extends '332561' salience 3170

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000", pdtCode == "013600", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("OTHER - RETAIL ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FINANCIAL LEASE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176552' extends '332561' salience 3160

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", pdtCode == "013600", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("OTHER - RETAIL ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FINANCIAL LEASE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176554' extends '332561' salience 3150

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", pdtCode == "013600", cgpCode != "P0049")
        
    then
        $gda.setIlaapCat1("OTHER - WHOLESALE ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FINANCIAL LEASE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176555' extends '332561' salience 3140

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", pdtCode == "013600", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("OTHER - RETAIL ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FINANCIAL LEASE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176558' extends '332561' salience 3130

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "027800", cgpCode in ("B0035", "B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("RREPO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176560' extends '332561' salience 3120

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "027800", cgpCode in ("P0039", "P0045"))
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("RREPO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176562' extends '332561' salience 3110

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "027800", cgpCode matches "G.*")
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("RREPO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176563' extends '332561' salience 3100

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0057000", pdtCode == "027800", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("RREPO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176565' extends '332561' salience 3090

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000", pdtCode == "027800")
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("RREPO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176567' extends '332561' salience 3080

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000", pdtCode == "027800", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("RREPO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176568' extends '332561' salience 3070

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", pdtCode == "027800")
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("RREPO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176569' extends '332561' salience 3060

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", pdtCode == "027800")
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("RREPO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176570' extends '332561' salience 3050

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "027800")
        
    then
        $gda.setIlaapCat1("REPO");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("REPO2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176571' extends '332561' salience 3040

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1425000", pdtCode == "027800")
        
    then
        $gda.setIlaapCat1("REPO");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("REPO2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176572' extends '332561' salience 3030

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3334000", pdtCode == "027800")
        
    then
        $gda.setIlaapCat1("REPO");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("REPO2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176573' extends '332561' salience 3020

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3343000", pdtCode == "027800")
        
    then
        $gda.setIlaapCat1("REPO");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("REPO2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176574' extends '332561' salience 3010

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3933000", pdtCode == "027800")
        
    then
        $gda.setIlaapCat1("REPO");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("REPO2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176576' extends '332561' salience 3000

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "027900", cgpCode in ("B0035", "B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SBL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176578' extends '332561' salience 2990

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "027900", cgpCode in ("P0039", "P0045"))
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SBL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176580' extends '332561' salience 2980

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "027900", cgpCode matches "G.*")
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SBL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176581' extends '332561' salience 2970

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0057000", pdtCode == "027900", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SBL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176583' extends '332561' salience 2960

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000", pdtCode == "027900")
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SBL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176585' extends '332561' salience 2950

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", pdtCode == "027900")
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SBL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176586' extends '332561' salience 2940

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", pdtCode == "027900")
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SBL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176587' extends '332561' salience 2930

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "027900")
        
    then
        $gda.setIlaapCat1("REPO");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SBL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176588' extends '332561' salience 2920

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1425000", pdtCode == "027900")
        
    then
        $gda.setIlaapCat1("REPO");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SBL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176589' extends '332561' salience 2910

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3334000", pdtCode == "027900")
        
    then
        $gda.setIlaapCat1("REPO");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SBL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176590' extends '332561' salience 2900

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3343000", pdtCode == "027900")
        
    then
        $gda.setIlaapCat1("REPO");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SBL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176591' extends '332561' salience 2890

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3933000", pdtCode == "027900")
        
    then
        $gda.setIlaapCat1("REPO");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("SBL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176597' extends '332561' salience 2880

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0237000", pdtCode == "031100", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("OTHER ABS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176598' extends '332561' salience 2870

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3333000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("DEBT SECURITIES (AFS) OWN ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176599' extends '332561' salience 2860

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode in ("012200", "004000", "004300", "004400"), cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("TERM-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("NTRD FUNDS ENTRUSTED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176600' extends '332561' salience 2850

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3334000", pdtCode in ("012200", "004000", "004300", "004400"), cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("TERM-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("VALUE ADJ HEDGED PART FUNDS ENTR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176601' extends '332561' salience 2840

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3343000", pdtCode in ("012200", "004000", "004300", "004400"), cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("TERM-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("FVO FUNDS ENTR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176602' extends '332561' salience 2830

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3933000", pdtCode in ("012200", "004000", "004300", "004400"), cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("TERM-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("HEDGED PART FUND ENT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176605' extends '332561' salience 2820

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode in ("004200", "014000", "028000"), cgpCode in ("B0034", "B0035"))
        
    then
        $gda.setIlaapCat1("CASH AND CASH BALANCES CENTRAL BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD LOANS AND ADVANCES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176617' extends '332561' salience 2810

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0007000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FX SPOT (ASSETS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176634' extends '332561' salience 2800

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0025000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("IT TB CLD IRO SEC TR-DT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176638' extends '332561' salience 2790

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", rteCode == "010", cgpCode in ("P0039", "P0045"))
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD LOANS AND ADVANCES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176676' extends '332561' salience 2780

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3291000", rteCode == "010", cgpCode in ("00017", "00018", "00019"))
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("DEBT SECURITIES (HTM) OWN ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176684' extends '332561' salience 2770

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3331000", rteCode != "010", cgpCode == "00017")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES BOUGHT - UNSECURED");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FVO SECURITIES - OWN ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176714' extends '332561' salience 2760

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4412000", rteCode == "010", cgpCode == "00017")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SECURITIES (AMORT COST) OWN ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176717' extends '332561' salience 2750

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4564000", rteCode == "010", cgpCode in ("00017", "00018", "00019"))
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SECURITIES (AMORT COST) OWN ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176720' extends '332561' salience 2740

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4565000", rteCode == "010", cgpCode in ("00017", "00018", "00019"))
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SECURITIES (AMORT COST) OWN ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176762' extends '332561' salience 2730

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode in ("014000", "027100", "028000", "004200"), cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("SIGHT-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("NTRD FUNDS ENTRUSTED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176789' extends '332561' salience 2720

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1425000", pdtCode in ("012200", "004000", "004300", "004400"), cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("TERM-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("TRD FUNDS ENTRUSTED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176809' extends '332561' salience 2710

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3334000", pdtCode in ("014000", "027100", "028000", "004200"), cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("SIGHT-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("VALUE ADJ HEDGED PART FUNDS ENTR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176814' extends '332561' salience 2700

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3343000", pdtCode in ("014000", "027100", "028000", "004200"), cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("SIGHT-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("FVO FUNDS ENTR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176834' extends '332561' salience 2690

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3933000", pdtCode in ("014000", "027100", "028000", "004200"), cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("SIGHT-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("HEDGED PART FUND ENT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187006' extends '332561' salience 2680

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "027800", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD LOANS AND ADVANCES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187030' extends '332561' salience 2670

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8350000", pdtCode == "009400", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("MORTGAGES");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CUMM CH FV DUE TO CR RISK LOAN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187031' extends '332561' salience 2660

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8350000", pdtCode == "013600", cgpCode != "P0049")
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CUMM CH FV DUE TO CR RISK LOAN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187032' extends '332561' salience 2650

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8350000", pdtCode == "013600", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("OTHER - RETAIL ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CUMM CH FV DUE TO CR RISK LOAN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187033' extends '332561' salience 2640

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8350000", pdtCode == "027800")
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CUMM CH FV DUE TO CR RISK LOAN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187034' extends '332561' salience 2630

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8350000", pdtCode == "027900")
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CUMM CH FV DUE TO CR RISK LOAN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187036' extends '332561' salience 2620

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0237000", pdtCode == "030300", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY LIABILITIES");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("RMBS-PRIME NON US");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187042' extends '332561' salience 2610

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0237000", pdtCode == "007300", rteCode == "120")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("BONDS LONG (EXCL CDS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187043' extends '332561' salience 2600

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "014100", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("GUARANTEES CREDIT SUBSTITUTE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187044' extends '332561' salience 2590

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "014100", rteCode == "010")
        
    then
        $gda.setIlaapCat1("IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("GUARANTEES CREDIT SUBSTITUTE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187045' extends '332561' salience 2580

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "014200", rteCode == "010")
        
    then
        $gda.setIlaapCat1("IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("GUARANTEES NON CRED.SUBSTITUTE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187046' extends '332561' salience 2570

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "014200", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("GUARANTEES NON CRED.SUBSTITUTE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187047' extends '332561' salience 2560

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "014300", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("LETTER OF INTENT-OR MAT =< 1YR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187049' extends '332561' salience 2550

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "014400", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("NOTE ISS.FAC.,NIF/REV.UW.FAC.");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187050' extends '332561' salience 2540

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "014500", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("LETTER OF INTENT-OR MAT > 1 YR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187051' extends '332561' salience 2530

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "014500", rteCode == "010")
        
    then
        $gda.setIlaapCat1("IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("LETTER OF INTENT-OR MAT > 1 YR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187052' extends '332561' salience 2520

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "014800", rteCode == "010")
        
    then
        $gda.setIlaapCat1("IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("CREDIT FACILITIES, REVOCABLE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187053' extends '332561' salience 2510

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "014800", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("CREDIT FACILITIES, REVOCABLE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187054' extends '332561' salience 2500

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "014900", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("LETTER OF CREDIT NOT SELF LIQ.");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187055' extends '332561' salience 2490

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "014900", rteCode == "010")
        
    then
        $gda.setIlaapCat1("IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("LETTER OF CREDIT NOT SELF LIQ.");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187056' extends '332561' salience 2480

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "015000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("LETTER OF CREDIT SHIPM ACT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187057' extends '332561' salience 2470

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "015000", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("LETTER OF CREDIT SHIPM ACT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187058' extends '332561' salience 2460

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "015100", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("ACCEPTED BILLS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187059' extends '332561' salience 2450

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "015500", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("ACCEPTANCE CREDIT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187060' extends '332561' salience 2440

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "015500", rteCode == "010")
        
    then
        $gda.setIlaapCat1("IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("ACCEPTANCE CREDIT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187061' extends '332561' salience 2430

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "026900", rteCode == "010")
        
    then
        $gda.setIlaapCat1("IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("CREDIT FAC, IRREV-OR MAT=< 1YR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187062' extends '332561' salience 2420

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "026900", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("CREDIT FAC, IRREV-OR MAT=< 1YR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187063' extends '332561' salience 2410

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "027000", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("CREDIT FAC, IRREV-OR MAT > 1YR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187064' extends '332561' salience 2400

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "027000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("CREDIT FAC, IRREV-OR MAT > 1YR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187065' extends '332561' salience 2390

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0334000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("CREDIT EQUIVALENT DERIVATIVES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187066' extends '332561' salience 2380

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0334000", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("CREDIT EQUIVALENT DERIVATIVES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187067' extends '332561' salience 2370

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0593000", pdtCode == "014600", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("FORWARD ASSET PURCHASES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187068' extends '332561' salience 2360

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0593000", pdtCode == "014600", rteCode == "010")
        
    then
        $gda.setIlaapCat1("IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("FORWARD ASSET PURCHASES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187069' extends '332561' salience 2350

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0593000", pdtCode == "014700", rteCode == "010")
        
    then
        $gda.setIlaapCat1("IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("FORWARD FORWARD CONTRACTS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187070' extends '332561' salience 2340

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0593000", pdtCode == "014700", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("FORWARD FORWARD CONTRACTS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187071' extends '332561' salience 2330

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0594000", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("CONT LIAB IRO INV LAND&BUILD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187073' extends '332561' salience 2320

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0595000", pdtCode == "014200", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("GUARANTEES NON CRED.SUBSTITUTE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187074' extends '332561' salience 2310

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0595000", pdtCode == "014400", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("NOTE ISS.FAC.,NIF/REV.UW.FAC.");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187075' extends '332561' salience 2300

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0595000", pdtCode == "014800", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("CREDIT FACILITIES, REVOCABLE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187076' extends '332561' salience 2290

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0595000", pdtCode == "026900", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("CREDIT FAC, IRREV-OR MAT=< 1YR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187077' extends '332561' salience 2280

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0595000", pdtCode == "027000", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("CREDIT FAC, IRREV-OR MAT > 1YR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187078' extends '332561' salience 2270

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0597000", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("CP RISK IRO REPO & SEC LEND TR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187079' extends '332561' salience 2260

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0597000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("CP RISK IRO REPO & SEC LEND TR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187080' extends '332561' salience 2250

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0607000", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("MANAGED ASS, ADV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187081' extends '332561' salience 2240

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0608000", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("MANAGED ASS,DISCR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187082' extends '332561' salience 2230

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0609000", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("PAYMENT COMMITM  IRO PART INT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187083' extends '332561' salience 2220

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0610000", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("RECOURSE COMMITMENTS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187084' extends '332561' salience 2210

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0611000", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("SPOT CONTRACTS - BUY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187085' extends '332561' salience 2200

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0612000", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("SPOT CONTRACTS - SELL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1342783' extends '332561' salience 2190

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3943000", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("CONSUMER LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("LOAN LOSS PROVISION");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1364499' extends '332561' salience 2180

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "031400", cgpCode matches "G.*")
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FACTORING LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1364500' extends '332561' salience 2170

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "031400", cgpCode in ("B0035", "B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("LOANS TO / DEPOSITS AT BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FACTORING LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1364501' extends '332561' salience 2160

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "031400", cgpCode in ("P0039", "P0045"))
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FACTORING LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1364505' extends '332561' salience 2150

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4412000", rteCode != "010", cgpCode == "00017")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES BOUGHT - UNSECURED");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SECURITIES (AMORT COST) OWN ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1364509' extends '332561' salience 2140

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1425000", pdtCode in ("014000", "027100", "028000", "004200"), cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("SIGHT-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("TRD FUNDS ENTRUSTED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1364513' extends '332561' salience 2130

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3334000", pdtCode == "027800", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("REPO");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("REPO2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1468236' extends '332561' salience 2120

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0017000", pdtCode == "029000", cgpCode == "00017")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES BOUGHT - SECURED");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("COVERED BONDS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1468237' extends '332561' salience 2110

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0596000", pdtCode == "031300", rteCode != "010")
        
    then
        $gda.setIlaapCat1("NON-IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("CREDIT CARDS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1487160' extends '332561' salience 2100

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0046000", cgpCode == "00017")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES BOUGHT - UNSECURED");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("LOAN LOSS PROVISION");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1582359' extends '332561' salience 2090

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0045000", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("CONSUMER LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("LOAN LOSS PROVISION");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1584682' extends '332561' salience 2080

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode in ("004300", "004400", "012200", "012700", "031300"), cgpCode == "B0036")
        
    then
        $gda.setIlaapCat1("LOANS TO / DEPOSITS AT BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD LOANS AND ADVANCES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1584691' extends '332561' salience 2070

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000", pdtCode in ("012200", "012700", "014000"), cgpCode == "B0034")
        
    then
        $gda.setIlaapCat1("CASH AND CASH BALANCES CENTRAL BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FVO LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1584692' extends '332561' salience 2060

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", pdtCode in ("004300", "004400", "012200", "012700"), cgpCode == "B0034")
        
    then
        $gda.setIlaapCat1("LOANS TO / DEPOSITS AT BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("HEDGE PART LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1584699' extends '332561' salience 2050

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", pdtCode == "014000", cgpCode == "B0035")
        
    then
        $gda.setIlaapCat1("CASH AND CASH BALANCES CENTRAL BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("HEDGE PART LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1584701' extends '332561' salience 2040

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", pdtCode in ("004300", "004400", "012200", "012700"), cgpCode == "B0034")
        
    then
        $gda.setIlaapCat1("LOANS TO / DEPOSITS AT BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("VALUE ADJ HEDGED PART LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1584702' extends '332561' salience 2030

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", pdtCode == "014000", cgpCode == "B0035")
        
    then
        $gda.setIlaapCat1("CASH AND CASH BALANCES CENTRAL BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("VALUE ADJ HEDGED PART LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1584794' extends '332561' salience 2020

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8350000", pdtCode in ("012200", "012700", "014000"), cgpCode == "B0034")
        
    then
        $gda.setIlaapCat1("LOANS TO / DEPOSITS AT BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CUMM CH FV DUE TO CR RISK LOAN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1614308' extends '332561' salience 2010

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "031500", cgpCode in ("B0034", "B0035", "B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("LOANS TO / DEPOSITS AT BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CASH COLL IRO DERIVATIVES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1614324' extends '332561' salience 2000

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "031500", cgpCode matches "G.*")
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CASH COLL IRO DERIVATIVES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1614748' extends '332561' salience 1990

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "031500", cgpCode in ("P0039", "P0045"))
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CASH COLL IRO DERIVATIVES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1614749' extends '332561' salience 1980

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0057000", pdtCode == "031500", cgpCode in ("P0039", "P0045"))
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CASH COLL IRO DERIVATIVES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1614750' extends '332561' salience 1970

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0057000", pdtCode == "031500", cgpCode in ("B0034", "B0035", "B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("LOANS TO / DEPOSITS AT BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CASH COLL IRO DERIVATIVES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1614751' extends '332561' salience 1960

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "031500", cgpCode in ("P0039", "P0045"))
        
    then
        $gda.setIlaapCat1("CORPORATE DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("CASH COLL IRO DERIVATIVES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1614752' extends '332561' salience 1950

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "031500", cgpCode in ("B0034", "B0035"))
        
    then
        $gda.setIlaapCat1("CENTRAL BANK DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("CASH COLL IRO DERIVATIVES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1614753' extends '332561' salience 1940

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "031500", cgpCode in ("B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("BANK DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("CASH COLL IRO DERIVATIVES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1614754' extends '332561' salience 1930

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2569000", pdtCode == "027100", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("SIGHT-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1614759' extends '332561' salience 1920

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2569000", pdtCode in ("004000", "027100", "004300", "004400"), cgpCode in ("G008", "G009", "P0039", "P0045"))
        
    then
        $gda.setIlaapCat1("CORPORATE DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("ACCRUED INTEREST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1615992' extends '332561' salience 1910

    when
        
        GrlDetAmounts(this == $gda, actCode == "B0595000", pdtCode == "014100", cpyBeyNumber matches "U.*")
        
    then
        $gda.setIlaapCat1("IC OFF BALANCE");
        $gda.setIlaapCat3("OFF BALANCE");
        $gda.setIlaapCat2("GUARANTEES CREDIT SUBSTITUTE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1615995' extends '332561' salience 1900

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "031500", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("TERM-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("CASH COLL IRO DERIVATIVES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1649285' extends '332561' salience 1890

    when
        
        GrlDetAmounts(this == $gda, actCode == "A7985000", pdtCode == "007300", cgpCode in ("00004", "00005", "00007"))
        
    then
        $gda.setIlaapCat1("INVESTMENT PORTFOLIO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SECURITIES (AMORT COST)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1678557' extends '332561' salience 1880

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3934000", pdtCode == "002900", rteCode in ("205", "206"))
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("VALUE ADJ HEDGED PART FUNDS ENTR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1678558' extends '332561' salience 1870

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3934000", pdtCode == "005900", rteCode in ("205", "206"))
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("BONDS SHORT (EXCL CDS AND CP)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1678559' extends '332561' salience 1860

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3934000", pdtCode == "006100", rteCode in ("205", "206"))
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES - UNSECURED");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("FVO DEBT SECURITIES IN ISSUE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1690819' extends '332561' salience 1850

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "015000", cgpCode == "P0045")
        
    then
        $gda.setIlaapCat1("CORPORATE LOANS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("LETTER OF CREDIT SHIPM ACT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1690820' extends '332561' salience 1840

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "015000", cgpCode == "P0045")
        
    then
        $gda.setIlaapCat1("CORPORATE DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("LETTER OF CREDIT SHIPM ACT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1690823' extends '332561' salience 1830

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8939000", pdtCode == "009400", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("MORTGAGES");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("OTHER ASSETS2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1697904' extends '332561' salience 1820

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "031700")
        
    then
        $gda.setIlaapCat1("TERM-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("NTRD FUNDS ENTRUSTED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1697905' extends '332561' salience 1810

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3343000", pdtCode == "031700", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("TERM-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("NTRD FUNDS ENTRUSTED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1697906' extends '332561' salience 1800

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3933000", pdtCode == "031700", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("TERM-DEPOSITS (SAVINGS)");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("NTRD FUNDS ENTRUSTED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1701787' extends '332561' salience 1790

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "013600")
        
    then
        $gda.setIlaapCat1("OTHER - WHOLESALE ASSETS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("FINANCIAL LEASE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1705513' extends '332561' salience 1780

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000", pdtCode in ("004300", "004400"), cgpCode == "B0034")
        
    then
        $gda.setIlaapCat1("CASH AND CASH BALANCES CENTRAL BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD LOANS AND ADVANCES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1706449' extends '332561' salience 1770

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode in ("004300", "004400", "012200", "012700", "031300"), cgpCode in ("B0034", "B0035"))
        
    then
        $gda.setIlaapCat1("CASH AND CASH BALANCES CENTRAL BANKS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD LOANS AND ADVANCES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176544' extends '332561' salience 1760

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "013600", rteCode == "010", cgpCode in ("B0035", "B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FINANCIAL LEASE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176546' extends '332561' salience 1750

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "013600", rteCode == "010", cgpCode in ("P0039", "P0045"))
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FINANCIAL LEASE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176556' extends '332561' salience 1740

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "015200", rteCode == "010", cgpCode in ("B0035", "B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD LOANS AND ADVANCES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176557' extends '332561' salience 1730

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "027800", rteCode == "010", cgpCode in ("B0035", "B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("RREPO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176559' extends '332561' salience 1720

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "027800", rteCode == "010", cgpCode in ("P0039", "P0045"))
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("RREPO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176561' extends '332561' salience 1710

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "027800", rteCode != "010")
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("RREPO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176575' extends '332561' salience 1700

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "027900", rteCode == "010", cgpCode in ("B0035", "B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SBL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176577' extends '332561' salience 1690

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "027900", rteCode == "010", cgpCode in ("P0039", "P0045"))
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SBL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176579' extends '332561' salience 1680

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "027900", rteCode != "010")
        
    then
        $gda.setIlaapCat1("REVERSE REPO");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SBL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176592' extends '332561' salience 1670

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "028000", rteCode == "010", cgpCode in ("B0035", "B0036", "B0037"))
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD LOANS AND ADVANCES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176604' extends '332561' salience 1660

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000", pdtCode in ("012200", "004300", "004400", "028000"), rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FVO LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176625' extends '332561' salience 1650

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0017000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("DEBT SECURITIES (AFS) OWN ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176636' extends '332561' salience 1640

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode not in ("013600", "015200", "027800", "027900", "028000"), rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("NTRD LOANS AND ADVANCES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1187035' extends '332561' salience 1630

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8350000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("CUMM CH FV DUE TO CR RISK LOAN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1248078' extends '332561' salience 1620

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0058000", pdtCode matches "03.*", rteCode == "070", cgpCode != "00017")
        
    then
        $gda.setIlaapCat1("OTHER - WHOLESALE ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("TRD DEBT SECURITIES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1475074' extends '332561' salience 1610

    when
        
        GrlDetAmounts(this == $gda, actCode matches "A.*", pdtCode != "004700", rteCode != "010", cgpCode == "00017")
        
    then
        $gda.setIlaapCat1("WHOLESALE LIABILITIES BOUGHT - UNSECURED");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("TRD - DEBT SECURITES OWN ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1608118' extends '332561' salience 1600

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "012700", rteCode == "163", cgpCode in ("B0034", "B0035"))
        
    then
        $gda.setIlaapCat1("CENTRAL BANK DEPOSITS");
        $gda.setIlaapCat3("LIABILITIES");
        $gda.setIlaapCat2("NTRD FUNDS ENTRUSTED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1690822' extends '332561' salience 1590

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8939000", pdtCode == "009400", rteCode == "011", cgpCode == "P0049")
        
    then
        $gda.setIlaapCat1("MORTGAGES");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FVO LOANS -  MORTGAGES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1701780' extends '332561' salience 1580

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8294000", pdtCode in ("007300", "029000", "030300", "031100"), rteCode == "010", cgpCode == "00017")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SECURITIES (AMORT COST) OWN ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1701781' extends '332561' salience 1570

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8294000", pdtCode in ("007300", "030300", "031100"), rteCode == "010", cgpCode != "00017")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("OTHER ABS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1701783' extends '332561' salience 1560

    when
        
        GrlDetAmounts(this == $gda, actCode == "A9018000", pdtCode in ("005100", "005900", "006100", "007300", "029000", "031100"), rteCode == "010", cgpCode == "00017")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("SECURITIES (AMORT COST) OWN ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1701784' extends '332561' salience 1550

    when
        
        GrlDetAmounts(this == $gda, actCode == "A9018000", pdtCode == "030300", rteCode == "010", cgpCode == "00017")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("OTHER ABS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end

rule '1176682' extends '332561' salience 1540

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000", rteCode == "010")
        
    then
        $gda.setIlaapCat1("INTERCOMPANY ASSETS");
        $gda.setIlaapCat3("ASSETS");
        $gda.setIlaapCat2("FVO LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3692");
        
end


