package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '333550'
	when
		$gda : GrlDetAmounts()
	then
        
end





rule '1475016' extends '333550' salience 6540

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxt21("RETAIL_IND_ORG:" + retailInd + " SME_IND_ORG:" + smeInd );
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4318");
        
end


