package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '337822'
	when
		$gda : GrlDetAmounts(1 == 1)
	then
        
end





rule '1907651' extends '337822' salience 540

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setDgsLcrInd("N");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"7852");
        
end


