package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '333599'
	when
		$gda : GrlDetAmounts(pdtCode == "014005")
	then
        
end





rule '1489917' extends '333599' salience 10

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCgpCode("P0049");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4362");
        
end


