package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;


dialect  "mvel"


rule '330558'
	when
		$gda : GrlDetAmounts(( ( hpePdtType in ( "CAPITAL AND RESERVE" , "CASH" , "CUST ACCT" , "FIXED ASSET" , "MINORITY INTEREST" , "NOSTRO" , "OTHER NON PROD PL ITEM" , "OTHER PAYABLES" , "OTHER RECEIVABLES" , "PART" , "PROV" , "TAXES" ) && intInd == "N" && contingInd == "N" && hacAmtCl == "01" && hscAcctSubcl not matches "30.*" && hscAcctSubcl not matches "31.*" && scyActCode != null && scyActCode not in ( "A0003000" , "A0031000" , "L3348000" ) ) || ( scyActCode == "L2569000" && hscAcctSubcl != null ) ))
	then
end


rule '892758' extends '330558' salience 16230

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setScyPdtCode(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892727' extends '330558' salience 16220

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2812")
        
    then
        $gda.setScyPdtCode("015200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892728' extends '330558' salience 16210

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2813")
        
    then
        $gda.setScyPdtCode("025600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892625' extends '330558' salience 16200

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2102")
        
    then
        $gda.setScyPdtCode("012700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892627' extends '330558' salience 16190

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "2103")
        
    then
        $gda.setScyPdtCode("012700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892630' extends '330558' salience 16180

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2105")
        
    then
        $gda.setScyPdtCode("012700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892632' extends '330558' salience 16170

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2106")
        
    then
        $gda.setScyPdtCode("012700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892634' extends '330558' salience 16160

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2107")
        
    then
        $gda.setScyPdtCode("012700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892640' extends '330558' salience 16150

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2110")
        
    then
        $gda.setScyPdtCode("012700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892642' extends '330558' salience 16140

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2111")
        
    then
        $gda.setScyPdtCode("012700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892645' extends '330558' salience 16130

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2112")
        
    then
        $gda.setScyPdtCode("012700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892648' extends '330558' salience 16120

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2117")
        
    then
        $gda.setScyPdtCode("012700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892650' extends '330558' salience 16110

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2118")
        
    then
        $gda.setScyPdtCode("012700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892652' extends '330558' salience 16100

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2119")
        
    then
        $gda.setScyPdtCode("012700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892653' extends '330558' salience 16090

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2201")
        
    then
        $gda.setScyPdtCode("004200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892654' extends '330558' salience 16080

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2202")
        
    then
        $gda.setScyPdtCode("004400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892656' extends '330558' salience 16070

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2203")
        
    then
        $gda.setScyPdtCode("004400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1362684' extends '330558' salience 16060

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2512")
        
    then
        $gda.setScyPdtCode("031300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1740961' extends '330558' salience 16050

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "1107")
        
    then
        $gda.setScyPdtCode("004800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1740960' extends '330558' salience 16040

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "1106")
        
    then
        $gda.setScyPdtCode("004700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1156392' extends '330558' salience 16030

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2205")
        
    then
        $gda.setScyPdtCode("004200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1156393' extends '330558' salience 16020

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2206")
        
    then
        $gda.setScyPdtCode("014000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1706968' extends '330558' salience 16010

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "2820")
        
    then
        $gda.setScyPdtCode("024600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1706969' extends '330558' salience 16000

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "2821")
        
    then
        $gda.setScyPdtCode("024700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1706970' extends '330558' salience 15990

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "2822")
        
    then
        $gda.setScyPdtCode("024800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1706971' extends '330558' salience 15980

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "2823")
        
    then
        $gda.setScyPdtCode("024900");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1706972' extends '330558' salience 15970

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "2824")
        
    then
        $gda.setScyPdtCode("025000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1706973' extends '330558' salience 15960

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "2825")
        
    then
        $gda.setScyPdtCode("025100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1706974' extends '330558' salience 15950

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "2826")
        
    then
        $gda.setScyPdtCode("025200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1706975' extends '330558' salience 15940

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "2827")
        
    then
        $gda.setScyPdtCode("025300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1706976' extends '330558' salience 15930

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "2828")
        
    then
        $gda.setScyPdtCode("025400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1173865' extends '330558' salience 15920

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2727")
        
    then
        $gda.setScyPdtCode("014000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '993584' extends '330558' salience 15910

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "2813")
        
    then
        $gda.setScyPdtCode("025600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1706977' extends '330558' salience 15900

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "2829")
        
    then
        $gda.setScyPdtCode("025500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '908991' extends '330558' salience 15890

    when
        
        GrlDetAmounts(this == $gda, hssSecuProdSubcl in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"))
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1035203' extends '330558' salience 15880

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "1104")
        
    then
        $gda.setScyPdtCode("004700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1035204' extends '330558' salience 15870

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "1105")
        
    then
        $gda.setScyPdtCode("004800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1769747' extends '330558' salience 15860

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2814")
        
    then
        $gda.setScyPdtCode("015200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1614070' extends '330558' salience 15850

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "2718")
        
    then
        $gda.setScyPdtCode("004000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1614071' extends '330558' salience 15840

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl in ("2724", "2725"))
        
    then
        $gda.setScyPdtCode("027100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '894266' extends '330558' salience 15830

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2503")
        
    then
        $gda.setScyPdtCode("014000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892704' extends '330558' salience 15820

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2501")
        
    then
        $gda.setScyPdtCode("014000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892711' extends '330558' salience 15810

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2506")
        
    then
        $gda.setScyPdtCode("014000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892712' extends '330558' salience 15800

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl in ("2507", "2510"))
        
    then
        $gda.setScyPdtCode("004000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892713' extends '330558' salience 15790

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl in ("2508", "2511"))
        
    then
        $gda.setScyPdtCode("004000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892714' extends '330558' salience 15780

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "2602")
        
    then
        $gda.setScyPdtCode("014000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892716' extends '330558' salience 15770

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2701")
        
    then
        $gda.setScyPdtCode("014000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892717' extends '330558' salience 15760

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "2704")
        
    then
        $gda.setScyPdtCode("014000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892722' extends '330558' salience 15750

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2807")
        
    then
        $gda.setScyPdtCode("014100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892723' extends '330558' salience 15740

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2808")
        
    then
        $gda.setScyPdtCode("014200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892724' extends '330558' salience 15730

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2809")
        
    then
        $gda.setScyPdtCode("014900");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892725' extends '330558' salience 15720

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2810")
        
    then
        $gda.setScyPdtCode("015000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892726' extends '330558' salience 15710

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2811")
        
    then
        $gda.setScyPdtCode("015500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1150623' extends '330558' salience 15700
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2816", getCase0_1150623() == "more_then_a_year")
        
    then
        $gda.setScyPdtCode("014500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1150645' extends '330558' salience 15690
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2816", getCase0_1150623() == "within_one_year")
        
    then
        $gda.setScyPdtCode("014300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892706' extends '330558' salience 15680

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2502")
        
    then
        $gda.setScyPdtCode("014000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892620' extends '330558' salience 15670

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "1110", hreRelTypeCtpy not in ("INDV", "ISTF", "IIPB"))
        
    then
        $gda.setScyPdtCode("014000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892621' extends '330558' salience 15660

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "1111", hreRelTypeCtpy not in ("INDV", "ISTF", "IIPB"))
        
    then
        $gda.setScyPdtCode("004700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892623' extends '330558' salience 15650

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2101", hreRelTypeCtpy not in ("INDV", "ISTF", "IIPB"))
        
    then
        $gda.setScyPdtCode("012700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892624' extends '330558' salience 15640
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2102", getCase0_1029992() == "long_term")
        
    then
        $gda.setScyPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892626' extends '330558' salience 15630
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl == "2103", getCase0_1029992() == "long_term")
        
    then
        $gda.setScyPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892628' extends '330558' salience 15620

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2104", hreRelTypeCtpy not in ("INDV", "ISTF", "IIPB"))
        
    then
        $gda.setScyPdtCode("013600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892629' extends '330558' salience 15610
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2105", getCase0_1029992() == "long_term")
        
    then
        $gda.setScyPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892631' extends '330558' salience 15600
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2106", getCase0_1029992() == "long_term")
        
    then
        $gda.setScyPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892633' extends '330558' salience 15590
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2107", getCase0_1029992() == "long_term")
        
    then
        $gda.setScyPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892636' extends '330558' salience 15580

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2108", hreRelTypeCtpy not in ("INDV", "ISTF", "IIPB"))
        
    then
        $gda.setScyPdtCode("012700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892638' extends '330558' salience 15570

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2109", hreRelTypeCtpy not in ("INDV", "ISTF", "IIPB"))
        
    then
        $gda.setScyPdtCode("012700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892639' extends '330558' salience 15560
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2110", getCase0_1029992() == "long_term")
        
    then
        $gda.setScyPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892641' extends '330558' salience 15550
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2111", getCase0_1029992() == "long_term")
        
    then
        $gda.setScyPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892643' extends '330558' salience 15540

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2112", hreRelTypeCtpy in ("INDV", "IIPB"))
        
    then
        $gda.setScyPdtCode("009400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892644' extends '330558' salience 15530
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2112", getCase0_1029992() == "long_term")
        
    then
        $gda.setScyPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892646' extends '330558' salience 15520

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2113", hreRelTypeCtpy == "ISTF")
        
    then
        $gda.setScyPdtCode("009400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892647' extends '330558' salience 15510
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2117", getCase0_1029992() == "long_term")
        
    then
        $gda.setScyPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892649' extends '330558' salience 15500
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2118", getCase0_1029992() == "long_term")
        
    then
        $gda.setScyPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892651' extends '330558' salience 15490
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2119", getCase0_1029992() == "long_term")
        
    then
        $gda.setScyPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892655' extends '330558' salience 15480
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2202", getCase0_1029992() == "long_term")
        
    then
        $gda.setScyPdtCode("004300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892657' extends '330558' salience 15470
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2203", getCase0_1029992() == "long_term")
        
    then
        $gda.setScyPdtCode("004300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892616' extends '330558' salience 15460

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hreRelTypeCtpy in ("INDV", "ISTF", "IIPB"), hceCovType == "4009")
        
    then
        $gda.setScyPdtCode("008200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1101809' extends '330558' salience 15450

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "1108", icInd == "N")
        
    then
        $gda.setScyPdtCode("004700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1706861' extends '330558' salience 15440

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2201", collInd == "Y", hfeFacType == "IPC")
        
    then
        $gda.setScyPdtCode("031800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1706862' extends '330558' salience 15430

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2205", collInd == "Y", hfeFacType == "IPC")
        
    then
        $gda.setScyPdtCode("031800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892705' extends '330558' salience 15420

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl == "2501", hreRelTypeCtpy in ("INDV", "ISTF", "IIPB"), hceCovType in ("1403", "1404", "1416", "1417"))
        
    then
        $gda.setScyPdtCode("009400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892708' extends '330558' salience 15410

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", hscAcctSubcl in ("2504", "2509"), icInd == "N")
        
    then
        $gda.setScyPdtCode("027100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892709' extends '330558' salience 15400

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl in ("2504", "2509"), hreRelTypeCtpy not in ("INDV", "ISTF", "IIPB"), icInd == "Y")
        
    then
        $gda.setScyPdtCode("014000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1621260' extends '330558' salience 15390

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2205", collInd == "Y", hfeFacType != "IPC")
        
    then
        $gda.setScyPdtCode("031500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892618' extends '330558' salience 15380

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hscAcctSubcl matches "21.*", hreRelTypeCtpy not in ("INDV", "ISTF", "IIPB"), hceCovType matches "14.*")
        
    then
        $gda.setScyPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892622' extends '330558' salience 15370
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2101", hreRelTypeCtpy not in ("INDV", "ISTF", "IIPB"), getCase0_1029992() == "long_term")
        
    then
        $gda.setScyPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892635' extends '330558' salience 15360
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2108", hreRelTypeCtpy not in ("INDV", "ISTF", "IIPB"), getCase0_1029992() == "long_term")
        
    then
        $gda.setScyPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892637' extends '330558' salience 15350
no-loop
    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2109", hreRelTypeCtpy not in ("INDV", "ISTF", "IIPB"), getCase0_1029992() == "long_term")
        
    then
        $gda.setScyPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '1621259' extends '330558' salience 15340

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2201", collInd == "Y", hfeFacType != "IPC")
        
    then
        $gda.setScyPdtCode("031500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end

rule '892710' extends '330558' salience 15330

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "2505", hreRelTypeCtpy == "BCEN", icInd == "N")
        
    then
        $gda.setScyPdtCode("014000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2354");
        
end


