package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;


dialect  "mvel"


rule '331946'
	when
		$gda : GrlDetAmounts(hpePdtType in ( "STOCK BOND" , "STOCK CD AND CP" , "STOCK CONV BOND" , "STOCK FLOATING RATE NOTE" , "STOCK MEDIUM TERM NOTE" , "STOCK SAVING CERT" , "STOCK SHARE" , "STOCK TREASURY PAPER" ) && intInd == "N" && scyActCode != null && contingInd == "N" && hacAmtCl in ( "01" , "05" , "12" ) && ( hreRelTypeIssuer in ( "ZABG" , "ZABS" , "ZAIN" , "ZCMB" , "ZCMG" , "ZMBG" , "ZMBS" , "ZMIN" , "ZRMB" , "ZSEC" ) || nvl(hreRelTypeIssuer, "") + nvl(custSeg, "") in ( "FAMTNBSEC" , "GAMTNBSEC" , "FAMTSECAM" , "GAMTSECAM" , "FAMTSECAS" , "GAMTSECAS" , "FAMTSECEU" , "GAMTSECEU" , "FGVONBSEC" , "FGVOSECAM" , "FGVOSECAS" , "FGVOSECEU" ) ))
	then
end


rule '1118046' extends '331946' salience 14470

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118053' extends '331946' salience 14460

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117985' extends '331946' salience 14450

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117995' extends '331946' salience 14440

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117996' extends '331946' salience 14430

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117979' extends '331946' salience 14420

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118123' extends '331946' salience 14410

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", hssSecuProdSubcl == "0285", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163652' extends '331946' salience 14400

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163653' extends '331946' salience 14390

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163667' extends '331946' salience 14380

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163668' extends '331946' salience 14370

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118045' extends '331946' salience 14360

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", hssSecuProdSubcl == "0280", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118049' extends '331946' salience 14350

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118051' extends '331946' salience 14340

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118060' extends '331946' salience 14330

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", hssSecuProdSubcl == "0220", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118067' extends '331946' salience 14320

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", hssSecuProdSubcl == "0230", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118081' extends '331946' salience 14310

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", hssSecuProdSubcl == "0240", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1676335' extends '331946' salience 14300

    when
        
        GrlDetAmounts(this == $gda, hssSecuProdSubcl == "0295")
        
    then
        $gda.setScyPdtCode("031600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118095' extends '331946' salience 14290

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", hssSecuProdSubcl == "0250", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118109' extends '331946' salience 14280

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", hssSecuProdSubcl == "0260", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117982' extends '331946' salience 14270

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("11", "12", "13"), htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117984' extends '331946' salience 14260

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("20", "21", "22"), htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117987' extends '331946' salience 14250

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), hssSecuProdSubcl == "0250", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117991' extends '331946' salience 14240

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), hssSecuProdSubcl == "0285", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117994' extends '331946' salience 14230

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), hssSecuProdSubcl == "0280", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117997' extends '331946' salience 14220

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), hssSecuProdSubcl == "0220", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117998' extends '331946' salience 14210

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), hssSecuProdSubcl == "0230", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118000' extends '331946' salience 14200

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), hssSecuProdSubcl == "0240", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118002' extends '331946' salience 14190

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), hssSecuProdSubcl == "0250", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118004' extends '331946' salience 14180

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), hssSecuProdSubcl == "0260", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118006' extends '331946' salience 14170

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), hssSecuProdSubcl == "0285", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117983' extends '331946' salience 14160

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("14", "15", "16", "17", "18", "19"), htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118032' extends '331946' salience 14150

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118039' extends '331946' salience 14140

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117971' extends '331946' salience 14130

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("1", "2", "3", "4"), htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117972' extends '331946' salience 14120

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), hssSecuProdSubcl == "0220", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117973' extends '331946' salience 14110

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), hssSecuProdSubcl == "0230", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117975' extends '331946' salience 14100

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), hssSecuProdSubcl == "0240", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117978' extends '331946' salience 14090

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), hssSecuProdSubcl == "0280", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117980' extends '331946' salience 14080

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("5", "6", "7"), htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117981' extends '331946' salience 14070

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("8", "9", "10"), htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117810' extends '331946' salience 14060

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117817' extends '331946' salience 14050

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117821' extends '331946' salience 14040

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117823' extends '331946' salience 14030

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117686' extends '331946' salience 14020

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117687' extends '331946' salience 14010

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117701' extends '331946' salience 14000

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117702' extends '331946' salience 13990

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117989' extends '331946' salience 13980

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), hssSecuProdSubcl == "0260", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117833' extends '331946' salience 13970

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117835' extends '331946' salience 13960

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117843' extends '331946' salience 13950

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117847' extends '331946' salience 13940

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117829' extends '331946' salience 13930

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117855' extends '331946' salience 13920

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117859' extends '331946' salience 13910

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117765' extends '331946' salience 13900

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", secuAssetCl == "PRIME", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117766' extends '331946' salience 13890

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", secuAssetCl == "PRIME", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117685' extends '331946' salience 13880

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117688' extends '331946' salience 13870

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117689' extends '331946' salience 13860

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117691' extends '331946' salience 13850

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117693' extends '331946' salience 13840

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117695' extends '331946' salience 13830

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117697' extends '331946' salience 13820

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117700' extends '331946' salience 13810

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0280", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117703' extends '331946' salience 13800

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0220", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117704' extends '331946' salience 13790

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0230", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117706' extends '331946' salience 13780

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0240", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117708' extends '331946' salience 13770

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0250", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117710' extends '331946' salience 13760

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0260", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117712' extends '331946' salience 13750

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0285", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117723' extends '331946' salience 13740

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", secuAssetCl == "PRIME", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117724' extends '331946' salience 13730

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", secuAssetCl == "PRIME", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118122' extends '331946' salience 13720

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163651' extends '331946' salience 13710

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163654' extends '331946' salience 13700

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163655' extends '331946' salience 13690

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163657' extends '331946' salience 13680

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163659' extends '331946' salience 13670

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163661' extends '331946' salience 13660

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163663' extends '331946' salience 13650

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163666' extends '331946' salience 13640

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0280", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163669' extends '331946' salience 13630

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0220", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163670' extends '331946' salience 13620

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0230", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163672' extends '331946' salience 13610

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0240", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163676' extends '331946' salience 13600

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0260", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163678' extends '331946' salience 13590

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0285", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118056' extends '331946' salience 13580

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0220", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118058' extends '331946' salience 13570

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0220", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118063' extends '331946' salience 13560

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0230", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118065' extends '331946' salience 13550

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0230", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118073' extends '331946' salience 13540

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0240", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118077' extends '331946' salience 13530

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0240", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118080' extends '331946' salience 13520

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117939' extends '331946' salience 13510

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", secuAssetCl == "ALT-A", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118087' extends '331946' salience 13500

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0250", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118091' extends '331946' salience 13490

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0250", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118094' extends '331946' salience 13480

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118101' extends '331946' salience 13470

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0260", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118105' extends '331946' salience 13460

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0260", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118113' extends '331946' salience 13450

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0285", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118117' extends '331946' salience 13440

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0285", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118108' extends '331946' salience 13430

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117986' extends '331946' salience 13420

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117988' extends '331946' salience 13410

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117990' extends '331946' salience 13400

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117992' extends '331946' salience 13390

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117993' extends '331946' salience 13380

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117999' extends '331946' salience 13370

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118001' extends '331946' salience 13360

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118003' extends '331946' salience 13350

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118005' extends '331946' salience 13340

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118031' extends '331946' salience 13330

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0280", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118038' extends '331946' salience 13320

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0280", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118043' extends '331946' salience 13310

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118044' extends '331946' salience 13300

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117940' extends '331946' salience 13290

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", secuAssetCl == "ALT-A", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117974' extends '331946' salience 13280

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117976' extends '331946' salience 13270

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117977' extends '331946' salience 13260

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117867' extends '331946' salience 13250

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163674' extends '331946' salience 13240

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0250", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117871' extends '331946' salience 13230

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117879' extends '331946' salience 13220

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117883' extends '331946' salience 13210

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117894' extends '331946' salience 13200

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", secuAssetCl == "SUBPRIME", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117895' extends '331946' salience 13190

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", secuAssetCl == "SUBPRIME", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117809' extends '331946' salience 13180

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117816' extends '331946' salience 13170

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117820' extends '331946' salience 13160

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", secuAssetCl == "ALT-A", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117822' extends '331946' salience 13150

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", secuAssetCl == "ALT-A", htyTradCat in ("01", "02"))
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117827' extends '331946' salience 13140

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117796' extends '331946' salience 13130

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0285", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117683' extends '331946' salience 13120

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117684' extends '331946' salience 13110

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117690' extends '331946' salience 13100

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117692' extends '331946' salience 13090

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117699' extends '331946' salience 13080

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117705' extends '331946' salience 13070

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117709' extends '331946' salience 13060

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117711' extends '331946' salience 13050

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117718' extends '331946' salience 13040

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117721' extends '331946' salience 13030

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117726' extends '331946' salience 13020

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117727' extends '331946' salience 13010

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117729' extends '331946' salience 13000

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117730' extends '331946' salience 12990

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117734' extends '331946' salience 12980

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117736' extends '331946' salience 12970

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117740' extends '331946' salience 12960

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117794' extends '331946' salience 12950

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0285", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117878' extends '331946' salience 12940

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117882' extends '331946' salience 12930

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117889' extends '331946' salience 12920

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117892' extends '331946' salience 12910

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117897' extends '331946' salience 12900

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117898' extends '331946' salience 12890

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117900' extends '331946' salience 12880

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117901' extends '331946' salience 12870

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117905' extends '331946' salience 12860

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117907' extends '331946' salience 12850

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117911' extends '331946' salience 12840

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117913' extends '331946' salience 12830

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117917' extends '331946' salience 12820

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117919' extends '331946' salience 12810

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117805' extends '331946' salience 12800

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117808' extends '331946' salience 12790

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117812' extends '331946' salience 12780

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117815' extends '331946' salience 12770

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117826' extends '331946' salience 12760

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117828' extends '331946' salience 12750

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117832' extends '331946' salience 12740

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117834' extends '331946' salience 12730

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117870' extends '331946' salience 12720

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117841' extends '331946' salience 12710

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117842' extends '331946' salience 12700

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117845' extends '331946' salience 12690

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117846' extends '331946' salience 12680

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117854' extends '331946' salience 12670

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117858' extends '331946' salience 12660

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117742' extends '331946' salience 12650

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117746' extends '331946' salience 12640

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117748' extends '331946' salience 12630

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117752' extends '331946' salience 12620

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117754' extends '331946' salience 12610

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117760' extends '331946' salience 12600

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0280", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117763' extends '331946' salience 12590

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0280", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117768' extends '331946' salience 12580

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0220", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117769' extends '331946' salience 12570

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0220", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117771' extends '331946' salience 12560

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0230", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117772' extends '331946' salience 12550

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0230", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117776' extends '331946' salience 12540

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0240", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117778' extends '331946' salience 12530

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0240", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117782' extends '331946' salience 12520

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0250", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117784' extends '331946' salience 12510

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0250", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117788' extends '331946' salience 12500

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0260", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117790' extends '331946' salience 12490

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0260", secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118090' extends '331946' salience 12480

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118100' extends '331946' salience 12470

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118104' extends '331946' salience 12460

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118116' extends '331946' salience 12450

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1184286' extends '331946' salience 12440

    when
        
        GrlDetAmounts(this == $gda, secuAssetCl == "CMBS")
        
    then
        $gda.setScyPdtCode("030800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117853' extends '331946' salience 12430

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117857' extends '331946' salience 12420

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117707' extends '331946' salience 12410

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117694' extends '331946' salience 12400

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118111' extends '331946' salience 12390

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117877' extends '331946' salience 12380

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117881' extends '331946' salience 12370

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117696' extends '331946' salience 12360

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118029' extends '331946' salience 12350

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118036' extends '331946' salience 12340

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117923' extends '331946' salience 12330

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117925' extends '331946' salience 12320

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117932' extends '331946' salience 12310

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0280", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117942' extends '331946' salience 12300

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0220", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117946' extends '331946' salience 12290

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0230", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117952' extends '331946' salience 12280

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0240", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117956' extends '331946' salience 12270

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0250", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117964' extends '331946' salience 12260

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0260", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117968' extends '331946' salience 12250

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0285", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117970' extends '331946' salience 12240

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0285", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118086' extends '331946' salience 12230

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117865' extends '331946' salience 12220

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117866' extends '331946' salience 12210

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117869' extends '331946' salience 12200

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163649' extends '331946' salience 12190

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163650' extends '331946' salience 12180

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163656' extends '331946' salience 12170

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163658' extends '331946' salience 12160

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163660' extends '331946' salience 12150

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163662' extends '331946' salience 12140

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163664' extends '331946' salience 12130

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163665' extends '331946' salience 12120

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163671' extends '331946' salience 12110

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163673' extends '331946' salience 12100

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163675' extends '331946' salience 12090

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1163677' extends '331946' salience 12080

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118072' extends '331946' salience 12070

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118076' extends '331946' salience 12060

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117936' extends '331946' salience 12050

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0280", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117943' extends '331946' salience 12040

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0220", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117945' extends '331946' salience 12030

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0230", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117950' extends '331946' salience 12020

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0240", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117958' extends '331946' salience 12010

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0250", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117962' extends '331946' salience 12000

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0260", secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117698' extends '331946' salience 11990

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118030' extends '331946' salience 11980

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1118037' extends '331946' salience 11970

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117807' extends '331946' salience 11960

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117814' extends '331946' salience 11950

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1184281' extends '331946' salience 11940

    when
        
        GrlDetAmounts(this == $gda, secuAssetCl == "CBO")
        
    then
        $gda.setScyPdtCode("030900");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1184282' extends '331946' salience 11930

    when
        
        GrlDetAmounts(this == $gda, secuAssetCl == "ABCP")
        
    then
        $gda.setScyPdtCode("031000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1184283' extends '331946' salience 11920

    when
        
        GrlDetAmounts(this == $gda, secuAssetCl == "OTHER")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1184284' extends '331946' salience 11910

    when
        
        GrlDetAmounts(this == $gda, ratingIng in ("1", "2", "3", "4"), secuAssetCl == "CMBS")
        
    then
        $gda.setScyPdtCode("030700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1184285' extends '331946' salience 11900

    when
        
        GrlDetAmounts(this == $gda, ratingIng == null, secuAssetCl == "CMBS")
        
    then
        $gda.setScyPdtCode("030800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117957' extends '331946' salience 11890

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117961' extends '331946' salience 11880

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117868' extends '331946' salience 11870

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117916' extends '331946' salience 11860

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117745' extends '331946' salience 11850

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117924' extends '331946' salience 11840

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117922' extends '331946' salience 11830

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117753' extends '331946' salience 11820

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117795' extends '331946' salience 11810

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1186251' extends '331946' salience 11800

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdIssuerRes != "US", secuAssetCl == "CMO")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1186252' extends '331946' salience 11790

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdIssuerRes == "US", secuAssetCl == "CMO")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117931' extends '331946' salience 11780

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117934' extends '331946' salience 11770

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117949' extends '331946' salience 11760

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117951' extends '331946' salience 11750

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117955' extends '331946' salience 11740

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117963' extends '331946' salience 11730

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117967' extends '331946' salience 11720

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117969' extends '331946' salience 11710

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117864' extends '331946' salience 11700

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117876' extends '331946' salience 11690

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1184280' extends '331946' salience 11680

    when
        
        GrlDetAmounts(this == $gda, secuAssetCl == "CLO")
        
    then
        $gda.setScyPdtCode("030900");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117793' extends '331946' salience 11670

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117716' extends '331946' salience 11660

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117717' extends '331946' salience 11650

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117733' extends '331946' salience 11640

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117735' extends '331946' salience 11630

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117739' extends '331946' salience 11620

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117887' extends '331946' salience 11610

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117811' extends '331946' salience 11600

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117761' extends '331946' salience 11590

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117719' extends '331946' salience 11580

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117935' extends '331946' salience 11570

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117888' extends '331946' salience 11560

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117762' extends '331946' salience 11550

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117720' extends '331946' salience 11540

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1184287' extends '331946' salience 11530

    when
        
        GrlDetAmounts(this == $gda, ratingIng in ("5", "6", "7"), secuAssetCl == "CMBS")
        
    then
        $gda.setScyPdtCode("030700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117930' extends '331946' salience 11520

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1184279' extends '331946' salience 11510

    when
        
        GrlDetAmounts(this == $gda, secuAssetCl == "CDO")
        
    then
        $gda.setScyPdtCode("030900");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117890' extends '331946' salience 11500

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117891' extends '331946' salience 11490

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117904' extends '331946' salience 11480

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117906' extends '331946' salience 11470

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117910' extends '331946' salience 11460

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117912' extends '331946' salience 11450

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117918' extends '331946' salience 11440

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117804' extends '331946' salience 11430

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117806' extends '331946' salience 11420

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117813' extends '331946' salience 11410

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117840' extends '331946' salience 11400

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117844' extends '331946' salience 11390

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117852' extends '331946' salience 11380

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117856' extends '331946' salience 11370

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117741' extends '331946' salience 11360

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117747' extends '331946' salience 11350

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117751' extends '331946' salience 11340

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117758' extends '331946' salience 11330

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117759' extends '331946' salience 11320

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117775' extends '331946' salience 11310

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117777' extends '331946' salience 11300

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117781' extends '331946' salience 11290

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117783' extends '331946' salience 11280

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117787' extends '331946' salience 11270

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117789' extends '331946' salience 11260

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end

rule '1117880' extends '331946' salience 11250

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3327");
        
end


