package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;


dialect  "mvel"


rule '332522'
	when
		$gda : GrlDetAmounts(lseHlyRelId in ( "9704" , "9705" ) && ownUse01 != null && hacAmtCl in ( "01" , "03" , "04" , "05" ))
	then
end


rule '1175728' extends '332522' salience 11240

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "005900")
        
    then
        $gda.setScyPdtCode("005900");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3678");
        
end

rule '1897987' extends '332522' salience 11230

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "012200")
        
    then
        $gda.setScyPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3678");
        
end

rule '1175730' extends '332522' salience 11220

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "007300")
        
    then
        $gda.setScyPdtCode("007300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3678");
        
end

rule '1175731' extends '332522' salience 11210

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "029000")
        
    then
        $gda.setScyPdtCode("029000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3678");
        
end

rule '1175732' extends '332522' salience 11200

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030000")
        
    then
        $gda.setScyPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3678");
        
end

rule '1175733' extends '332522' salience 11190

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030100")
        
    then
        $gda.setScyPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3678");
        
end

rule '1175734' extends '332522' salience 11180

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030200")
        
    then
        $gda.setScyPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3678");
        
end

rule '1175735' extends '332522' salience 11170

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030300")
        
    then
        $gda.setScyPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3678");
        
end

rule '1175736' extends '332522' salience 11160

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030400")
        
    then
        $gda.setScyPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3678");
        
end

rule '1175737' extends '332522' salience 11150

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030500")
        
    then
        $gda.setScyPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3678");
        
end

rule '1175738' extends '332522' salience 11140

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030600")
        
    then
        $gda.setScyPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3678");
        
end

rule '1175739' extends '332522' salience 11130

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030700")
        
    then
        $gda.setScyPdtCode("030700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3678");
        
end

rule '1175740' extends '332522' salience 11120

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030800")
        
    then
        $gda.setScyPdtCode("030800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3678");
        
end

rule '1175741' extends '332522' salience 11110

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030900")
        
    then
        $gda.setScyPdtCode("030900");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3678");
        
end

rule '1175742' extends '332522' salience 11100

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "031000")
        
    then
        $gda.setScyPdtCode("031000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3678");
        
end

rule '1175743' extends '332522' salience 11090

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "031100")
        
    then
        $gda.setScyPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3678");
        
end

rule '1175729' extends '332522' salience 11080

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "006100")
        
    then
        $gda.setScyPdtCode("006100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3678");
        
end


