package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlPlYtd;




dialect  "mvel"


rule '335887'
	when
		$gpy : GrlPlYtd(hpnPlCl != null && hpnPlCl not in ( "6000" , "7000" ))
	then
        
end





rule '1744605' extends '335887' salience 110

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setLocMassLine(massLine );
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"6138");
        
end

rule '1744595' extends '335887' salience 100

    when
        
        GrlPlYtd(this == $gpy, massLine == "Impairments on Securities")
        
    then
        $gpy.setLocMassLine("Impairments on Securities");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"6138");
        
end

rule '1744599' extends '335887' salience 90

    when
        
        GrlPlYtd(this == $gpy, massLine == "Group Overhead Staff FA")
        
    then
        $gpy.setLocMassLine("Group Overhead Staff FA");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"6138");
        
end

rule '1744600' extends '335887' salience 80

    when
        
        GrlPlYtd(this == $gpy, massLine == "Investment Income")
        
    then
        $gpy.setLocMassLine("Investment Income");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"6138");
        
end

rule '1744601' extends '335887' salience 70

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setLocMassLine("Realised gains and FV changes on investments (excl. IoS)");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"6138");
        
end

rule '1744602' extends '335887' salience 60

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Result of Trading Portfolio")
        
    then
        $gpy.setLocMassLine("Trading results");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"6138");
        
end

rule '1744603' extends '335887' salience 50

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Valuation Result Non-Trading Derivatives")
        
    then
        $gpy.setLocMassLine("Other Valuation Result Non-Trading Derivatives");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"6138");
        
end

rule '1744604' extends '335887' salience 40

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setLocMassLine("Other (Income)");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"6138");
        
end

rule '1744606' extends '335887' salience 30

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setLocMassLine("Interest paid (external)");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"6138");
        
end

rule '1744607' extends '335887' salience 20

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setLocMassLine("Interest received (external)");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"6138");
        
end

rule '1744608' extends '335887' salience 10

    when
        
        GrlPlYtd(this == $gpy, massLine == "Capital Charge")
        
    then
        $gpy.setLocMassLine("Capital Charge");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"6138");
        
end


