package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '331638'
	when
		$gda : GrlDetAmounts(massLine != "99.999")
	then
        
end





rule '1092714' extends '331638' salience 460

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxt01("99.999");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092667' extends '331638' salience 450

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Leveraged Finance")
        
    then
        $gda.setCustomTxt01("Acquisition Finance");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092668' extends '331638' salience 440

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Capital Management")
        
    then
        $gda.setCustomTxt01("Capital Management");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092669' extends '331638' salience 430

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "CF Geographic Coverage")
        
    then
        $gda.setCustomTxt01("CF Geographic Coverage");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092670' extends '331638' salience 420

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Corporate Audit Services")
        
    then
        $gda.setCustomTxt01("Corporate Audit Services");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092671' extends '331638' salience 410

    when
        
        GrlDetAmounts(this == $gda, localMassProduct in ("Corporate Clients", "Structured Export Finance"))
        
    then
        $gda.setCustomTxt01("Corporate Clients");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092672' extends '331638' salience 400

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Credit Risk Management")
        
    then
        $gda.setCustomTxt01("Credit Risk Management");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092673' extends '331638' salience 390

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxt01("Current accounts (Other)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092674' extends '331638' salience 380

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "DCM - HG")
        
    then
        $gda.setCustomTxt01("Debt & Capital Markets");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092675' extends '331638' salience 370

    when
        
        GrlDetAmounts(this == $gda, localMassProduct in ("Government Bonds", "Other Research"))
        
    then
        $gda.setCustomTxt01("DM Rates");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092676' extends '331638' salience 360

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Documentary Trading")
        
    then
        $gda.setCustomTxt01("Documentary Trading");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092677' extends '331638' salience 350

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Domestic Payments")
        
    then
        $gda.setCustomTxt01("Domestic Payments");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092678' extends '331638' salience 340

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "WE ECM")
        
    then
        $gda.setCustomTxt01("Equity Capital Market (IPO)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092679' extends '331638' salience 330

    when
        
        GrlDetAmounts(this == $gda, localMassProduct in ("WE Secondary Sales", "WE Research", "WE Trading"))
        
    then
        $gda.setCustomTxt01("Equity markets (From F.M.)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092680' extends '331638' salience 320

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "FI Banking")
        
    then
        $gda.setCustomTxt01("FI Banking");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092681' extends '331638' salience 310

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Finance")
        
    then
        $gda.setCustomTxt01("Finance");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092682' extends '331638' salience 300

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Financial Institutions")
        
    then
        $gda.setCustomTxt01("Financial Institutions");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092683' extends '331638' salience 290

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "FO Support")
        
    then
        $gda.setCustomTxt01("FO Support");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092684' extends '331638' salience 280

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "FX Derivatives")
        
    then
        $gda.setCustomTxt01("FX Derivatives");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092685' extends '331638' salience 270

    when
        
        GrlDetAmounts(this == $gda, localMassProduct in ("Term Loan", "FI Banking", "Trade Banking", "Overdraft", "Revolving credits", "Guarantees", "Non risk / admin limits", "FI Payment Sales", "Guarantees"))
        
    then
        $gda.setCustomTxt01("General Lending Products");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092686' extends '331638' salience 260

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "General Relationship Management")
        
    then
        $gda.setCustomTxt01("General Relationship Management");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092687' extends '331638' salience 250

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Government Bonds")
        
    then
        $gda.setCustomTxt01("Government Bonds");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092688' extends '331638' salience 240

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Head Office Charges Cost Center")
        
    then
        $gda.setCustomTxt01("Head Office Charges Cost Center");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092689' extends '331638' salience 230

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Human Resources")
        
    then
        $gda.setCustomTxt01("Human Resources");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092690' extends '331638' salience 220

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "IGA")
        
    then
        $gda.setCustomTxt01("IGA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092691' extends '331638' salience 210

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "International Payments")
        
    then
        $gda.setCustomTxt01("International Payments");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092692' extends '331638' salience 200

    when
        
        GrlDetAmounts(this == $gda, localMassProduct in ("ITEF Management", "Structured Commodity Finance", "Structured Export Finance", "Trade & Commodity Finance"))
        
    then
        $gda.setCustomTxt01("ITEF Management");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092693' extends '331638' salience 190

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Legal")
        
    then
        $gda.setCustomTxt01("Legal");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092694' extends '331638' salience 180

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxt01("M / Advisory Revenues");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092695' extends '331638' salience 170

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Management")
        
    then
        $gda.setCustomTxt01("Management");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092696' extends '331638' salience 160

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Nostro loro accounts")
        
    then
        $gda.setCustomTxt01("Nostro loro accounts");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092697' extends '331638' salience 150

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Occupancy and Premises")
        
    then
        $gda.setCustomTxt01("Occupancy and Premises");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092698' extends '331638' salience 140

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Operational Risk Management")
        
    then
        $gda.setCustomTxt01("Operational Risk Management");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092699' extends '331638' salience 130

    when
        
        GrlDetAmounts(this == $gda, localMassProduct in ("Operations Financial Markets", "Operations Equity Markets", "Operations Payments", "Operations Lending & Guarantees"))
        
    then
        $gda.setCustomTxt01("Operations");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092700' extends '331638' salience 120

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Operations Financial Markets")
        
    then
        $gda.setCustomTxt01("Operations Financial Markets");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092701' extends '331638' salience 110

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxt01("Operations Lending & Guarantees");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092702' extends '331638' salience 100

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Operations Other")
        
    then
        $gda.setCustomTxt01("Operations Other");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092703' extends '331638' salience 90

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxt01("Ops & IT Management");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092704' extends '331638' salience 80

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Other IT Applications")
        
    then
        $gda.setCustomTxt01("Other IT Applications");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092705' extends '331638' salience 70

    when
        
        GrlDetAmounts(this == $gda, localMassProduct in ("Current accounts (EUR)", "European Business Desks"))
        
    then
        $gda.setCustomTxt01("PCM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092706' extends '331638' salience 60

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxt01("Savings/Deposits (EUR)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092707' extends '331638' salience 50

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxt01("Savings/Deposits (Other)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092708' extends '331638' salience 40

    when
        
        GrlDetAmounts(this == $gda, localMassProduct in ("Oil & Gas", "Offshore", "Metals & Mining", "Telecommunications Finance", "Media Finance", "Utilities Finance - Power", "Industrial Sectors"))
        
    then
        $gda.setCustomTxt01("Sector Based Structured Lending");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092709' extends '331638' salience 30

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Sundry")
        
    then
        $gda.setCustomTxt01("Sundry");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092710' extends '331638' salience 20

    when
        
        GrlDetAmounts(this == $gda, localMassProduct == "Trade Finance Services")
        
    then
        $gda.setCustomTxt01("Trade Finance Services");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end

rule '1092713' extends '331638' salience 10

    when
        
        GrlDetAmounts(this == $gda, localMassProduct in ("ABF Shipping Finance", "Aviation", "Containers", "Rail / Other", "Infrastructure Finance", "Local Structured Finance", "Financial Engineering"))
        
    then
        $gda.setCustomTxt01("Sector Based Structured Lending");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3121");
        
end


