package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '334249'
	when
		$gda : GrlDetAmounts(lseHlyRelId != "0557")
	then
        
end





rule '1607678' extends '334249' salience 10800

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setSeCtryCd("CNT_NLD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607679' extends '334249' salience 10790

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "IL")
        
    then
        $gda.setSeCtryCd("CNT_ISR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607549' extends '334249' salience 10780

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "LI")
        
    then
        $gda.setSeCtryCd("CNT_LIE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607550' extends '334249' salience 10770

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "LK")
        
    then
        $gda.setSeCtryCd("CNT_LKA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607551' extends '334249' salience 10760

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "LS")
        
    then
        $gda.setSeCtryCd("CNT_LSO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607552' extends '334249' salience 10750

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "LT")
        
    then
        $gda.setSeCtryCd("CNT_LTU");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607553' extends '334249' salience 10740

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "LU")
        
    then
        $gda.setSeCtryCd("CNT_LUX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607554' extends '334249' salience 10730

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "LV")
        
    then
        $gda.setSeCtryCd("CNT_LVA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607555' extends '334249' salience 10720

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MO")
        
    then
        $gda.setSeCtryCd("CNT_MAC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607556' extends '334249' salience 10710

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MA")
        
    then
        $gda.setSeCtryCd("CNT_MAR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607557' extends '334249' salience 10700

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MC")
        
    then
        $gda.setSeCtryCd("CNT_MCO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607558' extends '334249' salience 10690

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MD")
        
    then
        $gda.setSeCtryCd("CNT_MDA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607559' extends '334249' salience 10680

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MG")
        
    then
        $gda.setSeCtryCd("CNT_MDG");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607560' extends '334249' salience 10670

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MV")
        
    then
        $gda.setSeCtryCd("CNT_MDV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607561' extends '334249' salience 10660

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MX")
        
    then
        $gda.setSeCtryCd("CNT_MEX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607562' extends '334249' salience 10650

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MH")
        
    then
        $gda.setSeCtryCd("CNT_MHL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607563' extends '334249' salience 10640

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MK")
        
    then
        $gda.setSeCtryCd("CNT_MKD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607564' extends '334249' salience 10630

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "ML")
        
    then
        $gda.setSeCtryCd("CNT_MLI");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607565' extends '334249' salience 10620

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MT")
        
    then
        $gda.setSeCtryCd("CNT_MLT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607566' extends '334249' salience 10610

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MM")
        
    then
        $gda.setSeCtryCd("CNT_MMR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607567' extends '334249' salience 10600

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MN")
        
    then
        $gda.setSeCtryCd("CNT_MNG");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607568' extends '334249' salience 10590

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MP")
        
    then
        $gda.setSeCtryCd("CNT_MNP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607569' extends '334249' salience 10580

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MZ")
        
    then
        $gda.setSeCtryCd("CNT_MOZ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607570' extends '334249' salience 10570

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MR")
        
    then
        $gda.setSeCtryCd("CNT_MRT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607571' extends '334249' salience 10560

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MS")
        
    then
        $gda.setSeCtryCd("CNT_MSR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607572' extends '334249' salience 10550

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MQ")
        
    then
        $gda.setSeCtryCd("CNT_MTQ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607573' extends '334249' salience 10540

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MU")
        
    then
        $gda.setSeCtryCd("CNT_MUS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607574' extends '334249' salience 10530

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MW")
        
    then
        $gda.setSeCtryCd("CNT_MWI");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607575' extends '334249' salience 10520

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "MY")
        
    then
        $gda.setSeCtryCd("CNT_MYS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607576' extends '334249' salience 10510

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "YT")
        
    then
        $gda.setSeCtryCd("CNT_MYT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607577' extends '334249' salience 10500

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "NA")
        
    then
        $gda.setSeCtryCd("CNT_NAM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607578' extends '334249' salience 10490

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "NC")
        
    then
        $gda.setSeCtryCd("CNT_NCL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607579' extends '334249' salience 10480

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "NE")
        
    then
        $gda.setSeCtryCd("CNT_NER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607580' extends '334249' salience 10470

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "NF")
        
    then
        $gda.setSeCtryCd("CNT_NFK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607581' extends '334249' salience 10460

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "NG")
        
    then
        $gda.setSeCtryCd("CNT_NGA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607582' extends '334249' salience 10450

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "NI")
        
    then
        $gda.setSeCtryCd("CNT_NIC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607583' extends '334249' salience 10440

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "NU")
        
    then
        $gda.setSeCtryCd("CNT_NIU");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607584' extends '334249' salience 10430

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "NL")
        
    then
        $gda.setSeCtryCd("CNT_NLD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607585' extends '334249' salience 10420

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "NO")
        
    then
        $gda.setSeCtryCd("CNT_NOR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607586' extends '334249' salience 10410

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "NP")
        
    then
        $gda.setSeCtryCd("CNT_NPL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607587' extends '334249' salience 10400

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "NR")
        
    then
        $gda.setSeCtryCd("CNT_NRU");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607588' extends '334249' salience 10390

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "NZ")
        
    then
        $gda.setSeCtryCd("CNT_NZL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607589' extends '334249' salience 10380

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "OM")
        
    then
        $gda.setSeCtryCd("CNT_OMN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607590' extends '334249' salience 10370

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "PK")
        
    then
        $gda.setSeCtryCd("CNT_PAK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607591' extends '334249' salience 10360

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "PA")
        
    then
        $gda.setSeCtryCd("CNT_PAN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607592' extends '334249' salience 10350

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "PN")
        
    then
        $gda.setSeCtryCd("CNT_PCN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607593' extends '334249' salience 10340

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "PE")
        
    then
        $gda.setSeCtryCd("CNT_PER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607594' extends '334249' salience 10330

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "PH")
        
    then
        $gda.setSeCtryCd("CNT_PHL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607595' extends '334249' salience 10320

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "PW")
        
    then
        $gda.setSeCtryCd("CNT_PLW");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607596' extends '334249' salience 10310

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "PG")
        
    then
        $gda.setSeCtryCd("CNT_PNG");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607597' extends '334249' salience 10300

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "PL")
        
    then
        $gda.setSeCtryCd("CNT_POL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607598' extends '334249' salience 10290

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "PR")
        
    then
        $gda.setSeCtryCd("CNT_PRI");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607599' extends '334249' salience 10280

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "KP")
        
    then
        $gda.setSeCtryCd("CNT_PRK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607600' extends '334249' salience 10270

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "PT")
        
    then
        $gda.setSeCtryCd("CNT_PRT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607601' extends '334249' salience 10260

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "PY")
        
    then
        $gda.setSeCtryCd("CNT_PRY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607602' extends '334249' salience 10250

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "PF")
        
    then
        $gda.setSeCtryCd("CNT_PYF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607603' extends '334249' salience 10240

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "QA")
        
    then
        $gda.setSeCtryCd("CNT_QAT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607604' extends '334249' salience 10230

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "RE")
        
    then
        $gda.setSeCtryCd("CNT_REU");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607605' extends '334249' salience 10220

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "RO")
        
    then
        $gda.setSeCtryCd("CNT_ROU");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607606' extends '334249' salience 10210

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "RU")
        
    then
        $gda.setSeCtryCd("CNT_RUS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607607' extends '334249' salience 10200

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "RW")
        
    then
        $gda.setSeCtryCd("CNT_RWA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607608' extends '334249' salience 10190

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "SA")
        
    then
        $gda.setSeCtryCd("CNT_SAU");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607609' extends '334249' salience 10180

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "SD")
        
    then
        $gda.setSeCtryCd("CNT_SDN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607610' extends '334249' salience 10170

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "SN")
        
    then
        $gda.setSeCtryCd("CNT_SEN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607611' extends '334249' salience 10160

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "SG")
        
    then
        $gda.setSeCtryCd("CNT_SGP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607612' extends '334249' salience 10150

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GS")
        
    then
        $gda.setSeCtryCd("CNT_SGS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607613' extends '334249' salience 10140

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "WS")
        
    then
        $gda.setSeCtryCd("CNT_WSM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607614' extends '334249' salience 10130

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "YE")
        
    then
        $gda.setSeCtryCd("CNT_YEM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607615' extends '334249' salience 10120

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "RS")
        
    then
        $gda.setSeCtryCd("CNT_SRB");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607616' extends '334249' salience 10110

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "ME")
        
    then
        $gda.setSeCtryCd("CNT_MNE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607617' extends '334249' salience 10100

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "ZA")
        
    then
        $gda.setSeCtryCd("CNT_ZAF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607618' extends '334249' salience 10090

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "CD")
        
    then
        $gda.setSeCtryCd("CNT_COD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607619' extends '334249' salience 10080

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "ZM")
        
    then
        $gda.setSeCtryCd("CNT_ZMB");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607620' extends '334249' salience 10070

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "ZW")
        
    then
        $gda.setSeCtryCd("CNT_ZWE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607621' extends '334249' salience 10060

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "IO")
        
    then
        $gda.setSeCtryCd("CNT_IOT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607622' extends '334249' salience 10050

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "IE")
        
    then
        $gda.setSeCtryCd("CNT_IRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607623' extends '334249' salience 10040

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "IR")
        
    then
        $gda.setSeCtryCd("CNT_IRN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607624' extends '334249' salience 10030

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "IQ")
        
    then
        $gda.setSeCtryCd("CNT_IRQ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607625' extends '334249' salience 10020

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "IS")
        
    then
        $gda.setSeCtryCd("CNT_ISL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607626' extends '334249' salience 10010

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "IT")
        
    then
        $gda.setSeCtryCd("CNT_ITA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607627' extends '334249' salience 10000

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "JM")
        
    then
        $gda.setSeCtryCd("CNT_JAM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607628' extends '334249' salience 9990

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "JO")
        
    then
        $gda.setSeCtryCd("CNT_JOR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607629' extends '334249' salience 9980

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "JP")
        
    then
        $gda.setSeCtryCd("CNT_JPN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607630' extends '334249' salience 9970

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "KZ")
        
    then
        $gda.setSeCtryCd("CNT_KAZ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607631' extends '334249' salience 9960

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "KE")
        
    then
        $gda.setSeCtryCd("CNT_KEN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607632' extends '334249' salience 9950

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "KG")
        
    then
        $gda.setSeCtryCd("CNT_KGZ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607633' extends '334249' salience 9940

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "KH")
        
    then
        $gda.setSeCtryCd("CNT_KHM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607634' extends '334249' salience 9930

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "KI")
        
    then
        $gda.setSeCtryCd("CNT_KIR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607635' extends '334249' salience 9920

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "KN")
        
    then
        $gda.setSeCtryCd("CNT_KNA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607636' extends '334249' salience 9910

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "KR")
        
    then
        $gda.setSeCtryCd("CNT_KOR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607637' extends '334249' salience 9900

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "KW")
        
    then
        $gda.setSeCtryCd("CNT_KWT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607638' extends '334249' salience 9890

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "LA")
        
    then
        $gda.setSeCtryCd("CNT_LAO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607639' extends '334249' salience 9880

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "LB")
        
    then
        $gda.setSeCtryCd("CNT_LBN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607640' extends '334249' salience 9870

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "LR")
        
    then
        $gda.setSeCtryCd("CNT_LBR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607641' extends '334249' salience 9860

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "LY")
        
    then
        $gda.setSeCtryCd("CNT_LBY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607642' extends '334249' salience 9850

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "LC")
        
    then
        $gda.setSeCtryCd("CNT_LCA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607643' extends '334249' salience 9840

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "AW")
        
    then
        $gda.setSeCtryCd("CNT_ABW");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607644' extends '334249' salience 9830

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "AF")
        
    then
        $gda.setSeCtryCd("CNT_AFG");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607645' extends '334249' salience 9820

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "AO")
        
    then
        $gda.setSeCtryCd("CNT_AGO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607646' extends '334249' salience 9810

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "AI")
        
    then
        $gda.setSeCtryCd("CNT_AIA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607647' extends '334249' salience 9800

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "AL")
        
    then
        $gda.setSeCtryCd("CNT_ALB");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607648' extends '334249' salience 9790

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "AD")
        
    then
        $gda.setSeCtryCd("CNT_AND");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607649' extends '334249' salience 9780

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "AN")
        
    then
        $gda.setSeCtryCd("CNT_ANT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607650' extends '334249' salience 9770

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "AE")
        
    then
        $gda.setSeCtryCd("CNT_ARE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607651' extends '334249' salience 9760

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "AR")
        
    then
        $gda.setSeCtryCd("CNT_ARG");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607652' extends '334249' salience 9750

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "AM")
        
    then
        $gda.setSeCtryCd("CNT_ARM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607653' extends '334249' salience 9740

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "AS")
        
    then
        $gda.setSeCtryCd("CNT_ASM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607654' extends '334249' salience 9730

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "AQ")
        
    then
        $gda.setSeCtryCd("CNT_ATA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607655' extends '334249' salience 9720

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "TF")
        
    then
        $gda.setSeCtryCd("CNT_ATF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607656' extends '334249' salience 9710

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "AG")
        
    then
        $gda.setSeCtryCd("CNT_ATG");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607657' extends '334249' salience 9700

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "AU")
        
    then
        $gda.setSeCtryCd("CNT_AUS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607658' extends '334249' salience 9690

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "AT")
        
    then
        $gda.setSeCtryCd("CNT_AUT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607659' extends '334249' salience 9680

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "AZ")
        
    then
        $gda.setSeCtryCd("CNT_AZE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607660' extends '334249' salience 9670

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BI")
        
    then
        $gda.setSeCtryCd("CNT_BDI");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607661' extends '334249' salience 9660

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BE")
        
    then
        $gda.setSeCtryCd("CNT_BEL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607662' extends '334249' salience 9650

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BJ")
        
    then
        $gda.setSeCtryCd("CNT_BEN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607663' extends '334249' salience 9640

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BF")
        
    then
        $gda.setSeCtryCd("CNT_BFA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607664' extends '334249' salience 9630

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BD")
        
    then
        $gda.setSeCtryCd("CNT_BGD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607665' extends '334249' salience 9620

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BG")
        
    then
        $gda.setSeCtryCd("CNT_BGR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607666' extends '334249' salience 9610

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BH")
        
    then
        $gda.setSeCtryCd("CNT_BHR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607667' extends '334249' salience 9600

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BS")
        
    then
        $gda.setSeCtryCd("CNT_BHS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607668' extends '334249' salience 9590

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BA")
        
    then
        $gda.setSeCtryCd("CNT_BIH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607669' extends '334249' salience 9580

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BY")
        
    then
        $gda.setSeCtryCd("CNT_BLR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607670' extends '334249' salience 9570

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BZ")
        
    then
        $gda.setSeCtryCd("CNT_BLZ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607671' extends '334249' salience 9560

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BM")
        
    then
        $gda.setSeCtryCd("CNT_BMU");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607672' extends '334249' salience 9550

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BO")
        
    then
        $gda.setSeCtryCd("CNT_BOL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607673' extends '334249' salience 9540

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BR")
        
    then
        $gda.setSeCtryCd("CNT_BRA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607674' extends '334249' salience 9530

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BB")
        
    then
        $gda.setSeCtryCd("CNT_BRB");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607675' extends '334249' salience 9520

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BN")
        
    then
        $gda.setSeCtryCd("CNT_BRN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607676' extends '334249' salience 9510

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BT")
        
    then
        $gda.setSeCtryCd("CNT_BTN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607677' extends '334249' salience 9500

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BV")
        
    then
        $gda.setSeCtryCd("CNT_BVT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607680' extends '334249' salience 9490

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "TZ")
        
    then
        $gda.setSeCtryCd("CNT_TZA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607681' extends '334249' salience 9480

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GG")
        
    then
        $gda.setSeCtryCd("CNT_GGY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607682' extends '334249' salience 9470

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "IM")
        
    then
        $gda.setSeCtryCd("CNT_IMN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607683' extends '334249' salience 9460

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "JE")
        
    then
        $gda.setSeCtryCd("CNT_JEY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607684' extends '334249' salience 9450

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "PS")
        
    then
        $gda.setSeCtryCd("CNT_PSE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607685' extends '334249' salience 9440

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "TM")
        
    then
        $gda.setSeCtryCd("CNT_TKM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607686' extends '334249' salience 9430

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "TL")
        
    then
        $gda.setSeCtryCd("CNT_TLS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607687' extends '334249' salience 9420

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "TO")
        
    then
        $gda.setSeCtryCd("CNT_TON");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607688' extends '334249' salience 9410

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "TT")
        
    then
        $gda.setSeCtryCd("CNT_TTO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607689' extends '334249' salience 9400

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "TN")
        
    then
        $gda.setSeCtryCd("CNT_TUN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607690' extends '334249' salience 9390

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "TR")
        
    then
        $gda.setSeCtryCd("CNT_TUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607691' extends '334249' salience 9380

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "TV")
        
    then
        $gda.setSeCtryCd("CNT_TUV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607692' extends '334249' salience 9370

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "TW")
        
    then
        $gda.setSeCtryCd("CNT_TWN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607693' extends '334249' salience 9360

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "UG")
        
    then
        $gda.setSeCtryCd("CNT_UGA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607694' extends '334249' salience 9350

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "UA")
        
    then
        $gda.setSeCtryCd("CNT_UKR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607695' extends '334249' salience 9340

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "UM")
        
    then
        $gda.setSeCtryCd("CNT_UMI");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607696' extends '334249' salience 9330

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "UY")
        
    then
        $gda.setSeCtryCd("CNT_URY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607697' extends '334249' salience 9320

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "US")
        
    then
        $gda.setSeCtryCd("CNT_USA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607698' extends '334249' salience 9310

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "UZ")
        
    then
        $gda.setSeCtryCd("CNT_UZB");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607699' extends '334249' salience 9300

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "VA")
        
    then
        $gda.setSeCtryCd("CNT_VAT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607700' extends '334249' salience 9290

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "VC")
        
    then
        $gda.setSeCtryCd("CNT_VCT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607701' extends '334249' salience 9280

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "VE")
        
    then
        $gda.setSeCtryCd("CNT_VEN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607702' extends '334249' salience 9270

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "VG")
        
    then
        $gda.setSeCtryCd("CNT_VGB");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607703' extends '334249' salience 9260

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "VI")
        
    then
        $gda.setSeCtryCd("CNT_VIR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607704' extends '334249' salience 9250

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "VN")
        
    then
        $gda.setSeCtryCd("CNT_VNM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607705' extends '334249' salience 9240

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "VU")
        
    then
        $gda.setSeCtryCd("CNT_VUT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607706' extends '334249' salience 9230

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "WF")
        
    then
        $gda.setSeCtryCd("CNT_WLF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607707' extends '334249' salience 9220

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "SH")
        
    then
        $gda.setSeCtryCd("CNT_SHN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607708' extends '334249' salience 9210

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "SJ")
        
    then
        $gda.setSeCtryCd("CNT_SJM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607709' extends '334249' salience 9200

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "SB")
        
    then
        $gda.setSeCtryCd("CNT_SLB");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607710' extends '334249' salience 9190

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "SL")
        
    then
        $gda.setSeCtryCd("CNT_SLE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607711' extends '334249' salience 9180

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "SV")
        
    then
        $gda.setSeCtryCd("CNT_SLV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607712' extends '334249' salience 9170

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "SM")
        
    then
        $gda.setSeCtryCd("CNT_SMR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607713' extends '334249' salience 9160

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "SO")
        
    then
        $gda.setSeCtryCd("CNT_SOM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607714' extends '334249' salience 9150

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "PM")
        
    then
        $gda.setSeCtryCd("CNT_SPM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607715' extends '334249' salience 9140

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "ST")
        
    then
        $gda.setSeCtryCd("CNT_STP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607716' extends '334249' salience 9130

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "SR")
        
    then
        $gda.setSeCtryCd("CNT_SUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607717' extends '334249' salience 9120

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "SK")
        
    then
        $gda.setSeCtryCd("CNT_SVK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607718' extends '334249' salience 9110

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "SI")
        
    then
        $gda.setSeCtryCd("CNT_SVN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607719' extends '334249' salience 9100

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "SE")
        
    then
        $gda.setSeCtryCd("CNT_SWE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607720' extends '334249' salience 9090

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "SZ")
        
    then
        $gda.setSeCtryCd("CNT_SWZ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607721' extends '334249' salience 9080

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "SC")
        
    then
        $gda.setSeCtryCd("CNT_SYC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607722' extends '334249' salience 9070

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "SY")
        
    then
        $gda.setSeCtryCd("CNT_SYR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607723' extends '334249' salience 9060

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "TC")
        
    then
        $gda.setSeCtryCd("CNT_TCA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607724' extends '334249' salience 9050

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "TD")
        
    then
        $gda.setSeCtryCd("CNT_TCD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607725' extends '334249' salience 9040

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "TG")
        
    then
        $gda.setSeCtryCd("CNT_TGO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607726' extends '334249' salience 9030

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "TH")
        
    then
        $gda.setSeCtryCd("CNT_THA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607727' extends '334249' salience 9020

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "TJ")
        
    then
        $gda.setSeCtryCd("CNT_TJK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607728' extends '334249' salience 9010

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "TK")
        
    then
        $gda.setSeCtryCd("CNT_TKL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607729' extends '334249' salience 9000

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "BW")
        
    then
        $gda.setSeCtryCd("CNT_BWA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607730' extends '334249' salience 8990

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "CF")
        
    then
        $gda.setSeCtryCd("CNT_CAF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607731' extends '334249' salience 8980

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "CA")
        
    then
        $gda.setSeCtryCd("CNT_CAN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607732' extends '334249' salience 8970

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "CC")
        
    then
        $gda.setSeCtryCd("CNT_CCK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607733' extends '334249' salience 8960

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "CH")
        
    then
        $gda.setSeCtryCd("CNT_CHE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607734' extends '334249' salience 8950

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "CL")
        
    then
        $gda.setSeCtryCd("CNT_CHL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607735' extends '334249' salience 8940

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "CN")
        
    then
        $gda.setSeCtryCd("CNT_CHN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607736' extends '334249' salience 8930

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "CI")
        
    then
        $gda.setSeCtryCd("CNT_CIV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607737' extends '334249' salience 8920

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "CM")
        
    then
        $gda.setSeCtryCd("CNT_CMR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607738' extends '334249' salience 8910

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "CG")
        
    then
        $gda.setSeCtryCd("CNT_COG");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607739' extends '334249' salience 8900

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "CK")
        
    then
        $gda.setSeCtryCd("CNT_COK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607740' extends '334249' salience 8890

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "CO")
        
    then
        $gda.setSeCtryCd("CNT_COL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607741' extends '334249' salience 8880

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "KM")
        
    then
        $gda.setSeCtryCd("CNT_COM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607742' extends '334249' salience 8870

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "CV")
        
    then
        $gda.setSeCtryCd("CNT_CPV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607743' extends '334249' salience 8860

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "CR")
        
    then
        $gda.setSeCtryCd("CNT_CRI");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607744' extends '334249' salience 8850

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "CU")
        
    then
        $gda.setSeCtryCd("CNT_CUB");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607745' extends '334249' salience 8840

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "CX")
        
    then
        $gda.setSeCtryCd("CNT_CXR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607746' extends '334249' salience 8830

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "KY")
        
    then
        $gda.setSeCtryCd("CNT_CYM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607747' extends '334249' salience 8820

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "CY")
        
    then
        $gda.setSeCtryCd("CNT_CYP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607748' extends '334249' salience 8810

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "CZ")
        
    then
        $gda.setSeCtryCd("CNT_CZE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607749' extends '334249' salience 8800

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "DE")
        
    then
        $gda.setSeCtryCd("CNT_DEU");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607750' extends '334249' salience 8790

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "DJ")
        
    then
        $gda.setSeCtryCd("CNT_DJI");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607751' extends '334249' salience 8780

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "DM")
        
    then
        $gda.setSeCtryCd("CNT_DMA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607752' extends '334249' salience 8770

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "DK")
        
    then
        $gda.setSeCtryCd("CNT_DNK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607753' extends '334249' salience 8760

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "DO")
        
    then
        $gda.setSeCtryCd("CNT_DOM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607754' extends '334249' salience 8750

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "DZ")
        
    then
        $gda.setSeCtryCd("CNT_DZA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607755' extends '334249' salience 8740

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "EC")
        
    then
        $gda.setSeCtryCd("CNT_ECU");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607756' extends '334249' salience 8730

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "EG")
        
    then
        $gda.setSeCtryCd("CNT_EGY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607757' extends '334249' salience 8720

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "ER")
        
    then
        $gda.setSeCtryCd("CNT_ERI");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607758' extends '334249' salience 8710

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "EH")
        
    then
        $gda.setSeCtryCd("CNT_ESH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607759' extends '334249' salience 8700

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "ES")
        
    then
        $gda.setSeCtryCd("CNT_ESP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607760' extends '334249' salience 8690

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "EE")
        
    then
        $gda.setSeCtryCd("CNT_EST");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607761' extends '334249' salience 8680

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "ET")
        
    then
        $gda.setSeCtryCd("CNT_ETH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607762' extends '334249' salience 8670

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "FI")
        
    then
        $gda.setSeCtryCd("CNT_FIN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607763' extends '334249' salience 8660

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "FJ")
        
    then
        $gda.setSeCtryCd("CNT_FJI");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607764' extends '334249' salience 8650

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "FK")
        
    then
        $gda.setSeCtryCd("CNT_FLK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607765' extends '334249' salience 8640

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "FR")
        
    then
        $gda.setSeCtryCd("CNT_FRA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607766' extends '334249' salience 8630

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "FO")
        
    then
        $gda.setSeCtryCd("CNT_FRO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607767' extends '334249' salience 8620

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "FM")
        
    then
        $gda.setSeCtryCd("CNT_FSM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607768' extends '334249' salience 8610

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GA")
        
    then
        $gda.setSeCtryCd("CNT_GAB");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607769' extends '334249' salience 8600

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GB")
        
    then
        $gda.setSeCtryCd("CNT_GBR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607770' extends '334249' salience 8590

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GE")
        
    then
        $gda.setSeCtryCd("CNT_GEO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607771' extends '334249' salience 8580

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GH")
        
    then
        $gda.setSeCtryCd("CNT_GHA");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607772' extends '334249' salience 8570

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GI")
        
    then
        $gda.setSeCtryCd("CNT_GIB");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607773' extends '334249' salience 8560

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GN")
        
    then
        $gda.setSeCtryCd("CNT_GIN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607774' extends '334249' salience 8550

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GP")
        
    then
        $gda.setSeCtryCd("CNT_GLP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607775' extends '334249' salience 8540

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GM")
        
    then
        $gda.setSeCtryCd("CNT_GMB");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607776' extends '334249' salience 8530

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GW")
        
    then
        $gda.setSeCtryCd("CNT_GNB");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607777' extends '334249' salience 8520

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GQ")
        
    then
        $gda.setSeCtryCd("CNT_GNQ");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607778' extends '334249' salience 8510

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GR")
        
    then
        $gda.setSeCtryCd("CNT_GRC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607779' extends '334249' salience 8500

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GD")
        
    then
        $gda.setSeCtryCd("CNT_GRD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607780' extends '334249' salience 8490

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GL")
        
    then
        $gda.setSeCtryCd("CNT_GRL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607781' extends '334249' salience 8480

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GT")
        
    then
        $gda.setSeCtryCd("CNT_GTM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607782' extends '334249' salience 8470

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GF")
        
    then
        $gda.setSeCtryCd("CNT_GUF");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607783' extends '334249' salience 8460

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GU")
        
    then
        $gda.setSeCtryCd("CNT_GUM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607784' extends '334249' salience 8450

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "GY")
        
    then
        $gda.setSeCtryCd("CNT_GUY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607785' extends '334249' salience 8440

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "HK")
        
    then
        $gda.setSeCtryCd("CNT_HKG");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607786' extends '334249' salience 8430

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "HM")
        
    then
        $gda.setSeCtryCd("CNT_HMD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607787' extends '334249' salience 8420

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "HN")
        
    then
        $gda.setSeCtryCd("CNT_HND");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607788' extends '334249' salience 8410

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "HR")
        
    then
        $gda.setSeCtryCd("CNT_HRV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607789' extends '334249' salience 8400

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "HT")
        
    then
        $gda.setSeCtryCd("CNT_HTI");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607790' extends '334249' salience 8390

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "HU")
        
    then
        $gda.setSeCtryCd("CNT_HUN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607791' extends '334249' salience 8380

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "ID")
        
    then
        $gda.setSeCtryCd("CNT_IDN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end

rule '1607792' extends '334249' salience 8370

    when
        
        GrlDetAmounts(this == $gda, hcyCtryCdRes == "IN")
        
    then
        $gda.setSeCtryCd("CNT_IND");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4947");
        
end


