package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '334289'
	when
		$gda : GrlDetAmounts(lseHlyRelId == "9193" && seCode2 matches ".*9001-HK1_06.5.*" && customTxtHo18 in ( "9001-HK3_2241" , "9001-HK3_2242" , "9001-HK3_2251" , "9001-HK3_2252" ))
	then
        
end





rule '1608440' extends '334289' salience 11250

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxtHo21(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4987");
        
end

rule '1608428' extends '334289' salience 11240

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo21("9001-HK3_06.510-1.070.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4987");
        
end

rule '1608429' extends '334289' salience 11230

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo21("9001-HK3_06.510-1.010.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4987");
        
end

rule '1608430' extends '334289' salience 11220

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo21("9001-HK3_06.510-1.040.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4987");
        
end

rule '1608431' extends '334289' salience 11210

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo21("9001-HK3_06.530-1.070.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4987");
        
end

rule '1608432' extends '334289' salience 11200

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo21("9001-HK3_06.530-1.010.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4987");
        
end

rule '1608433' extends '334289' salience 11190

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo21("9001-HK3_06.530-1.040.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4987");
        
end

rule '1608434' extends '334289' salience 11180

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2241", "9001-HK3_2242", "9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo21("9001-HK3_06.540-1.000.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4987");
        
end

rule '1608435' extends '334289' salience 11170

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2241", "9001-HK3_2242", "9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo21("9001-HK3_06.550-1.000.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4987");
        
end

rule '1608436' extends '334289' salience 11160

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2241", "9001-HK3_2242", "9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo21("9001-HK3_06.560-1.000.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4987");
        
end

rule '1608437' extends '334289' salience 11150

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2241", "9001-HK3_2242", "9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo21("9001-HK3_06.570-1.070.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4987");
        
end

rule '1608438' extends '334289' salience 11140

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2241", "9001-HK3_2242", "9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo21("9001-HK3_06.570-1.010.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4987");
        
end

rule '1608439' extends '334289' salience 11130

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2241", "9001-HK3_2242", "9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo21("9001-HK3_06.570-1.040.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4987");
        
end


