package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '334283'
	when
		$gda : GrlDetAmounts(lseHlyRelId == "9193" && seCode2 matches ".*9001-HK1_06.5.*" && customTxtHo18 in ( "9001-HK3_2241" , "9001-HK3_2242" , "9001-HK3_2251" , "9001-HK3_2252" ))
	then
        
end





rule '1608427' extends '334283' salience 11350

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxtHo19(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4981");
        
end

rule '1608418' extends '334283' salience 11340

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo19("9001-HK3_06.510-0.010.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4981");
        
end

rule '1608419' extends '334283' salience 11330

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo19("9001-HK3_06.510-0.040.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4981");
        
end

rule '1608420' extends '334283' salience 11320

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo19("9001-HK3_06.510-0.070.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4981");
        
end

rule '1608421' extends '334283' salience 11310

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo19("9001-HK3_06.530-0.010.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4981");
        
end

rule '1608422' extends '334283' salience 11300

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo19("9001-HK3_06.530-0.040.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4981");
        
end

rule '1608423' extends '334283' salience 11290

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo19("9001-HK3_06.530-0.070.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4981");
        
end

rule '1608424' extends '334283' salience 11280

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2241", "9001-HK3_2242", "9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo19("9001-HK3_06.570-0.010.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4981");
        
end

rule '1608425' extends '334283' salience 11270

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2241", "9001-HK3_2242", "9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo19("9001-HK3_06.570-0.040.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4981");
        
end

rule '1608426' extends '334283' salience 11260

    when
        
        GrlDetAmounts(this == $gda, customTxtHo18 in ("9001-HK3_2241", "9001-HK3_2242", "9001-HK3_2251", "9001-HK3_2252"))
        
    then
        $gda.setCustomTxtHo19("9001-HK3_06.570-0.070.0");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"4981");
        
end


