package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '331519'
	when
		$gda : GrlDetAmounts(actCode != null && hpePdtType == "LOAN")
	then
        
end





rule '1086291' extends '331519' salience 1560

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "01", hcuCcyCdOrg == "BGN", prodSubSubTypeLoc in ("LVAR", "LFIX", "LFRT"), residentInd == "Y", icInd == "N", ownUse20 matches "C.*")
        
    then
        $gda.setCustomTxt01("5311_2_BGN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2998");
        
end

rule '1086292' extends '331519' salience 1550

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "01", hcuCcyCdOrg == "BGN", prodSubSubTypeLoc in ("LVAR", "LFRT"), residentInd == "Y", icInd == "N", ownUse20 matches "F.*")
        
    then
        $gda.setCustomTxt01("5311_3_BGN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2998");
        
end

rule '1086293' extends '331519' salience 1540

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "01", hcuCcyCdOrg != "BGN", prodSubSubTypeLoc in ("LVAR", "LFRT", "LFIX", "LCDP"), residentInd == "Y", icInd == "N", ownUse20 matches "C.*")
        
    then
        $gda.setCustomTxt01("5312_2_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2998");
        
end

rule '1086600' extends '331519' salience 1530

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("02", "03"), hcuCcyCdOrg == "BGN", prodSubSubTypeLoc in ("LVAR", "LFRT"), residentInd == "Y", icInd == "N", ownUse20 matches "F.*")
        
    then
        $gda.setCustomTxt01("4961_8_BGN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2998");
        
end

rule '1086601' extends '331519' salience 1520

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("02", "03"), hcuCcyCdOrg == "BGN", prodSubSubTypeLoc in ("LVAR", "LFRT", "LFIX"), residentInd == "Y", icInd == "N", ownUse20 matches "C.*")
        
    then
        $gda.setCustomTxt01("4961_6_BGN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2998");
        
end

rule '1086603' extends '331519' salience 1510

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("02", "03"), hcuCcyCdOrg != "BGN", prodSubSubTypeLoc in ("LVAR", "LFRT", "LFIX"), residentInd == "Y", icInd == "N", ownUse20 matches "F.*")
        
    then
        $gda.setCustomTxt01("4962_9_BGN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2998");
        
end

rule '1086608' extends '331519' salience 1500

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("02", "03"), hcuCcyCdOrg != "BGN", prodSubSubTypeLoc in ("LVAR", "LFRT", "LFIX"), residentInd == "Y", icInd == "N", ownUse20 matches "C.*")
        
    then
        $gda.setCustomTxt01("4962_7_OTH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2998");
        
end

rule '1086609' extends '331519' salience 1490

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "01", hcuCcyCdOrg != "BGN", prodSubSubTypeLoc in ("LVAR", "LFRT", "LCDP"), residentInd == "Y", icInd == "N", ownUse20 matches "F.*")
        
    then
        $gda.setCustomTxt01("5312_3_EUR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2998");
        
end

rule '1102131' extends '331519' salience 1480

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "01", hcuCcyCdOrg == "BGN", prodSubSubTypeLoc in ("LVAR", "LFIX", "LFRT"), residentInd == "Y", icInd == "N", ownUse20 matches "F.*")
        
    then
        $gda.setCustomTxt01("5311_3_BGN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2998");
        
end

rule '1102132' extends '331519' salience 1470

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("02", "03"), hcuCcyCdOrg == "BGN", prodSubSubTypeLoc in ("LVAR", "LFRT", "LFIX"), residentInd == "Y", icInd == "N", ownUse20 matches "F.*")
        
    then
        $gda.setCustomTxt01("4961_8_BGN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2998");
        
end


