package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '331716'
	when
		$gda : GrlDetAmounts(actCode != null && hpePdtType == "TAXES")
	then
        
end





rule '1102155' extends '331716' salience 270

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "1401")
        
    then
        $gda.setCustomTxt01("4520_0_BGN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3204");
        
end

rule '1102156' extends '331716' salience 260

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "1402")
        
    then
        $gda.setCustomTxt01("4540_0_BGN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3204");
        
end

rule '1102157' extends '331716' salience 250

    when
        
        GrlDetAmounts(this == $gda, hscAcctSubcl == "1403")
        
    then
        $gda.setCustomTxt01("4971_0_BGN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3204");
        
end


