package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '335726'
	when
		$gda : GrlDetAmounts(( hpePdtType in ( "CCY SWAP" , "SPOT FX" , "CCY FORW" ) ) && hacAmtCl == "10" && repAssetInd == "N" && ( signFlipCode == null || signFlipCode not matches ".*OTC.*" ))
	then
        
end





rule '1727429' extends '335726' salience 150

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setSignFlipCode(signFlipCode + "[OTC]" );
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6055");
        
end


