package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '334334'
	when
		$gda : GrlDetAmounts(actCode matches "A.*" && cgpCode == "00017" && liquidityCd matches "12.*")
	then
        
end





rule '1614252' extends '334334' salience 190

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setSignFlipCode("[MM,LRR]");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5025");
        
end


