package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '332993'
	when
		$gda : GrlDetAmounts(actCode in ( "A0017000" , "A0058000" , "A3291000" , "A3331000" , "A3333000" , "A4112000" , "A4412000" , "A4564000" , "A4565000" , "A7985000" , "A7986000" , "A7987000" , "A7988000" , "A8349000" , "A8609000" , "A9018000" , "A9260000" , "A9458000" , "A9460000" ) && pdtCode in ( "002900" , "005100" , "005900" , "006100" , "007300" , "029000" , "030000" , "030100" , "030200" , "030300" , "030400" , "030500" , "030600" , "030700" , "030800" , "030900" , "031000" , "031100" , "031200" ) && smnBeyNumber != nvl ( cpyBeyNumber , "X" ))
	then
        
end





rule '1356168' extends '332993' salience 140

    when
        
        GrlDetAmounts(this == $gda, nvl2(isinCd,  'Y',  'N' ) == "Y")
        
    then
        $gda.setDnbSecurityCode("DEBT SECURITIES ORIGINAL MATURITY MORE THAN TWO YEARS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3875");
        
end

rule '1389720' extends '332993' salience 130

    when
        
        GrlDetAmounts(this == $gda, nvl2(isinCd,  'Y',  'N' ) == "N")
        
    then
        $gda.setDnbSecurityCode("DEBT SECURITIES TO BE SPECIFIED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3875");
        
end

rule '1342789' extends '332993' salience 120
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1342790() == "between_one_and_two_years")
        
    then
        $gda.setDnbSecurityCode("DEBT SECURITIES ORIGINAL MATURITY BETWEEN ONE AND TWO YEARS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3875");
        
end

rule '1342790' extends '332993' salience 110
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1342790() == "more_than_two_years")
        
    then
        $gda.setDnbSecurityCode("DEBT SECURITIES ORIGINAL MATURITY MORE THAN TWO YEARS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3875");
        
end

rule '1342791' extends '332993' salience 100
no-loop
    when
        
        GrlDetAmounts(this == $gda, getCase0_1342790() == "one year or less")
        
    then
        $gda.setDnbSecurityCode("DEBT SECURITIES ORIGINAL MATURITY 1 YEAR OR LESS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3875");
        
end


