package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlPlYtd;




dialect  "mvel"


rule '338558'
	when
		$gpy : GrlPlYtd(hpnPlCl in ( "6000" , "7000" ) && hsoPlSubcl != 7401)
	then
        
end





rule '2009238' extends '338558' salience 310

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setLocMassLine(massLine );
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009064' extends '338558' salience 300

    when
        
        GrlPlYtd(this == $gpy, massLine == "Capitalisation Own Developed Software")
        
    then
        $gpy.setLocMassLine("Global Procurement Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009065' extends '338558' salience 290

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Consulting")
        
    then
        $gpy.setLocMassLine("Consultancy Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009074' extends '338558' salience 280

    when
        
        GrlPlYtd(this == $gpy, massLine == "Depreciation Hardware")
        
    then
        $gpy.setLocMassLine("Depreciation Locally Selected Hardware");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009183' extends '338558' salience 270

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setLocMassLine("Interest External Paid Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009215' extends '338558' salience 260

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Rental", ownUse03 == "61200001")
        
    then
        $gpy.setLocMassLine("Office Rental - Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009216' extends '338558' salience 250

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Rental", ownUse03 == "68500001")
        
    then
        $gpy.setLocMassLine("Office Rental - Recharge");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009220' extends '338558' salience 240

    when
        
        GrlPlYtd(this == $gpy, massLine == "Software Expenses not Capitalised")
        
    then
        $gpy.setLocMassLine("Leasing/Renting Locally Selected Software");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009221' extends '338558' salience 230

    when
        
        GrlPlYtd(this == $gpy, massLine == "Legal Expenses")
        
    then
        $gpy.setLocMassLine("Legal Fees");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009223' extends '338558' salience 220

    when
        
        GrlPlYtd(this == $gpy, massLine == "Salaries and Wages")
        
    then
        $gpy.setLocMassLine("Salaries and Wages Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009225' extends '338558' salience 210

    when
        
        GrlPlYtd(this == $gpy, massLine == "Intercompany Services Sold")
        
    then
        $gpy.setLocMassLine("IC Services Sold Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009227' extends '338558' salience 200

    when
        
        GrlPlYtd(this == $gpy, massLine == "Lease Cars Expenses")
        
    then
        $gpy.setLocMassLine("T&R - Lease Cars Related Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009229' extends '338558' salience 190

    when
        
        GrlPlYtd(this == $gpy, massLine == "Depr - Leasehold Improvements")
        
    then
        $gpy.setLocMassLine("Depr - Office Leasehold Improvements");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009230' extends '338558' salience 180

    when
        
        GrlPlYtd(this == $gpy, massLine == "Communication Expenses")
        
    then
        $gpy.setLocMassLine("Communications - Phones");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009232' extends '338558' salience 170

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Expenses")
        
    then
        $gpy.setLocMassLine("Sundry Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009243' extends '338558' salience 160

    when
        
        GrlPlYtd(this == $gpy, massLine == "Depreciation Software")
        
    then
        $gpy.setLocMassLine("Depreciation Locally Selected Software");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009244' extends '338558' salience 150

    when
        
        GrlPlYtd(this == $gpy, massLine == "Hardware Expenses not Capitalised")
        
    then
        $gpy.setLocMassLine("Leasing/Renting Locally Selected Hardware");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009063' extends '338558' salience 140

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Personnel Related Costs", hsoPlSubcl == "6403")
        
    then
        $gpy.setLocMassLine("Other Staff Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009126' extends '338558' salience 130

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Accommodation Expenses", hsoPlSubcl == "6502")
        
    then
        $gpy.setLocMassLine("Other Accommodation - Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009127' extends '338558' salience 120

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Accommodation Expenses", hsoPlSubcl == "6548")
        
    then
        $gpy.setLocMassLine("Other Accommodation - Cleaning");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009182' extends '338558' salience 110

    when
        
        GrlPlYtd(this == $gpy, massLine == "Travel related Costs", hsoPlSubcl == "6512")
        
    then
        $gpy.setLocMassLine("T&R - Representation");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009218' extends '338558' salience 100

    when
        
        GrlPlYtd(this == $gpy, massLine == "Payroll Taxes and Social Security", hsoPlSubcl == "6301")
        
    then
        $gpy.setLocMassLine("Payroll Taxes and Social Security Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009219' extends '338558' salience 90

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Professional Services", hsoPlSubcl == "6514")
        
    then
        $gpy.setLocMassLine("Other Prof Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009226' extends '338558' salience 80

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Supplies and Equipment", hsoPlSubcl in ("6509", "6595"))
        
    then
        $gpy.setLocMassLine("Other Office Supplies and Equipment Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009233' extends '338558' salience 70

    when
        
        GrlPlYtd(this == $gpy, massLine == "IC Services Bought Other", hsoPlSubcl == "6520")
        
    then
        $gpy.setLocMassLine("IC Services Bought Other - Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end

rule '2009242' extends '338558' salience 60

    when
        
        GrlPlYtd(this == $gpy, massLine == "Office Supplies and Equipment", hsoPlSubcl == "6613")
        
    then
        $gpy.setLocMassLine("Office Equipment Depreciation");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8531");
        
end


