package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlPlYtd;




dialect  "mvel"


rule '338561'
	when
		$gpy : GrlPlYtd(hpnPlCl != null && hpnPlCl not in ( "6000" , "7000" ) && hsoPlSubcl != 7401)
	then
        
end





rule '2009239' extends '338561' salience 50

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setLocMassLine(massLine );
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8534");
        
end

rule '2009234' extends '338561' salience 40

    when
        
        GrlPlYtd(this == $gpy, ownUse03 == "66850001")
        
    then
        $gpy.setLocMassLine("Interest External Paid Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8534");
        
end

rule '2009235' extends '338561' salience 30

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Expenses")
        
    then
        $gpy.setLocMassLine("Sundry Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8534");
        
end

rule '2009236' extends '338561' salience 20

    when
        
        GrlPlYtd(this == $gpy, massLine == "Funds Transfer Fees received")
        
    then
        $gpy.setLocMassLine(Warning: selecting from funds: data will not be available in source topic.
 full statement: Commissions from funds transfer);
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8534");
        
end

rule '2009237' extends '338561' salience 10

    when
        
        GrlPlYtd(this == $gpy, massLine == "Other Result of Trading Portfolio")
        
    then
        $gpy.setLocMassLine("FX Income");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"8534");
        
end


