package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '337151'
	when
		$gda : GrlDetAmounts()
	then
        
end





rule '1783523' extends '337151' salience 770

    when
        
        /*MANUAL adjustment here, because of error: Table gre_hr_ctry_ccy does not have an entry within the refDataApi within the dbConfig file*/
        
    then
        $gda.setConvCd("02");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"7190");
        
end

rule '1783524' extends '337151' salience 760

    when
        
        /*MANUAL adjustment here, because of error: Table gre_hr_ctry_ccy does not have an entry within the refDataApi within the dbConfig file*/
        
    then
        $gda.setConvCd("01");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"7190");
        
end


