package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '332584'
	when
		$gda : GrlDetAmounts()
	then
        
end





rule '1178739' extends '332584' salience 10

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setLocMassLine(massLine );
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3694");
        
end


