package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '331934'
	when
		$gda : GrlDetAmounts(customTxt04 != null)
	then
        
end





rule '1117350' extends '331934' salience 10

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxt10("L");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3314");
        
end


