package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;


dialect  "mvel"


rule '331947'
	when
		$gda : GrlDetAmounts(scyActCode in ( "A0017000" , "A0058000" , "A3291000" , "A3331000" , "A3333000" , "A4412000" , "A4564000" , "A4565000" , "A7985000" , "A7986000" , "A7987000" , "A7988000" , "A8294000" , "A8349000" , "A8609000" , "A9018000" , "L0237000" , "L0269000" ) && ( hreRelTypeIssuer in ( "ZABG" , "ZABS" , "ZAIN" , "ZCMB" , "ZCMG" , "ZMBG" , "ZMBS" , "ZMIN" , "ZRMB" , "ZSEC" ) || nvl(hreRelTypeIssuer, "") + nvl(custSeg, "") in ( "FAMTNBSEC" , "GAMTNBSEC" , "FAMTSECAM" , "GAMTSECAM" , "FAMTSECAS" , "GAMTSECAS" , "FAMTSECEU" , "GAMTSECEU" , "FGVONBSEC" , "FGVOSECAM" , "FGVOSECAS" , "FGVOSECEU" ) ))
	then
end


rule '1175110' extends '331947' salience 3770
no-loop
    when
        
        GrlDetAmounts(this == $gda, icInd == "Y", getCase0_1175110() == "NOT_INTERNAL")
        
    then
        $gda.setScyRteCode("010");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1184926' extends '331947' salience 3760
no-loop
    when
        
        GrlDetAmounts(this == $gda, icInd == "Y", getCase0_1175110() == "INTERNAL")
        
    then
        $gda.setScyRteCode(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1184925' extends '331947' salience 3750

    when
        
        GrlDetAmounts(this == $gda, htyTradCat == "03", icInd == "N", repAssetInd == "N")
        
    then
        $gda.setScyRteCode(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118426' extends '331947' salience 3740

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118487' extends '331947' salience 3730

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118436' extends '331947' salience 3720

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118437' extends '331947' salience 3710

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118420' extends '331947' salience 3700

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118494' extends '331947' salience 3690

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118419' extends '331947' salience 3680

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), hssSecuProdSubcl == "0280", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118421' extends '331947' salience 3670

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("5", "6", "7"), htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118422' extends '331947' salience 3660

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("8", "9", "10"), htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118423' extends '331947' salience 3650

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("11", "12", "13"), htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118424' extends '331947' salience 3640

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("14", "15", "16", "17", "18", "19"), htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118425' extends '331947' salience 3630

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("20", "21", "22"), htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118428' extends '331947' salience 3620

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), hssSecuProdSubcl == "0250", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118430' extends '331947' salience 3610

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), hssSecuProdSubcl == "0260", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118432' extends '331947' salience 3600

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), hssSecuProdSubcl == "0285", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118435' extends '331947' salience 3590

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), hssSecuProdSubcl == "0280", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118438' extends '331947' salience 3580

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), hssSecuProdSubcl == "0220", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118439' extends '331947' salience 3570

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), hssSecuProdSubcl == "0230", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118441' extends '331947' salience 3560

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), hssSecuProdSubcl == "0240", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118443' extends '331947' salience 3550

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), hssSecuProdSubcl == "0250", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118445' extends '331947' salience 3540

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), hssSecuProdSubcl == "0260", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118447' extends '331947' salience 3530

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), hssSecuProdSubcl == "0285", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163682' extends '331947' salience 3520

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118143' extends '331947' salience 3510

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118142' extends '331947' salience 3500

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118128' extends '331947' salience 3490

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118127' extends '331947' salience 3480

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118264' extends '331947' salience 3470

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118262' extends '331947' salience 3460

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118473' extends '331947' salience 3450

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118251' extends '331947' salience 3440

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118258' extends '331947' salience 3430

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163683' extends '331947' salience 3420

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163697' extends '331947' salience 3410

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163698' extends '331947' salience 3400

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118550' extends '331947' salience 3390

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", hssSecuProdSubcl == "0260", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118564' extends '331947' salience 3380

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", hssSecuProdSubcl == "0285", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118480' extends '331947' salience 3370

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118486' extends '331947' salience 3360

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", hssSecuProdSubcl == "0280", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118490' extends '331947' salience 3350

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118492' extends '331947' salience 3340

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118501' extends '331947' salience 3330

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", hssSecuProdSubcl == "0220", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118508' extends '331947' salience 3320

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", hssSecuProdSubcl == "0230", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118522' extends '331947' salience 3310

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", hssSecuProdSubcl == "0240", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118536' extends '331947' salience 3300

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", hssSecuProdSubcl == "0250", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118412' extends '331947' salience 3290

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("1", "2", "3", "4"), htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118413' extends '331947' salience 3280

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), hssSecuProdSubcl == "0220", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118414' extends '331947' salience 3270

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), hssSecuProdSubcl == "0230", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118416' extends '331947' salience 3260

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), hssSecuProdSubcl == "0240", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118472' extends '331947' salience 3250

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0280", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118446' extends '331947' salience 3240

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163708' extends '331947' salience 3230

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0285", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163681' extends '331947' salience 3220

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163684' extends '331947' salience 3210

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163685' extends '331947' salience 3200

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163687' extends '331947' salience 3190

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163689' extends '331947' salience 3180

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163691' extends '331947' salience 3170

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163693' extends '331947' salience 3160

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163696' extends '331947' salience 3150

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0280", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163699' extends '331947' salience 3140

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0220", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163700' extends '331947' salience 3130

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0230", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163702' extends '331947' salience 3120

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0240", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1184922' extends '331947' salience 3110

    when
        
        GrlDetAmounts(this == $gda, secuAssetCl in ("ABCP", "CBO", "CDO", "CLO", "CMBS", "CMO", "OTHER"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1184923' extends '331947' salience 3100

    when
        
        GrlDetAmounts(this == $gda, secuAssetCl in ("ABCP", "CBO", "CDO", "CLO", "CMBS", "CMO", "OTHER"), htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118497' extends '331947' salience 3090

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0220", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118535' extends '331947' salience 3080

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118484' extends '331947' salience 3070

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118542' extends '331947' salience 3060

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0260", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118546' extends '331947' salience 3050

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0260", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118549' extends '331947' salience 3040

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118554' extends '331947' salience 3030

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0285", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118558' extends '331947' salience 3020

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0285", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118563' extends '331947' salience 3010

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118479' extends '331947' salience 3000

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0280", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118485' extends '331947' salience 2990

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118499' extends '331947' salience 2980

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0220", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118504' extends '331947' salience 2970

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0230", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118506' extends '331947' salience 2960

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0230", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118514' extends '331947' salience 2950

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0240", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118518' extends '331947' salience 2940

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0240", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118521' extends '331947' salience 2930

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZSEC", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118528' extends '331947' salience 2920

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0250", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118532' extends '331947' salience 2910

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0250", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118415' extends '331947' salience 2900

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118417' extends '331947' salience 2890

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118418' extends '331947' salience 2880

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118427' extends '331947' salience 2870

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118429' extends '331947' salience 2860

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118431' extends '331947' salience 2850

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZCMB", "ZCMG"), ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118433' extends '331947' salience 2840

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118434' extends '331947' salience 2830

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118440' extends '331947' salience 2820

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118442' extends '331947' salience 2810

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118444' extends '331947' salience 2800

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZABG", "ZABS"), ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163706' extends '331947' salience 2790

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0260", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118380' extends '331947' salience 2780

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", secuAssetCl == "ALT-A", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118381' extends '331947' salience 2770

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", secuAssetCl == "ALT-A", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118296' extends '331947' salience 2760

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118300' extends '331947' salience 2750

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118308' extends '331947' salience 2740

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118312' extends '331947' salience 2730

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118320' extends '331947' salience 2720

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118324' extends '331947' salience 2710

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118335' extends '331947' salience 2700

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", secuAssetCl == "SUBPRIME", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118336' extends '331947' salience 2690

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", secuAssetCl == "SUBPRIME", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118250' extends '331947' salience 2680

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118257' extends '331947' salience 2670

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118261' extends '331947' salience 2660

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", secuAssetCl == "ALT-A", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118263' extends '331947' salience 2650

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", secuAssetCl == "ALT-A", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118268' extends '331947' salience 2640

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118270' extends '331947' salience 2630

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118274' extends '331947' salience 2620

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118276' extends '331947' salience 2610

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118284' extends '331947' salience 2600

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118288' extends '331947' salience 2590

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118206' extends '331947' salience 2580

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", secuAssetCl == "PRIME", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118207' extends '331947' salience 2570

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", secuAssetCl == "PRIME", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118165' extends '331947' salience 2560

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", secuAssetCl == "PRIME", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118126' extends '331947' salience 2550

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118129' extends '331947' salience 2540

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118130' extends '331947' salience 2530

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118132' extends '331947' salience 2520

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118134' extends '331947' salience 2510

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118136' extends '331947' salience 2500

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118138' extends '331947' salience 2490

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118141' extends '331947' salience 2480

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0280", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118144' extends '331947' salience 2470

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0220", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118145' extends '331947' salience 2460

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0230", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118147' extends '331947' salience 2450

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0240", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118149' extends '331947' salience 2440

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0250", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118151' extends '331947' salience 2430

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0260", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118153' extends '331947' salience 2420

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0285", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118164' extends '331947' salience 2410

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", secuAssetCl == "PRIME", htyTradCat in ("01", "02"), icInd == "N")
        
    then
        $gda.setScyRteCode("070");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163704' extends '331947' salience 2400

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0250", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118175' extends '331947' salience 2390

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118177' extends '331947' salience 2380

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118181' extends '331947' salience 2370

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118183' extends '331947' salience 2360

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118187' extends '331947' salience 2350

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118189' extends '331947' salience 2340

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118193' extends '331947' salience 2330

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118171' extends '331947' salience 2320

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118397' extends '331947' salience 2310

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0250", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118399' extends '331947' salience 2300

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0250", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118403' extends '331947' salience 2290

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0260", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118405' extends '331947' salience 2280

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0260", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118409' extends '331947' salience 2270

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0285", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118411' extends '331947' salience 2260

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0285", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118294' extends '331947' salience 2250

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118295' extends '331947' salience 2240

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118298' extends '331947' salience 2230

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118299' extends '331947' salience 2220

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118306' extends '331947' salience 2210

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118307' extends '331947' salience 2200

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118311' extends '331947' salience 2190

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118319' extends '331947' salience 2180

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118322' extends '331947' salience 2170

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118323' extends '331947' salience 2160

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118330' extends '331947' salience 2150

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118333' extends '331947' salience 2140

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118338' extends '331947' salience 2130

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118339' extends '331947' salience 2120

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118341' extends '331947' salience 2110

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118342' extends '331947' salience 2100

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118346' extends '331947' salience 2090

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118348' extends '331947' salience 2080

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118393' extends '331947' salience 2070

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0240", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118229' extends '331947' salience 2060

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0260", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118231' extends '331947' salience 2050

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0260", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118235' extends '331947' salience 2040

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0285", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118237' extends '331947' salience 2030

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0285", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118246' extends '331947' salience 2020

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118249' extends '331947' salience 2010

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118253' extends '331947' salience 2000

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118256' extends '331947' salience 1990

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118267' extends '331947' salience 1980

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118269' extends '331947' salience 1970

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118273' extends '331947' salience 1960

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118275' extends '331947' salience 1950

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118282' extends '331947' salience 1940

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118283' extends '331947' salience 1930

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118286' extends '331947' salience 1920

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118287' extends '331947' salience 1910

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0240", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118167' extends '331947' salience 1900

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118168' extends '331947' salience 1890

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0220", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1184921' extends '331947' salience 1880

    when
        
        GrlDetAmounts(this == $gda, hssSecuProdSubcl == "0285", secuAssetCl in ("ABCP", "CBO", "CDO", "CLO", "CMBS", "CMO", "OTHER"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118170' extends '331947' salience 1870

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0230", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163695' extends '331947' salience 1860

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118471' extends '331947' salience 1850

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118248' extends '331947' salience 1840

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118255' extends '331947' salience 1830

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118140' extends '331947' salience 1820

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118124' extends '331947' salience 1810

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118148' extends '331947' salience 1800

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118310' extends '331947' salience 1790

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118318' extends '331947' salience 1780

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118137' extends '331947' salience 1770

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163694' extends '331947' salience 1760

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118545' extends '331947' salience 1750

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118552' extends '331947' salience 1740

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118557' extends '331947' salience 1730

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118541' extends '331947' salience 1720

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118477' extends '331947' salience 1710

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118478' extends '331947' salience 1700

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118513' extends '331947' salience 1690

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118517' extends '331947' salience 1680

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1184920' extends '331947' salience 1670

    when
        
        GrlDetAmounts(this == $gda, hssSecuProdSubcl == "0260", secuAssetCl in ("ABCP", "CBO", "CDO", "CLO", "CMBS", "CMO", "OTHER"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118527' extends '331947' salience 1660

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118531' extends '331947' salience 1650

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118470' extends '331947' salience 1640

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118352' extends '331947' salience 1630

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118354' extends '331947' salience 1620

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0250", secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118358' extends '331947' salience 1610

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118360' extends '331947' salience 1600

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0260", secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118364' extends '331947' salience 1590

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118366' extends '331947' salience 1580

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118373' extends '331947' salience 1570

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0280", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118377' extends '331947' salience 1560

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0280", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118383' extends '331947' salience 1550

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0220", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118384' extends '331947' salience 1540

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0220", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118386' extends '331947' salience 1530

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0230", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118387' extends '331947' salience 1520

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0230", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118391' extends '331947' salience 1510

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", hssSecuProdSubcl == "0240", secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118195' extends '331947' salience 1500

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0285", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118201' extends '331947' salience 1490

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0280", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118204' extends '331947' salience 1480

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0280", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118209' extends '331947' salience 1470

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0220", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118210' extends '331947' salience 1460

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0220", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118212' extends '331947' salience 1450

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0230", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118213' extends '331947' salience 1440

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0230", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118217' extends '331947' salience 1430

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0240", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118219' extends '331947' salience 1420

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0240", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118223' extends '331947' salience 1410

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0250", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118225' extends '331947' salience 1400

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", hssSecuProdSubcl == "0250", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118125' extends '331947' salience 1390

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118131' extends '331947' salience 1380

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118133' extends '331947' salience 1370

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118135' extends '331947' salience 1360

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118139' extends '331947' salience 1350

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118146' extends '331947' salience 1340

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118150' extends '331947' salience 1330

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118152' extends '331947' salience 1320

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("FAMT", "FGVO", "GAMT"), hcyCtryCdIssuerRes != "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118159' extends '331947' salience 1310

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118162' extends '331947' salience 1300

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", hssSecuProdSubcl == "0280", secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163703' extends '331947' salience 1290

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163705' extends '331947' salience 1280

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163707' extends '331947' salience 1270

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163679' extends '331947' salience 1260

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163680' extends '331947' salience 1250

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163686' extends '331947' salience 1240

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163688' extends '331947' salience 1230

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163690' extends '331947' salience 1220

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163692' extends '331947' salience 1210

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1163701' extends '331947' salience 1200

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZAIN", "ZMIN"), hcyCtryCdIssuerRes != "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1184915' extends '331947' salience 1190

    when
        
        GrlDetAmounts(this == $gda, hssSecuProdSubcl == "0280", secuAssetCl in ("ABCP", "CBO", "CDO", "CLO", "CMBS", "CMO", "OTHER"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1184916' extends '331947' salience 1180

    when
        
        GrlDetAmounts(this == $gda, hssSecuProdSubcl == "0220", secuAssetCl in ("ABCP", "CBO", "CDO", "CLO", "CMBS", "CMO", "OTHER"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("110");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1184917' extends '331947' salience 1170

    when
        
        GrlDetAmounts(this == $gda, hssSecuProdSubcl == "0230", secuAssetCl in ("ABCP", "CBO", "CDO", "CLO", "CMBS", "CMO", "OTHER"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1184918' extends '331947' salience 1160

    when
        
        GrlDetAmounts(this == $gda, hssSecuProdSubcl == "0240", secuAssetCl in ("ABCP", "CBO", "CDO", "CLO", "CMBS", "CMO", "OTHER"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1184919' extends '331947' salience 1150

    when
        
        GrlDetAmounts(this == $gda, hssSecuProdSubcl == "0250", secuAssetCl in ("ABCP", "CBO", "CDO", "CLO", "CMBS", "CMO", "OTHER"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1184914' extends '331947' salience 1140

    when
        
        GrlDetAmounts(this == $gda, ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl in ("ABCP", "CBO", "CDO", "CLO", "CMBS", "CMO", "OTHER"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1184911' extends '331947' salience 1130

    when
        
        GrlDetAmounts(this == $gda, ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl in ("ABCP", "CBO", "CDO", "CLO", "CMBS", "CMO", "OTHER"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1184909' extends '331947' salience 1120

    when
        
        GrlDetAmounts(this == $gda, ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl in ("ABCP", "CBO", "CDO", "CLO", "CMBS", "CMO", "OTHER"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1184910' extends '331947' salience 1110

    when
        
        GrlDetAmounts(this == $gda, ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl in ("ABCP", "CBO", "CDO", "CLO", "CMBS", "CMO", "OTHER"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118157' extends '331947' salience 1100

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118376' extends '331947' salience 1090

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118332' extends '331947' salience 1080

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118158' extends '331947' salience 1070

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118398' extends '331947' salience 1060

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118297' extends '331947' salience 1050

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118182' extends '331947' salience 1040

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118224' extends '331947' salience 1030

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118359' extends '331947' salience 1020

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118402' extends '331947' salience 1010

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118305' extends '331947' salience 1000

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118186' extends '331947' salience 990

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118363' extends '331947' salience 980

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118234' extends '331947' salience 970

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1184913' extends '331947' salience 960

    when
        
        GrlDetAmounts(this == $gda, ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl in ("ABCP", "CBO", "CDO", "CLO", "CMBS", "CMO", "OTHER"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118245' extends '331947' salience 950

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118247' extends '331947' salience 940

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118254' extends '331947' salience 930

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118281' extends '331947' salience 920

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118285' extends '331947' salience 910

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118174' extends '331947' salience 900

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118176' extends '331947' salience 890

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118180' extends '331947' salience 880

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118188' extends '331947' salience 870

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118194' extends '331947' salience 860

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118199' extends '331947' salience 850

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118200' extends '331947' salience 840

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118202' extends '331947' salience 830

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118203' extends '331947' salience 820

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118216' extends '331947' salience 810

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118236' extends '331947' salience 800

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118218' extends '331947' salience 790

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118222' extends '331947' salience 780

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118160' extends '331947' salience 770

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118161' extends '331947' salience 760

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1184912' extends '331947' salience 750

    when
        
        GrlDetAmounts(this == $gda, ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl in ("ABCP", "CBO", "CDO", "CLO", "CMBS", "CMO", "OTHER"), htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118192' extends '331947' salience 740

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118252' extends '331947' salience 730

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118351' extends '331947' salience 720

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118353' extends '331947' salience 710

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118357' extends '331947' salience 700

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118365' extends '331947' salience 690

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118371' extends '331947' salience 680

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118372' extends '331947' salience 670

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118375' extends '331947' salience 660

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118390' extends '331947' salience 650

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118392' extends '331947' salience 640

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118396' extends '331947' salience 630

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118404' extends '331947' salience 620

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118408' extends '331947' salience 610

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "GB", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118410' extends '331947' salience 600

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "GB", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118293' extends '331947' salience 590

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("5", "6", "7"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("113");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118309' extends '331947' salience 580

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118317' extends '331947' salience 570

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118321' extends '331947' salience 560

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("11", "12", "13"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "ALT-A", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("115");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118328' extends '331947' salience 550

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118329' extends '331947' salience 540

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("20", "21", "22"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118331' extends '331947' salience 530

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("14", "15", "16", "17", "18", "19"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("008");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118345' extends '331947' salience 520

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118347' extends '331947' salience 510

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes == "US", ratingIng in ("1", "2", "3", "4"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "SUBPRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("112");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118228' extends '331947' salience 500

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer in ("ZMBG", "ZMBS"), hcyCtryCdIssuerRes != "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end

rule '1118230' extends '331947' salience 490

    when
        
        GrlDetAmounts(this == $gda, hreRelTypeIssuer == "ZRMB", hcyCtryCdIssuerRes != "US", ratingIng in ("8", "9", "10"), hssSecuProdSubcl not in ("0220", "0230", "0240", "0250", "0260", "0280", "0285"), secuAssetCl == "PRIME", htyTradCat == "03", icInd == "N", repAssetInd == "Y")
        
    then
        $gda.setScyRteCode("114");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"3328");
        
end


