package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlPlYtd;




dialect  "mvel"


rule '332856'
	when
		$gpy : GrlPlYtd()
	then
        
end





rule '1232039' extends '332856' salience 220

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setLocMassLine(massLine );
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1232040' extends '332856' salience 210

    when
        
        GrlPlYtd(this == $gpy, (plAcctId matches "60734X00.*" || plAcctId matches "60874X00.*" || plAcctId matches "69151X30.*" || plAcctId matches "70684X00.*"))
        
    then
        $gpy.setLocMassLine("Interest External Received (Core)");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1232041' extends '332856' salience 200

    when
        
        GrlPlYtd(this == $gpy, plAcctId matches "66830X00.*")
        
    then
        $gpy.setLocMassLine("Off Balance Fees received");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1232042' extends '332856' salience 190

    when
        
        GrlPlYtd(this == $gpy, plAcctId matches "69150X00.*")
        
    then
        $gpy.setLocMassLine("Other Result of Trading Portfolio");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1232043' extends '332856' salience 180

    when
        
        GrlPlYtd(this == $gpy, (plAcctId matches "69722X07.*" || plAcctId matches "69737X31.*" || plAcctId matches "69738X00.*" || plAcctId matches "79730X02ABB.*"))
        
    then
        $gpy.setLocMassLine("Other Personnel Related Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1232044' extends '332856' salience 170

    when
        
        GrlPlYtd(this == $gpy, (plAcctId matches "69734X11AAA.*" || plAcctId matches "69734X11AAG.*" || plAcctId matches "69734X11MAI.*"))
        
    then
        $gpy.setLocMassLine("IC Services Bought NL Direct Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1232045' extends '332856' salience 160

    when
        
        GrlPlYtd(this == $gpy, (plAcctId matches "69734X11AAB.*" || plAcctId matches "69736X04FBB.*" || plAcctId matches "69736X04MAI.*"))
        
    then
        $gpy.setLocMassLine("IC Services Bought Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1232046' extends '332856' salience 150

    when
        
        GrlPlYtd(this == $gpy, (plAcctId matches "69734X11ABB.*" || plAcctId matches "69736X04ABB.*"))
        
    then
        $gpy.setLocMassLine("IC Services Bought Belgium");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1232047' extends '332856' salience 140

    when
        
        GrlPlYtd(this == $gpy, (plAcctId matches "69736X04AAA.*" || plAcctId matches "69736X04AAG.*"))
        
    then
        $gpy.setLocMassLine("IC Services Bought NL Overhead Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1232048' extends '332856' salience 130

    when
        
        GrlPlYtd(this == $gpy, (plAcctId matches "69737X05.*" || plAcctId matches "69737X06.*"), massLine == "XX")
        
    then
        $gpy.setLocMassLine("Marketing");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1232049' extends '332856' salience 120

    when
        
        GrlPlYtd(this == $gpy, plAcctId matches "69737X17.*")
        
    then
        $gpy.setLocMassLine("Employee Education");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1232050' extends '332856' salience 110

    when
        
        GrlPlYtd(this == $gpy, (plAcctId matches "69737X18.*" || plAcctId matches "79730X05MNT.*"))
        
    then
        $gpy.setLocMassLine("Other Accommodation Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1232051' extends '332856' salience 100

    when
        
        GrlPlYtd(this == $gpy, (plAcctId matches "69737X19.*" || plAcctId matches "69737X21.*"))
        
    then
        $gpy.setLocMassLine("Pension Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1232052' extends '332856' salience 90

    when
        
        GrlPlYtd(this == $gpy, (plAcctId matches "69737X33AAA.*" || plAcctId matches "69737X33AAG.*" || plAcctId matches "79730X01ABB.*" || plAcctId matches "79730X09MNT.*"))
        
    then
        $gpy.setLocMassLine("Payroll Taxes and Social Security");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1232053' extends '332856' salience 80

    when
        
        GrlPlYtd(this == $gpy, (plAcctId matches "69737X48.*" || plAcctId matches "69737X61.*" || plAcctId matches "79730X09AAG.*" || plAcctId matches "79730X09ABB.*"))
        
    then
        $gpy.setLocMassLine("Other Professional Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1232055' extends '332856' salience 70

    when
        
        GrlPlYtd(this == $gpy, plAcctId matches "69737X66.*")
        
    then
        $gpy.setLocMassLine("Software Expenses not Capitalised");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1232057' extends '332856' salience 60

    when
        
        GrlPlYtd(this == $gpy, (plAcctId matches "69737X80.*" || plAcctId matches "69737X82.*"))
        
    then
        $gpy.setLocMassLine("Communication Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1241123' extends '332856' salience 50

    when
        
        GrlPlYtd(this == $gpy, (plAcctId matches "78715X02.*" || plAcctId matches "78750X01.*" || plAcctId matches "78750X05.*" || plAcctId matches "79750X07.*"))
        
    then
        $gpy.setLocMassLine("Other Commissions/Fees received");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1241124' extends '332856' salience 40

    when
        
        GrlPlYtd(this == $gpy, (plAcctId matches "79150X04.*" || plAcctId matches "79150X05.*" || plAcctId matches "79730X05AA7.*" || plAcctId matches "79730X05ABB.*" || plAcctId matches "79730X05MBH.*"))
        
    then
        $gpy.setLocMassLine("Intercompany Services Sold");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1241125' extends '332856' salience 30

    when
        
        GrlPlYtd(this == $gpy, (plAcctId matches "79730X01LLA.*" || plAcctId matches "79730X01MNT.*"))
        
    then
        $gpy.setLocMassLine("Salaries and Wages");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1241126' extends '332856' salience 20

    when
        
        GrlPlYtd(this == $gpy, (plAcctId matches "79730X02MBH.*" || plAcctId matches "79730X05LLA.*" || plAcctId matches "79823X62.*"))
        
    then
        $gpy.setLocMassLine("Office Rental");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end

rule '1700870' extends '332856' salience 10

    when
        
        GrlPlYtd(this == $gpy, plAcctId matches "78720X00.*")
        
    then
        $gpy.setLocMassLine("Interest External Received (Core)");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3784");
        
end


