package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '335209'
	when
		$gda : GrlDetAmounts(lseHlyRelId == "2222")
	then
        
end





rule '1697754' extends '335209' salience 720

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxt01("no det yet");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697766' extends '335209' salience 710

    when
        
        GrlDetAmounts(this == $gda, acctType == "SOXA")
        
    then
        $gda.setCustomTxt01("1102030");
        $gda.setCustomTxt02("intangible assets");
        $gda.setCustomTxt03("software");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697768' extends '335209' salience 700

    when
        
        GrlDetAmounts(this == $gda, acctType == "ECXA")
        
    then
        $gda.setCustomTxt01("1104900");
        $gda.setCustomTxt02("others");
        $gda.setCustomTxt03("other long-term deferred expenses");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697775' extends '335209' salience 690

    when
        
        GrlDetAmounts(this == $gda, acctType == "BCXA")
        
    then
        $gda.setCustomTxt01("1109040");
        $gda.setCustomTxt02("accumulated depreciation & amortization");
        $gda.setCustomTxt03("accumulated depreciation of transportation vehicles");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697827' extends '335209' salience 680

    when
        
        GrlDetAmounts(this == $gda, acctType == "AINP", ownUse12 == "REPO")
        
    then
        $gda.setCustomTxt01("2301160");
        $gda.setCustomTxt02("interest payables");
        $gda.setCustomTxt03("interest payables - repo");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697846' extends '335209' salience 670

    when
        
        GrlDetAmounts(this == $gda, acctType == "ACPA")
        
    then
        $gda.setCustomTxt01("2302900");
        $gda.setCustomTxt02("other account payables");
        $gda.setCustomTxt03("other accounts payable");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697744' extends '335209' salience 660

    when
        
        GrlDetAmounts(this == $gda, acctType == "CASH", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1001010");
        $gda.setCustomTxt02("cash");
        $gda.setCustomTxt03("notes and coins");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697759' extends '335209' salience 650

    when
        
        GrlDetAmounts(this == $gda, acctType == "NOST", hreRelTypeCtpy == "NHOF")
        
    then
        $gda.setCustomTxt01("3001091");
        $gda.setCustomTxt02("inter-affiliated bank and subsidiary transactions");
        $gda.setCustomTxt03("other exchanges with overseas headquarters");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697760' extends '335209' salience 640

    when
        
        GrlDetAmounts(this == $gda, acctType == "NOST", hreRelTypeCtpy == "NSGO")
        
    then
        $gda.setCustomTxt01("3001093");
        $gda.setCustomTxt02("inter-affiliated bank and subsidiary transactions");
        $gda.setCustomTxt03("other exchanges with overseas branches");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697764' extends '335209' salience 630

    when
        
        GrlDetAmounts(this == $gda, acctType == "TPLG", contSubtSrc == "DGM")
        
    then
        $gda.setCustomTxt01("1003030");
        $gda.setCustomTxt02("inter-bank transaction");
        $gda.setCustomTxt03("inter-bank lending");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697765' extends '335209' salience 620

    when
        
        GrlDetAmounts(this == $gda, acctType == "TPLG", contSubtSrc == "DGS")
        
    then
        $gda.setCustomTxt01("1003030");
        $gda.setCustomTxt02("inter-bank transaction");
        $gda.setCustomTxt03("inter-bank lending");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697767' extends '335209' salience 610

    when
        
        GrlDetAmounts(this == $gda, acctType == "LEXA", ownUse05 == "ACDEP-DECOR")
        
    then
        $gda.setCustomTxt01("1104900");
        $gda.setCustomTxt02("others");
        $gda.setCustomTxt03("other long-term deferred expenses");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697769' extends '335209' salience 600

    when
        
        GrlDetAmounts(this == $gda, acctType == "LEXA", ownUse05 == "CONSTR")
        
    then
        $gda.setCustomTxt01("1104900");
        $gda.setCustomTxt02("others");
        $gda.setCustomTxt03("other long-term deferred expenses");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697770' extends '335209' salience 590

    when
        
        GrlDetAmounts(this == $gda, acctType == "FUXA", ownUse05 == "ACDEP-FURN")
        
    then
        $gda.setCustomTxt01("1109020");
        $gda.setCustomTxt02("accumulated depreciation & amortization");
        $gda.setCustomTxt03("accumulated depreciation of furniture");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697771' extends '335209' salience 580

    when
        
        GrlDetAmounts(this == $gda, acctType == "CEXA", ownUse05 matches "ACDEP.*")
        
    then
        $gda.setCustomTxt01("1109030");
        $gda.setCustomTxt02("accumulated depreciation & amortization");
        $gda.setCustomTxt03("accumulated depreciation of electronic device");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697772' extends '335209' salience 570

    when
        
        GrlDetAmounts(this == $gda, acctType == "OMXA", ownUse05 == "ACDEP-TEL")
        
    then
        $gda.setCustomTxt01("1109030");
        $gda.setCustomTxt02("accumulated depreciation & amortization");
        $gda.setCustomTxt03("accumulated depreciation of electronic device");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697773' extends '335209' salience 560

    when
        
        GrlDetAmounts(this == $gda, acctType == "OTXA", ownUse05 matches "ACDEP.*")
        
    then
        $gda.setCustomTxt01("1109030");
        $gda.setCustomTxt02("accumulated depreciation & amortization");
        $gda.setCustomTxt03("accumulated depreciation of electronic device");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697774' extends '335209' salience 550

    when
        
        GrlDetAmounts(this == $gda, acctType == "PCXA", ownUse05 matches "ACDEP.*")
        
    then
        $gda.setCustomTxt01("1109030");
        $gda.setCustomTxt02("accumulated depreciation & amortization");
        $gda.setCustomTxt03("accumulated depreciation of electronic device");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697776' extends '335209' salience 540

    when
        
        GrlDetAmounts(this == $gda, acctType == "OMXA", ownUse05 == "ACDEP-EQUIP")
        
    then
        $gda.setCustomTxt01("1109040");
        $gda.setCustomTxt02("accumulated depreciation & amortization");
        $gda.setCustomTxt03("accumulated depreciation of transportation vehicles");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697777' extends '335209' salience 530

    when
        
        GrlDetAmounts(this == $gda, acctType == "ROBT", ownUse05 == "BIDOFFERADJ")
        
    then
        $gda.setCustomTxt01("1201010");
        $gda.setCustomTxt02("financial assets");
        $gda.setCustomTxt03("financial assets held for trading");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697778' extends '335209' salience 520

    when
        
        GrlDetAmounts(this == $gda, acctType == "ROBT", ownUse05 == "CVA")
        
    then
        $gda.setCustomTxt01("1201010");
        $gda.setCustomTxt02("financial assets");
        $gda.setCustomTxt03("financial assets held for trading");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697779' extends '335209' salience 510

    when
        
        GrlDetAmounts(this == $gda, acctType == "ROBT", ownUse05 == "MODELRISK")
        
    then
        $gda.setCustomTxt01("1201010");
        $gda.setCustomTxt02("financial assets");
        $gda.setCustomTxt03("financial assets held for trading");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697780' extends '335209' salience 500

    when
        
        GrlDetAmounts(this == $gda, acctType == "ROBT", ownUse05 == "RESERVE")
        
    then
        $gda.setCustomTxt01("1201010");
        $gda.setCustomTxt02("financial assets");
        $gda.setCustomTxt03("financial assets held for trading");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697835' extends '335209' salience 490

    when
        
        GrlDetAmounts(this == $gda, acctType == "AINR", ownUse12 == "DGM")
        
    then
        $gda.setCustomTxt01("1401100");
        $gda.setCustomTxt02("interest receivables");
        $gda.setCustomTxt03(Warning: selecting from inter-bank: data will not be available in source topic.
 full statement: interest receivables - due from inter-bank lending);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697837' extends '335209' salience 480

    when
        
        GrlDetAmounts(this == $gda, acctType == "AINR", ownUse12 == "BOND")
        
    then
        $gda.setCustomTxt01("1401110");
        $gda.setCustomTxt02("interest receivables");
        $gda.setCustomTxt03("interest receivables - bond investment");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697745' extends '335209' salience 470

    when
        
        GrlDetAmounts(this == $gda, acctType == "FUXA", ownUse05 == "FURN-FIXTURE", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1101030");
        $gda.setCustomTxt02("fixed assets");
        $gda.setCustomTxt03("furniture");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697747' extends '335209' salience 460

    when
        
        GrlDetAmounts(this == $gda, acctType == "BCXA", ownUse05 == "BK-VEHICAL", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1101050");
        $gda.setCustomTxt02("fixed assets");
        $gda.setCustomTxt03("transportation vehicles");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697748' extends '335209' salience 450

    when
        
        GrlDetAmounts(this == $gda, acctType == "BCXA", ownUse05 == "ACDEP-CAR", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1109040");
        $gda.setCustomTxt02("accumulated depreciation & amortization");
        $gda.setCustomTxt03("accumulated depreciation of transportation vehicles");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697749' extends '335209' salience 440

    when
        
        GrlDetAmounts(this == $gda, acctType == "CEXA", ownUse05 == "ACDEP-PC", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1109030");
        $gda.setCustomTxt02("accumulated depreciation & amortization");
        $gda.setCustomTxt03("accumulated depreciation of electronic device");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697750' extends '335209' salience 430

    when
        
        GrlDetAmounts(this == $gda, acctType == "CEXA", ownUse05 == "ACDEP-MF", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1109030");
        $gda.setCustomTxt02("accumulated depreciation & amortization");
        $gda.setCustomTxt03("accumulated depreciation of electronic device");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697751' extends '335209' salience 420

    when
        
        GrlDetAmounts(this == $gda, acctType == "CEXA", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1109030");
        $gda.setCustomTxt02("accumulated depreciation & amortization");
        $gda.setCustomTxt03("accumulated depreciation of electronic device");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697758' extends '335209' salience 410

    when
        
        /*MANUAL adjustment here, because of error: Table gpl_relations does not have an entry within the refDataApi within the dbConfig file*/
        GrlDetAmounts(this == $gda, acctType == "NOST", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1003010");
        $gda.setCustomTxt02("inter-bank transaction");
        $gda.setCustomTxt03(Warning: selecting from bank: data will not be available in source topic.
 full statement: due from bank - demand);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697761' extends '335209' salience 400

    when
        
        GrlDetAmounts(this == $gda, acctType == "OMXA", ownUse05 == "GENOFF-EQUIP", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1101060");
        $gda.setCustomTxt02("fixed assets");
        $gda.setCustomTxt03("transportation vehicles");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697762' extends '335209' salience 390

    when
        
        GrlDetAmounts(this == $gda, acctType == "REGP", ownUse12 == "RGPL", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1003020");
        $gda.setCustomTxt02("inter-bank transaction");
        $gda.setCustomTxt03(Warning: selecting from bank: data will not be available in source topic.
 full statement: due from bank - term);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697763' extends '335209' salience 380

    when
        
        GrlDetAmounts(this == $gda, acctType == "REGP", ownUse05 == "DEPOINSFUND", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1003020");
        $gda.setCustomTxt02("inter-bank transaction");
        $gda.setCustomTxt03(Warning: selecting from bank: data will not be available in source topic.
 full statement: due from bank - term);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697822' extends '335209' salience 370

    when
        
        GrlDetAmounts(this == $gda, acctType == "AINR", ownUse12 in ("IRSG", "IRST"), repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1201010");
        $gda.setCustomTxt02("financial assets");
        $gda.setCustomTxt03("financial assets held for trading");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697823' extends '335209' salience 360

    when
        
        GrlDetAmounts(this == $gda, acctType == "ROBT", ownUse12 in ("IRSG", "IRST"), repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1201010");
        $gda.setCustomTxt02("financial assets");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697824' extends '335209' salience 350

    when
        
        GrlDetAmounts(this == $gda, acctType == "AINP", ownUse12 in ("DTV", "DTP"), repAssetInd == "N")
        
    then
        $gda.setCustomTxt01("2301010");
        $gda.setCustomTxt02("interest payables");
        $gda.setCustomTxt03("interest payables - whole sale term deposit");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697825' extends '335209' salience 340

    when
        
        GrlDetAmounts(this == $gda, acctType == "AINP", ownUse12 == "DTC", repAssetInd == "N")
        
    then
        $gda.setCustomTxt01("2301050");
        $gda.setCustomTxt02("interest payables");
        $gda.setCustomTxt03("interest payables - notice deposit");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697828' extends '335209' salience 330

    when
        
        GrlDetAmounts(this == $gda, acctType == "AINP", ownUse05 == "ACCT-SAVG", repAssetInd == "N")
        
    then
        $gda.setCustomTxt01("2301030");
        $gda.setCustomTxt02("interest payables");
        $gda.setCustomTxt03("interest payables - whole sale demand deposit");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697830' extends '335209' salience 320

    when
        
        GrlDetAmounts(this == $gda, acctType == "AINP", hreRelTypeCtpy matches "N.*", repAssetInd == "N")
        
    then
        $gda.setCustomTxt01("2301900");
        $gda.setCustomTxt02("interest payables");
        $gda.setCustomTxt03("other interest payables");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697831' extends '335209' salience 310

    when
        
        GrlDetAmounts(this == $gda, acctType == "AINR", ownUse12 in ("LFIX", "LVAR"), repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1401010");
        $gda.setCustomTxt02("interest receivables");
        $gda.setCustomTxt03("interest receivables - corporate loan");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697832' extends '335209' salience 300

    when
        
        GrlDetAmounts(this == $gda, acctType == "AINR", ownUse12 == "LPAR", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1401030");
        $gda.setCustomTxt02("interest receivables");
        $gda.setCustomTxt03("interest receivables - syndicated loan");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697833' extends '335209' salience 290

    when
        
        GrlDetAmounts(this == $gda, acctType == "AINR", ownUse05 == "ACCT-NOST", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1401080");
        $gda.setCustomTxt02("interest receivables");
        $gda.setCustomTxt03(Warning: selecting from central: data will not be available in source topic.
 full statement: interest receivables - due from central bank);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697834' extends '335209' salience 280

    when
        
        GrlDetAmounts(this == $gda, acctType == "AINR", ownUse12 == "RGPL", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1401090");
        $gda.setCustomTxt02("interest receivables");
        $gda.setCustomTxt03(Warning: selecting from bank: data will not be available in source topic.
 full statement: interest receivables - due from bank);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697840' extends '335209' salience 270

    when
        
        GrlDetAmounts(this == $gda, acctType == "LADV", ownUse05 == "HLMBENZ", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1003030");
        $gda.setCustomTxt02("inter-bank transaction");
        $gda.setCustomTxt03("inter-bank lending");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697841' extends '335209' salience 260

    when
        
        GrlDetAmounts(this == $gda, acctType == "LADV", ownUse05 == "VWFINANCE", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1003030");
        $gda.setCustomTxt02("inter-bank transaction");
        $gda.setCustomTxt03("inter-bank lending");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697842' extends '335209' salience 250

    when
        
        GrlDetAmounts(this == $gda, acctType == "LADV", ownUse05 == "HLMTOYOTA", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1003030");
        $gda.setCustomTxt02("inter-bank transaction");
        $gda.setCustomTxt03("inter-bank lending");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697843' extends '335209' salience 240

    when
        
        GrlDetAmounts(this == $gda, acctType == "LADV", ownUse05 == "HLMBMW", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1003030");
        $gda.setCustomTxt02("inter-bank transaction");
        $gda.setCustomTxt03("inter-bank lending");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697844' extends '335209' salience 230

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1201010");
        $gda.setCustomTxt02("financial assets");
        $gda.setCustomTxt03("financial assets held for trading");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697845' extends '335209' salience 220

    when
        
        GrlDetAmounts(this == $gda, acctType == "REMM", ownUse12 in ("DGM", "REPO"), repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1201010");
        $gda.setCustomTxt02("financial assets");
        $gda.setCustomTxt03("financial assets held for trading");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697756' extends '335209' salience 210

    when
        
        /*MANUAL adjustment here, because of error: Table gpl_relations does not have an entry within the refDataApi within the dbConfig file*/
        GrlDetAmounts(this == $gda, acctType == "NOST", hreRelTypeCtpy == "BCEN", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1002020");
        $gda.setCustomTxt02(Warning: selecting from central: data will not be available in source topic.
 full statement: due from central bank);
        $gda.setCustomTxt03("excess reserve");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697757' extends '335209' salience 200

    when
        
        /*MANUAL adjustment here, because of error: Table gpl_relations does not have an entry within the refDataApi within the dbConfig file*/
        GrlDetAmounts(this == $gda, acctType == "NOST", hreRelTypeCtpy == "BCEN", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1002900");
        $gda.setCustomTxt02(Warning: selecting from central: data will not be available in source topic.
 full statement: due from central bank);
        $gda.setCustomTxt03("other deposit in central bank");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697826' extends '335209' salience 190

    when
        
        GrlDetAmounts(this == $gda, acctType == "AINP", ownUse12 == "DTM", hreRelTypeCtpy not matches "N.*", repAssetInd == "N")
        
    then
        $gda.setCustomTxt01("2301150");
        $gda.setCustomTxt02("interest payables");
        $gda.setCustomTxt03("interest payables - inter-bank lending");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697829' extends '335209' salience 180

    when
        
        GrlDetAmounts(this == $gda, acctType == "AINP", ownUse05 == "ACCT-LORO", hreRelTypeCtpy not matches "N.*", repAssetInd == "N")
        
    then
        $gda.setCustomTxt01("2301130");
        $gda.setCustomTxt02("interest payables");
        $gda.setCustomTxt03(Warning: selecting from bank: data will not be available in source topic.
 full statement: interest payables - due from bank);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697836' extends '335209' salience 170

    when
        
        /*MANUAL adjustment here, because of error: Table gpl_relations does not have an entry within the refDataApi within the dbConfig file*/
        GrlDetAmounts(this == $gda, lseHlyRelId matches "SHRMB.*", acctType == "AINR", ownUse12 in ("LFIX", "LVAR"), repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1401100");
        $gda.setCustomTxt02("interest receivables");
        $gda.setCustomTxt03(Warning: selecting from inter-bank: data will not be available in source topic.
 full statement: interest receivables - due from inter-bank lending);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697838' extends '335209' salience 160

    when
        
        GrlDetAmounts(this == $gda, acctType == "LADV", ownUse12 in ("LFIX", "LVAR"), hreRelTypeCtpy matches "B.*", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1003030");
        $gda.setCustomTxt02("inter-bank transaction");
        $gda.setCustomTxt03("inter-bank lending");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697839' extends '335209' salience 150

    when
        
        GrlDetAmounts(this == $gda, acctType == "LADV", ownUse12 in ("LFIX", "LVAR"), hreRelTypeCtpy matches "F.*", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1003030");
        $gda.setCustomTxt02("inter-bank transaction");
        $gda.setCustomTxt03("inter-bank lending");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end

rule '1697755' extends '335209' salience 140

    when
        
        /*MANUAL adjustment here, because of error: Table gpl_relations does not have an entry within the refDataApi within the dbConfig file*/
        GrlDetAmounts(this == $gda, acctType == "NOST", ownUse12 == "OVDRFT", hreRelTypeCtpy == "BCEN", repAssetInd == "Y")
        
    then
        $gda.setCustomTxt01("1002010");
        $gda.setCustomTxt02(Warning: selecting from central: data will not be available in source topic.
 full statement: due from central bank);
        $gda.setCustomTxt03("legal deposit reserve");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5736");
        
end


