package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '330095'
	when
		$gda : GrlDetAmounts(( contingInd == "N" || contingInd == null ) && ( hacAmtCl in ( "01" , "16" ) ) && ( lseId != null && lseId != null && lseId not in ( "9349" , "19165" , "19230" , "20684" , "20695" , "20698" ) ) && ( posGroupId != null && posGroupId not in ( "10703" , "20601" , "20606" ) ) && ( nvl ( prodSubTypeLoc , 0 ) != "WASH" ) && ( hpePdtType != "POS MOV" ) && ( posGroupId matches "2.*" ))
	then
        
end





rule '824136' extends '330095' salience 3030

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxt11("NOT FOUND seq 11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823949' extends '330095' salience 3020

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20716")
        
    then
        $gda.setCustomTxt11("20716");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823958' extends '330095' salience 3010

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20715")
        
    then
        $gda.setCustomTxt11("20715");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823963' extends '330095' salience 3000

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20706")
        
    then
        $gda.setCustomTxt11("20706");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823988' extends '330095' salience 2990

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21801")
        
    then
        $gda.setCustomTxt11("21801");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823990' extends '330095' salience 2980

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20602")
        
    then
        $gda.setCustomTxt11("20602");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823992' extends '330095' salience 2970

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20607")
        
    then
        $gda.setCustomTxt11("20607");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823996' extends '330095' salience 2960

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20605")
        
    then
        $gda.setCustomTxt11("20605");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824001' extends '330095' salience 2950

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20401")
        
    then
        $gda.setCustomTxt11("20401");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824016' extends '330095' salience 2940

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20701")
        
    then
        $gda.setCustomTxt11("20701");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824021' extends '330095' salience 2930

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20802")
        
    then
        $gda.setCustomTxt11("20802");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824023' extends '330095' salience 2920

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20502")
        
    then
        $gda.setCustomTxt11("20502");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824025' extends '330095' salience 2910

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20712")
        
    then
        $gda.setCustomTxt11("20712");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824031' extends '330095' salience 2900

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20604")
        
    then
        $gda.setCustomTxt11("20604");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824034' extends '330095' salience 2890

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21101")
        
    then
        $gda.setCustomTxt11("21101");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824036' extends '330095' salience 2880

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21901")
        
    then
        $gda.setCustomTxt11("21901");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824038' extends '330095' salience 2870

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20612")
        
    then
        $gda.setCustomTxt11("20612");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824067' extends '330095' salience 2860

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20201")
        
    then
        $gda.setCustomTxt11("20201");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824077' extends '330095' salience 2850

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21001")
        
    then
        $gda.setCustomTxt11("21001");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824079' extends '330095' salience 2840

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20801")
        
    then
        $gda.setCustomTxt11("20801");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824080' extends '330095' salience 2830

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20901")
        
    then
        $gda.setCustomTxt11("20901");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824083' extends '330095' salience 2820

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20603")
        
    then
        $gda.setCustomTxt11("20603");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824084' extends '330095' salience 2810

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20608")
        
    then
        $gda.setCustomTxt11("20608");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824085' extends '330095' salience 2800

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20609")
        
    then
        $gda.setCustomTxt11("20609");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824093' extends '330095' salience 2790

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20702")
        
    then
        $gda.setCustomTxt11("20702");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824097' extends '330095' salience 2780

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20703")
        
    then
        $gda.setCustomTxt11("20703");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824098' extends '330095' salience 2770

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20705")
        
    then
        $gda.setCustomTxt11("20705");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824099' extends '330095' salience 2760

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20707")
        
    then
        $gda.setCustomTxt11("20707");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824100' extends '330095' salience 2750

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20710")
        
    then
        $gda.setCustomTxt11("20710");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824101' extends '330095' salience 2740

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20711")
        
    then
        $gda.setCustomTxt11("20711");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824102' extends '330095' salience 2730

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20717")
        
    then
        $gda.setCustomTxt11("20717");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824103' extends '330095' salience 2720

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21002")
        
    then
        $gda.setCustomTxt11("21002");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824104' extends '330095' salience 2710

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21003")
        
    then
        $gda.setCustomTxt11("21003");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824108' extends '330095' salience 2700

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21004")
        
    then
        $gda.setCustomTxt11("21004");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824109' extends '330095' salience 2690

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21201")
        
    then
        $gda.setCustomTxt11("21201");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824124' extends '330095' salience 2680

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20101")
        
    then
        $gda.setCustomTxt11("20101 NET");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824126' extends '330095' salience 2670

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20102")
        
    then
        $gda.setCustomTxt11("20102");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824127' extends '330095' salience 2660

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20301")
        
    then
        $gda.setCustomTxt11("20301");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824736' extends '330095' salience 2650

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20713")
        
    then
        $gda.setCustomTxt11("20713");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824746' extends '330095' salience 2640

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "29000")
        
    then
        $gda.setCustomTxt11("29000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '826348' extends '330095' salience 2630

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20718")
        
    then
        $gda.setCustomTxt11("20718");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823948' extends '330095' salience 2620

    when
        
        GrlDetAmounts(this == $gda, prodSubSubTypeLoc == "CPI", posGroupId == "20401")
        
    then
        $gda.setCustomTxt11("20401 CD'S ISSUED CP ISS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823950' extends '330095' salience 2610

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20716", prodSubTypeLoc == "PRPL")
        
    then
        $gda.setCustomTxt11("20716 PROV.PENSION LIAB.");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823964' extends '330095' salience 2600

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20706", prodSubTypeLoc == "PRVB")
        
    then
        $gda.setCustomTxt11("20706 PROV BONDS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823965' extends '330095' salience 2590

    when
        
        GrlDetAmounts(this == $gda, prodSubSubTypeLoc == "LTKN", posGroupId == "20802")
        
    then
        $gda.setCustomTxt11("20802 BOND LNS & BORR FNDS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823966' extends '330095' salience 2580

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20609", prodSubTypeLoc == "SSTL")
        
    then
        $gda.setCustomTxt11("20609 SECURITIES SETTLEMEN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823970' extends '330095' salience 2570

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20301", prodSubTypeLoc == "TDPT")
        
    then
        $gda.setCustomTxt11("20301 TERM DEPOSITS TAKEN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823975' extends '330095' salience 2560

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20603", prodSubTypeLoc == "INRA")
        
    then
        $gda.setCustomTxt11("20603 INTEREST RCV ADVANCE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823976' extends '330095' salience 2550

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20608", prodSubTypeLoc == "LASD")
        
    then
        $gda.setCustomTxt11("20608 DISCOUNT A/TRADING");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823977' extends '330095' salience 2540

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20710", prodSubTypeLoc == "PRDC")
        
    then
        $gda.setCustomTxt11("20710 PROV DOUBT CRI 100%");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823978' extends '330095' salience 2530

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20711", prodSubTypeLoc == "PRDG")
        
    then
        $gda.setCustomTxt11("20711 PROV DOUBT GOV 100%");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823979' extends '330095' salience 2520

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20717", prodSubTypeLoc == "PRRR")
        
    then
        $gda.setCustomTxt11("20717 PROV.REORG.&REALLOC.");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823980' extends '330095' salience 2510

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20703", prodSubTypeLoc == "PRVN")
        
    then
        $gda.setCustomTxt11("20703 PRV INT NPLN DBT 50%");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823984' extends '330095' salience 2500

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20605", prodSubTypeLoc == "DCRI")
        
    then
        $gda.setCustomTxt11("20605 DISCOUNT RCV INVESTM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823989' extends '330095' salience 2490

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21801", prodSubTypeLoc == "ACPB")
        
    then
        $gda.setCustomTxt11("21801 ACCEPTANCES BANK LB");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823991' extends '330095' salience 2480

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20602", prodSubTypeLoc == "AFCP")
        
    then
        $gda.setCustomTxt11("20602 ACCR FEES/COMM PAY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '823993' extends '330095' salience 2470

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20607", prodSubTypeLoc == "CHON")
        
    then
        $gda.setCustomTxt11("20607 CHEQUES DRAWN OURS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824002' extends '330095' salience 2460

    when
        
        GrlDetAmounts(this == $gda, prodSubSubTypeLoc == "CDIV", posGroupId == "20401")
        
    then
        $gda.setCustomTxt11("20401 CD'S ISSUED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824008' extends '330095' salience 2450

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20102", prodSubTypeLoc == "COVR")
        
    then
        $gda.setCustomTxt11("20102 COVER ACCOUNTS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824012' extends '330095' salience 2440

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20201", prodSubTypeLoc == "CAL1")
        
    then
        $gda.setCustomTxt11("20201 CALL (1 DAY)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824013' extends '330095' salience 2430

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20201", prodSubTypeLoc == "CAL7")
        
    then
        $gda.setCustomTxt11("20201 CALL (7 DAYS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824014' extends '330095' salience 2420

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20201", prodSubTypeLoc == "CAL2")
        
    then
        $gda.setCustomTxt11("20201 CALL (2 DAYS)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824015' extends '330095' salience 2410

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20502", prodSubTypeLoc == "SAVG")
        
    then
        $gda.setCustomTxt11("20502 SAVINGS ACCOUNTS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824017' extends '330095' salience 2400

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21004", prodSubTypeLoc == "MCSF")
        
    then
        $gda.setCustomTxt11("21004 MON.CORR.CAPITAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824018' extends '330095' salience 2390

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21901", prodSubTypeLoc == "LCDB")
        
    then
        $gda.setCustomTxt11("21901 DEFEERED PAYM BANK L");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824019' extends '330095' salience 2380

    when
        
        GrlDetAmounts(this == $gda, prodSubSubTypeLoc in ("DTS", "DTSX"), posGroupId == "20301")
        
    then
        $gda.setCustomTxt11("20301 TERM DEPOSITS TAKEN DTSX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824022' extends '330095' salience 2370

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20802", prodSubTypeLoc == "BORF")
        
    then
        $gda.setCustomTxt11("20802 BOND LNS & BORR FNDS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824026' extends '330095' salience 2360

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20712", prodSubTypeLoc == "PRDT")
        
    then
        $gda.setCustomTxt11("20712 DEFERRED TAX CREDIT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824032' extends '330095' salience 2350

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20604", prodSubTypeLoc == "FCRA")
        
    then
        $gda.setCustomTxt11("20604 FEES/COM RCV ADVANCE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824033' extends '330095' salience 2340

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20603", prodSubTypeLoc == "AMLI")
        
    then
        $gda.setCustomTxt11("20603 AMORTISATION LIABIL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824039' extends '330095' salience 2330

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20612", prodSubTypeLoc == "ROBT")
        
    then
        $gda.setCustomTxt11("20612 REV.OFF BAL/INSTR.TR NET");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824053' extends '330095' salience 2320

    when
        
        GrlDetAmounts(this == $gda, prodSubSubTypeLoc == "DTC", posGroupId == "20201")
        
    then
        $gda.setCustomTxt11("20201 CALL DEPOSITS TAKEN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824054' extends '330095' salience 2310

    when
        
        GrlDetAmounts(this == $gda, prodSubSubTypeLoc in ("DTF", "DTM", "DTP", "DTV"), posGroupId == "20301")
        
    then
        $gda.setCustomTxt11("20301 TERM DEPOSITS TAKEN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824055' extends '330095' salience 2300

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20705", prodSubTypeLoc == "PRVT")
        
    then
        $gda.setCustomTxt11("20705 PROV CORPORATE TAX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824056' extends '330095' salience 2290

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20707", prodSubTypeLoc == "PRVO")
        
    then
        $gda.setCustomTxt11("20707 PROV OTHER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824057' extends '330095' salience 2280

    when
        
        GrlDetAmounts(this == $gda, prodSubSubTypeLoc == "SULT", posGroupId == "20801")
        
    then
        $gda.setCustomTxt11("20801 SUBORDINATED LOANS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824058' extends '330095' salience 2270

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21001", prodSubTypeLoc == "SCAP")
        
    then
        $gda.setCustomTxt11("21001 SHARE CAPITAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824059' extends '330095' salience 2260

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21002", prodSubTypeLoc == "WCAP")
        
    then
        $gda.setCustomTxt11("21002 WORKING CAPITAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824060' extends '330095' salience 2250

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21003", prodSubTypeLoc == "OTSV")
        
    then
        $gda.setCustomTxt11("21003 OTHER RESERVES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824061' extends '330095' salience 2240

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21003", prodSubTypeLoc == "RESV")
        
    then
        $gda.setCustomTxt11("21003 RESERVES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824062' extends '330095' salience 2230

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21003", prodSubTypeLoc == "RRRE")
        
    then
        $gda.setCustomTxt11("21003 REV RES ESTATE/ASSET");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824063' extends '330095' salience 2220

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21003", prodSubTypeLoc == "SHSV")
        
    then
        $gda.setCustomTxt11("21003 SHARE PREMIUM RESERV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824064' extends '330095' salience 2210

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21004", prodSubTypeLoc == "BPLP")
        
    then
        $gda.setCustomTxt11("21004 BAL P&L PREV YEARS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824065' extends '330095' salience 2200

    when
        
        GrlDetAmounts(this == $gda, prodSubSubTypeLoc == "REPO", posGroupId == "21201")
        
    then
        $gda.setCustomTxt11("21201 SEC.SOLD REPUR.AGR.");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824066' extends '330095' salience 2190

    when
        
        GrlDetAmounts(this == $gda, prodSubSubTypeLoc in ("DTI", "DTIX"), posGroupId == "20010")
        
    then
        $gda.setCustomTxt11("DTI/DTIX");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824076' extends '330095' salience 2180

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20701", prodSubTypeLoc == "PRVG")
        
    then
        $gda.setCustomTxt11("20701 PROV GEN OPERATING");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824086' extends '330095' salience 2170

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20609", prodSubTypeLoc == "ACPA")
        
    then
        $gda.setCustomTxt11("20609 ACCOUNTS PAYABLE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824087' extends '330095' salience 2160

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20609", prodSubTypeLoc == "BOAC")
        
    then
        $gda.setCustomTxt11("20609 BONUS ACCRUAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824088' extends '330095' salience 2150

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20609", prodSubTypeLoc == "OTHL")
        
    then
        $gda.setCustomTxt11("20609 OTHER LIABILITIES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824089' extends '330095' salience 2140

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20609", prodSubTypeLoc == "OTTP")
        
    then
        $gda.setCustomTxt11("20609 OTHER TAXES PAYABLE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824090' extends '330095' salience 2130

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20609", prodSubTypeLoc == "PEFP")
        
    then
        $gda.setCustomTxt11("20609 PENSION FEES PAYABLE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824091' extends '330095' salience 2120

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20609", prodSubTypeLoc == "SOSP")
        
    then
        $gda.setCustomTxt11("20609 SOC.SECURITY PAYABLE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824092' extends '330095' salience 2110

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20609", prodSubTypeLoc == "SSPL")
        
    then
        $gda.setCustomTxt11("20609 SUSPENSE LIABILITIES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824094' extends '330095' salience 2100

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20702", prodSubTypeLoc == "PROI")
        
    then
        $gda.setCustomTxt11("20702 PROV DOUBT OTH 0%");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824095' extends '330095' salience 2090

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20702", prodSubTypeLoc == "PRVD")
        
    then
        $gda.setCustomTxt11("20702 PROV DOUBT OTH 100%");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824096' extends '330095' salience 2080

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20702", prodSubTypeLoc == "PROJ")
        
    then
        $gda.setCustomTxt11("20702 PROV DOUBT OTH 20%");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824105' extends '330095' salience 2070

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21003", prodSubTypeLoc == "AVSV")
        
    then
        $gda.setCustomTxt11("21003 ASSET VALUATION RSV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824106' extends '330095' salience 2060

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21003", prodSubTypeLoc == "LITR")
        
    then
        $gda.setCustomTxt11("21003 LITIGATION RESERVE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824107' extends '330095' salience 2050

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "21003", prodSubTypeLoc == "RRIP")
        
    then
        $gda.setCustomTxt11("21003 REV RES INVESTM PORT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824125' extends '330095' salience 2040

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20501", assetInd == "Y")
        
    then
        $gda.setCustomTxt11("20501 ASSET");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824737' extends '330095' salience 2030

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20713", prodSubTypeLoc == "PRER")
        
    then
        $gda.setCustomTxt11("20713 PROV EARLY RETIREM.");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824747' extends '330095' salience 2020

    when
        
        GrlDetAmounts(this == $gda, prodSubSubTypeLoc == "UCL", posGroupId == "29000")
        
    then
        $gda.setCustomTxt11("29000 UNSPECIFIED LIABIL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824929' extends '330095' salience 2010

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20501", assetInd == "N")
        
    then
        $gda.setCustomTxt11("20501 LIABILITY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824939' extends '330095' salience 2000

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20604", prodSubTypeLoc == "FCRC")
        
    then
        $gda.setCustomTxt11("20604 FEES/COM RCV ADVANCE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '826356' extends '330095' salience 1990

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20715", prodSubTypeLoc == "PRNS")
        
    then
        $gda.setCustomTxt11("20715 OTH.NON-ACT.SCHEMES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '826361' extends '330095' salience 1980

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20718", prodSubTypeLoc == "PRSB")
        
    then
        $gda.setCustomTxt11("20718 PR SHARE BAS PAYMENT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '1005536' extends '330095' salience 1970

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "29999", prodSubTypeLoc == "SPOS")
        
    then
        $gda.setCustomTxt11("29999 SPOS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824009' extends '330095' salience 1960

    when
        
        GrlDetAmounts(this == $gda, prodSubSubTypeLoc == "CORP", posGroupId == "20102", prodSubTypeLoc == "COVR")
        
    then
        $gda.setCustomTxt11("20102 COVER ACCOUNTS CORP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824010' extends '330095' salience 1950

    when
        
        GrlDetAmounts(this == $gda, prodSubSubTypeLoc == "CSRV", posGroupId == "20102", prodSubTypeLoc == "COVR")
        
    then
        $gda.setCustomTxt11("20102 COVER ACCOUNTS CSRV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824011' extends '330095' salience 1940

    when
        
        GrlDetAmounts(this == $gda, prodSubSubTypeLoc == "TFIN", posGroupId == "20102", prodSubTypeLoc == "COVR")
        
    then
        $gda.setCustomTxt11("20102 COVER ACCOUNTS TFIN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '824035' extends '330095' salience 1930

    when
        
        GrlDetAmounts(this == $gda, prodSubSubTypeLoc == "SECS", posGroupId == "21101", prodSubTypeLoc == "SESS")
        
    then
        $gda.setCustomTxt11("21101 SECURITY SOLD SHORT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '1038738' extends '330095' salience 1920
no-loop
    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20609", prodSubTypeLoc == "SSTL", assetInd == "N", getCase0_1047522() == "PEND-SETTL")
        
    then
        $gda.setCustomTxt11("PEND-SETTL NTBR SSTL LI");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end

rule '1047522' extends '330095' salience 1910
no-loop
    when
        
        GrlDetAmounts(this == $gda, posGroupId == "20609", prodSubTypeLoc == "SSTL", assetInd == "Y", getCase0_1047522() == "PEND-SETTL")
        
    then
        $gda.setCustomTxt11("PEND-SETTL NTBR SSTL AS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1981");
        
end


