package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '330094'
	when
		$gda : GrlDetAmounts(( contingInd == "N" || contingInd == null ) && ( hacAmtCl == "01" ) && ( lseId != null && lseId != null && lseId not in ( "9349" , "19165" , "19230" , "20684" , "20695" , "20698" ) ) && ( posGroupId != null && posGroupId not in ( "10703" , "20601" , "20606" ) ) && ( nvl ( prodSubTypeLoc , 0 ) != "WASH" ) && ( hpePdtType != "POS MOV" ) && ( substr ( posGroupId , 1 , 1 ) in ( "5" , "6" ) ))
	then
        
end





rule '823932' extends '330094' salience 5710

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxt11("NOT FOUND seq 9");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823635' extends '330094' salience 5700

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60202")
        
    then
        $gda.setCustomTxt11("60202");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823699' extends '330094' salience 5690

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61311")
        
    then
        $gda.setCustomTxt11("61311");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823732' extends '330094' salience 5680

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60201")
        
    then
        $gda.setCustomTxt11("60201");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823749' extends '330094' salience 5670

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50401")
        
    then
        $gda.setCustomTxt11("50401");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823777' extends '330094' salience 5660

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50601")
        
    then
        $gda.setCustomTxt11("50601");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823778' extends '330094' salience 5650

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50201")
        
    then
        $gda.setCustomTxt11("50201");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823779' extends '330094' salience 5640

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50301")
        
    then
        $gda.setCustomTxt11("50301");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823780' extends '330094' salience 5630

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50501")
        
    then
        $gda.setCustomTxt11("50501");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823781' extends '330094' salience 5620

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50701")
        
    then
        $gda.setCustomTxt11("50701");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823783' extends '330094' salience 5610

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50801")
        
    then
        $gda.setCustomTxt11("50801");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823784' extends '330094' salience 5600

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60401")
        
    then
        $gda.setCustomTxt11("60401 BROKERAGE FEES PAID");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823800' extends '330094' salience 5590

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61401")
        
    then
        $gda.setCustomTxt11("61401");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823801' extends '330094' salience 5580

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61001")
        
    then
        $gda.setCustomTxt11("61001 SUNDRY EXPENSE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823805' extends '330094' salience 5570

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61121")
        
    then
        $gda.setCustomTxt11("61121");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823807' extends '330094' salience 5560

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61131")
        
    then
        $gda.setCustomTxt11("61131");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823810' extends '330094' salience 5550

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61251")
        
    then
        $gda.setCustomTxt11("61251");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823812' extends '330094' salience 5540

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61261")
        
    then
        $gda.setCustomTxt11("61261");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823814' extends '330094' salience 5530

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61271")
        
    then
        $gda.setCustomTxt11("61271");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823816' extends '330094' salience 5520

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61301")
        
    then
        $gda.setCustomTxt11("61301");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823818' extends '330094' salience 5510

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61501")
        
    then
        $gda.setCustomTxt11("61501");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823825' extends '330094' salience 5500

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60611")
        
    then
        $gda.setCustomTxt11("60611");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823828' extends '330094' salience 5490

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60621")
        
    then
        $gda.setCustomTxt11("60621");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823829' extends '330094' salience 5480

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60631")
        
    then
        $gda.setCustomTxt11("60631");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823834' extends '330094' salience 5470

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60701")
        
    then
        $gda.setCustomTxt11("60701");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823837' extends '330094' salience 5460

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60801")
        
    then
        $gda.setCustomTxt11("60801");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823844' extends '330094' salience 5450

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60811")
        
    then
        $gda.setCustomTxt11("60811");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823846' extends '330094' salience 5440

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60821")
        
    then
        $gda.setCustomTxt11("60821");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823849' extends '330094' salience 5430

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60831")
        
    then
        $gda.setCustomTxt11("60831");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823851' extends '330094' salience 5420

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60841")
        
    then
        $gda.setCustomTxt11("60841");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823855' extends '330094' salience 5410

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60901")
        
    then
        $gda.setCustomTxt11("60901");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823862' extends '330094' salience 5400

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61101")
        
    then
        $gda.setCustomTxt11("61101");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823865' extends '330094' salience 5390

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61111")
        
    then
        $gda.setCustomTxt11("61111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823893' extends '330094' salience 5380

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50101")
        
    then
        $gda.setCustomTxt11("50101 AND 60101 NET");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823894' extends '330094' salience 5370

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50111")
        
    then
        $gda.setCustomTxt11("50111");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823901' extends '330094' salience 5360

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60301")
        
    then
        $gda.setCustomTxt11("60301 FEES/COMM PAID");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823902' extends '330094' salience 5350

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60551")
        
    then
        $gda.setCustomTxt11("60551");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823903' extends '330094' salience 5340

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60601")
        
    then
        $gda.setCustomTxt11("60601");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823946' extends '330094' salience 5330

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60101")
        
    then
        $gda.setCustomTxt11("50101 AND 60101 NET");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '826327' extends '330094' salience 5320

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61611")
        
    then
        $gda.setCustomTxt11("61611");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '1142591' extends '330094' salience 5310

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "59999")
        
    then
        $gda.setCustomTxt11("59999");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823631' extends '330094' salience 5300

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60601", prodSubTypeLoc == "STFC")
        
    then
        $gda.setCustomTxt11("60601 STAFF COSTS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823632' extends '330094' salience 5290

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60551", prodSubTypeLoc == "SCSW")
        
    then
        $gda.setCustomTxt11("60551 SALARIES AND WAGES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823636' extends '330094' salience 5280

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60202", prodSubTypeLoc == "DCEX")
        
    then
        $gda.setCustomTxt11("60202 DISCOUNT EXPENSE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823648' extends '330094' salience 5270

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50801", prodSubTypeLoc == "NOPD")
        
    then
        $gda.setCustomTxt11("50801 PART DIVIDENDS REC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823656' extends '330094' salience 5260

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60101", hscAcctSubcl == "1999")
        
    then
        $gda.setCustomTxt11("FUNDINGINTR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823657' extends '330094' salience 5250

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50601", prodSubTypeLoc == "FCPD")
        
    then
        $gda.setCustomTxt11("50601 FEES/COMM PAID");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823658' extends '330094' salience 5240

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50601", prodSubTypeLoc == "FCRC")
        
    then
        $gda.setCustomTxt11("50601 FEE/COMM RECEIVED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823659' extends '330094' salience 5230

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50501", prodSubTypeLoc == "IDSR")
        
    then
        $gda.setCustomTxt11("50501 IDS FOREX RESULTS IDS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823660' extends '330094' salience 5220

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50501", prodSubTypeLoc == "INIR")
        
    then
        $gda.setCustomTxt11("50501 INTERN INT-RECEIVED IDS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823661' extends '330094' salience 5210

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50501", prodSubTypeLoc == "INIP")
        
    then
        $gda.setCustomTxt11("50501 INTERN INTEREST PAID IDS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823700' extends '330094' salience 5200

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61311", prodSubTypeLoc == "PRGO")
        
    then
        $gda.setCustomTxt11("61311 GEN OPERATING RISK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823719' extends '330094' salience 5190

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60551", prodSubTypeLoc == "NLFA")
        
    then
        $gda.setCustomTxt11("60551 FIXED ASSETS SOLD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823733' extends '330094' salience 5180

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60201", prodSubTypeLoc == "PREX")
        
    then
        $gda.setCustomTxt11("60201 PREMIUM EXPENSE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823744' extends '330094' salience 5170

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61501", prodSubTypeLoc == "CTPY")
        
    then
        $gda.setCustomTxt11("61501 CORP TAXES PREV YEAR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823745' extends '330094' salience 5160

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60701", prodSubTypeLoc == "ACME")
        
    then
        $gda.setCustomTxt11("60701 ACCOMMODATION EXP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823746' extends '330094' salience 5150

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61301", prodSubTypeLoc == "APRV")
        
    then
        $gda.setCustomTxt11("61301 ALLOC TO PROVISIONS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823747' extends '330094' salience 5140

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50111", prodSubTypeLoc == "PINL")
        
    then
        $gda.setCustomTxt11("50111 INT REC NON-PERF LN");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823748' extends '330094' salience 5130

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50401", prodSubTypeLoc == "ATIN")
        
    then
        $gda.setCustomTxt11("50401 ASSETS TRADING INC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823773' extends '330094' salience 5120

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60631", prodSubTypeLoc == "SCRC")
        
    then
        $gda.setCustomTxt11("60631 RECRUITMENT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823774' extends '330094' salience 5110

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61501", prodSubTypeLoc == "CTCY")
        
    then
        $gda.setCustomTxt11("61501 CORP TAXES CURR YEAR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823775' extends '330094' salience 5100

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60551", prodSubTypeLoc == "NLLO")
        
    then
        $gda.setCustomTxt11("60551 OTH NON OPER LOSSES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823776' extends '330094' salience 5090

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60551", prodSubTypeLoc == "NOEX")
        
    then
        $gda.setCustomTxt11("60551 NON-OPERATING EXP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823782' extends '330094' salience 5080

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50801", prodSubTypeLoc == "NOFA")
        
    then
        $gda.setCustomTxt11("50801 FIXED ASSETS SOLD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823802' extends '330094' salience 5070

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61111", prodSubTypeLoc == "DPEE")
        
    then
        $gda.setCustomTxt11("61111 DEPR EDP EQUIPMENT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823803' extends '330094' salience 5060

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61111", prodSubTypeLoc == "DPMF")
        
    then
        $gda.setCustomTxt11("61111 DEPR MAINFRAME");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823804' extends '330094' salience 5050

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61111", prodSubTypeLoc == "DPPC")
        
    then
        $gda.setCustomTxt11("61111 DEPR PC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823806' extends '330094' salience 5040

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61121", prodSubTypeLoc == "DPCS")
        
    then
        $gda.setCustomTxt11("61121 DEPR COMP SOFTWARE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823808' extends '330094' salience 5030

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61131", prodSubTypeLoc == "DPBC")
        
    then
        $gda.setCustomTxt11("61131 DEPR BANK OWNED CARS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823809' extends '330094' salience 5020

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61131", prodSubTypeLoc == "DPFA")
        
    then
        $gda.setCustomTxt11("61131 DEPR OTHER FIXED ASS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823811' extends '330094' salience 5010

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61251", prodSubTypeLoc == "HOCH")
        
    then
        $gda.setCustomTxt11("61251 HEAD OFFICE CHARGES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823813' extends '330094' salience 5000

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61261", prodSubTypeLoc == "CHPD")
        
    then
        $gda.setCustomTxt11("61261 SERVICE CHARGES PAID");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823815' extends '330094' salience 4990

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61271", prodSubTypeLoc == "CHRC")
        
    then
        $gda.setCustomTxt11("61271 SERVICE CHARGES REC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823817' extends '330094' salience 4980

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61301", prodSubTypeLoc == "PRDD")
        
    then
        $gda.setCustomTxt11("61301 DEF DOUBTFUL RECVBLE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823819' extends '330094' salience 4970

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61501", prodSubTypeLoc == "CINT")
        
    then
        $gda.setCustomTxt11("61501 CORP INCOME TAXES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823822' extends '330094' salience 4960

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60601", prodSubTypeLoc == "SCPT")
        
    then
        $gda.setCustomTxt11("60601 PAYROLL TX & SOC SEC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823823' extends '330094' salience 4950

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60601", prodSubTypeLoc == "SCPS")
        
    then
        $gda.setCustomTxt11("60601 PENSION");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823824' extends '330094' salience 4940

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60601", prodSubTypeLoc == "SCSW")
        
    then
        $gda.setCustomTxt11("60601 SALARIES AND WAGES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823826' extends '330094' salience 4930

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60611", prodSubTypeLoc == "SCBO")
        
    then
        $gda.setCustomTxt11("60611 BONUSES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823827' extends '330094' salience 4920

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60611", prodSubTypeLoc == "SCGF")
        
    then
        $gda.setCustomTxt11("60611 GRATIFICATIONS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823830' extends '330094' salience 4910

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60631", prodSubTypeLoc == "ACGS")
        
    then
        $gda.setCustomTxt11("60631 GRP STAFF DEPT COSTS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823831' extends '330094' salience 4900

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60631", prodSubTypeLoc == "SCOT")
        
    then
        $gda.setCustomTxt11("60631 OTH PERSONNEL COSTS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823832' extends '330094' salience 4890

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60631", prodSubTypeLoc == "SEVC")
        
    then
        $gda.setCustomTxt11("60631 SEVERANCE COSTS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823833' extends '330094' salience 4880

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60631", prodSubTypeLoc == "ACSO")
        
    then
        $gda.setCustomTxt11("60631 STOCK OPTIONS COSTS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823835' extends '330094' salience 4870

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60701", prodSubTypeLoc == "GEOR")
        
    then
        $gda.setCustomTxt11("60701 OFFICE RENTAL");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823836' extends '330094' salience 4860

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60701", prodSubTypeLoc == "GEAC")
        
    then
        $gda.setCustomTxt11("60701 OTH ACCOMODATION EXP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823838' extends '330094' salience 4850

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60801", prodSubTypeLoc == "GEAS")
        
    then
        $gda.setCustomTxt11("60801 ACQUISITION SOFTWARE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823839' extends '330094' salience 4840

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60801", prodSubTypeLoc == "GEEE")
        
    then
        $gda.setCustomTxt11("60801 EDP EQUIPMENT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823840' extends '330094' salience 4830

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60801", prodSubTypeLoc == "GEHE")
        
    then
        $gda.setCustomTxt11("60801 GEN.HARDWARE EXPENSE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823841' extends '330094' salience 4820

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60801", prodSubTypeLoc == "GEIS")
        
    then
        $gda.setCustomTxt11("60801 INFORMATION SERVICES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823842' extends '330094' salience 4810

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60801", prodSubTypeLoc == "GEAU")
        
    then
        $gda.setCustomTxt11("60801 OTHER AUTOMATION EXP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823843' extends '330094' salience 4800

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60801", prodSubTypeLoc == "GESO")
        
    then
        $gda.setCustomTxt11("60801 RENT.LEASE,MAIN.SOFT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823845' extends '330094' salience 4790

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60811", prodSubTypeLoc == "GETR")
        
    then
        $gda.setCustomTxt11("60811 TRAVEL AND REPRESENT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823847' extends '330094' salience 4780

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60821", prodSubTypeLoc == "GECM")
        
    then
        $gda.setCustomTxt11("60821 COMMUNICATION");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823848' extends '330094' salience 4770

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60621", prodSubTypeLoc == "SCEE")
        
    then
        $gda.setCustomTxt11("60621 EMPLOYEE EDUCATION");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823850' extends '330094' salience 4760

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60831", prodSubTypeLoc == "GEAP")
        
    then
        $gda.setCustomTxt11("60831 ADVERT AND PROMOTION");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823852' extends '330094' salience 4750

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60841", prodSubTypeLoc == "GEAE")
        
    then
        $gda.setCustomTxt11("60841 ADVISORY EXPENSES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823853' extends '330094' salience 4740

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60841", prodSubTypeLoc == "GEEA")
        
    then
        $gda.setCustomTxt11("60841 EXTERNAL AUDITOR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823854' extends '330094' salience 4730

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60841", prodSubTypeLoc == "GEOS")
        
    then
        $gda.setCustomTxt11("60841 PROF OUTSIDE SERVICE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823856' extends '330094' salience 4720

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60901", prodSubTypeLoc == "GECP")
        
    then
        $gda.setCustomTxt11("60901 CHARGES PASSED OTHER");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823857' extends '330094' salience 4710

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60901", prodSubTypeLoc == "GESE")
        
    then
        $gda.setCustomTxt11("60901 OFF SUPPL AND EQUIPM");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823858' extends '330094' salience 4700

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60901", prodSubTypeLoc == "GEOT")
        
    then
        $gda.setCustomTxt11("60901 OTHER EXPENSES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823859' extends '330094' salience 4690

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60901", prodSubTypeLoc == "GETX")
        
    then
        $gda.setCustomTxt11("60901 OTHER TAXES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823860' extends '330094' salience 4680

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60901", prodSubTypeLoc == "GESM")
        
    then
        $gda.setCustomTxt11("60901 SUBSCRP AND MEMBERSH");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823861' extends '330094' salience 4670

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60901", prodSubTypeLoc == "EXPN")
        
    then
        $gda.setCustomTxt11("60901 SUNDRY EXPENSE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823863' extends '330094' salience 4660

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61101", prodSubTypeLoc == "DPLI")
        
    then
        $gda.setCustomTxt11("61101 DEPR LEASEHOLD IMPRV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823864' extends '330094' salience 4650

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61101", prodSubTypeLoc == "DPRB")
        
    then
        $gda.setCustomTxt11("61101 DEPR RESIDENT BLDGS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823895' extends '330094' salience 4640

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50201", prodSubTypeLoc == "DCIN")
        
    then
        $gda.setCustomTxt11("50201 DISCOUNT INCOME");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823896' extends '330094' salience 4630

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50301", prodSubTypeLoc == "FCRC")
        
    then
        $gda.setCustomTxt11("50301 FEE/COMM RECEIVED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823897' extends '330094' salience 4620

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50501", prodSubTypeLoc == "FXRS")
        
    then
        $gda.setCustomTxt11("50501 FOREX RESULTS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823898' extends '330094' salience 4610

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50601", prodSubTypeLoc == "STRS")
        
    then
        $gda.setCustomTxt11("50601 RES SECURITIES TRADE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823899' extends '330094' salience 4600

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50701", prodSubTypeLoc == "OOIN")
        
    then
        $gda.setCustomTxt11("50701 OTHER OPERATING INC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823900' extends '330094' salience 4590

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50801", prodSubTypeLoc == "NOIN")
        
    then
        $gda.setCustomTxt11("50801 OTHER NON-OPER INC");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823904' extends '330094' salience 4580

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60601", prodSubTypeLoc == "SCEA")
        
    then
        $gda.setCustomTxt11("60601 EMPLOYMENT AGENCIES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823905' extends '330094' salience 4570

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60601", prodSubTypeLoc == "SCOP")
        
    then
        $gda.setCustomTxt11("60601 OVERTIME PAY");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823947' extends '330094' salience 4560

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50101", hscAcctSubcl == "1999")
        
    then
        $gda.setCustomTxt11("FUNDINGINTR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '824591' extends '330094' salience 4550

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60901", prodSubTypeLoc == "MGEX")
        
    then
        $gda.setCustomTxt11("60901 MISCELLANEOUS EXP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '824592' extends '330094' salience 4540
no-loop
    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60101", getCase0_824739() == "FUNDING")
        
    then
        $gda.setCustomTxt11("FUNDINGINTP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '824593' extends '330094' salience 4530
no-loop
    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50101", getCase0_824739() == "IDS-DEPOSIT")
        
    then
        $gda.setCustomTxt11("50501 INTERN INT-RECEIVED");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '824594' extends '330094' salience 4520
no-loop
    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60101", getCase0_824739() == "IDS-DEPOSIT")
        
    then
        $gda.setCustomTxt11("50501 INTERN INTEREST PAID");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '824738' extends '330094' salience 4510

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60901", prodSubTypeLoc == "SSEX")
        
    then
        $gda.setCustomTxt11("60901 SERVICES & SUPPLIES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '824739' extends '330094' salience 4500
no-loop
    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50101", getCase0_824739() == "FUNDING")
        
    then
        $gda.setCustomTxt11("FUNDINGINTR");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '824936' extends '330094' salience 4490

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60801", prodSubTypeLoc == "EQPE")
        
    then
        $gda.setCustomTxt11("60801 EQUIPMENT EXPENSES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '826340' extends '330094' salience 4480

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60631", prodSubTypeLoc == "PSES")
        
    then
        $gda.setCustomTxt11("60631 PERF SHARES EQTY SET");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '826341' extends '330094' salience 4470

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60631", prodSubTypeLoc == "EOPE")
        
    then
        $gda.setCustomTxt11("60631 OPTION PLAN EQTY SET");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '826350' extends '330094' salience 4460

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60601", prodSubTypeLoc == "SCOT")
        
    then
        $gda.setCustomTxt11("60601 OTH PERSONNEL COSTS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '826362' extends '330094' salience 4450

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60631", prodSubTypeLoc == "EOPC")
        
    then
        $gda.setCustomTxt11("60631 OPTION PLAN CASH SET");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '917994' extends '330094' salience 4440

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60631", prodSubTypeLoc == "PSCS")
        
    then
        $gda.setCustomTxt11("60631 PERF SHARES CASH SET");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '984964' extends '330094' salience 4430

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61251", prodSubTypeLoc == "ACGS")
        
    then
        $gda.setCustomTxt11("61251 GRP STAFF DEPT COSTS");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '1004297' extends '330094' salience 4420

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "69999", prodSubTypeLoc == "ICIP")
        
    then
        $gda.setCustomTxt11("69999 INTEREST PAID (INT)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '1004298' extends '330094' salience 4410

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "69999", prodSubTypeLoc == "ICIR")
        
    then
        $gda.setCustomTxt11("69999 INTEREST RECVD (INT)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '1004299' extends '330094' salience 4400

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "69999", prodSubTypeLoc == "ICFP")
        
    then
        $gda.setCustomTxt11("69999 INT FEES/COMM PAID");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '1004300' extends '330094' salience 4390

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "69999", prodSubTypeLoc == "ICFR")
        
    then
        $gda.setCustomTxt11("69999 INT FEE/COM RECVD");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '1005531' extends '330094' salience 4380

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61301", prodSubTypeLoc == "PRAC")
        
    then
        $gda.setCustomTxt11("61301 ADDITION COLL PROV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '1005532' extends '330094' salience 4370

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61301", prodSubTypeLoc == "PRRO")
        
    then
        $gda.setCustomTxt11("61301 RELEASE COLL PROV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '1005533' extends '330094' salience 4360

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61301", prodSubTypeLoc == "PRRS")
        
    then
        $gda.setCustomTxt11("61301 RELEASE ISFA PROV");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '1005534' extends '330094' salience 4350

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50601", prodSubTypeLoc == "FVHD")
        
    then
        $gda.setCustomTxt11("50601 CHANGE FV HEDGES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '1005535' extends '330094' salience 4340

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50601", prodSubTypeLoc == "FVHI")
        
    then
        $gda.setCustomTxt11("50601 CHANGE FV HEDGED IT");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '1032016' extends '330094' salience 4330

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "61311", prodSubTypeLoc == "PRCR")
        
    then
        $gda.setCustomTxt11("61311 COUNTRY RISK");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '1035208' extends '330094' salience 4320

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "60821", prodSubTypeLoc == "GEIS")
        
    then
        $gda.setCustomTxt11("60821 INFORMATION SERVICES");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '1035209' extends '330094' salience 4310

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50601", prodSubTypeLoc == "URMM")
        
    then
        $gda.setCustomTxt11("50601 RES MONEY MARKET");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '1038660' extends '330094' salience 4300

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "59999", prodSubTypeLoc == "PLRM")
        
    then
        $gda.setCustomTxt11("59999 P&L REMITTANCE");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '1084183' extends '330094' salience 4290

    when
        
        GrlDetAmounts(this == $gda, posGroupId == "50601", prodSubTypeLoc == "URMO")
        
    then
        $gda.setCustomTxt11("NTBR 50601 URMO");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823633' extends '330094' salience 4280

    when
        
        GrlDetAmounts(this == $gda, prodSubSubTypeLoc == "INT ISWP", posGroupId == "50501", prodSubTypeLoc == "INTR")
        
    then
        $gda.setCustomTxt11("50501 INTEREST REC INT ISWP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end

rule '823649' extends '330094' salience 4270

    when
        
        GrlDetAmounts(this == $gda, prodSubSubTypeLoc == "INT ISWP", posGroupId == "50501", prodSubTypeLoc == "INTP")
        
    then
        $gda.setCustomTxt11("50501 INTEREST PAID INT ISWP");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"1980");
        
end


