package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '331303'
	when
		$gda : GrlDetAmounts(( hacAmtCl == "12" && hpePdtType in ( "LOAN" , "DEPOSIT" ) && lseId != null && lseId != null && lseId not in ( "9349" , "19165" , "19230" , "20684" , "20695" , "20698" ) ))
	then
        
end





rule '1035213' extends '331303' salience 1690

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y")
        
    then
        $gda.setCustomTxt11("20612 REV.MONEY MARKET ASSET");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2859");
        
end

rule '1035214' extends '331303' salience 1680

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N")
        
    then
        $gda.setCustomTxt11("20612 REV.MONEY MARKET LIAB");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2859");
        
end

rule '1086195' extends '331303' salience 1670

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", ownUse06 == "REMO")
        
    then
        $gda.setCustomTxt11("NTBR REMO 20612 ASSET");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2859");
        
end

rule '1086196' extends '331303' salience 1660

    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "N", ownUse06 == "REMO")
        
    then
        $gda.setCustomTxt11("NTBR REMO 20612 LIAB");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2859");
        
end


