package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlPlYtd;




dialect  "mvel"


rule '332332'
	when
		$gpy : GrlPlYtd(hpnPlCl in ( "6000" , "7000" ))
	then
        
end





rule '1156386' extends '332332' salience 2920

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setLocMassLine(massLine );
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156325' extends '332332' salience 2910

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E3900000", "E3901000", "E3902000", "E3903000"))
        
    then
        $gpy.setLocMassLine("Expenses related to Deferred Equity/Shares");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156344' extends '332332' salience 2900

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0128000")
        
    then
        $gpy.setLocMassLine("Third Party Staff IT");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156345' extends '332332' salience 2890

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E3161000", "E3905000", "E4032000", "E8242000"))
        
    then
        $gpy.setLocMassLine("Impairments on Securities");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156346' extends '332332' salience 2880

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E3151000", "E3152000", "E3153000", "E3341000"))
        
    then
        $gpy.setLocMassLine("Other Operational Lease Income");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156347' extends '332332' salience 2870

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E3091000", "E3158000", "E3160000", "E3949000", "E4151000"))
        
    then
        $gpy.setLocMassLine("Other (Income)");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156348' extends '332332' salience 2860

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7997000")
        
    then
        $gpy.setLocMassLine("Lease Cars Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156349' extends '332332' salience 2850

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8003000")
        
    then
        $gpy.setLocMassLine("Audit Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156350' extends '332332' salience 2840

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8001000")
        
    then
        $gpy.setLocMassLine("Management Consultants");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156351' extends '332332' salience 2830

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0372000")
        
    then
        $gpy.setLocMassLine("Impairments on Securities");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156353' extends '332332' salience 2820

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0114000", "E3148000", "E3149000", "E3150000", "E3159000", "E3162000", "E3163000", "E3164000", "E3165000", "E3166000", "E4030000", "E4169000"))
        
    then
        $gpy.setLocMassLine("Intangible Amortisation and Other Impairments");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156354' extends '332332' salience 2810

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4875000")
        
    then
        $gpy.setLocMassLine("Interest External Paid (Core)");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156355' extends '332332' salience 2800

    when
        
        GrlPlYtd(this == $gpy, (actCode == "E6683000" || actCode == "E6686000" || actCode == "E6688000" || actCode == "E6689000" || actCode matches "E669.*" || actCode == "E6700000" || actCode == "E6701000" || actCode == "E6702000" || actCode == "E6703000" || actCode == "E6704000" || actCode == "E7504000" || actCode == "I0026000"))
        
    then
        $gpy.setLocMassLine("Intangible Amortisation and Other Impairments");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156356' extends '332332' salience 2790

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0176000")
        
    then
        $gpy.setLocMassLine("Depreciation Software");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156357' extends '332332' salience 2780

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0123000")
        
    then
        $gpy.setLocMassLine("Depreciation Hardware");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156358' extends '332332' salience 2770

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0079000", "E7998000", "E7999000", "E8000000"))
        
    then
        $gpy.setLocMassLine("Other Accommodation Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156360' extends '332332' salience 2760

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0109000", "E0112000", "E4877000"))
        
    then
        $gpy.setLocMassLine("Corporate Tax Financial Accounting");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156361' extends '332332' salience 2750

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0120000", "E0184000"))
        
    then
        $gpy.setLocMassLine(Warning: selecting from Non-Controlling: data will not be available in source topic.
 full statement: Net Result from Non-Controlling Interests);
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156362' extends '332332' salience 2740

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0126000")
        
    then
        $gpy.setLocMassLine("Third Party Staff Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156364' extends '332332' salience 2730

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0147000", "E0148000", "E0149000"))
        
    then
        $gpy.setLocMassLine("Office Supplies and Equipment");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156365' extends '332332' salience 2720

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0117000", "E0113000", "E0114000", "E0137000", "E0138000", "E0139000", "E0157000", "E0158000", "E0165000", "E0172000", "E2343000", "E2344000", "E2345000", "E2346000", "E2583000", "E7509000", "E0118000", "E0119000"))
        
    then
        $gpy.setLocMassLine("Other Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156367' extends '332332' salience 2710

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0154000")
        
    then
        $gpy.setLocMassLine("Payroll Taxes and Social Security");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156368' extends '332332' salience 2700

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0159000", "E4566000"))
        
    then
        $gpy.setLocMassLine("Pension Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156369' extends '332332' salience 2690

    when
        
        GrlPlYtd(this == $gpy, (actCode == "E0169000" || actCode == "E8007000" || actCode == "E8006000" || actCode == "E0169000" || actCode == "E0084000" || actCode == "E0085000" || actCode matches "E3944.*" || actCode matches "E3945.*" || actCode == "E4599000"))
        
    then
        $gpy.setLocMassLine("Loss allowances");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156370' extends '332332' salience 2680

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0183000", "E0182000"))
        
    then
        $gpy.setLocMassLine("Communication Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156371' extends '332332' salience 2670

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0078000")
        
    then
        $gpy.setLocMassLine("Depr - Leasehold Improvements");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156372' extends '332332' salience 2660

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0125000")
        
    then
        $gpy.setLocMassLine("Employee Education");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156373' extends '332332' salience 2650

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0133000", "E3350000", "E8229000"))
        
    then
        $gpy.setLocMassLine("Group Overhead Staff FA");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156374' extends '332332' salience 2640

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0130000")
        
    then
        $gpy.setLocMassLine("Information Services Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156375' extends '332332' salience 2630

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0174000")
        
    then
        $gpy.setLocMassLine("IC Services Bought Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156376' extends '332332' salience 2620

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0175000")
        
    then
        $gpy.setLocMassLine("Intercompany Services Sold");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156378' extends '332332' salience 2610

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0129000")
        
    then
        $gpy.setLocMassLine("Office Rental");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156379' extends '332332' salience 2600

    when
        
        GrlPlYtd(this == $gpy, actCode == "E6705000")
        
    then
        $gpy.setLocMassLine("Depreciation Software");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156380' extends '332332' salience 2590

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7461000")
        
    then
        $gpy.setLocMassLine("DIP Local");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156381' extends '332332' salience 2580

    when
        
        GrlPlYtd(this == $gpy, actCode == "E4390000")
        
    then
        $gpy.setLocMassLine("Corporate Tax MA Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156382' extends '332332' salience 2570

    when
        
        GrlPlYtd(this == $gpy, actCode == "E4388000")
        
    then
        $gpy.setLocMassLine("Corporate Tax MA Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156383' extends '332332' salience 2560

    when
        
        GrlPlYtd(this == $gpy, actCode == "E4389000")
        
    then
        $gpy.setLocMassLine("Corporate Tax MA Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156384' extends '332332' salience 2550

    when
        
        GrlPlYtd(this == $gpy, actCode == "E4391000")
        
    then
        $gpy.setLocMassLine("Corporate Tax MA Other");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156385' extends '332332' salience 2540

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8236000")
        
    then
        $gpy.setLocMassLine("Expenses related to Deferred Equity/Shares");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1178751' extends '332332' salience 2530

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8291000")
        
    then
        $gpy.setLocMassLine("Bank Levies Local");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1181693' extends '332332' salience 2520

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8296000")
        
    then
        $gpy.setLocMassLine("Expenses related to Upfront Equity/Shares");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1706448' extends '332332' salience 2510

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8644000XX")
        
    then
        $gpy.setLocMassLine("Single Resolution Mechanism Dutch N.V.");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156310' extends '332332' salience 2500

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0131000", "E0136000", "E0181000"), hsoPlSubcl not in ("6401", "6542"))
        
    then
        $gpy.setLocMassLine("Other Personnel Related Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156311' extends '332332' salience 2490

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8004000", hsoPlSubcl == "6536")
        
    then
        $gpy.setLocMassLine("Outsourcing");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156312' extends '332332' salience 2480

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0174000", cpyBeyNumber in ("U0039", "U3039"))
        
    then
        $gpy.setLocMassLine("IC Services Bought Belgium");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156313' extends '332332' salience 2470

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0174000", cpyBeyNumber in ("U0618", "U2211"))
        
    then
        $gpy.setLocMassLine("IC Services Bought NL Direct Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156314' extends '332332' salience 2460

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0181000", hsoPlSubcl == "6401")
        
    then
        $gpy.setLocMassLine("Recruitment Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156316' extends '332332' salience 2450

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6540")
        
    then
        $gpy.setLocMassLine("Events/Relationship Marketing");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156317' extends '332332' salience 2440

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000", hsoPlSubcl == "6541")
        
    then
        $gpy.setLocMassLine("Internal Communication");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156322' extends '332332' salience 2430

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000", hsoPlSubcl == "6543")
        
    then
        $gpy.setLocMassLine("Claims");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156323' extends '332332' salience 2420

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000", hsoPlSubcl == "6539")
        
    then
        $gpy.setLocMassLine("Postal Charges");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156324' extends '332332' salience 2410

    when
        
        GrlPlYtd(this == $gpy, actCode == "E6684000", hsoPlSubcl == "6108")
        
    then
        $gpy.setLocMassLine("Deferred cash bonuses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156326' extends '332332' salience 2400

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0096000", hsoPlSubcl == "6107")
        
    then
        $gpy.setLocMassLine(massLine );
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156327' extends '332332' salience 2390

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0166000", "I3174000"))
        
    then
        $gpy.setLocMassLine("Investment Income");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156328' extends '332332' salience 2380

    when
        
        GrlPlYtd(this == $gpy, intInd == "Y", actCode == null, hsoPlSubcl == "6521")
        
    then
        $gpy.setLocMassLine("Intercompany Services Sold");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156329' extends '332332' salience 2370

    when
        
        GrlPlYtd(this == $gpy, actCode == "E6684000", hsoPlSubcl == "6538")
        
    then
        $gpy.setLocMassLine("Deferred cash bonuses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156330' extends '332332' salience 2360

    when
        
        GrlPlYtd(this == $gpy, actCode == "E4621000", hsoPlSubcl == "6501")
        
    then
        $gpy.setLocMassLine("Office Rental");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156331' extends '332332' salience 2350

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E8002000", "E8004000", "E0164000"), hsoPlSubcl != "6536")
        
    then
        $gpy.setLocMassLine("Other Professional Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156332' extends '332332' salience 2340

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E0108000", "E0122000", "E0140000", "E0173000", "E7483000"), hsoPlSubcl not in ("6404", "6405"))
        
    then
        $gpy.setLocMassLine("Salaries and Wages");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156333' extends '332332' salience 2330

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0173000", hsoPlSubcl == "6404")
        
    then
        $gpy.setLocMassLine("Severance Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156336' extends '332332' salience 2320

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000", hsoPlSubcl not in ("6519", "6539", "6543", "6560"))
        
    then
        $gpy.setLocMassLine("Other Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156337' extends '332332' salience 2310

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000", hsoPlSubcl == "6519")
        
    then
        $gpy.setLocMassLine("Other Taxes");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156339' extends '332332' salience 2300

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0162000", hsoPlSubcl == "6527")
        
    then
        $gpy.setLocMassLine("Postal Charges");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156340' extends '332332' salience 2290

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0122000", hsoPlSubcl == "7112")
        
    then
        $gpy.setLocMassLine("Pension Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156341' extends '332332' salience 2280

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0140000", hsoPlSubcl == "7111")
        
    then
        $gpy.setLocMassLine("Pension Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1284293' extends '332332' salience 2270

    when
        
        GrlPlYtd(this == $gpy, actCode in ("E8337000", "E0180000"), hsoPlSubcl == "6560")
        
    then
        $gpy.setLocMassLine("VAT on Head Office Charges");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156387' extends '332332' salience 2260

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0096000", hsoPlSubcl == "6102", plAcctId in ("9404016", "7950401211", "7950401259"))
        
    then
        $gpy.setLocMassLine("Upfront cash bonuses WB Pool");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end

rule '1156388' extends '332332' salience 2250

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0096000", hsoPlSubcl == "6102", plAcctId not in ("9404016", "7950401211", "7950401259"))
        
    then
        $gpy.setLocMassLine(massLine );
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3597");
        
end


