package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlPlYtd;




dialect  "mvel"


rule '331648'
	when
		$gpy : GrlPlYtd(hpnPlCl in ( "6000" , "7000" ) && hsoPlSubcl != "7401")
	then
        
end





rule '1095048' extends '331648' salience 460

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setLocMassLine("99.999");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095018' extends '331648' salience 450

    when
        
        GrlPlYtd(this == $gpy, plAcctId in ("4351", "4361", "4383"))
        
    then
        $gpy.setLocMassLine("Advertising Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095019' extends '331648' salience 440

    when
        
        GrlPlYtd(this == $gpy, plAcctId in ("4359", "4369", "4370", "4375"))
        
    then
        $gpy.setLocMassLine("Books and Periodicals");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095020' extends '331648' salience 430

    when
        
        GrlPlYtd(this == $gpy, plAcctId in ("4432", "4439"))
        
    then
        $gpy.setLocMassLine("Clubs Depreciation");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095021' extends '331648' salience 420

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4435")
        
    then
        $gpy.setLocMassLine("EDP Equipment Depreciation");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095022' extends '331648' salience 410

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4363")
        
    then
        $gpy.setLocMassLine("Financial News Services");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095023' extends '331648' salience 400

    when
        
        GrlPlYtd(this == $gpy, plAcctId in ("4401", "4403"))
        
    then
        $gpy.setLocMassLine("Hardware Maintenance");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095024' extends '331648' salience 390

    when
        
        GrlPlYtd(this == $gpy, plAcctId in ("4492", "4495"))
        
    then
        $gpy.setLocMassLine("Irrecoverable GST");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095025' extends '331648' salience 380

    when
        
        GrlPlYtd(this == $gpy, plAcctId in ("4431", "4438"))
        
    then
        $gpy.setLocMassLine("Leasehold Depreciation");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095026' extends '331648' salience 370

    when
        
        GrlPlYtd(this == $gpy, plAcctId in ("4367", "4380"))
        
    then
        $gpy.setLocMassLine("Legal Fees");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095027' extends '331648' salience 360

    when
        
        GrlPlYtd(this == $gpy, plAcctId in ("4434", "4440"))
        
    then
        $gpy.setLocMassLine("Main Frame Depreciation");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095028' extends '331648' salience 350

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4433")
        
    then
        $gpy.setLocMassLine("Motor Vehicle Depreciation");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095029' extends '331648' salience 340

    when
        
        GrlPlYtd(this == $gpy, plAcctId in ("4360", "4402"))
        
    then
        $gpy.setLocMassLine("Office Assets not Capitalised");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095030' extends '331648' salience 330

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4311")
        
    then
        $gpy.setLocMassLine("Office Rent");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095031' extends '331648' salience 320

    when
        
        GrlPlYtd(this == $gpy, plAcctId in ("4313", "4314", "4316", "4318", "4319"))
        
    then
        $gpy.setLocMassLine("Office Utilities");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095032' extends '331648' salience 310

    when
        
        GrlPlYtd(this == $gpy, plAcctId in ("4364", "4368", "4378", "4529", "4531"))
        
    then
        $gpy.setLocMassLine("Other Sundry Expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095033' extends '331648' salience 300

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4358")
        
    then
        $gpy.setLocMassLine("Regulatory Subscriptions");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095034' extends '331648' salience 290

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4405")
        
    then
        $gpy.setLocMassLine("Software Agent Charges");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095035' extends '331648' salience 280

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4436")
        
    then
        $gpy.setLocMassLine("Software Depreciation");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095036' extends '331648' salience 270

    when
        
        GrlPlYtd(this == $gpy, plAcctId in ("4374", "4385"))
        
    then
        $gpy.setLocMassLine("Telephone Costs");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095037' extends '331648' salience 260

    when
        
        GrlPlYtd(this == $gpy, plAcctId in ("4355", "4357", "4362", "4365", "4376", "4377"))
        
    then
        $gpy.setLocMassLine("Travel");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095038' extends '331648' salience 250

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4273")
        
    then
        $gpy.setLocMassLine("Overtime");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095039' extends '331648' salience 240

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4283")
        
    then
        $gpy.setLocMassLine("Gratuities - Local");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095040' extends '331648' salience 230

    when
        
        GrlPlYtd(this == $gpy, plAcctId in ("4276", "4277"))
        
    then
        $gpy.setLocMassLine("Salaries - Local");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095041' extends '331648' salience 220

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4253")
        
    then
        $gpy.setLocMassLine("CPF");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095042' extends '331648' salience 210

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4282")
        
    then
        $gpy.setLocMassLine("Pension");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095043' extends '331648' salience 200

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4258")
        
    then
        $gpy.setLocMassLine("Education - Local");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095044' extends '331648' salience 190

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4274")
        
    then
        $gpy.setLocMassLine("Recruitment Fees");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095045' extends '331648' salience 180

    when
        
        GrlPlYtd(this == $gpy, plAcctId in ("4260", "4261", "4262", "4266", "4267", "4275", "4279", "4280"))
        
    then
        $gpy.setLocMassLine("Sundries - Local");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095046' extends '331648' salience 170

    when
        
        GrlPlYtd(this == $gpy, plAcctId in ("4251", "4252", "4254"))
        
    then
        $gpy.setLocMassLine("Bonus WB Pool");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095047' extends '331648' salience 160

    when
        
        GrlPlYtd(this == $gpy, massLine == "Invoiced Intercompany Services Bought")
        
    then
        $gpy.setLocMassLine("Invoiced Intercompany Services Bought");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095049' extends '331648' salience 150

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4281")
        
    then
        $gpy.setLocMassLine("Staff - Temp Help");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1095050' extends '331648' salience 140

    when
        
        GrlPlYtd(this == $gpy, plAcctId in ("4491", "4497"))
        
    then
        $gpy.setLocMassLine("Corporate Tax");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1140580' extends '331648' salience 130

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4259")
        
    then
        $gpy.setLocMassLine("Home Leave - Expat");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1140581' extends '331648' salience 120

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4271")
        
    then
        $gpy.setLocMassLine("Medical Insurance - Local");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1140582' extends '331648' salience 110

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4270")
        
    then
        $gpy.setLocMassLine("Medical Insurance - Expat");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1140583' extends '331648' salience 100

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4269")
        
    then
        $gpy.setLocMassLine("Medical - Local");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1140584' extends '331648' salience 90

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4268")
        
    then
        $gpy.setLocMassLine("Medical - Expat");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1140585' extends '331648' salience 80

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4312")
        
    then
        $gpy.setLocMassLine("Office Services and Cleaning");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1140586' extends '331648' salience 70

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4315")
        
    then
        $gpy.setLocMassLine("Funiture and Equipment Maintenance");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1140587' extends '331648' salience 60

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4317")
        
    then
        $gpy.setLocMassLine("Office Insurance");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1140588' extends '331648' salience 50

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4320")
        
    then
        $gpy.setLocMassLine("Sundry expenses");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1140589' extends '331648' salience 40

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4352")
        
    then
        $gpy.setLocMassLine("Audit Fees");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1140590' extends '331648' salience 30

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4353")
        
    then
        $gpy.setLocMassLine("Books and Periodicals");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1140591' extends '331648' salience 20

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4371")
        
    then
        $gpy.setLocMassLine("Regulatory Subscriptions");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end

rule '1140592' extends '331648' salience 10

    when
        
        GrlPlYtd(this == $gpy, plAcctId == "4404")
        
    then
        $gpy.setLocMassLine("External DP Charges");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"3133");
        
end


