package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '331427'
	when
		$gda : GrlDetAmounts(scyActCode != null)
	then
        
end





rule '1081038' extends '331427' salience 8780

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxt02("9999");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080865' extends '331427' salience 8770

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0001000")
        
    then
        $gda.setCustomTxt02("g");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080866' extends '331427' salience 8760

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0002000")
        
    then
        $gda.setCustomTxt02("g");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080867' extends '331427' salience 8750

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0003000")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080868' extends '331427' salience 8740

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0005000")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080869' extends '331427' salience 8730

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0006000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080870' extends '331427' salience 8720

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0007000", rteCode == "025")
        
    then
        $gda.setCustomTxt02("g");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080871' extends '331427' salience 8710

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0007000", rteCode in ("010", "035", "036", "073", "098", "100"))
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080872' extends '331427' salience 8700

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0009000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080873' extends '331427' salience 8690

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0011000")
        
    then
        $gda.setCustomTxt02("h");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080874' extends '331427' salience 8680

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0012000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080875' extends '331427' salience 8670

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0014000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080876' extends '331427' salience 8660

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0015000")
        
    then
        $gda.setCustomTxt02("na");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080877' extends '331427' salience 8650

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0016000")
        
    then
        $gda.setCustomTxt02("na");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080878' extends '331427' salience 8640

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0017000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080879' extends '331427' salience 8630

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0019000")
        
    then
        $gda.setCustomTxt02("na");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080880' extends '331427' salience 8620

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0020000")
        
    then
        $gda.setCustomTxt02("na");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080881' extends '331427' salience 8610

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0021000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080882' extends '331427' salience 8600

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0022000")
        
    then
        $gda.setCustomTxt02("na");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080883' extends '331427' salience 8590

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0023000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080884' extends '331427' salience 8580

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0024000")
        
    then
        $gda.setCustomTxt02("h");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080885' extends '331427' salience 8570

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0025000", rteCode in ("010", "035", "036", "037", "073", "173"))
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080886' extends '331427' salience 8560

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0025000", rteCode in ("074", "174"))
        
    then
        $gda.setCustomTxt02("e");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080887' extends '331427' salience 8550

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", cgpCode matches "B.*")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080888' extends '331427' salience 8540

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", cgpCode not matches "B.*")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080889' extends '331427' salience 8530

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0028000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080890' extends '331427' salience 8520

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0029000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080891' extends '331427' salience 8510

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0031000")
        
    then
        $gda.setCustomTxt02("h");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080892' extends '331427' salience 8500

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0034000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080893' extends '331427' salience 8490

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0036000")
        
    then
        $gda.setCustomTxt02("g");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080894' extends '331427' salience 8480

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0037000")
        
    then
        $gda.setCustomTxt02("g");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080895' extends '331427' salience 8470

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0038000")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080896' extends '331427' salience 8460

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0039000")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080897' extends '331427' salience 8450

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0040000")
        
    then
        $gda.setCustomTxt02("g");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080898' extends '331427' salience 8440

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0045000", rteCode in ("078", "080"))
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080899' extends '331427' salience 8430

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0045000", rteCode in ("084", "085", "087", "088"))
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080900' extends '331427' salience 8420

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0046000")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080901' extends '331427' salience 8410

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0047000")
        
    then
        $gda.setCustomTxt02("g");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080902' extends '331427' salience 8400

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0050000")
        
    then
        $gda.setCustomTxt02("na");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080903' extends '331427' salience 8390

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0051000")
        
    then
        $gda.setCustomTxt02("na");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080904' extends '331427' salience 8380

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0052000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080905' extends '331427' salience 8370

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0053000")
        
    then
        $gda.setCustomTxt02("h");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080906' extends '331427' salience 8360

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0054000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080907' extends '331427' salience 8350

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0055000")
        
    then
        $gda.setCustomTxt02("d");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080908' extends '331427' salience 8340

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0056000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080909' extends '331427' salience 8330

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0057000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080910' extends '331427' salience 8320

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0058000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080911' extends '331427' salience 8310

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0060000")
        
    then
        $gda.setCustomTxt02("g");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080912' extends '331427' salience 8300

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0061000")
        
    then
        $gda.setCustomTxt02("h");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080913' extends '331427' salience 8290

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0624000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080914' extends '331427' salience 8280

    when
        
        GrlDetAmounts(this == $gda, actCode == "A1112000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080915' extends '331427' salience 8270

    when
        
        GrlDetAmounts(this == $gda, actCode == "A1614000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080916' extends '331427' salience 8260

    when
        
        GrlDetAmounts(this == $gda, actCode == "A2342000")
        
    then
        $gda.setCustomTxt02("d");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080917' extends '331427' salience 8250

    when
        
        GrlDetAmounts(this == $gda, actCode == "A2500000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080918' extends '331427' salience 8240

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3145000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080919' extends '331427' salience 8230

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3147000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080920' extends '331427' salience 8220

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3176000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080921' extends '331427' salience 8210

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3177000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080922' extends '331427' salience 8200

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3178000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080923' extends '331427' salience 8190

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3179000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080924' extends '331427' salience 8180

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3282000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080925' extends '331427' salience 8170

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3291000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080926' extends '331427' salience 8160

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000")
        
    then
        $gda.setCustomTxt02("d");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080927' extends '331427' salience 8150

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3331000")
        
    then
        $gda.setCustomTxt02("d");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080928' extends '331427' salience 8140

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", cgpCode matches "B.*")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080929' extends '331427' salience 8130

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", cgpCode not matches "B.*")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080930' extends '331427' salience 8120

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3333000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080931' extends '331427' salience 8110

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3869000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080932' extends '331427' salience 8100

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3906000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080933' extends '331427' salience 8090

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3908000")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080934' extends '331427' salience 8080

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3910000")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080935' extends '331427' salience 8070

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3912000")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080936' extends '331427' salience 8060

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3914000")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080937' extends '331427' salience 8050

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3916000")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080938' extends '331427' salience 8040

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", cgpCode matches "B.*")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080939' extends '331427' salience 8030

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", cgpCode not matches "B.*")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080940' extends '331427' salience 8020

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3943000", rteCode == "078")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080941' extends '331427' salience 8010

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3943000", rteCode != "078")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080942' extends '331427' salience 8000

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4144000")
        
    then
        $gda.setCustomTxt02("d");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080943' extends '331427' salience 7990

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4145000")
        
    then
        $gda.setCustomTxt02("d");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080944' extends '331427' salience 7980

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4152000")
        
    then
        $gda.setCustomTxt02("d");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080945' extends '331427' salience 7970

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4257000")
        
    then
        $gda.setCustomTxt02("h");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080946' extends '331427' salience 7960

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4392000")
        
    then
        $gda.setCustomTxt02("h");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080947' extends '331427' salience 7950

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0229000")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080948' extends '331427' salience 7940

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0230000", rteCode in ("100", "010", "098"))
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080949' extends '331427' salience 7930

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0233000")
        
    then
        $gda.setCustomTxt02("g");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080950' extends '331427' salience 7920

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0234000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080951' extends '331427' salience 7910

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0237000")
        
    then
        $gda.setCustomTxt02("na");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080952' extends '331427' salience 7900

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0238000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080953' extends '331427' salience 7890

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0239000")
        
    then
        $gda.setCustomTxt02("i");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080976' extends '331427' salience 7880

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0243000")
        
    then
        $gda.setCustomTxt02("h");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080977' extends '331427' salience 7870

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0244000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080978' extends '331427' salience 7860

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0245000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080979' extends '331427' salience 7850

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0249000")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080980' extends '331427' salience 7840

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0250000")
        
    then
        $gda.setCustomTxt02("i");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080981' extends '331427' salience 7830

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0251000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080982' extends '331427' salience 7820

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0252000")
        
    then
        $gda.setCustomTxt02("i");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080983' extends '331427' salience 7810

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0253000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080984' extends '331427' salience 7800

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0254000")
        
    then
        $gda.setCustomTxt02("g");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080985' extends '331427' salience 7790

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0255000")
        
    then
        $gda.setCustomTxt02("g");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080986' extends '331427' salience 7780

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0256000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080987' extends '331427' salience 7770

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0257000")
        
    then
        $gda.setCustomTxt02("d");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080988' extends '331427' salience 7760

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0265000")
        
    then
        $gda.setCustomTxt02("h");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080989' extends '331427' salience 7750

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0266000")
        
    then
        $gda.setCustomTxt02("i");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080990' extends '331427' salience 7740

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0267000")
        
    then
        $gda.setCustomTxt02("h");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080991' extends '331427' salience 7730

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0268000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080992' extends '331427' salience 7720

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0269000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080993' extends '331427' salience 7710

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0271000")
        
    then
        $gda.setCustomTxt02("d");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080994' extends '331427' salience 7700

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0272000")
        
    then
        $gda.setCustomTxt02("na");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080995' extends '331427' salience 7690

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0273000")
        
    then
        $gda.setCustomTxt02("d");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080996' extends '331427' salience 7680

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0277000")
        
    then
        $gda.setCustomTxt02("d");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080997' extends '331427' salience 7670

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1425000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080998' extends '331427' salience 7660

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1605000")
        
    then
        $gda.setCustomTxt02("z");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080999' extends '331427' salience 7650

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1615000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081000' extends '331427' salience 7640

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2510000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081001' extends '331427' salience 7630

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2569000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081002' extends '331427' salience 7620

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2571000")
        
    then
        $gda.setCustomTxt02("g");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081003' extends '331427' salience 7610

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2730000")
        
    then
        $gda.setCustomTxt02("h");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081004' extends '331427' salience 7600

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3180000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081005' extends '331427' salience 7590

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3181000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081006' extends '331427' salience 7580

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3182000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081007' extends '331427' salience 7570

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3183000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081008' extends '331427' salience 7560

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3279000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081009' extends '331427' salience 7550

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3283000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081011' extends '331427' salience 7540

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3343000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081012' extends '331427' salience 7530

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3345000")
        
    then
        $gda.setCustomTxt02("na");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081013' extends '331427' salience 7520

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3346000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081014' extends '331427' salience 7510

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3348000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081015' extends '331427' salience 7500

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3351000")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081016' extends '331427' salience 7490

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3873000")
        
    then
        $gda.setCustomTxt02("h");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081017' extends '331427' salience 7480

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3899000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081018' extends '331427' salience 7470

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3907000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081019' extends '331427' salience 7460

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3909000")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081020' extends '331427' salience 7450

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3911000")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081021' extends '331427' salience 7440

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3915000")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081022' extends '331427' salience 7430

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3917000")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081023' extends '331427' salience 7420

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3933000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081024' extends '331427' salience 7410

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3934000")
        
    then
        $gda.setCustomTxt02("na");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081025' extends '331427' salience 7400

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3935000")
        
    then
        $gda.setCustomTxt02("na");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081026' extends '331427' salience 7390

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3936000")
        
    then
        $gda.setCustomTxt02("na");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081027' extends '331427' salience 7380

    when
        
        GrlDetAmounts(this == $gda, actCode == "L9998000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081028' extends '331427' salience 7370

    when
        
        GrlDetAmounts(this == $gda, actCode == "L9999000")
        
    then
        $gda.setCustomTxt02("i");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081029' extends '331427' salience 7360

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0065000")
        
    then
        $gda.setCustomTxt02("e");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081030' extends '331427' salience 7350

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0068000")
        
    then
        $gda.setCustomTxt02("g");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081031' extends '331427' salience 7340

    when
        
        GrlDetAmounts(this == $gda, actCode in ("Q0069000", "Q0070000", "Q0071000"))
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081032' extends '331427' salience 7330

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0073000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081033' extends '331427' salience 7320

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0076000")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081034' extends '331427' salience 7310

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0077000")
        
    then
        $gda.setCustomTxt02("h");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081035' extends '331427' salience 7300

    when
        
        GrlDetAmounts(this == $gda, actCode in ("Q3167000", "Q3168000", "Q3335000"))
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081036' extends '331427' salience 7290

    when
        
        GrlDetAmounts(this == $gda, actCode matches "B.*")
        
    then
        $gda.setCustomTxt02("xxx");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081037' extends '331427' salience 7280

    when
        
        GrlDetAmounts(this == $gda, actCode matches "D.*")
        
    then
        $gda.setCustomTxt02("xxx");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1082946' extends '331427' salience 7270

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0066000")
        
    then
        $gda.setCustomTxt02("z");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1109455' extends '331427' salience 7260

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0032000")
        
    then
        $gda.setCustomTxt02("h");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1109456' extends '331427' salience 7250

    when
        
        GrlDetAmounts(this == $gda, actCode == "A6685000")
        
    then
        $gda.setCustomTxt02("g");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1109468' extends '331427' salience 7240

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2530000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1109469' extends '331427' salience 7230

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2532000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1109470' extends '331427' salience 7220

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2533000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1109471' extends '331427' salience 7210

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0064000")
        
    then
        $gda.setCustomTxt02("z");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1109472' extends '331427' salience 7200

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0069000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1109473' extends '331427' salience 7190

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0070000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1109474' extends '331427' salience 7180

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0071000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1109475' extends '331427' salience 7170

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q3167000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1109476' extends '331427' salience 7160

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q3168000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1109477' extends '331427' salience 7150

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q3335000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1109478' extends '331427' salience 7140

    when
        
        GrlDetAmounts(this == $gda, actCode == "V0015160")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1109481' extends '331427' salience 7130

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0004000")
        
    then
        $gda.setCustomTxt02("f");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1109482' extends '331427' salience 7120

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0010000")
        
    then
        $gda.setCustomTxt02("g");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1125492' extends '331427' salience 7110

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0025000", rteCode == "010")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1150806' extends '331427' salience 7100

    when
        
        GrlDetAmounts(this == $gda, actCode == "L8276000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1150807' extends '331427' salience 7090

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8268000", rteCode == "070")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1150808' extends '331427' salience 7080

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8269000", rteCode == "070")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1150809' extends '331427' salience 7070

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8270000", rteCode == "070")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1156478' extends '331427' salience 7060

    when
        
        GrlDetAmounts(this == $gda, actCode == "L8277000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1156480' extends '331427' salience 7050

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8267000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1163648' extends '331427' salience 7040

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0025000", rteCode == "172")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1179241' extends '331427' salience 7030

    when
        
        GrlDetAmounts(this == $gda, actCode == "L8333000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1181649' extends '331427' salience 7020

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q8332000")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1182225' extends '331427' salience 7010

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8334000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1781498' extends '331427' salience 7000

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0081000", cgpCode matches "P.*")
        
    then
        $gda.setCustomTxt02("g");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1781499' extends '331427' salience 6990

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0081000", cgpCode == "B0037")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1781501' extends '331427' salience 6980

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0111000")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080962' extends '331427' salience 6970

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "004200")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080975' extends '331427' salience 6960

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode in ("027800", "027900", "031500"))
        
    then
        $gda.setCustomTxt02("d");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1081010' extends '331427' salience 6950

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3334000", (cgpCode matches "G.*" || cgpCode matches "P.*"))
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1160003' extends '331427' salience 6940

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode matches "004.*", cgpCode == "P0039")
        
    then
        $gda.setCustomTxt02("e");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1160004' extends '331427' salience 6930

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "009400", cgpCode == "P0049")
        
    then
        $gda.setCustomTxt02("e");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1160006' extends '331427' salience 6920

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "012700", cgpCode matches "P.*")
        
    then
        $gda.setCustomTxt02("e");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1160007' extends '331427' salience 6910

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "014000", cgpCode not matches "B.*")
        
    then
        $gda.setCustomTxt02("e");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1160008' extends '331427' salience 6900

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "027800")
        
    then
        $gda.setCustomTxt02("e");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1161608' extends '331427' salience 6890

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "014000", cgpCode matches "B.*")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1781488' extends '331427' salience 6880

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "027800", cgpCode matches "B.*")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1781489' extends '331427' salience 6870

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "027900", cgpCode matches "B.*")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1781490' extends '331427' salience 6860

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "027900", cgpCode matches "P.*")
        
    then
        $gda.setCustomTxt02("e");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080954' extends '331427' salience 6850

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0241000", pdtCode == "004300", cgpCode == "P0046")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080955' extends '331427' salience 6840

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0241000", pdtCode == "004400", cgpCode == "P0046")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080956' extends '331427' salience 6830

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0241000", pdtCode == "004400", cgpCode == "P0049")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080957' extends '331427' salience 6820

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0241000", pdtCode == "014000", (cgpCode matches "G.*" || cgpCode matches "P.*"))
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080958' extends '331427' salience 6810

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0241000", pdtCode == "027100", cgpCode in ("P0045", "P0046"))
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080959' extends '331427' salience 6800

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0241000", pdtCode == "027100", cgpCode == "P0049")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080960' extends '331427' salience 6790

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "004000", cgpCode in ("P0045", "P0046"))
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080961' extends '331427' salience 6780

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "004000", cgpCode == "P0049")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080963' extends '331427' salience 6770

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "004300", cgpCode == "P0049")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080964' extends '331427' salience 6760

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "004300", cgpCode != "P0049")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080965' extends '331427' salience 6750

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "004400", cgpCode == "P0049")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080966' extends '331427' salience 6740

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "004400", cgpCode != "P0049")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080967' extends '331427' salience 6730

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "012200", cgpCode == "B0036")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080968' extends '331427' salience 6720

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "012200", (cgpCode matches "G.*" || cgpCode matches "P.*"))
        
    then
        $gda.setCustomTxt02("d");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080969' extends '331427' salience 6710

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "012700", cgpCode == "B0036")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080970' extends '331427' salience 6700

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "012700", (cgpCode matches "G.*" || cgpCode matches "P.*"))
        
    then
        $gda.setCustomTxt02("d");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080971' extends '331427' salience 6690

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "014000", cgpCode == "B0036")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080972' extends '331427' salience 6680

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "014000", (cgpCode matches "G.*" || cgpCode matches "P.*"))
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080973' extends '331427' salience 6670

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "027100", cgpCode == "P0049")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1080974' extends '331427' salience 6660

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "027100", cgpCode != "P0049")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1149802' extends '331427' salience 6650

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "004400", cgpCode == "B0036")
        
    then
        $gda.setCustomTxt02("c");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1149803' extends '331427' salience 6640

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode in ("028000", "027800"), cgpCode == "B0036")
        
    then
        $gda.setCustomTxt02("b");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1159995' extends '331427' salience 6630

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "012200", cgpCode == "P0045", rteCode == "055")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1159996' extends '331427' salience 6620

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "012700", cgpCode == "G0008", rteCode == "041")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1159997' extends '331427' salience 6610

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "012700", cgpCode == "P0039", rteCode == "055")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1159998' extends '331427' salience 6600

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "012700", cgpCode == "P0045", rteCode == "055")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1159999' extends '331427' salience 6590

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", pdtCode == "012200", cgpCode == "P0045", rteCode == "055")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1160000' extends '331427' salience 6580

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", pdtCode == "012700", cgpCode == "P0039", rteCode == "055")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1160001' extends '331427' salience 6570

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", pdtCode == "012200", cgpCode == "P0045", rteCode == "055")
        
    then
        $gda.setCustomTxt02("e");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1160002' extends '331427' salience 6560

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", pdtCode == "012700", cgpCode == "P0039", rteCode == "055")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1160005' extends '331427' salience 6550

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", pdtCode == "012200", cgpCode matches "P.*")
        
    then
        $gda.setCustomTxt02("e");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1160009' extends '331427' salience 6540

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", pdtCode == "012200", cgpCode == "P0045", rteCode == "059")
        
    then
        $gda.setCustomTxt02("e");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1161609' extends '331427' salience 6530

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", pdtCode == "012200", cgpCode == "P0045", rteCode == "059")
        
    then
        $gda.setCustomTxt02("e");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1781493' extends '331427' salience 6520

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "027800", cgpCode matches "P.*")
        
    then
        $gda.setCustomTxt02("d");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1781494' extends '331427' salience 6510

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "027900", cgpCode matches "B.*")
        
    then
        $gda.setCustomTxt02("a");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1119564' extends '331427' salience 6500

    when
        
        GrlDetAmounts(this == $gda, actCode == "L7510000")
        
    then
        $gda.setCustomTxt02("h");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1146523' extends '331427' salience 6490

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", pdtCode == "012200", cgpCode == "P0039", rteCode == "059")
        
    then
        $gda.setCustomTxt02("e");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1146524' extends '331427' salience 6480

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", pdtCode == "012200", cgpCode == "P0039", rteCode == "059")
        
    then
        $gda.setCustomTxt02("e");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1149860' extends '331427' salience 6470

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", pdtCode == "012200", cgpCode == "P0039", rteCode == "045")
        
    then
        $gda.setCustomTxt02("e");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1149861' extends '331427' salience 6460

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", pdtCode == "012200", cgpCode == "P0039", rteCode == "045")
        
    then
        $gda.setCustomTxt02("e");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end

rule '1182227' extends '331427' salience 6450

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000", pdtCode == "012700", cgpCode == "B0036", rteCode == "010")
        
    then
        $gda.setCustomTxt02("d");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2913");
        
end


