package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '331426'
	when
		$gda : GrlDetAmounts(scyActCode != null)
	then
        
end





rule '1080860' extends '331426' salience 10890

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setCustomTxt01("9999");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080687' extends '331426' salience 10880

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0001000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080688' extends '331426' salience 10870

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0002000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080689' extends '331426' salience 10860

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0003000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080690' extends '331426' salience 10850

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0005000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080691' extends '331426' salience 10840

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0006000")
        
    then
        $gda.setCustomTxt01("8");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080692' extends '331426' salience 10830

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0007000", rteCode == "025")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080693' extends '331426' salience 10820

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0007000", rteCode in ("010", "035", "036", "073", "098", "100"))
        
    then
        $gda.setCustomTxt01("2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080694' extends '331426' salience 10810

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0009000")
        
    then
        $gda.setCustomTxt01("1");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080695' extends '331426' salience 10800

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0011000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080696' extends '331426' salience 10790

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0012000")
        
    then
        $gda.setCustomTxt01("8");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080697' extends '331426' salience 10780

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0014000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080698' extends '331426' salience 10770

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0015000")
        
    then
        $gda.setCustomTxt01("9");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080699' extends '331426' salience 10760

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0016000")
        
    then
        $gda.setCustomTxt01("9");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080700' extends '331426' salience 10750

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0017000")
        
    then
        $gda.setCustomTxt01("4");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080701' extends '331426' salience 10740

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0019000")
        
    then
        $gda.setCustomTxt01("7");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080702' extends '331426' salience 10730

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0020000")
        
    then
        $gda.setCustomTxt01("7");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080703' extends '331426' salience 10720

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0021000")
        
    then
        $gda.setCustomTxt01("8");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080704' extends '331426' salience 10710

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0022000")
        
    then
        $gda.setCustomTxt01("6");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080705' extends '331426' salience 10700

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0023000")
        
    then
        $gda.setCustomTxt01("4");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080706' extends '331426' salience 10690

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0024000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080707' extends '331426' salience 10680

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0025000", rteCode in ("010", "035", "036", "037", "073", "173"))
        
    then
        $gda.setCustomTxt01("2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080708' extends '331426' salience 10670

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0025000", rteCode in ("074", "174", "172"))
        
    then
        $gda.setCustomTxt01("5");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080709' extends '331426' salience 10660

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", cgpCode matches "B.*")
        
    then
        $gda.setCustomTxt01("2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080710' extends '331426' salience 10650

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", cgpCode not matches "B.*")
        
    then
        $gda.setCustomTxt01("5");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080711' extends '331426' salience 10640

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0028000")
        
    then
        $gda.setCustomTxt01("8");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080712' extends '331426' salience 10630

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0029000")
        
    then
        $gda.setCustomTxt01("8");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080713' extends '331426' salience 10620

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0031000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080714' extends '331426' salience 10610

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0034000")
        
    then
        $gda.setCustomTxt01("2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080715' extends '331426' salience 10600

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0036000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080716' extends '331426' salience 10590

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0037000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080717' extends '331426' salience 10580

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0038000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080718' extends '331426' salience 10570

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0039000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080719' extends '331426' salience 10560

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0040000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080720' extends '331426' salience 10550

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0045000", rteCode in ("078", "080"))
        
    then
        $gda.setCustomTxt01("2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080721' extends '331426' salience 10540

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0045000", rteCode in ("084", "085", "087", "088"))
        
    then
        $gda.setCustomTxt01("5");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080722' extends '331426' salience 10530

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0046000")
        
    then
        $gda.setCustomTxt01("5");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080723' extends '331426' salience 10520

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0047000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080724' extends '331426' salience 10510

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0050000")
        
    then
        $gda.setCustomTxt01("6");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080725' extends '331426' salience 10500

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0051000")
        
    then
        $gda.setCustomTxt01("9");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080726' extends '331426' salience 10490

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0052000")
        
    then
        $gda.setCustomTxt01("8");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080727' extends '331426' salience 10480

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0053000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080728' extends '331426' salience 10470

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0054000")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080729' extends '331426' salience 10460

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0055000")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080730' extends '331426' salience 10450

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0056000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080731' extends '331426' salience 10440

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0057000")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080732' extends '331426' salience 10430

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0058000")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080733' extends '331426' salience 10420

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0060000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080734' extends '331426' salience 10410

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0061000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080735' extends '331426' salience 10400

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0624000")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080736' extends '331426' salience 10390

    when
        
        GrlDetAmounts(this == $gda, actCode == "A1112000")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080737' extends '331426' salience 10380

    when
        
        GrlDetAmounts(this == $gda, actCode == "A1614000")
        
    then
        $gda.setCustomTxt01("2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080738' extends '331426' salience 10370

    when
        
        GrlDetAmounts(this == $gda, actCode == "A2342000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080739' extends '331426' salience 10360

    when
        
        GrlDetAmounts(this == $gda, actCode == "A2500000")
        
    then
        $gda.setCustomTxt01("2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080740' extends '331426' salience 10350

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3145000")
        
    then
        $gda.setCustomTxt01("8");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080741' extends '331426' salience 10340

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3147000")
        
    then
        $gda.setCustomTxt01("8");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080742' extends '331426' salience 10330

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3176000")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080743' extends '331426' salience 10320

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3177000")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080744' extends '331426' salience 10310

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3178000")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080745' extends '331426' salience 10300

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3179000")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080746' extends '331426' salience 10290

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3282000")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080747' extends '331426' salience 10280

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3291000")
        
    then
        $gda.setCustomTxt01("4");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080748' extends '331426' salience 10270

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080749' extends '331426' salience 10260

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3331000")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080750' extends '331426' salience 10250

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", cgpCode matches "B.*")
        
    then
        $gda.setCustomTxt01("2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080751' extends '331426' salience 10240

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3332000", cgpCode not matches "B.*")
        
    then
        $gda.setCustomTxt01("5");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080752' extends '331426' salience 10230

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3333000")
        
    then
        $gda.setCustomTxt01("4");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080753' extends '331426' salience 10220

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3869000")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080754' extends '331426' salience 10210

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3906000")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080755' extends '331426' salience 10200

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3908000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080756' extends '331426' salience 10190

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3910000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080757' extends '331426' salience 10180

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3912000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080758' extends '331426' salience 10170

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3914000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080759' extends '331426' salience 10160

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3916000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080760' extends '331426' salience 10150

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", cgpCode matches "B.*")
        
    then
        $gda.setCustomTxt01("2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080761' extends '331426' salience 10140

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3931000", cgpCode not matches "B.*")
        
    then
        $gda.setCustomTxt01("5");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080762' extends '331426' salience 10130

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3943000", rteCode == "078")
        
    then
        $gda.setCustomTxt01("2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080763' extends '331426' salience 10120

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3943000", rteCode != "078")
        
    then
        $gda.setCustomTxt01("5");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080764' extends '331426' salience 10110

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4144000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080765' extends '331426' salience 10100

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4145000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080766' extends '331426' salience 10090

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4152000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080767' extends '331426' salience 10080

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4257000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080768' extends '331426' salience 10070

    when
        
        GrlDetAmounts(this == $gda, actCode == "A4392000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080769' extends '331426' salience 10060

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0229000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080770' extends '331426' salience 10050

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0230000", rteCode in ("100", "010", "098"))
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080771' extends '331426' salience 10040

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0233000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080772' extends '331426' salience 10030

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0234000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080773' extends '331426' salience 10020

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0237000")
        
    then
        $gda.setCustomTxt01("15");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080774' extends '331426' salience 10010

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0238000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080775' extends '331426' salience 10000

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0239000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080798' extends '331426' salience 9990

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0243000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080799' extends '331426' salience 9980

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0244000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080800' extends '331426' salience 9970

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0245000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080801' extends '331426' salience 9960

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0249000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080802' extends '331426' salience 9950

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0250000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080803' extends '331426' salience 9940

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0251000")
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080804' extends '331426' salience 9930

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0252000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080805' extends '331426' salience 9920

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0253000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080806' extends '331426' salience 9910

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0254000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080807' extends '331426' salience 9900

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0255000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080808' extends '331426' salience 9890

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0256000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080809' extends '331426' salience 9880

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0257000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080810' extends '331426' salience 9870

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0265000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080811' extends '331426' salience 9860

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0266000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080812' extends '331426' salience 9850

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0267000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080813' extends '331426' salience 9840

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0268000")
        
    then
        $gda.setCustomTxt01("20");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080814' extends '331426' salience 9830

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0269000")
        
    then
        $gda.setCustomTxt01("20");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080815' extends '331426' salience 9820

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0271000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080816' extends '331426' salience 9810

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0272000")
        
    then
        $gda.setCustomTxt01("14");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080817' extends '331426' salience 9800

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0273000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080818' extends '331426' salience 9790

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0277000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080819' extends '331426' salience 9780

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1425000")
        
    then
        $gda.setCustomTxt01("20");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080820' extends '331426' salience 9770

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1605000")
        
    then
        $gda.setCustomTxt01("12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080821' extends '331426' salience 9760

    when
        
        GrlDetAmounts(this == $gda, actCode == "L1615000")
        
    then
        $gda.setCustomTxt01("18");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080822' extends '331426' salience 9750

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2510000")
        
    then
        $gda.setCustomTxt01("18");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080823' extends '331426' salience 9740

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2569000")
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080824' extends '331426' salience 9730

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2571000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080825' extends '331426' salience 9720

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2730000")
        
    then
        $gda.setCustomTxt01("12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080826' extends '331426' salience 9710

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3180000")
        
    then
        $gda.setCustomTxt01("20");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080827' extends '331426' salience 9700

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3181000")
        
    then
        $gda.setCustomTxt01("20");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080828' extends '331426' salience 9690

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3182000")
        
    then
        $gda.setCustomTxt01("20");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080829' extends '331426' salience 9680

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3183000")
        
    then
        $gda.setCustomTxt01("20");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080830' extends '331426' salience 9670

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3279000")
        
    then
        $gda.setCustomTxt01("20");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080831' extends '331426' salience 9660

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3283000")
        
    then
        $gda.setCustomTxt01("20");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080833' extends '331426' salience 9650

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3343000")
        
    then
        $gda.setCustomTxt01("20");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080834' extends '331426' salience 9640

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3345000")
        
    then
        $gda.setCustomTxt01("15");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080835' extends '331426' salience 9630

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3346000")
        
    then
        $gda.setCustomTxt01("20");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080836' extends '331426' salience 9620

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3348000")
        
    then
        $gda.setCustomTxt01("20");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080837' extends '331426' salience 9610

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3351000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080838' extends '331426' salience 9600

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3873000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080839' extends '331426' salience 9590

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3899000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080840' extends '331426' salience 9580

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3907000")
        
    then
        $gda.setCustomTxt01("20");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080841' extends '331426' salience 9570

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3909000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080842' extends '331426' salience 9560

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3911000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080843' extends '331426' salience 9550

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3915000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080844' extends '331426' salience 9540

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3917000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080845' extends '331426' salience 9530

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3933000")
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080846' extends '331426' salience 9520

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3934000")
        
    then
        $gda.setCustomTxt01("15");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080847' extends '331426' salience 9510

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3935000")
        
    then
        $gda.setCustomTxt01("14");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080848' extends '331426' salience 9500

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3936000")
        
    then
        $gda.setCustomTxt01("14");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080849' extends '331426' salience 9490

    when
        
        GrlDetAmounts(this == $gda, actCode == "L9998000")
        
    then
        $gda.setCustomTxt01("18");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080850' extends '331426' salience 9480

    when
        
        GrlDetAmounts(this == $gda, actCode == "L9999000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080851' extends '331426' salience 9470

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0065000")
        
    then
        $gda.setCustomTxt01("12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080852' extends '331426' salience 9460

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0068000")
        
    then
        $gda.setCustomTxt01("12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080853' extends '331426' salience 9450

    when
        
        GrlDetAmounts(this == $gda, actCode in ("Q0069000", "Q0070000", "Q0071000"))
        
    then
        $gda.setCustomTxt01("12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080854' extends '331426' salience 9440

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0073000")
        
    then
        $gda.setCustomTxt01("12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080855' extends '331426' salience 9430

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0076000")
        
    then
        $gda.setCustomTxt01("12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080856' extends '331426' salience 9420

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0077000")
        
    then
        $gda.setCustomTxt01("12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080857' extends '331426' salience 9410

    when
        
        GrlDetAmounts(this == $gda, actCode in ("Q3167000", "Q3168000", "Q3335000"))
        
    then
        $gda.setCustomTxt01("12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080858' extends '331426' salience 9400

    when
        
        GrlDetAmounts(this == $gda, actCode matches "B.*")
        
    then
        $gda.setCustomTxt01("xxx");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080859' extends '331426' salience 9390

    when
        
        GrlDetAmounts(this == $gda, actCode matches "D.*")
        
    then
        $gda.setCustomTxt01("xxx");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1082939' extends '331426' salience 9380

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0066000")
        
    then
        $gda.setCustomTxt01("12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1109453' extends '331426' salience 9370

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0032000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1109454' extends '331426' salience 9360

    when
        
        GrlDetAmounts(this == $gda, actCode == "A6685000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1109457' extends '331426' salience 9350

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2530000")
        
    then
        $gda.setCustomTxt01("18");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1109458' extends '331426' salience 9340

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2532000")
        
    then
        $gda.setCustomTxt01("18");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1109459' extends '331426' salience 9330

    when
        
        GrlDetAmounts(this == $gda, actCode == "L2533000")
        
    then
        $gda.setCustomTxt01("18");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1109460' extends '331426' salience 9320

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0064000")
        
    then
        $gda.setCustomTxt01("12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1109461' extends '331426' salience 9310

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0069000")
        
    then
        $gda.setCustomTxt01("12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1109462' extends '331426' salience 9300

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0070000")
        
    then
        $gda.setCustomTxt01("12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1109463' extends '331426' salience 9290

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q0071000")
        
    then
        $gda.setCustomTxt01("12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1109464' extends '331426' salience 9280

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q3167000")
        
    then
        $gda.setCustomTxt01("12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1109465' extends '331426' salience 9270

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q3168000")
        
    then
        $gda.setCustomTxt01("12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1109466' extends '331426' salience 9260

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q3335000")
        
    then
        $gda.setCustomTxt01("12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1109467' extends '331426' salience 9250

    when
        
        GrlDetAmounts(this == $gda, actCode == "V0015160")
        
    then
        $gda.setCustomTxt01("31");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1109479' extends '331426' salience 9240

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0004000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1109480' extends '331426' salience 9230

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0010000")
        
    then
        $gda.setCustomTxt01("11");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1125491' extends '331426' salience 9220

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0025000", rteCode == "010")
        
    then
        $gda.setCustomTxt01("2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1150802' extends '331426' salience 9210

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8268000", rteCode == "070")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1150803' extends '331426' salience 9200

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8269000", rteCode == "070")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1150804' extends '331426' salience 9190

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8270000", rteCode == "070")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1150805' extends '331426' salience 9180

    when
        
        GrlDetAmounts(this == $gda, actCode == "L8276000")
        
    then
        $gda.setCustomTxt01("20");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1156477' extends '331426' salience 9170

    when
        
        GrlDetAmounts(this == $gda, actCode == "L8277000")
        
    then
        $gda.setCustomTxt01("20");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1156479' extends '331426' salience 9160

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8267000")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1179240' extends '331426' salience 9150

    when
        
        GrlDetAmounts(this == $gda, actCode == "L8333000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1181648' extends '331426' salience 9140

    when
        
        GrlDetAmounts(this == $gda, actCode == "Q8332000")
        
    then
        $gda.setCustomTxt01("12");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1182224' extends '331426' salience 9130

    when
        
        GrlDetAmounts(this == $gda, actCode == "A8334000")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1781495' extends '331426' salience 9120

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0027000", cgpCode matches "P.*")
        
    then
        $gda.setCustomTxt01("5");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1781500' extends '331426' salience 9110

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0111000")
        
    then
        $gda.setCustomTxt01("20");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080784' extends '331426' salience 9100

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "004200")
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080797' extends '331426' salience 9090

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode in ("027800", "027900", "031500"))
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080832' extends '331426' salience 9080

    when
        
        GrlDetAmounts(this == $gda, actCode == "L3334000", (cgpCode matches "G.*" || cgpCode matches "P.*"))
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1781491' extends '331426' salience 9070

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "027800", cgpCode matches "P.*")
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1781492' extends '331426' salience 9060

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "027900", cgpCode matches "B.*")
        
    then
        $gda.setCustomTxt01("18");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1781496' extends '331426' salience 9050

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0081000", cgpCode matches "P.*")
        
    then
        $gda.setCustomTxt01("5");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1781497' extends '331426' salience 9040

    when
        
        GrlDetAmounts(this == $gda, actCode == "A0081000", cgpCode == "B0037")
        
    then
        $gda.setCustomTxt01("2");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080776' extends '331426' salience 9030

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0241000", pdtCode == "004300", cgpCode == "P0046")
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080777' extends '331426' salience 9020

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0241000", pdtCode == "004400", cgpCode == "P0046")
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080778' extends '331426' salience 9010

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0241000", pdtCode == "004400", cgpCode == "P0049")
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080779' extends '331426' salience 9000

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0241000", pdtCode == "014000", (cgpCode matches "G.*" || cgpCode matches "P.*"))
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080780' extends '331426' salience 8990

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0241000", pdtCode == "027100", cgpCode in ("P0045", "P0046"))
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080781' extends '331426' salience 8980

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0241000", pdtCode == "027100", cgpCode == "P0049")
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080782' extends '331426' salience 8970

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "004000", cgpCode in ("P0045", "P0046"))
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080783' extends '331426' salience 8960

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "004000", cgpCode == "P0049")
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080785' extends '331426' salience 8950

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "004300", cgpCode == "P0049")
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080786' extends '331426' salience 8940

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "004300", cgpCode != "P0049")
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080787' extends '331426' salience 8930

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "004400", cgpCode == "P0049")
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080788' extends '331426' salience 8920

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "004400", cgpCode != "P0049")
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080789' extends '331426' salience 8910

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "012200", cgpCode == "B0036")
        
    then
        $gda.setCustomTxt01("18");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080790' extends '331426' salience 8900

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "012200", (cgpCode matches "G.*" || cgpCode matches "P.*"))
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080791' extends '331426' salience 8890

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode in ("012700", "027800"), cgpCode == "B0036")
        
    then
        $gda.setCustomTxt01("18");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080793' extends '331426' salience 8880

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "014000", cgpCode == "B0036")
        
    then
        $gda.setCustomTxt01("18");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080794' extends '331426' salience 8870

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "014000", (cgpCode matches "G.*" || cgpCode matches "P.*"))
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080795' extends '331426' salience 8860

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "027100", cgpCode == "P0049")
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1080796' extends '331426' salience 8850

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "027100", cgpCode != "P0049")
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1149801' extends '331426' salience 8840

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "004400", cgpCode == "B0036")
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1149804' extends '331426' salience 8830

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "028000", cgpCode == "B0036")
        
    then
        $gda.setCustomTxt01("18");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1182226' extends '331426' salience 8820

    when
        
        GrlDetAmounts(this == $gda, actCode == "A3329000", pdtCode == "012700", cgpCode == "B0036", rteCode == "010")
        
    then
        $gda.setCustomTxt01("3");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1695628' extends '331426' salience 8810

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "012700", cgpCode matches "[B.*,G.*}")
        
    then
        $gda.setCustomTxt01("18");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1695629' extends '331426' salience 8800

    when
        
        GrlDetAmounts(this == $gda, actCode == "L0242000", pdtCode == "012700", cgpCode matches "P.*")
        
    then
        $gda.setCustomTxt01("19");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end

rule '1119563' extends '331426' salience 8790

    when
        
        GrlDetAmounts(this == $gda, actCode == "L7510000")
        
    then
        $gda.setCustomTxt01("21");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2912");
        
end


