package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '330937'
	when
		$gda : GrlDetAmounts(massLine != "99.999")
	then
        
end





rule '995900' extends '330937' salience 780

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setLocMassLine("99.999");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993918' extends '330937' salience 770

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setLocMassLine("15.182");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993919' extends '330937' salience 760

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setLocMassLine("09.720");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993920' extends '330937' salience 750

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setLocMassLine("15.622");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993921' extends '330937' salience 740

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setLocMassLine("15.623");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993922' extends '330937' salience 730

    when
        
        GrlDetAmounts(this == $gda, actCode in ("A0046000", "A0045000", "A3943000"))
        
    then
        $gda.setLocMassLine("45.922");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993923' extends '330937' salience 720

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Loans")
        
    then
        $gda.setLocMassLine("Other Loans");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993924' extends '330937' salience 710

    when
        
        GrlDetAmounts(this == $gda, massLine == "Trading Securities")
        
    then
        $gda.setLocMassLine("Trading Securities");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993925' extends '330937' salience 700

    when
        
        GrlDetAmounts(this == $gda, massLine == "Trading Derivatives")
        
    then
        $gda.setLocMassLine("Trading Derivatives");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993926' extends '330937' salience 690

    when
        
        GrlDetAmounts(this == $gda, massLine == "Available for Sale Securities")
        
    then
        $gda.setLocMassLine("Available for Sale Securities");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993927' extends '330937' salience 680

    when
        
        GrlDetAmounts(this == $gda, massLine == "Bank Deposits Given")
        
    then
        $gda.setLocMassLine("05.201");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993929' extends '330937' salience 670

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets")
        
    then
        $gda.setLocMassLine("01.100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993931' extends '330937' salience 660

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setLocMassLine("Reverse Repos & Borrowing");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993932' extends '330937' salience 650

    when
        
        GrlDetAmounts(this == $gda, massLine == "Non-Trading Derivatives")
        
    then
        $gda.setLocMassLine("Non-Trading derivatives");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993934' extends '330937' salience 640

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets")
        
    then
        $gda.setLocMassLine("15.885");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993946' extends '330937' salience 630

    when
        
        GrlDetAmounts(this == $gda, massLine == "Capital and Reserves")
        
    then
        $gda.setLocMassLine("33.900");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993947' extends '330937' salience 620

    when
        
        GrlDetAmounts(this == $gda, massLine == "Capital and Reserves")
        
    then
        $gda.setLocMassLine("31.100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993948' extends '330937' salience 610

    when
        
        GrlDetAmounts(this == $gda, massLine == "Capital and Reserves")
        
    then
        $gda.setLocMassLine("33.200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993949' extends '330937' salience 600

    when
        
        GrlDetAmounts(this == $gda, massLine == "Net Profit")
        
    then
        $gda.setLocMassLine("51.100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993950' extends '330937' salience 590

    when
        
        GrlDetAmounts(this == $gda, massLine == "Total Assets Intercompany")
        
    then
        $gda.setLocMassLine("Total Assets Intercompany");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993951' extends '330937' salience 580

    when
        
        GrlDetAmounts(this == $gda, massLine == "Current accounts taken")
        
    then
        $gda.setLocMassLine("45.400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993952' extends '330937' salience 570

    when
        
        GrlDetAmounts(this == $gda, massLine == "Bank Deposits Taken", hscAcctSubcl == null)
        
    then
        $gda.setLocMassLine("47.403");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993953' extends '330937' salience 560

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities")
        
    then
        $gda.setLocMassLine("47.103");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993954' extends '330937' salience 550

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other deposits taken")
        
    then
        $gda.setLocMassLine("43.700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993955' extends '330937' salience 540

    when
        
        GrlDetAmounts(this == $gda, massLine == "Capital and Reserves", hscAcctSubcl == "1601")
        
    then
        $gda.setLocMassLine("45.905");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993957' extends '330937' salience 530

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities", hscAcctSubcl == "1401")
        
    then
        $gda.setLocMassLine("45.800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993959' extends '330937' salience 520

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities")
        
    then
        $gda.setLocMassLine("45.833");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993960' extends '330937' salience 510

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities")
        
    then
        $gda.setLocMassLine("45.900");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993961' extends '330937' salience 500

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities")
        
    then
        $gda.setLocMassLine("45.823");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993962' extends '330937' salience 490

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities", prodSubSubTypeLoc matches "45.83.*")
        
    then
        $gda.setLocMassLine("45.830");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993963' extends '330937' salience 480

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities")
        
    then
        $gda.setLocMassLine("45.834");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993964' extends '330937' salience 470

    when
        
        GrlDetAmounts(this == $gda, massLine == "Total Liabilities Intercompany")
        
    then
        $gda.setLocMassLine("Total Liabilities intercompany");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '995902' extends '330937' salience 460

    when
        
        GrlDetAmounts(this == $gda, massLine == "Off Balance Sheet Contingents")
        
    then
        $gda.setLocMassLine("Off balance sheet contingents");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '995903' extends '330937' salience 450

    when
        
        GrlDetAmounts(this == $gda, massLine == "Off Balance Sheet Derivatives")
        
    then
        $gda.setLocMassLine("Off balance sheet derivatives");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '995909' extends '330937' salience 440

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities", hscAcctSubcl == "1628")
        
    then
        $gda.setLocMassLine("45.850");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '995910' extends '330937' salience 430

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setLocMassLine("Non-Trading derivatives (Liabilities)");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '995911' extends '330937' salience 420

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setLocMassLine("15.622");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '1104133' extends '330937' salience 410

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities")
        
    then
        $gda.setLocMassLine("45.801");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '1104134' extends '330937' salience 400

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets")
        
    then
        $gda.setLocMassLine("05.103");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '1106404' extends '330937' salience 390

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets", actCode == "A0011000")
        
    then
        $gda.setLocMassLine("Corporate Tax Receivable");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '1106405' extends '330937' salience 380

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities")
        
    then
        $gda.setLocMassLine("45.824");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '1106406' extends '330937' salience 370

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities")
        
    then
        $gda.setLocMassLine("45.820");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '1106407' extends '330937' salience 360

    when
        
        GrlDetAmounts(this == $gda, massLine == "Savings Accounts Taken")
        
    then
        $gda.setLocMassLine("Savings Accounts Taken");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '1106414' extends '330937' salience 350

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets")
        
    then
        $gda.setLocMassLine("05.103");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '1106415' extends '330937' salience 340

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities")
        
    then
        $gda.setLocMassLine("47.103");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '1106416' extends '330937' salience 330

    when
        
        GrlDetAmounts(this == $gda, massLine == "Total Assets Intracompany")
        
    then
        $gda.setLocMassLine("Total Assets Intracompany");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '1106417' extends '330937' salience 320

    when
        
        GrlDetAmounts(this == $gda, massLine == "Total Liabilities Intracompany")
        
    then
        $gda.setLocMassLine("Total Liabilities Intracompany");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '1106441' extends '330937' salience 310

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities")
        
    then
        $gda.setLocMassLine("45.824");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '1113193' extends '330937' salience 300

    when
        
        GrlDetAmounts(this == $gda, massLine == "Voluntary Trade Securities")
        
    then
        $gda.setLocMassLine("Voluntary Trade Securities");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '1113194' extends '330937' salience 290

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities", actCode == "L3873000")
        
    then
        $gda.setLocMassLine("45.905");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993915' extends '330937' salience 280

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setLocMassLine("15.183");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993916' extends '330937' salience 270

    when
        
        GrlDetAmounts(this == $gda, massLine == "Current Accounts")
        
    then
        $gda.setLocMassLine("15.400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993917' extends '330937' salience 260

    when
        
        GrlDetAmounts(this == $gda, massLine == "Long Term Loans")
        
    then
        $gda.setLocMassLine("Medium term loans");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993928' extends '330937' salience 250

    when
        
        GrlDetAmounts(this == $gda, cpyBeyNumber == null)
        
    then
        $gda.setLocMassLine("05.103");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993933' extends '330937' salience 240

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets")
        
    then
        $gda.setLocMassLine("19.400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993935' extends '330937' salience 230

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets")
        
    then
        $gda.setLocMassLine("19.401");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993936' extends '330937' salience 220

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets")
        
    then
        $gda.setLocMassLine("19.500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993937' extends '330937' salience 210

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets")
        
    then
        $gda.setLocMassLine("19.600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993938' extends '330937' salience 200

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets")
        
    then
        $gda.setLocMassLine("19.700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993939' extends '330937' salience 190

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets")
        
    then
        $gda.setLocMassLine("19.701");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993940' extends '330937' salience 180

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets", prodSubSubTypeLoc matches "15.9.*")
        
    then
        $gda.setLocMassLine("15.900");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993941' extends '330937' salience 170

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets")
        
    then
        $gda.setLocMassLine("19.900");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993942' extends '330937' salience 160

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets")
        
    then
        $gda.setLocMassLine("15.864");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993943' extends '330937' salience 150

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets")
        
    then
        $gda.setLocMassLine("15.881");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993944' extends '330937' salience 140

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets")
        
    then
        $gda.setLocMassLine("21.300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '995901' extends '330937' salience 130

    when
        
        GrlDetAmounts(this == $gda, massLine == "Capital and Reserves", prodSubSubTypeLoc == null)
        
    then
        $gda.setLocMassLine("33.900");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '995904' extends '330937' salience 120

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets", hscAcctSubcl == "2702", prodSubSubTypeLoc == null)
        
    then
        $gda.setLocMassLine("15.900");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '995905' extends '330937' salience 110

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets", actCode in ("A3914000", "A0003000"), prodSubSubTypeLoc == null)
        
    then
        $gda.setLocMassLine("15.864");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '995906' extends '330937' salience 100

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities", actCode in ("L0229000", "L3915000"), prodSubSubTypeLoc == null)
        
    then
        $gda.setLocMassLine("45.823");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '995907' extends '330937' salience 90

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities", hscAcctSubcl == "2708", prodSubSubTypeLoc == null)
        
    then
        $gda.setLocMassLine("45.830");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '995908' extends '330937' salience 80

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities", hscAcctSubcl == "2702", prodSubSubTypeLoc == null)
        
    then
        $gda.setLocMassLine("45.900");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '1011627' extends '330937' salience 70

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets", actCode == "A0014000")
        
    then
        $gda.setLocMassLine("13.935");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '1108058' extends '330937' salience 60

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities", hscAcctSubcl == "2501")
        
    then
        $gda.setLocMassLine("45.401");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '1113196' extends '330937' salience 50

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets", hscAcctSubcl == "2708", prodSubSubTypeLoc == null)
        
    then
        $gda.setLocMassLine("15.881");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993930' extends '330937' salience 40

    when
        
        GrlDetAmounts(this == $gda, massLine == "Operational Lease")
        
    then
        $gda.setLocMassLine("Operational Lease");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993945' extends '330937' salience 30

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Assets", actCode == "A0007000", hpePdtType == "SPOT FX")
        
    then
        $gda.setLocMassLine("15.885");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '993956' extends '330937' salience 20

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities", actCode == "L0230000", hpePdtType == "SPOT FX")
        
    then
        $gda.setLocMassLine("53.500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end

rule '1106413' extends '330937' salience 10

    when
        
        GrlDetAmounts(this == $gda, massLine == "Other Client Liabilities", actCode == "L0230000", hpePdtType != "SPOT FX")
        
    then
        $gda.setLocMassLine("45.820");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"2612");
        
end


