package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '335528'
	when
		$gda : GrlDetAmounts(hpePdtType in ( "LEASING" ) && intInd == "N" && hacAmtCl in ( "01" , "02" , "03" , "05" , "12" , "16" ) && actCode != null)
	then
        
end





rule '1710446' extends '335528' salience 39550

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gda.setPdtCode(null);
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5904");
        
end

rule '1710440' extends '335528' salience 39540

    when
        
        GrlDetAmounts(this == $gda, hacAmtCl == "12")
        
    then
        $gda.setPdtCode("012700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5904");
        
end

rule '1710444' extends '335528' salience 39530

    when
        
        GrlDetAmounts(this == $gda, hacAmtCl in ("01", "02", "03", "05", "16"), contingInd == "N")
        
    then
        $gda.setPdtCode("012700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5904");
        
end

rule '1710438' extends '335528' salience 39520

    when
        
        GrlDetAmounts(this == $gda, hacAmtCl == "12", suborInd == "Y")
        
    then
        $gda.setPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5904");
        
end

rule '1710439' extends '335528' salience 39510
no-loop
    when
        
        GrlDetAmounts(this == $gda, hacAmtCl == "12", getCase0_1710436() == "long_term")
        
    then
        $gda.setPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5904");
        
end

rule '1710442' extends '335528' salience 39500

    when
        
        GrlDetAmounts(this == $gda, hacAmtCl in ("01", "02", "03", "05", "16"), suborInd == "Y", contingInd == "N")
        
    then
        $gda.setPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5904");
        
end

rule '1710443' extends '335528' salience 39490
no-loop
    when
        
        GrlDetAmounts(this == $gda, hacAmtCl in ("01", "02", "03", "05", "16"), getCase0_1710436() == "long_term", contingInd == "N")
        
    then
        $gda.setPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5904");
        
end

rule '1740941' extends '335528' salience 39480
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("01", "05"), contingInd == "Y", getCase0_1711488() == "long_term")
        
    then
        $gda.setPdtCode("014600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5904");
        
end

rule '1710437' extends '335528' salience 39470
no-loop
    when
        
        GrlDetAmounts(this == $gda, hacAmtCl in ("01", "02", "03", "05", "16"), contingInd == "Y", credFacInd == "N", getCase0_1711488() == "short_term", htyTradCat in ("01", "02"))
        
    then
        $gda.setPdtCode("012700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5904");
        
end

rule '1710441' extends '335528' salience 39460
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl == "12", getCase0_1710445() == "CORPORATE", finLeaseInd == "Y")
        
    then
        $gda.setPdtCode("013600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5904");
        
end

rule '1710445' extends '335528' salience 39450
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("01", "02", "03", "05", "16"), getCase0_1710445() == "CORPORATE", finLeaseInd == "Y", contingInd == "N")
        
    then
        $gda.setPdtCode("013600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5904");
        
end

rule '1710447' extends '335528' salience 39440
no-loop
    when
        
        GrlDetAmounts(this == $gda, repAssetInd == "Y", hacAmtCl in ("01", "05"), contingInd == "Y", credFacInd == "Y", getCase0_1711488() == "short_term", commInd == "N")
        
    then
        $gda.setPdtCode("014800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5904");
        
end

rule '1710435' extends '335528' salience 39430
no-loop
    when
        
        GrlDetAmounts(this == $gda, hacAmtCl in ("01", "02", "03", "05", "16"), suborInd == "Y", contingInd == "Y", credFacInd == "N", getCase0_1711488() == "short_term", htyTradCat in ("01", "02"))
        
    then
        $gda.setPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5904");
        
end

rule '1710436' extends '335528' salience 39420
no-loop
    when
        
        GrlDetAmounts(this == $gda, hacAmtCl in ("01", "02", "03", "05", "16"), getCase0_1710436() == "long_term", contingInd == "Y", credFacInd == "N", getCase0_1711488() == "short_term", htyTradCat in ("01", "02"))
        
    then
        $gda.setPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"5904");
        
end


