package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlDetAmounts;




dialect  "mvel"


rule '336727'
	when
		$gda : GrlDetAmounts(lseHlyRelId == "9705" && ownUse01 != null && hacAmtCl in ( "01" , "02" , "03" , "04" , "05" ))
	then
        
end





rule '1768260' extends '336727' salience 33500

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "005900")
        
    then
        $gda.setPdtCode("005900");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6873");
        
end

rule '1768261' extends '336727' salience 33490

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "006100")
        
    then
        $gda.setPdtCode("006100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6873");
        
end

rule '1768262' extends '336727' salience 33480

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "007300")
        
    then
        $gda.setPdtCode("007300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6873");
        
end

rule '1768263' extends '336727' salience 33470

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "029000")
        
    then
        $gda.setPdtCode("029000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6873");
        
end

rule '1768264' extends '336727' salience 33460

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030000")
        
    then
        $gda.setPdtCode("030000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6873");
        
end

rule '1768265' extends '336727' salience 33450

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030100")
        
    then
        $gda.setPdtCode("030100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6873");
        
end

rule '1768266' extends '336727' salience 33440

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030200")
        
    then
        $gda.setPdtCode("030200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6873");
        
end

rule '1768267' extends '336727' salience 33430

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030300")
        
    then
        $gda.setPdtCode("030300");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6873");
        
end

rule '1768268' extends '336727' salience 33420

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030400")
        
    then
        $gda.setPdtCode("030400");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6873");
        
end

rule '1768269' extends '336727' salience 33410

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030500")
        
    then
        $gda.setPdtCode("030500");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6873");
        
end

rule '1768270' extends '336727' salience 33400

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030600")
        
    then
        $gda.setPdtCode("030600");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6873");
        
end

rule '1768271' extends '336727' salience 33390

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030700")
        
    then
        $gda.setPdtCode("030700");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6873");
        
end

rule '1768272' extends '336727' salience 33380

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030800")
        
    then
        $gda.setPdtCode("030800");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6873");
        
end

rule '1768273' extends '336727' salience 33370

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "030900")
        
    then
        $gda.setPdtCode("030900");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6873");
        
end

rule '1768274' extends '336727' salience 33360

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "031000")
        
    then
        $gda.setPdtCode("031000");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6873");
        
end

rule '1768275' extends '336727' salience 33350

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "031100")
        
    then
        $gda.setPdtCode("031100");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6873");
        
end

rule '1901919' extends '336727' salience 33340

    when
        
        GrlDetAmounts(this == $gda, ownUse01 == "012200")
        
    then
        $gda.setPdtCode("012200");
        
        $gda.updateLdlIdTrail(kcontext.rule.name,"6873");
        
end


