package com.ing.gfrs.rules;

import com.ing.gfrs.avro.GrlPlYtd;




dialect  "mvel"


rule '334224'
	when
		$gpy : GrlPlYtd(actCode != null)
	then
        
end





rule '1615958' extends '334224' salience 4810

    when
        
        /*WARNING: this rule will always be called, since it has no conditions*/
        
    then
        $gpy.setSeCode1("9008-HK1_02.216");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615570' extends '334224' salience 4800

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0201000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615588' extends '334224' salience 4790

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3946000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615593' extends '334224' salience 4780

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4143000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615629' extends '334224' salience 4770

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8235000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615630' extends '334224' salience 4760

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8297000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615631' extends '334224' salience 4750

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8311000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615640' extends '334224' salience 4740

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3928000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615641' extends '334224' salience 4730

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3947000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615694' extends '334224' salience 4720

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8298000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615706' extends '334224' salience 4710

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0211000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.103");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615707' extends '334224' salience 4700

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3918000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.103");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615708' extends '334224' salience 4690

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3920000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.103");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615709' extends '334224' salience 4680

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0193000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.223");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615710' extends '334224' salience 4670

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0209000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.223");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615711' extends '334224' salience 4660

    when
        
        GrlPlYtd(this == $gpy, actCode == "I1182000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.223");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615712' extends '334224' salience 4650

    when
        
        GrlPlYtd(this == $gpy, actCode == "I1184000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.223");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615713' extends '334224' salience 4640

    when
        
        GrlPlYtd(this == $gpy, actCode == "I1185000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.223");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615714' extends '334224' salience 4630

    when
        
        GrlPlYtd(this == $gpy, actCode == "I1186000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.223");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615715' extends '334224' salience 4620

    when
        
        GrlPlYtd(this == $gpy, actCode == "I1189000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.223");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615716' extends '334224' salience 4610

    when
        
        GrlPlYtd(this == $gpy, actCode == "I1192000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.223");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615717' extends '334224' salience 4600

    when
        
        GrlPlYtd(this == $gpy, actCode == "I1193000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.223");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615718' extends '334224' salience 4590

    when
        
        GrlPlYtd(this == $gpy, actCode == "I1194000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.223");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615719' extends '334224' salience 4580

    when
        
        GrlPlYtd(this == $gpy, actCode == "I1195000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.223");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615720' extends '334224' salience 4570

    when
        
        GrlPlYtd(this == $gpy, actCode == "I1196000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.223");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615721' extends '334224' salience 4560

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0214000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.223");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615722' extends '334224' salience 4550

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0224000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.300");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615723' extends '334224' salience 4540

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0226000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.300");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615724' extends '334224' salience 4530

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8331000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.300");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615725' extends '334224' salience 4520

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9997000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615726' extends '334224' salience 4510

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0212000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615727' extends '334224' salience 4500

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3171000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615728' extends '334224' salience 4490

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3898000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615729' extends '334224' salience 4480

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4270000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615730' extends '334224' salience 4470

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8284000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615731' extends '334224' salience 4460

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8286000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615732' extends '334224' salience 4450

    when
        
        GrlPlYtd(this == $gpy, actCode == "I9994000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615733' extends '334224' salience 4440

    when
        
        GrlPlYtd(this == $gpy, actCode == "I9995000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615734' extends '334224' salience 4430

    when
        
        GrlPlYtd(this == $gpy, actCode == "I9996000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615735' extends '334224' salience 4420

    when
        
        GrlPlYtd(this == $gpy, actCode == "I9999000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615736' extends '334224' salience 4410

    when
        
        GrlPlYtd(this == $gpy, actCode == "E9996000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615737' extends '334224' salience 4400

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8391000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615741' extends '334224' salience 4390

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0196000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615809' extends '334224' salience 4380

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8234000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615821' extends '334224' salience 4370

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0210000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.103");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615822' extends '334224' salience 4360

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3919000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.103");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615823' extends '334224' salience 4350

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3921000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.103");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615824' extends '334224' salience 4340

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0192000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.216");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615825' extends '334224' salience 4330

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0208000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.216");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615826' extends '334224' salience 4320

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0997000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.216");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615827' extends '334224' salience 4310

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0998000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.216");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615828' extends '334224' salience 4300

    when
        
        GrlPlYtd(this == $gpy, actCode == "I1198000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.216");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615829' extends '334224' salience 4290

    when
        
        GrlPlYtd(this == $gpy, actCode == "I1199000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.216");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615830' extends '334224' salience 4280

    when
        
        GrlPlYtd(this == $gpy, actCode == "I1414000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.216");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615831' extends '334224' salience 4270

    when
        
        GrlPlYtd(this == $gpy, actCode == "I1415000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.216");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615832' extends '334224' salience 4260

    when
        
        GrlPlYtd(this == $gpy, actCode == "I1416000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.216");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615833' extends '334224' salience 4250

    when
        
        GrlPlYtd(this == $gpy, actCode == "I1418000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.216");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615834' extends '334224' salience 4240

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8559000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.216");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615835' extends '334224' salience 4230

    when
        
        GrlPlYtd(this == $gpy, actCode == "I1411000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.216");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615836' extends '334224' salience 4220

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0096000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.321");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615837' extends '334224' salience 4210

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0108000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.321");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615838' extends '334224' salience 4200

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0125000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.328");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615839' extends '334224' salience 4190

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0126000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.325");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615840' extends '334224' salience 4180

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0128000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.325");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615841' extends '334224' salience 4170

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0136000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.328");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615842' extends '334224' salience 4160

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0154000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.324");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615843' extends '334224' salience 4150

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0173000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.321");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615844' extends '334224' salience 4140

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0181000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.328");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615845' extends '334224' salience 4130

    when
        
        GrlPlYtd(this == $gpy, actCode == "E3903000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.328");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615846' extends '334224' salience 4120

    when
        
        GrlPlYtd(this == $gpy, actCode == "E4566000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.323");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615847' extends '334224' salience 4110

    when
        
        GrlPlYtd(this == $gpy, actCode == "E6684000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.321");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615848' extends '334224' salience 4100

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7483000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.321");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615849' extends '334224' salience 4090

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8236000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.321");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615850' extends '334224' salience 4080

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8296000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.328");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615851' extends '334224' salience 4070

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0131000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.328");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615852' extends '334224' salience 4060

    when
        
        GrlPlYtd(this == $gpy, actCode == "E3902000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.328");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615853' extends '334224' salience 4050

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0079000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615854' extends '334224' salience 4040

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0091000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615855' extends '334224' salience 4030

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0124000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615856' extends '334224' salience 4020

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0127000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615857' extends '334224' salience 4010

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0129000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615858' extends '334224' salience 4000

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0130000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615859' extends '334224' salience 3990

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0133000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615860' extends '334224' salience 3980

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0138000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615861' extends '334224' salience 3970

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0139000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615862' extends '334224' salience 3960

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0148000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615863' extends '334224' salience 3950

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0149000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615864' extends '334224' salience 3940

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0158000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615865' extends '334224' salience 3930

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0162000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615866' extends '334224' salience 3920

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0174000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615867' extends '334224' salience 3910

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0175000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615868' extends '334224' salience 3900

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0177000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615869' extends '334224' salience 3890

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0180000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615870' extends '334224' salience 3880

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0183000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615871' extends '334224' salience 3870

    when
        
        GrlPlYtd(this == $gpy, actCode == "E4621000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615872' extends '334224' salience 3860

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7509000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615873' extends '334224' salience 3850

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7996000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615874' extends '334224' salience 3840

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7997000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615875' extends '334224' salience 3830

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7998000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615876' extends '334224' salience 3820

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7999000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615877' extends '334224' salience 3810

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8000000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615878' extends '334224' salience 3800

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8001000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615879' extends '334224' salience 3790

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8002000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615880' extends '334224' salience 3780

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8003000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615881' extends '334224' salience 3770

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8004000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615882' extends '334224' salience 3760

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8229000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615883' extends '334224' salience 3750

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8230000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615884' extends '334224' salience 3740

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8231000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615885' extends '334224' salience 3730

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8232000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615886' extends '334224' salience 3720

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8266000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615887' extends '334224' salience 3710

    when
        
        GrlPlYtd(this == $gpy, actCode == "E8291000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615888' extends '334224' salience 3700

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8573000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.500");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615889' extends '334224' salience 3690

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8574000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.500");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615890' extends '334224' salience 3680

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8575000")
        
    then
        $gpy.setSeCode1("9008-HK1_02.500");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615891' extends '334224' salience 3670

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0078000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.100");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615892' extends '334224' salience 3660

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0123000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.100");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615893' extends '334224' salience 3650

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0157000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.100");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615894' extends '334224' salience 3640

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0165000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.100");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615895' extends '334224' salience 3630

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0176000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.100");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615896' extends '334224' salience 3620

    when
        
        GrlPlYtd(this == $gpy, actCode == "E2583000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.100");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615897' extends '334224' salience 3610

    when
        
        GrlPlYtd(this == $gpy, actCode == "E6683000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.100");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615898' extends '334224' salience 3600

    when
        
        GrlPlYtd(this == $gpy, actCode == "V4620010")
        
    then
        $gpy.setSeCode1("9008-HK1_03.100");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615899' extends '334224' salience 3590

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0147000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.100");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615900' extends '334224' salience 3580

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0182000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.100");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615901' extends '334224' salience 3570

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0172000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.200");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615902' extends '334224' salience 3560

    when
        
        GrlPlYtd(this == $gpy, actCode == "E4169000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.310");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615903' extends '334224' salience 3550

    when
        
        GrlPlYtd(this == $gpy, actCode == "E6696000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.310");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615904' extends '334224' salience 3540

    when
        
        GrlPlYtd(this == $gpy, actCode == "E6705000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.310");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615905' extends '334224' salience 3530

    when
        
        GrlPlYtd(this == $gpy, actCode == "E7504000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.310");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615906' extends '334224' salience 3520

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0085000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.320");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615907' extends '334224' salience 3510

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0087000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.320");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615908' extends '334224' salience 3500

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0169000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.320");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615909' extends '334224' salience 3490

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0171000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.320");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615910' extends '334224' salience 3480

    when
        
        GrlPlYtd(this == $gpy, actCode == "E3944000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.320");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615911' extends '334224' salience 3470

    when
        
        GrlPlYtd(this == $gpy, actCode == "E3945000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.320");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615912' extends '334224' salience 3460

    when
        
        GrlPlYtd(this == $gpy, actCode == "E3905000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.320");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615913' extends '334224' salience 3450

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0372000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.320");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615914' extends '334224' salience 3440

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0206000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615915' extends '334224' salience 3430

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0218000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615917' extends '334224' salience 3420

    when
        
        GrlPlYtd(this == $gpy, actCode == "I1521000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615918' extends '334224' salience 3410

    when
        
        GrlPlYtd(this == $gpy, actCode == "I2410000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615919' extends '334224' salience 3400

    when
        
        GrlPlYtd(this == $gpy, actCode == "I2411000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615920' extends '334224' salience 3390

    when
        
        GrlPlYtd(this == $gpy, actCode == "I2412000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615921' extends '334224' salience 3380

    when
        
        GrlPlYtd(this == $gpy, actCode == "I2413000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615922' extends '334224' salience 3370

    when
        
        GrlPlYtd(this == $gpy, actCode == "I2414000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615923' extends '334224' salience 3360

    when
        
        GrlPlYtd(this == $gpy, actCode == "I2415000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615924' extends '334224' salience 3350

    when
        
        GrlPlYtd(this == $gpy, actCode == "I2522000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615925' extends '334224' salience 3340

    when
        
        GrlPlYtd(this == $gpy, actCode == "I2523000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615926' extends '334224' salience 3330

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3169000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615927' extends '334224' salience 3320

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3170000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615928' extends '334224' salience 3310

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3172000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615929' extends '334224' salience 3300

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3252000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615930' extends '334224' salience 3290

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3253000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615931' extends '334224' salience 3280

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3284000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615932' extends '334224' salience 3270

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3337000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615933' extends '334224' salience 3260

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3338000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615934' extends '334224' salience 3250

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3344000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615935' extends '334224' salience 3240

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3347000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615936' extends '334224' salience 3230

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3349000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615937' extends '334224' salience 3220

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3894000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615938' extends '334224' salience 3210

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3897000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615939' extends '334224' salience 3200

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3937000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615940' extends '334224' salience 3190

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3939000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615941' extends '334224' salience 3180

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3940000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615942' extends '334224' salience 3170

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4893000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615943' extends '334224' salience 3160

    when
        
        GrlPlYtd(this == $gpy, actCode == "I5320000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615944' extends '334224' salience 3150

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8271000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615945' extends '334224' salience 3140

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8272000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615946' extends '334224' salience 3130

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8274000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615947' extends '334224' salience 3120

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8275000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615948' extends '334224' salience 3110

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8310000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615949' extends '334224' salience 3100

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8338000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615950' extends '334224' salience 3090

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8576000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615951' extends '334224' salience 3080

    when
        
        GrlPlYtd(this == $gpy, actCode == "I8577000")
        
    then
        $gpy.setSeCode1("9008-HK1_03.400");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615952' extends '334224' salience 3070

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0220000")
        
    then
        $gpy.setSeCode1("9008-HK1_04.211");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615954' extends '334224' salience 3060

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0222000")
        
    then
        $gpy.setSeCode1("9008-HK1_04.212");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615955' extends '334224' salience 3050

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0225000")
        
    then
        $gpy.setSeCode1("9008-HK1_04.212");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615956' extends '334224' salience 3040

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0109000")
        
    then
        $gpy.setSeCode1("9008-HK1_05.000");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615957' extends '334224' salience 3030

    when
        
        GrlPlYtd(this == $gpy, actCode == "E0112000")
        
    then
        $gpy.setSeCode1("9008-HK1_05.000");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615959' extends '334224' salience 3020

    when
        
        GrlPlYtd(this == $gpy, actCode == "E1610000")
        
    then
        $gpy.setSeCode1(null);
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615586' extends '334224' salience 3010

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3928000", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615587' extends '334224' salience 3000

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3928000", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615589' extends '334224' salience 2990

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3946000", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615590' extends '334224' salience 2980

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3946000", cgpCode == "P0049")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615591' extends '334224' salience 2970

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3947000", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615592' extends '334224' salience 2960

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3947000", cgpCode == "P0049")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615649' extends '334224' salience 2950

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "005900")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615651' extends '334224' salience 2940

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "007300")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615660' extends '334224' salience 2930

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "029000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615665' extends '334224' salience 2920

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "030400")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615667' extends '334224' salience 2910

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "031100")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615668' extends '334224' salience 2900

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0200000", pdtCode == "006100")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615670' extends '334224' salience 2890

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0200000", pdtCode == "007300")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615687' extends '334224' salience 2880

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4404000", pdtCode == "007300")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615693' extends '334224' salience 2870

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4404000", pdtCode == "030900")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615695' extends '334224' salience 2860

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "030100")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615696' extends '334224' salience 2850

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "030200")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615697' extends '334224' salience 2840

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "030600")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615698' extends '334224' salience 2830

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "030900")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615700' extends '334224' salience 2820

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4168000", pdtCode == "007300")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615702' extends '334224' salience 2810

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4168000", pdtCode == "029000")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615703' extends '334224' salience 2800

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4168000", pdtCode == "031100")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615738' extends '334224' salience 2790

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0143000", pdtCode == "007300")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615804' extends '334224' salience 2780

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4406000", pdtCode == "007300")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615814' extends '334224' salience 2770

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0195000", pdtCode == "005900")
        
    then
        $gpy.setSeCode1("9008-HK1_02.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615815' extends '334224' salience 2760

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0195000", pdtCode == "006100")
        
    then
        $gpy.setSeCode1("9008-HK1_02.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615816' extends '334224' salience 2750

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0195000", pdtCode == "007300")
        
    then
        $gpy.setSeCode1("9008-HK1_02.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615817' extends '334224' salience 2740

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3922000", pdtCode == "007300")
        
    then
        $gpy.setSeCode1("9008-HK1_02.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615818' extends '334224' salience 2730

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4407000", pdtCode == "007300")
        
    then
        $gpy.setSeCode1("9008-HK1_02.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615819' extends '334224' salience 2720

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0195000", pdtCode == "002900")
        
    then
        $gpy.setSeCode1("9008-HK1_02.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615820' extends '334224' salience 2710

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0195000", pdtCode == "030300")
        
    then
        $gpy.setSeCode1("9008-HK1_02.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615527' extends '334224' salience 2700

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "004200", cgpCode == "B0035")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615528' extends '334224' salience 2690

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "004200", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615529' extends '334224' salience 2680

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "004200", cgpCode == "B0037")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615530' extends '334224' salience 2670

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "004200", cgpCode == "G0008")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615531' extends '334224' salience 2660

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "004200", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615532' extends '334224' salience 2650

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "004200", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615533' extends '334224' salience 2640

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "004300", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615534' extends '334224' salience 2630

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "004400", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615535' extends '334224' salience 2620

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "004400", cgpCode == "B0037")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615536' extends '334224' salience 2610

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "004400", cgpCode == "G0008")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615537' extends '334224' salience 2600

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "004400", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615538' extends '334224' salience 2590

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "004400", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615539' extends '334224' salience 2580

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "009400", cgpCode == "P0049")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615540' extends '334224' salience 2570

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "012200", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615541' extends '334224' salience 2560

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "012200", cgpCode == "B0037")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615542' extends '334224' salience 2550

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "012200", cgpCode == "G0008")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615543' extends '334224' salience 2540

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "012200", cgpCode == "G0009")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615544' extends '334224' salience 2530

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "012200", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615545' extends '334224' salience 2520

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "012200", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615546' extends '334224' salience 2510

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "012200", cgpCode == "P0049")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615547' extends '334224' salience 2500

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "012700", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615548' extends '334224' salience 2490

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "012700", cgpCode == "B0037")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615549' extends '334224' salience 2480

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "012700", cgpCode == "G0008")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615550' extends '334224' salience 2470

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "012700", cgpCode == "G0009")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615551' extends '334224' salience 2460

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "012700", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615552' extends '334224' salience 2450

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "012700", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615553' extends '334224' salience 2440

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "012700", cgpCode == "P0049")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615554' extends '334224' salience 2430

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "013600", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615555' extends '334224' salience 2420

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "014000", cgpCode == "B0034")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615556' extends '334224' salience 2410

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "014000", cgpCode == "B0035")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615557' extends '334224' salience 2400

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "014000", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615558' extends '334224' salience 2390

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "014000", cgpCode == "G0008")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615559' extends '334224' salience 2380

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "014000", cgpCode == "G0009")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615560' extends '334224' salience 2370

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "014000", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615561' extends '334224' salience 2360

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "014000", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615562' extends '334224' salience 2350

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "014000", cgpCode == "P0049")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615563' extends '334224' salience 2340

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "027800", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615564' extends '334224' salience 2330

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "027800", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615565' extends '334224' salience 2320

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "028000", cgpCode == "B0035")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615566' extends '334224' salience 2310

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "028000", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615567' extends '334224' salience 2300

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "028000", cgpCode == "G0008")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615568' extends '334224' salience 2290

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "028000", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615569' extends '334224' salience 2280

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "028000", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615571' extends '334224' salience 2270

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3924000", pdtCode == "004200", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615572' extends '334224' salience 2260

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3924000", pdtCode == "004200", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615573' extends '334224' salience 2250

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3924000", pdtCode == "004400", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615574' extends '334224' salience 2240

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3924000", pdtCode == "004400", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615575' extends '334224' salience 2230

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3924000", pdtCode == "012200", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615576' extends '334224' salience 2220

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3924000", pdtCode == "012200", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615577' extends '334224' salience 2210

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3924000", pdtCode == "012200", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615578' extends '334224' salience 2200

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3924000", pdtCode == "027800", cgpCode == "B0035")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615579' extends '334224' salience 2190

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3924000", pdtCode == "027800", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615580' extends '334224' salience 2180

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3924000", pdtCode == "027800", cgpCode == "G0008")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615581' extends '334224' salience 2170

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3924000", pdtCode == "027800", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615582' extends '334224' salience 2160

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3924000", pdtCode == "027800", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615583' extends '334224' salience 2150

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3924000", pdtCode == "028000", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615584' extends '334224' salience 2140

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3924000", pdtCode == "028000", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615585' extends '334224' salience 2130

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3924000", pdtCode == "028000", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615594' extends '334224' salience 2120

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4405000", pdtCode == "004300", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615595' extends '334224' salience 2110

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4405000", pdtCode == "004400", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615596' extends '334224' salience 2100

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4405000", pdtCode == "004400", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615597' extends '334224' salience 2090

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4405000", pdtCode == "012200", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615598' extends '334224' salience 2080

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4405000", pdtCode == "012200", cgpCode == "G0008")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615599' extends '334224' salience 2070

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4405000", pdtCode == "012200", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615600' extends '334224' salience 2060

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7467000", pdtCode == "007300", cgpCode == "00007")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615601' extends '334224' salience 2050

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7467000", pdtCode == "007300", cgpCode == "00010")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615602' extends '334224' salience 2040

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7467000", pdtCode == "007300", cgpCode == "00011")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615603' extends '334224' salience 2030

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7467000", pdtCode == "007300", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615604' extends '334224' salience 2020

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7467000", pdtCode == "029000", cgpCode == "00010")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615605' extends '334224' salience 2010

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7467000", pdtCode == "029000", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615606' extends '334224' salience 2000

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7467000", pdtCode == "030300", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615607' extends '334224' salience 1990

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7467000", pdtCode == "030300", cgpCode == "00017")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615608' extends '334224' salience 1980

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7467000", pdtCode == "030600", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615609' extends '334224' salience 1970

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7467000", pdtCode == "030700", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615610' extends '334224' salience 1960

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7467000", pdtCode == "031100", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615611' extends '334224' salience 1950

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7467000", pdtCode == "031100", cgpCode == "00017")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615612' extends '334224' salience 1940

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7468000", pdtCode == "007300", cgpCode == "00011")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615613' extends '334224' salience 1930

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7468000", pdtCode == "007300", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615614' extends '334224' salience 1920

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7468000", pdtCode == "029000", cgpCode == "00010")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615615' extends '334224' salience 1910

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7468000", pdtCode == "029000", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615616' extends '334224' salience 1900

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7468000", pdtCode == "030300", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615617' extends '334224' salience 1890

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7468000", pdtCode == "030700", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615618' extends '334224' salience 1880

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7468000", pdtCode == "031100", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615619' extends '334224' salience 1870

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7469000", pdtCode == "007300", cgpCode == "00007")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615620' extends '334224' salience 1860

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7469000", pdtCode == "007300", cgpCode == "00011")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615621' extends '334224' salience 1850

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7469000", pdtCode == "007300", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615622' extends '334224' salience 1840

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7469000", pdtCode == "029000", cgpCode == "00010")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615623' extends '334224' salience 1830

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7469000", pdtCode == "029000", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615624' extends '334224' salience 1820

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7469000", pdtCode == "030300", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615625' extends '334224' salience 1810

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7469000", pdtCode == "030600", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615626' extends '334224' salience 1800

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7469000", pdtCode == "030700", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615627' extends '334224' salience 1790

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7469000", pdtCode == "030900", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615628' extends '334224' salience 1780

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7469000", pdtCode == "031100", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615632' extends '334224' salience 1770

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "004200", cgpCode == "G0009")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615633' extends '334224' salience 1760

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "004300", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615634' extends '334224' salience 1750

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "004300", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615635' extends '334224' salience 1740

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "004400", cgpCode == "B0034")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615636' extends '334224' salience 1730

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "013600", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615637' extends '334224' salience 1720

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "027800", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615638' extends '334224' salience 1710

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "028000", cgpCode == "B0034")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615639' extends '334224' salience 1700

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3924000", pdtCode == "004400", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615642' extends '334224' salience 1690

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4405000", pdtCode == "004400", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615643' extends '334224' salience 1680

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4405000", pdtCode == "012700", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615644' extends '334224' salience 1670

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7467000", pdtCode == "007300", cgpCode == "00003")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615645' extends '334224' salience 1660

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7467000", pdtCode == "007300", cgpCode == "00013")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615646' extends '334224' salience 1650

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7468000", pdtCode == "007300", cgpCode == "00013")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615647' extends '334224' salience 1640

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7468000", pdtCode == "030600", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615648' extends '334224' salience 1630

    when
        
        GrlPlYtd(this == $gpy, actCode == "I7469000", pdtCode == "007300", cgpCode == "00010")
        
    then
        $gpy.setSeCode1("9008-HK1_01.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615650' extends '334224' salience 1620

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "005900", cgpCode == "00010")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615652' extends '334224' salience 1610

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "007300", cgpCode == "00003")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615653' extends '334224' salience 1600

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "007300", cgpCode == "00004")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615654' extends '334224' salience 1590

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "007300", cgpCode == "00005")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615655' extends '334224' salience 1580

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "007300", cgpCode == "00006")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615656' extends '334224' salience 1570

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "007300", cgpCode == "00007")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615657' extends '334224' salience 1560

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "007300", cgpCode == "00010")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615658' extends '334224' salience 1550

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "007300", cgpCode == "00011")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615659' extends '334224' salience 1540

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "007300", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615661' extends '334224' salience 1530

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "029000", cgpCode == "00010")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615662' extends '334224' salience 1520

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "029000", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615663' extends '334224' salience 1510

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "030100", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615664' extends '334224' salience 1500

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "030300", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615666' extends '334224' salience 1490

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0198000", pdtCode == "030900", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615669' extends '334224' salience 1480

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0200000", pdtCode == "006100", cgpCode == "00010")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615671' extends '334224' salience 1470

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0200000", pdtCode == "007300", cgpCode == "00003")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615672' extends '334224' salience 1460

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0200000", pdtCode == "007300", cgpCode == "00005")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615673' extends '334224' salience 1450

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0200000", pdtCode == "007300", cgpCode == "00006")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615674' extends '334224' salience 1440

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0200000", pdtCode == "007300", cgpCode == "00007")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615675' extends '334224' salience 1430

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0200000", pdtCode == "007300", cgpCode == "00008")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615676' extends '334224' salience 1420

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0200000", pdtCode == "007300", cgpCode == "00009")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615677' extends '334224' salience 1410

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0200000", pdtCode == "007300", cgpCode == "00010")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615678' extends '334224' salience 1400

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0200000", pdtCode == "007300", cgpCode == "00011")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615679' extends '334224' salience 1390

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0200000", pdtCode == "007300", cgpCode == "00012")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615680' extends '334224' salience 1380

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0200000", pdtCode == "007300", cgpCode == "00013")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615681' extends '334224' salience 1370

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0200000", pdtCode == "007300", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615682' extends '334224' salience 1360

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0200000", pdtCode == "007300", cgpCode == "00017")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615683' extends '334224' salience 1350

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4168000", pdtCode == "007300", cgpCode == "00010")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615684' extends '334224' salience 1340

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4168000", pdtCode == "029000", cgpCode == "00010")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615685' extends '334224' salience 1330

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4168000", pdtCode == "029000", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615686' extends '334224' salience 1320

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4168000", pdtCode == "031100", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615688' extends '334224' salience 1310

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4404000", pdtCode == "007300", cgpCode == "00005")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615689' extends '334224' salience 1300

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4404000", pdtCode == "007300", cgpCode == "00006")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615690' extends '334224' salience 1290

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4404000", pdtCode == "007300", cgpCode == "00007")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615691' extends '334224' salience 1280

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4404000", pdtCode == "007300", cgpCode == "00010")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615692' extends '334224' salience 1270

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4404000", pdtCode == "007300", cgpCode == "00011")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615699' extends '334224' salience 1260

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0200000", pdtCode == "007300", cgpCode == "00004")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615701' extends '334224' salience 1250

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4168000", pdtCode == "007300", cgpCode == "00011")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615704' extends '334224' salience 1240

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4404000", pdtCode == "007300", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615705' extends '334224' salience 1230

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4404000", pdtCode == "029000", cgpCode == "00015")
        
    then
        $gpy.setSeCode1("9008-HK1_01.102");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615739' extends '334224' salience 1220

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0143000", pdtCode == "012200", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615740' extends '334224' salience 1210

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0143000", pdtCode == "012200", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615742' extends '334224' salience 1200

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004000", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615743' extends '334224' salience 1190

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004000", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615744' extends '334224' salience 1180

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004000", cgpCode == "P0049")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615745' extends '334224' salience 1170

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004200", cgpCode == "B0034")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615746' extends '334224' salience 1160

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004200", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615747' extends '334224' salience 1150

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004200", cgpCode == "B0037")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615748' extends '334224' salience 1140

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004200", cgpCode == "G0008")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615749' extends '334224' salience 1130

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004200", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615750' extends '334224' salience 1120

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004200", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615751' extends '334224' salience 1110

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004300", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615752' extends '334224' salience 1100

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004300", cgpCode == "G0009")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615753' extends '334224' salience 1090

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004300", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615754' extends '334224' salience 1080

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004300", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615755' extends '334224' salience 1070

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004300", cgpCode == "P0049")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615756' extends '334224' salience 1060

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004400", cgpCode == "B0034")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615757' extends '334224' salience 1050

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004400", cgpCode == "B0035")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615758' extends '334224' salience 1040

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004400", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615759' extends '334224' salience 1030

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004400", cgpCode == "B0037")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615760' extends '334224' salience 1020

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004400", cgpCode == "G0008")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615761' extends '334224' salience 1010

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004400", cgpCode == "G0009")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615762' extends '334224' salience 1000

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004400", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615763' extends '334224' salience 990

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004400", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615764' extends '334224' salience 980

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "004400", cgpCode == "P0049")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615765' extends '334224' salience 970

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "012200", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615766' extends '334224' salience 960

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "012200", cgpCode == "B0037")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615767' extends '334224' salience 950

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "012200", cgpCode == "G0008")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615768' extends '334224' salience 940

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "012200", cgpCode == "G0009")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615769' extends '334224' salience 930

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "012200", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615770' extends '334224' salience 920

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "012200", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615771' extends '334224' salience 910

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "012700", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615772' extends '334224' salience 900

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "014000", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615773' extends '334224' salience 890

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "014000", cgpCode == "G0008")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615774' extends '334224' salience 880

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "014000", cgpCode == "G0009")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615775' extends '334224' salience 870

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "014000", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615776' extends '334224' salience 860

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "014000", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615777' extends '334224' salience 850

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "014000", cgpCode == "P0049")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615778' extends '334224' salience 840

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "027100", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615779' extends '334224' salience 830

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "027100", cgpCode == "G0008")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615780' extends '334224' salience 820

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "027100", cgpCode == "G0009")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615781' extends '334224' salience 810

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "027100", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615782' extends '334224' salience 800

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "027100", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615783' extends '334224' salience 790

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "027100", cgpCode == "P0049")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615784' extends '334224' salience 780

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "027800", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615785' extends '334224' salience 770

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "028000", cgpCode == "B0035")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615786' extends '334224' salience 760

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "028000", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615787' extends '334224' salience 750

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "028000", cgpCode == "B0037")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615788' extends '334224' salience 740

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "028000", cgpCode == "G0008")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615789' extends '334224' salience 730

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "028000", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615790' extends '334224' salience 720

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "028000", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615791' extends '334224' salience 710

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3923000", pdtCode == "004200", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615792' extends '334224' salience 700

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3923000", pdtCode == "004400", cgpCode == "B0035")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615793' extends '334224' salience 690

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3923000", pdtCode == "004400", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615794' extends '334224' salience 680

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3923000", pdtCode == "004400", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615795' extends '334224' salience 670

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3923000", pdtCode == "004400", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615796' extends '334224' salience 660

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3923000", pdtCode == "012200", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615797' extends '334224' salience 650

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3923000", pdtCode == "027800", cgpCode == "B0034")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615798' extends '334224' salience 640

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3923000", pdtCode == "027800", cgpCode == "B0035")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615799' extends '334224' salience 630

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3923000", pdtCode == "027800", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615800' extends '334224' salience 620

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3923000", pdtCode == "027800", cgpCode == "G0008")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615801' extends '334224' salience 610

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3923000", pdtCode == "027800", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615802' extends '334224' salience 600

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3923000", pdtCode == "027800", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615803' extends '334224' salience 590

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3923000", pdtCode == "028000", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615805' extends '334224' salience 580

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4408000", pdtCode == "004300", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615806' extends '334224' salience 570

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4408000", pdtCode == "004400", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615807' extends '334224' salience 560

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4408000", pdtCode == "004400", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615808' extends '334224' salience 550

    when
        
        GrlPlYtd(this == $gpy, actCode == "I4408000", pdtCode == "012200", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615810' extends '334224' salience 540

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "027800", cgpCode == "P0039")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615811' extends '334224' salience 530

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0197000", pdtCode == "028000", cgpCode == "B0034")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615812' extends '334224' salience 520

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3923000", pdtCode == "004200", cgpCode == "B0036")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '1615813' extends '334224' salience 510

    when
        
        GrlPlYtd(this == $gpy, actCode == "I3923000", pdtCode == "027800", cgpCode == "B0037")
        
    then
        $gpy.setSeCode1("9008-HK1_02.101");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end

rule '2008532' extends '334224' salience 500

    when
        
        GrlPlYtd(this == $gpy, actCode == "I0199000", pdtCode == "033300", cgpCode == "P0045")
        
    then
        $gpy.setSeCode1("9008-HK1_02.241");
        
        $gpy.updateLdlIdTrail(kcontext.rule.name,"4938");
        
end


